<?php

namespace MyModule\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * UploadImage
 *
 * @ORM\Table(name="upload_image", uniqueConstraints={@ORM\UniqueConstraint(name="upload_image", columns={"upload_image"})}, indexes={@ORM\Index(name="created_by", columns={"created_by"}), @ORM\Index(name="updated_by", columns={"updated_by"}), @ORM\Index(name="id_mvc_basic_upload_image", columns={"id_mvc_basic_upload_image"})})
 * @ORM\Entity
 */
class UploadImage
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id_upload_image", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idUploadImage;

    /**
     * @var string
     *
     * @ORM\Column(name="upload_image", type="string", length=255, nullable=false)
     */
    private $uploadImage;

    /**
     * @var integer
     *
     * @ORM\Column(name="ordination", type="integer", nullable=false)
     */
    private $ordination;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="created", type="datetime", nullable=false)
     */
    private $created;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated", type="datetime", nullable=true)
     */
    private $updated;

    /**
     * @var \MyModule\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="MyModule\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="created_by", referencedColumnName="id_user")
     * })
     */
    private $createdBy;

    /**
     * @var \MyModule\Entity\User
     *
     * @ORM\ManyToOne(targetEntity="MyModule\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="updated_by", referencedColumnName="id_user")
     * })
     */
    private $updatedBy;

    /**
     * @var \MyModule\Entity\MvcBasicUploadImage
     *
     * @ORM\ManyToOne(targetEntity="MyModule\Entity\MvcBasicUploadImage")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_mvc_basic_upload_image", referencedColumnName="id_mvc_basic_upload_image")
     * })
     */
    private $idMvcBasicUploadImage;



    /**
     * Get idUploadImage
     *
     * @return integer
     */
    public function getIdUploadImage()
    {
        return $this->idUploadImage;
    }

    /**
     * Set uploadImage
     *
     * @param string $uploadImage
     *
     * @return UploadImage
     */
    public function setUploadImage($uploadImage)
    {
        $this->uploadImage = $uploadImage;

        return $this;
    }

    /**
     * Get uploadImage
     *
     * @return string
     */
    public function getUploadImage()
    {
        return $this->uploadImage;
    }

    /**
     * Set ordination
     *
     * @param integer $ordination
     *
     * @return UploadImage
     */
    public function setOrdination($ordination)
    {
        $this->ordination = $ordination;

        return $this;
    }

    /**
     * Get ordination
     *
     * @return integer
     */
    public function getOrdination()
    {
        return $this->ordination;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     *
     * @return UploadImage
     */
    public function setCreated($created)
    {
        $this->created = $created;

        return $this;
    }

    /**
     * Get created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     *
     * @return UploadImage
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;

        return $this;
    }

    /**
     * Get updated
     *
     * @return \DateTime
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * Set createdBy
     *
     * @param \MyModule\Entity\User $createdBy
     *
     * @return UploadImage
     */
    public function setCreatedBy(\MyModule\Entity\User $createdBy = null)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get createdBy
     *
     * @return \MyModule\Entity\User
     */
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set updatedBy
     *
     * @param \MyModule\Entity\User $updatedBy
     *
     * @return UploadImage
     */
    public function setUpdatedBy(\MyModule\Entity\User $updatedBy = null)
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }

    /**
     * Get updatedBy
     *
     * @return \MyModule\Entity\User
     */
    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * Set idMvcBasicUploadImage
     *
     * @param \MyModule\Entity\MvcBasicUploadImage $idMvcBasicUploadImage
     *
     * @return UploadImage
     */
    public function setIdMvcBasicUploadImage(\MyModule\Entity\MvcBasicUploadImage $idMvcBasicUploadImage = null)
    {
        $this->idMvcBasicUploadImage = $idMvcBasicUploadImage;

        return $this;
    }

    /**
     * Get idMvcBasicUploadImage
     *
     * @return \MyModule\Entity\MvcBasicUploadImage
     */
    public function getIdMvcBasicUploadImage()
    {
        return $this->idMvcBasicUploadImage;
    }
}

