<?php
namespace SchemaModuleTest\RepositoryTest;

use GearBaseTest\AbstractTestCase;
use SchemaModule\Repository\MyRepositoryExtendsTrait;

/**
 * @group Repository
 */
class MyRepositoryExtendsTest extends AbstractTestCase
{
    use MyRepositoryExtendsTrait;

    /**
     * @group SchemaModule
     * @group MyRepositoryExtends
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getMyRepositoryExtends()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group SchemaModule
     * @group MyRepositoryExtends
    */
    public function testGet()
    {
        $myRepositoryExtends = $this->getMyRepositoryExtends();
        $this->assertInstanceOf('SchemaModule\Repository\MyRepositoryExtends', $myRepositoryExtends);
    }

    /**
     * @group SchemaModule
     * @group MyRepositoryExtends
    */
    public function testSet()
    {
        $mockMyRepository = $this->getMockSingleClass(
            'SchemaModule\Repository\MyRepositoryExtends'
        );
        $this->setMyRepositoryExtends($mockMyRepository);
        $this->assertEquals($mockMyRepository, $this->getMyRepositoryExtends());
    }
}
