namespace <?php echo $this->module;?>\FunctionalTester;

/**
 * @SuppressWarnings(PHPMD)
 */
class FunctionalSteps extends \<?php echo $this->module;?>\FunctionalTester
{
    public function verifyBreadcrumb($class, $module, $controller, $action)
    {
        $instance = new $class;
        $I = $this;

        $I->see($module, $instance::getBreadcrumbByIndex(1));
        $I->see($controller, $instance::getBreadcrumbByIndex(2));
        $I->see($action, $instance::getBreadcrumbByIndex(3));
        $I->seeNumberOfElements($instance::$breadscrumb, 3);
    }
}
