namespace <?php echo $this->namespace;?>\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;

class <?php echo $this->name;?>Fixture extends AbstractFixture implements
    FixtureInterface,
    OrderedFixtureInterface
{

    public function load(ObjectManager $manager)
    {


    }

    public function getFixture()
    {
        return array(
<?php foreach ($this->data as $item):?>
<?php echo $item;?>
<?php endforeach;?>

        );

    }

    public function getOrder()
    {
        return 9999;
    }
}
