namespace <?php echo $this->module;?>\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;

class <?php echo $this->name;?> extends AbstractFixture implements
    FixtureInterface,
    OrderedFixtureInterface
{

    public function load(ObjectManager $manager)
    {
        $userId = $this->getReference('admin-user');
        $user = $manager->getRepository('<?php echo $this->module?>\Entity\User')->findOneBy(array('idUser' => $userId->getIdUser()));

        foreach ($this->getFixture() as $fixture) {
            $<?php echo $this->str('var', str_replace('Fixture', '', $this->name));?> = new \<?php echo $this->module?>\Entity\<?php echo str_replace('Fixture', '', $this->name);?>();
<?php foreach ($this->fields as $field):?>
<?php echo $field.PHP_EOL;?>
<?php endforeach;?>
            $<?php echo $this->str('var', str_replace('Fixture', '', $this->name));?>->setCreated(new \DateTime('now'));
            $<?php echo $this->str('var', str_replace('Fixture', '', $this->name));?>->setCreatedBy($user->getIdUser());
            $manager->persist($<?php echo $this->str('var', str_replace('Fixture', '', $this->name));?>);
        }
        $manager->flush();
    }

    public function getFixture()
    {
        return array(
<?php foreach ($this->data as $item):?>
<?php echo $item;?>
<?php endforeach;?>

        );

    }

    public function getOrder()
    {
        return 9999;
    }
}
