namespace <?php echo $this->module;?>Test\ServiceTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Service
 */
class <?php echo $this->serviceNameClass;?>Test extends TestCase
{
<?php echo $this->static;?>
    public function setUp()
    {
        parent::setUp();

        $this->service = new \<?php echo $this->module;?>\Service\<?php echo $this->serviceNameClass;?>();

        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
        $this->service->setCache($this->cache->reveal());

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());
<?php echo $this->setUp;?>
    }
<?php echo $this->extraColumns;?>

    public function testSetSelectAllCache()
    {
        $this->service->setSessionName('testing');

        $data = $this->service->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->service->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->service->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'DESC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->service->getOrderBy());
        $this->assertEquals('DESC', $this->service->getOrder());

        $this->service->selectAll();

        $this->service->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'ASC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->service->getOrderBy());
        $this->assertEquals('ASC', $this->service->getOrder());

        $this->service->setRouteMatch(
            $this->getRouteMatch(1, 'id<?php echo $this->class;?>', 'DESC')
        );

        $this->assertEquals(
            'id<?php echo $this->class;?>',
            $this->service->getOrderBy()
        );
        $this->assertEquals('DESC', $this->service->getOrder());
    }

    public function testTableHead()
    {
        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->getMapReferences()->willReturn([***REMOVED***)->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $this->entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $this->entity->getId<?php echo $this->class;?>()->willReturn(1);

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->selectById(1)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->selectById(1);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(1, $resultSet->getId<?php echo $this->class;?>());
    }

    public function testSelectOne()
    {
        $this->entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $this->entity->getId<?php echo $this->class;?>()->willReturn(30);

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->selectOneBy(['id<?php echo $this->class;?>' => 30***REMOVED***)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->selectOneBy(
            array(
                'id<?php echo $this->class;?>' =>
                    30
            )
        );
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(
            30,
            $resultSet->getId<?php echo $this->class;?>()
        );
    }
<?php echo $this->selectbyidnull;?>

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $entity->getId<?php echo $this->class;?>()->willReturn(31);

        $data = array(
<?php echo $this->createValues;?>
        );

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

<?php echo ($this->createMock !== null) ? $this->createMock.PHP_EOL : '';?>
        $resultSet = $this->service->create($data);

        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(31, $resultSet->getId<?php echo $this->class;?>());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $entity->getId<?php echo $this->class;?>()->willReturn(31);

        $data = array(
<?php echo $this->updateValues;?>
        );

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $this->service->setCache($this->cache->reveal());

<?php echo ($this->updateMock !== null) ? $this->updateMock.PHP_EOL : '';?>
        $resultSet = $this->service
            ->update(31, $data);


        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(31, $resultSet->getId<?php echo $this->class;?>());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $entity->getId<?php echo $this->class;?>()->willReturn(31);

        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->service->setCache($this->cache->reveal());
        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {
        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>');
        $entity->getId<?php echo $this->class;?>()->willReturn(31);

        $data = ['id<?php echo $this->serviceNameClass;?>' => 31***REMOVED***;
        $this->repository = $this->prophesize('<?php echo $this->module;?>\Repository\<?php echo $this->class;?>Repository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();

        $this->service->set<?php echo $this->class;?>Repository($this->repository->reveal());

        $resultSet = $this->service->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'id<?php echo $this->class;?>', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => '<?php echo $this->module;?>\Controller\<?php echo $this->class;?>',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl;?>');
        return $routeMatch;
    }
}
