<?php
namespace MyModuleTest\ConsolistsNamespaceTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use MyModule\ConsolistsNamespace\SpecialDependencyConsoleFactory;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;
use Gear\Util\String\StringService;
use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;

/**
 * @group MyModule
 * @group SpecialDependencyConsole
 * @group Controller
 */
class SpecialDependencyConsoleFactoryTest extends TestCase
{
    public function testSpecialDependencyConsoleFactory()
    {


        $this->container = $this->prophesize(ServiceManager::class);

        $this->container->get('Gear\Util\String\StringService')
            ->willReturn($this->prophesize(StringService::class)->reveal())
            ->shouldBeCalled();

        $this->container->get('console')
            ->willReturn($this->prophesize(Posix::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();



        $factory = new SpecialDependencyConsoleFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(SpecialDependencyConsole::class, $instance);
    }
}
