<?php
namespace MyModuleTest\ConsolistsNamespaceTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use MyModule\ConsolistsNamespace\SpecialDependencyConsoleFactory;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;
use Gear\Util\String\StringService;
use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;

/**
 * @group MyModule
 * @group SpecialDependencyConsole
 * @group Controller
 */
class SpecialDependencyConsoleFactoryTest extends TestCase
{
    public function testSpecialDependencyConsoleFactory()
    {
        $this->controllerManager = $this->prophesize(ControllerManager::class);

        $this->serviceLocator = $this->prophesize(ServiceManager::class);

        $this->serviceLocator->get('Gear\Util\String\StringService')
            ->willReturn($this->prophesize(StringService::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('console')
            ->willReturn($this->prophesize(Posix::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();

        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal());

        $factory = new SpecialDependencyConsoleFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf(SpecialDependencyConsole::class, $instance);
    }
}
