namespace <?php echo $this->module;?>\Pages;

/**
 * @author Maurício Piber Fão
 * @SuppressWarnings(PHPMD)
 */
class <?php echo $this->class?>EditPage extends LayoutPage
{
    public static $URL = '/<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl?>/editar';

    use \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>FormPage;

    public static function route($param)
    {
        return static::$URL.$param;
    }
}
