namespace <?php echo $this->module;?>Test\ControllerTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use <?php echo $this->module;?>\Controller\IndexController;
use <?php echo $this->module;?>\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function setUp() : void
    {
        $this->factory = new IndexControllerFactory();

    }

    public function testCreateFactory()
    {
        $instance = $this->factory->__invoke($this->container->reveal(), null);
        $this->assertInstanceOf(IndexController::class, $instance);
    }
}
