namespace <?php echo $this->namespaceTest;?>\ControllerTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use <?php echo $this->namespace;?>\Controller\IndexController;
use <?php echo $this->namespace;?>\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function setUp()
    {
        $this->factory = new IndexControllerFactory();
        $this->controllerManager = $this->prophesize(ControllerManager::class);
    }

    public function testCreateFactory()
    {
        $instance = $this->factory->createService($this->controllerManager->reveal());
        $this->assertInstanceOf(IndexController::class, $instance);
    }
}
