namespace <?php echo $this->module;?>Test\ControllerTest;

use <?php echo $this->module?>Test\ControllerTest\AbstractControllerTestCase;

/**
 * @group Controller
 */
class IndexControllerTest extends AbstractControllerTestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->indexController = new \Coola\Controller\IndexController();
    }

    public function testCanAccessNewCreatedModule()
    {
        $resp = $this->indexController->indexAction();
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $resp);
    }
}
