namespace <?php echo $this->module;?>Test\ControllerTest;

use PHPUnit\Framework\TestCase;
use <?php echo $this->module;?>\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->container = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $factory = new IndexControllerFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf('<?php echo $this->module;?>\Controller\IndexController', $instance);
    }
}
