namespace <?php echo $this->module;?>Test\ControllerTest;

use PHPUnit_Framework_TestCase as TestCase;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');
        $this->serviceLocator->get('application')->shouldBeCalled();
        $this->serviceLocator->get('eventManager')->shouldBeCalled();

        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');
        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal())->shouldBeCalled();

        $factory = new \<?php echo $this->module;?>\Controller\IndexControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('<?php echo $this->module;?>\Controller\IndexController', $instance);
    }
}
