namespace <?php echo $this->module;?>Test\ControllerTest;

use PHPUnit\Framework\TestCase;
use <?php echo $this->module;?>\Controller\IndexController;
use Zend\Console\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;
use GearBaseTest\Assertions\AclAssertTrait;

/**
 * @group Controller
 */
class IndexControllerTest extends TestCase
{
    use AclAssertTrait;

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp() : void
    {
        parent::setUp();

        $this->controller = new IndexController();
        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'IndexController'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this->schema = \<?php echo $this->module;?>\Module::LOCATION.'/../schema/module.json';
    }

    public function testIndexAction()
    {
        $this->assertAcl(
            $this->schema,
            '<?php echo $this->module;?>',
            'IndexController',
            'Controller',
            'Index'
        );

        $this->routeMatch->setParam('action', 'index');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ConsoleModel', $result);
    }
}
