namespace <?php echo $this->module;?>\<?php echo $this->module;?>Test\EntityTest;

/**
use PHPUnit\Framework\TestCase;
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Entity
 */
class <?php echo $this->serviceNameClass;?>Test extends TestCase
{
    protected $<?php echo $this->serviceNameUline;?>;

    protected function setUp() : void
    {
        $this->bootstrap = new \<?php echo $this->module;?>\ZendServiceLocator();
    }

    protected function tearDown()
    {
        unset($this->bootstrap);
    }

    public function get<?php echo $this->serviceNameClass;?>()
    {
        if (!isset($this-><?php echo $this->serviceNameUline;?>)) {
            $this-><?php echo $this->serviceNameUline;?> =
                $this->bootstrap->get(
                    '<?php echo $this->module;?>\Entity\<?php echo $this->serviceNameClass;?>'
                );
        }
        return $this-><?php echo $this->serviceNameUline;?>;
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
     */
    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->serviceNameUline;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->serviceNameClass;?>', $<?php echo $this->serviceNameUline;?>);
    }


    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
    */
    public function testCallClassName()
    {
        $<?php echo $this->serviceNameUline;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $className = $<?php echo $this->serviceNameUline;?>->getClassName();
        $this->assertEquals('<?php echo $this->serviceNameClass;?>', $className);
    }
}
