namespace <?php echo $this->module;?>Test;

trait <?php echo $this->tableName;?>Mock
{
    public function get<?php echo $this->tableName;?>Mock()
    {
<?php echo $this->mockTable;?>
    }

    public function get<?php echo $this->tableName;?>ColumnsMock()
    {
<?php echo $this->mockColumns;?>
    }

    public function get<?php echo $this->tableName;?>ConstraintsMock()
    {
<?php echo $this->mockConstraints;?>
    }
}
