<?php
namespace SchemaModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;
use SchemaModule\Service\MyServiceExtendsTrait;

/**
 * @group Service
 */
class MyServiceExtendsTest extends AbstractTestCase
{
    use MyServiceExtendsTrait;

    /**
     * @group SchemaModule
     * @group MyServiceExtends
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getMyServiceExtends()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group SchemaModule
     * @group MyServiceExtends
    */
    public function testGet()
    {
        $myServiceExtends = $this->getMyServiceExtends();
        $this->assertInstanceOf('SchemaModule\Service\MyServiceExtends', $myServiceExtends);
    }

    /**
     * @group SchemaModule
     * @group MyServiceExtends
    */
    public function testSet()
    {
        $mockMyService = $this->getMockSingleClass(
            'SchemaModule\Service\MyServiceExtends'
        );
        $this->setMyServiceExtends($mockMyService);
        $this->assertEquals($mockMyService, $this->getMyServiceExtends());
    }
}
