<?php
namespace SchemaModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;
use SchemaModule\Service\MyServiceTrait;

/**
 * @group Service
 */
class MyServiceTest extends AbstractTestCase
{
    use MyServiceTrait;

    /**
     * @group SchemaModule
     * @group MyService
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getMyService()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group SchemaModule
     * @group MyService
    */
    public function testGet()
    {
        $myService = $this->getMyService();
        $this->assertInstanceOf('SchemaModule\Service\MyService', $myService);
    }

    /**
     * @group SchemaModule
     * @group MyService
    */
    public function testSet()
    {
        $mockMyService = $this->getMockSingleClass(
            'SchemaModule\Service\MyService'
        );
        $this->setMyService($mockMyService);
        $this->assertEquals($mockMyService, $this->getMyService());
    }
}
