<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle"><?php echo $this->translate('Edit');?>&nbsp;<?php echo $this->translate('Test Upload Image');?> - <?php echo $this->idTestUploadImage;?></h3>
	</div>
</div>
<?php if($this->success) :?>
<?php echo $this->render('layout/success');?>
<?php endif;?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('test-upload/test-upload-image/edit', array('id' => $this->idTestUploadImage)));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <?php echo $this->formHidden($form->get('idTestUploadImage')->setAttribute('class','form-control')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idTestUploadImage'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('image')); ?>
            <?php echo $this->formFile($form->get('image')); ?>
            <?php echo $this->formElementErrors($form->get('image')); ?>
        </div>
        <div class="form-group">
            <?php if ($this->image) : ?>
                <img src="<?php echo $this->image;?>" height="100" width="100"/>
            <?php endif;?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/view', array('id' => $this->idTestUploadImage));?>"><?php echo $this->translate('View');?></a>
            <a class="btn btn-primary" href="<?php echo $this->url('test-upload/test-upload-image/create');?>"><?php echo $this->translate('Create');?></a>
            <a class="btn btn-default reset" href="<?php echo $this->url('test-upload/test-upload-image/list');?>"><?php echo $this->translate('Back');?></a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>