<tr>

        <td>
            <?php echo $this->escapeHtml($this->idTestUploadImage); ?>
        </td>
    <td>
        <a href="<?php echo $this->url('test-upload/test-upload-image/view', array('id' => $this->idTestUploadImage)); ?>">
            <span class="glyphicon glyphicon-resize-full"></span>
        </a>
        <a href="<?php echo $this->url('test-upload/test-upload-image/edit', array('id' => $this->idTestUploadImage)); ?>">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('test-upload/test-upload-image/delete', array('id' => $this->idTestUploadImage)); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Test Upload Image" data-message="<?php echo $this->translate('Desejas realmente deletar Test Upload Image?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>