<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo $this->translate('View');?>&nbsp;<?php echo $this->translate('Test Upload Image');?> - <?php echo $this->id;?></h3>
	</div>
</div>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <div class="form-group">
            <table id="viewData" class="viewData">
                <tbody>
                        <tr><td><?php echo $this->translate('ID');?></td><td><?php echo $this->escapeHtml($this->idTestUploadImage);?></td></tr>
                <tr>
            <td><?php echo $this->translate('Image');?></td>
            <td>
                <?php if ($this->image !== null) : ?>
                    <img src="<?php echo str_replace('/public', '', sprintf($this->image, 'pre'));?>">
                <?php endif; ?>
            </td>
        </tr>
                    </tbody>
            </table>
        </div>
        <div class="form-group">
            <a id="btnBack" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/list');?>"><?php echo $this->translate('Back');?></a>
            <a id="btnPrev" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/view', array('id' => $this->id-1));?>"><?php echo $this->translate('Prev');?></a>
            <a id="btnNext" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/view', array('id' => $this->id+1));?>"><?php echo $this->translate('Next');?></a>
            <a id="btnEdit" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/edit', array('id' => $this->id));?>"><?php echo $this->translate('Edit');?></a>
            <a id="btnDelete" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/create');?>"><?php echo $this->translate('New');?></a>
            <a id="btnCreate" class="btn btn-default" href="<?php echo $this->url('test-upload/test-upload-image/delete', array('id' => $this->id));?>"><?php echo $this->translate('Delete');?></a>
        </div>    </div>
</div>