namespace <?php echo $this->module;?>Test\ControllerTest;

use PHPUnit_Framework_TestCase as TestCase;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $factory = new \<?php echo $this->module;?>\Controller\IndexControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('<?php echo $this->module;?>\Controller\IndexController', $instance);
    }
}
