<?php
namespace MyModule\Form\Search;

use Interop\Container\ContainerInterface;
use GearBase\Factory\AbstractFactory;
use MyModule\Form\Search\MyTableSearchForm;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Form/Search
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableSearchFormFactory extends AbstractFactory
{

    /**
     * Create MyTableSearchForm
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MyTableSearchForm
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $form = new MyTableSearchForm(
            $container->get('doctrine.entitymanager.orm_default')
        );
        return $form;
    }
}
