<?php
namespace MyModule\Form\Search;

use Zend\ServiceManager\ServiceLocatorInterface;
use GearBase\Factory\AbstractFactory;
use MyModule\Form\Search\MyTableSearchForm;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Form/Search
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableSearchFormFactory extends AbstractFactory
{

    /**
     * Create MyTableSearchForm
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     *
     * @return MyTableSearchForm
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new MyTableSearchForm(
            $serviceLocator->get('doctrine.entitymanager.orm_default')
        );
        return $form;
    }
}
