namespace AcceptanceTester;

/**
 * @SuppressWarnings(PHPMD)
 */
class AbstractCest
{
// @codingStandardsIgnoreStart
    public function _before(\AcceptanceTester $I)
    {
// @codingStandardsIgnoreEnd
        \TesteTest\LoginCommons::logMeIn($I);
    }
// @codingStandardsIgnoreStart
    public function _after(\AcceptanceTester $I)
    {
// @codingStandardsIgnoreEnd
        \TesteTest\LoginCommons::logMeOut($I);
    }
}
