namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;

/**
 * @SuppressWarnings(PHPMD)
 */
class AbstractCest
{
// @codingStandardsIgnoreStart
    public function _before(AcceptanceTester $I)
    {
// @codingStandardsIgnoreEnd
        \<?php echo $this->module;?>\LoginCommons::logMeIn($I);
    }

// @codingStandardsIgnoreStart
    public function _after(AcceptanceTester $I)
    {
// @codingStandardsIgnoreEnd
        \<?php echo $this->module;?>\LoginCommons::logMeOut($I);
    }
}
