/**
 * @SuppressWarning(PHPMD)
 * @guy AcceptanceTester\ViewSteps
 */
class EmailViewCest extends \AcceptanceTester\AbstractCest
{
    protected $fixture;

    public function _before(\AcceptanceTester $I)
    {
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
        <?php echo $this->fixtureHaveInDatabase;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 1
            )
        );
        parent::_before($I);
    }

    public function viewSuccessful(\AcceptanceTester $I)
    {
        $I->wantTo('View <?php echo $this->classLabel;?> Successful');
        $I->verifyOnPage('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage', '<?php echo $this->classLabel;?>', $this->fixture);
<?php echo $this->seeLabels;?>
<?php echo $this->seeValues;?>
    }
}
