/**
 * @SuppressWarning(PHPMD)
 * @guy AcceptanceTester\EditSteps
 */
class <?php echo $this->class;?>EditCest extends \AcceptanceTester\AbstractCest
{
    protected $fixture;

    public function _before(\AcceptanceTester $I)
    {

        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixtureHaveInDatabase;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 1
            )
        );
        parent::_before($I);
    }

    public function editSuccessful(\AcceptanceTester $I)
    {
        $I->wantTo('Edit <?php echo $this->classLabel;?> Successful');

        $I->verifyOnPage('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage', '<?php echo $this->classLabel;?> - '.$this->fixture, $this->fixture);

        $I->verifySubmitAndReturnSuccessful('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage', $this->fixture);

<?php echo $this->seeInFields;?>

<?php echo $this->fillField;?>

        $I->verifySubmitAndReturnSuccessful('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage', $this->fixture);

<?php echo $this->seeInFieldAfterFill;?>
    }
}
