namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\AcceptanceTester\DeleteSteps;

/**
 * @SuppressWarnings(PHPMD)
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group Delete
 */
class <?php echo $this->class;?>DeleteCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(DeleteSteps $I)
    {
// @codingStandardsIgnoreEnd
<?php echo $this->preFixture;?>
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixture;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );
        parent::_before($I);
    }

    public function deleteSuccessful(DeleteSteps $I)
    {
        $I->wantTo('Delete <?php echo $this->classLabel;?> Successful');
        $I->verifyCanViewBeforeDelete(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage',
            '<?php echo $this->classLabel;?>',
            $this->fixture
        );
        $I->verifyFilterInstanceBeforeDelete('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage', 31);
        $I->verifyDeleteSuccessfulFromTableIndex(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage',
            '<?php echo $this->classLabel;?>'
        );
    }
}
