/**
 * @SuppressWarnings(PHPMD)
 * @guy AcceptanceTester\DeleteSteps
 */
class <?php echo $this->class;?>DeleteCest extends \AcceptanceTester\AbstractCest
{
    protected $fixture;

    public function _before(\AcceptanceTester $I)
    {
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixtureHaveInDatabase;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 1
            )
        );
        parent::_before($I);
    }

    public function deleteSuccessful(\AcceptanceTester $I)
    {
        $I->wantTo('Delete <?php echo $this->classLabel;?> Successful');
        $I->verifyCanViewBeforeDelete('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage', '<?php echo $this->classLabel;?>', $this->fixture);
        $I->verifyFilterInstanceBeforeDelete('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage', 999);
        $I->verifyDeleteSuccessfulFromTableIndex('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage', '<?php echo $this->classLabel;?>', <?php echo $this->actionRow;?>);
    }
}
