/**
 * @SuppressWarnings(PHPMD)
 * @guy AcceptanceTester\ListSteps
 */
class <?php echo $this->class;?>ListCest extends \AcceptanceTester\AbstractCest
{
    public function listSuccessful(\AcceptanceTester $I)
    {
        $I->wantTo('List <?php echo $this->classLabel;?> Successful');
        $I->verifyOnPage('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', '<?php echo $this->classLabel;?>');
        $I->verifyHeadTable('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', <?php echo $this->tableHeadCount;?>);
        $I->verifyFirstListing('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyFilterByLike('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyResetFilter('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyPaginator('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyOrdenationById('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
    }
}
