/**
 * @author Maurício Piber Fão
 * @SuppressWarning(PHPMD)
 */
$I = new \AcceptanceTester($scenario);
\<?php echo $this->module;?>Test\LoginCommons::logMeIn($I);

$I->wantTo('Create <?php echo $this->class;?>');
$I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage::$URL);
$I->see('Criar <?php echo $this->class;?>');

<?php echo $this->fillField;?>

$I->click(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage::$submit);

$I->see('Sucesso! Os dados foram salvos corretamente.');

$I->seeCurrentUrlEquals(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage::$URL.'/31/1');

<?php echo $this->seeInFields;?>

\<?php echo $this->module;?>Test\LoginCommons::logMeOut($I);
