namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;

/**
 * @SuppressWarnings(PHPMD)
 * @guy <?php echo $this->module;?>\AcceptanceTester\ListSteps
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group List
 */
class <?php echo $this->class;?>ListCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    public function listSuccessful(AcceptanceTester $I)
    {
        $I->wantTo('List <?php echo $this->classLabel;?> Successful');
        $I->verifyOnPage('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', '<?php echo $this->classLabel;?>');
        $I->verifyHeadTable('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', <?php echo $this->tableHeadCount;?>);
        $I->verifyFirstListing('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyFilterByLike('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyResetFilter('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyPaginator('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyOrdenationById('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
    }
}
