namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage;
use <?php echo $this->module;?>\AcceptanceTester\CreateSteps;

/**
 * @SuppressWarnings(PHPMD)
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group Create
 */
class <?php echo $this->class;?>CreateCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    public function createSuccessful(CreateSteps $I)
    {
        $I->wantTo('Create <?php echo $this->classLabel;?> Successful');

        $I->verifyOnPage('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage', '<?php echo $this->classLabel;?>');
<?php echo $this->fillField;?>

        $I->verifyCreateSuccessful(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage',
            <?php echo $this->idElement.PHP_EOL?>
        );
<?php echo $this->seeInField;?>
    }
}
