namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage;
use <?php echo $this->module;?>\AcceptanceTester\EditSteps;

/**
 * @SuppressWarnings(PHPMD)
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group Edit
 */
class <?php echo $this->class;?>EditCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(EditSteps $I)
    {
// @codingStandardsIgnoreEnd
<?php echo $this->preFixture;?>
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixture;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );
        parent::_before($I);
    }

    public function edit<?php echo $this->class;?>(EditSteps $I)
    {
        $I->wantTo('Edit <?php echo $this->classLabel;?> Successful');

        $I->verifyOnPage(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage',
            '<?php echo $this->classLabel;?> - '.$this->fixture,
            $this->fixture
        );

        $I->verifySubmitAndReturnSuccessful('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage', $this->fixture);

<?php echo $this->seeInField;?>

<?php echo $this->fillField;?>

        $I->verifySubmitAndReturnSuccessful('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage', $this->fixture);

<?php echo $this->seeInFieldAfter;?>

    }
}
