namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;

/**
 * @SuppressWarnings(PHPMD)
 * @guy <?php echo $this->module;?>\AcceptanceTester\CreateSteps
 */
class <?php echo $this->class;?>CreateCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    public function createSuccessful(AcceptanceTester $I)
    {
        $I->wantTo('Create <?php echo $this->classLabel;?> Successful');

        $I->verifyOnPage('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage', '<?php echo $this->classLabel;?>');
<?php echo $this->fillField;?>
<?php echo $this->fillFieldJS;?>
<?php echo $this->fillFieldCheckbox;?>
<?php echo $this->fillFieldSelect;?>
        $I->verifyCreateSuccessful('<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage', '<?php echo $this->classLabel;?>');
<?php echo $this->seeInFields;?>
<?php echo $this->seeInFieldsCheckbox;?>
<?php echo $this->seeInFieldsSelect;?>
    }
}
