namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\Acceptance\AbstractCest;

/**
 * @SuppressWarnings(PHPMD)
 */
class ModuleMainPageCest extends AbstractCest
{
    public function seeModuleMainPageCest(AcceptanceTester $I)
    {
        $I->wantTo('See the message of module creation was sucessfull');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\ModuleMainPage::$URL);
        $I->see('<?php echo $this->moduleLabel;?> module was created sucessfull with Gear Engine Version <?php echo $this->version;?>');
    }
}
