<?php
namespace Column\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use GearImage\Fixture as ImagemFixtureTrait;

class ColumnsFixture extends AbstractFixture implements
    FixtureInterface,
    OrderedFixtureInterface
{
    use ImagemFixtureTrait;
    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;

        foreach ($this->getFixture() as $i => $fixture) {
            $reference = $i+1;
            $columns = new \Column\Entity\Columns();
            $columns->setColumnDate($fixture['columnDate'***REMOVED***);
            $columns->setColumnDatetime($fixture['columnDatetime'***REMOVED***);
            $columns->setColumnTime($fixture['columnTime'***REMOVED***);
            $columns->setColumnInt($fixture['columnInt'***REMOVED***);
            $columns->setColumnTinyint($fixture['columnTinyint'***REMOVED***);
            $columns->setColumnDecimal($fixture['columnDecimal'***REMOVED***);
            $columns->setColumnVarchar($fixture['columnVarchar'***REMOVED***);
            $columns->setColumnLongtext($fixture['columnLongtext'***REMOVED***);
            $columns->setColumnText($fixture['columnText'***REMOVED***);
            $columns->setColumnDatetimePtBr($fixture['columnDatetimePtBr'***REMOVED***);
            $columns->setColumnDatePtBr($fixture['columnDatePtBr'***REMOVED***);
            $columns->setColumnDecimalPtBr($fixture['columnDecimalPtBr'***REMOVED***);
            $columns->setColumnIntCheckbox($fixture['columnIntCheckbox'***REMOVED***);
            $columns->setColumnTinyintCheckbox($fixture['columnTinyintCheckbox'***REMOVED***);
            $columns->setColumnVarcharEmail($fixture['columnVarcharEmail'***REMOVED***);
            $columns->setColumnVarcharPasswordVerify($fixture['columnVarcharPasswordVerify'***REMOVED***);
            $columns->setColumnVarcharUniqueId($fixture['columnVarcharUniqueId'***REMOVED***);
            $columns->setColumnVarcharUploadImage($fixture['columnVarcharUploadImage'***REMOVED***);
            $columns->setColumnForeignKey($fixture['columnForeignKey'***REMOVED***);
            $userReferenced = $this->getReferenceToEntity($reference);
            $columns->setCreated(new \DateTime('now'));
            $columns->setCreatedBy($userReferenced);
            $this->manager->persist($columns);
            $this->manager->flush();
            $this->addReference("columns-$reference", $columns);
        }

    }

/**
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */

    public function getFixture()
    {
        return array(
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-01'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-01 01:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '01:00:02'),
                'columnInt' => '1',
                'columnTinyint' => '1',
                'columnDecimal' => '1.1',
                'columnVarchar' => '01Column Varchar',
                'columnLongtext' => '01Column Longtext',
                'columnText' => '01Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-01 01:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-01'),
                'columnDecimalPtBr' => '1.1',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email01@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc236e2e5.72923458',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 1, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-1'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-02'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-02 02:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '02:00:02'),
                'columnInt' => '2',
                'columnTinyint' => '2',
                'columnDecimal' => '2.2',
                'columnVarchar' => '02Column Varchar',
                'columnLongtext' => '02Column Longtext',
                'columnText' => '02Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-02 02:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-02'),
                'columnDecimalPtBr' => '2.2',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email02@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2375414.64472095',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 2, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-2'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-03'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-03 03:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '03:00:02'),
                'columnInt' => '3',
                'columnTinyint' => '3',
                'columnDecimal' => '3.3',
                'columnVarchar' => '03Column Varchar',
                'columnLongtext' => '03Column Longtext',
                'columnText' => '03Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-03 03:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-03'),
                'columnDecimalPtBr' => '3.3',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email03@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc237b777.02206015',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 3, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-3'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-04'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-04 04:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '04:00:02'),
                'columnInt' => '4',
                'columnTinyint' => '4',
                'columnDecimal' => '4.4',
                'columnVarchar' => '04Column Varchar',
                'columnLongtext' => '04Column Longtext',
                'columnText' => '04Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-04 04:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-04'),
                'columnDecimalPtBr' => '4.4',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email04@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2381e54.38643223',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 4, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-4'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-05'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-05 05:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '05:00:02'),
                'columnInt' => '5',
                'columnTinyint' => '5',
                'columnDecimal' => '5.5',
                'columnVarchar' => '05Column Varchar',
                'columnLongtext' => '05Column Longtext',
                'columnText' => '05Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-05 05:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-05'),
                'columnDecimalPtBr' => '5.5',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email05@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2387fc2.18382693',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 5, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-5'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-06'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-06 06:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '06:00:02'),
                'columnInt' => '6',
                'columnTinyint' => '6',
                'columnDecimal' => '6.6',
                'columnVarchar' => '06Column Varchar',
                'columnLongtext' => '06Column Longtext',
                'columnText' => '06Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-06 06:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-06'),
                'columnDecimalPtBr' => '6.6',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email06@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc238e198.48662670',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 6, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-6'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-07'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-07 07:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '07:00:02'),
                'columnInt' => '7',
                'columnTinyint' => '7',
                'columnDecimal' => '7.7',
                'columnVarchar' => '07Column Varchar',
                'columnLongtext' => '07Column Longtext',
                'columnText' => '07Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-07 07:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-07'),
                'columnDecimalPtBr' => '7.7',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email07@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2397525.51619518',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 7, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-7'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-08'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-08 08:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '08:00:02'),
                'columnInt' => '8',
                'columnTinyint' => '8',
                'columnDecimal' => '8.8',
                'columnVarchar' => '08Column Varchar',
                'columnLongtext' => '08Column Longtext',
                'columnText' => '08Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-08 08:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-08'),
                'columnDecimalPtBr' => '8.8',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email08@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc239e265.82008388',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 8, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-8'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-09'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-09 09:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '09:00:02'),
                'columnInt' => '9',
                'columnTinyint' => '9',
                'columnDecimal' => '9.9',
                'columnVarchar' => '09Column Varchar',
                'columnLongtext' => '09Column Longtext',
                'columnText' => '09Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-09 09:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-09'),
                'columnDecimalPtBr' => '9.9',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email09@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23a43b1.90669286',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 9, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-9'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-10'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-10 10:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '10:00:02'),
                'columnInt' => '10',
                'columnTinyint' => '10',
                'columnDecimal' => '10.10',
                'columnVarchar' => '10Column Varchar',
                'columnLongtext' => '10Column Longtext',
                'columnText' => '10Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-10 10:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-10'),
                'columnDecimalPtBr' => '10.10',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email10@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23aa4c8.80478176',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 10, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-10'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-11'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-11 11:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '11:00:02'),
                'columnInt' => '11',
                'columnTinyint' => '11',
                'columnDecimal' => '11.11',
                'columnVarchar' => '11Column Varchar',
                'columnLongtext' => '11Column Longtext',
                'columnText' => '11Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-11 11:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-11'),
                'columnDecimalPtBr' => '11.11',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email11@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23b08c2.95940597',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 11, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-11'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-12'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-12 12:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '12:00:02'),
                'columnInt' => '12',
                'columnTinyint' => '12',
                'columnDecimal' => '12.12',
                'columnVarchar' => '12Column Varchar',
                'columnLongtext' => '12Column Longtext',
                'columnText' => '12Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-12 12:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-12'),
                'columnDecimalPtBr' => '12.12',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email12@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23b6966.31724806',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 12, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-12'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-13'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-13 13:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '13:00:02'),
                'columnInt' => '13',
                'columnTinyint' => '13',
                'columnDecimal' => '13.13',
                'columnVarchar' => '13Column Varchar',
                'columnLongtext' => '13Column Longtext',
                'columnText' => '13Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-13 13:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-13'),
                'columnDecimalPtBr' => '13.13',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email13@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23bcb80.45839489',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 13, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-13'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-14'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-14 14:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '14:00:02'),
                'columnInt' => '14',
                'columnTinyint' => '14',
                'columnDecimal' => '14.14',
                'columnVarchar' => '14Column Varchar',
                'columnLongtext' => '14Column Longtext',
                'columnText' => '14Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-14 14:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-14'),
                'columnDecimalPtBr' => '14.14',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email14@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23c30b7.04680306',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 14, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-14'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-15'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-15 15:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '15:00:02'),
                'columnInt' => '15',
                'columnTinyint' => '15',
                'columnDecimal' => '15.15',
                'columnVarchar' => '15Column Varchar',
                'columnLongtext' => '15Column Longtext',
                'columnText' => '15Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-15 15:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-15'),
                'columnDecimalPtBr' => '15.15',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email15@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23c9a60.78798630',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 15, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-15'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-16'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-16 16:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '16:00:02'),
                'columnInt' => '16',
                'columnTinyint' => '16',
                'columnDecimal' => '16.16',
                'columnVarchar' => '16Column Varchar',
                'columnLongtext' => '16Column Longtext',
                'columnText' => '16Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-16 16:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-16'),
                'columnDecimalPtBr' => '16.16',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email16@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23cfe75.33785776',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 16, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-16'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-17'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-17 17:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '17:00:02'),
                'columnInt' => '17',
                'columnTinyint' => '17',
                'columnDecimal' => '17.17',
                'columnVarchar' => '17Column Varchar',
                'columnLongtext' => '17Column Longtext',
                'columnText' => '17Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-17 17:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-17'),
                'columnDecimalPtBr' => '17.17',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email17@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23d5ee0.29927749',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 17, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-17'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-18'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-18 18:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '18:00:02'),
                'columnInt' => '18',
                'columnTinyint' => '18',
                'columnDecimal' => '18.18',
                'columnVarchar' => '18Column Varchar',
                'columnLongtext' => '18Column Longtext',
                'columnText' => '18Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-18 18:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-18'),
                'columnDecimalPtBr' => '18.18',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email18@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23dc2e6.55893724',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 18, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-18'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-19'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-19 19:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '19:00:02'),
                'columnInt' => '19',
                'columnTinyint' => '19',
                'columnDecimal' => '19.19',
                'columnVarchar' => '19Column Varchar',
                'columnLongtext' => '19Column Longtext',
                'columnText' => '19Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-19 19:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-19'),
                'columnDecimalPtBr' => '19.19',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email19@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23e26b8.47589338',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 19, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-19'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-20'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-20 20:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '20:00:02'),
                'columnInt' => '20',
                'columnTinyint' => '20',
                'columnDecimal' => '20.20',
                'columnVarchar' => '20Column Varchar',
                'columnLongtext' => '20Column Longtext',
                'columnText' => '20Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-20 20:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-20'),
                'columnDecimalPtBr' => '20.20',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email20@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23e8af7.06181539',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 20, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-20'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-21'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-21 21:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '21:00:02'),
                'columnInt' => '21',
                'columnTinyint' => '21',
                'columnDecimal' => '21.21',
                'columnVarchar' => '21Column Varchar',
                'columnLongtext' => '21Column Longtext',
                'columnText' => '21Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-21 21:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-21'),
                'columnDecimalPtBr' => '21.21',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email21@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23eee57.21769895',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 21, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-21'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-22'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-22 22:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '22:00:02'),
                'columnInt' => '22',
                'columnTinyint' => '22',
                'columnDecimal' => '22.22',
                'columnVarchar' => '22Column Varchar',
                'columnLongtext' => '22Column Longtext',
                'columnText' => '22Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-22 22:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-22'),
                'columnDecimalPtBr' => '22.22',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email22@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23f50d7.98847361',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 22, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-22'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-23'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-23 23:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '23:00:02'),
                'columnInt' => '23',
                'columnTinyint' => '23',
                'columnDecimal' => '23.23',
                'columnVarchar' => '23Column Varchar',
                'columnLongtext' => '23Column Longtext',
                'columnText' => '23Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-23 23:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-23'),
                'columnDecimalPtBr' => '23.23',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email23@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc23fbbd6.39793785',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 23, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-23'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-24'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-24 06:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '06:00:02'),
                'columnInt' => '24',
                'columnTinyint' => '24',
                'columnDecimal' => '24.24',
                'columnVarchar' => '24Column Varchar',
                'columnLongtext' => '24Column Longtext',
                'columnText' => '24Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-24 06:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-24'),
                'columnDecimalPtBr' => '24.24',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email24@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2402959.05325975',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 24, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-24'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-25'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-25 05:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '05:00:02'),
                'columnInt' => '25',
                'columnTinyint' => '25',
                'columnDecimal' => '25.25',
                'columnVarchar' => '25Column Varchar',
                'columnLongtext' => '25Column Longtext',
                'columnText' => '25Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-25 05:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-25'),
                'columnDecimalPtBr' => '25.25',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email25@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc240ac04.62614592',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 25, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-25'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-26'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-26 04:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '04:00:02'),
                'columnInt' => '26',
                'columnTinyint' => '26',
                'columnDecimal' => '26.26',
                'columnVarchar' => '26Column Varchar',
                'columnLongtext' => '26Column Longtext',
                'columnText' => '26Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-26 04:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-26'),
                'columnDecimalPtBr' => '26.26',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email26@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2414b69.52052895',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 26, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-26'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-27'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-27 03:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '03:00:02'),
                'columnInt' => '27',
                'columnTinyint' => '27',
                'columnDecimal' => '27.27',
                'columnVarchar' => '27Column Varchar',
                'columnLongtext' => '27Column Longtext',
                'columnText' => '27Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-27 03:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-27'),
                'columnDecimalPtBr' => '27.27',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email27@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc241b316.15952768',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 27, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-27'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-28'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-28 02:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '02:00:02'),
                'columnInt' => '28',
                'columnTinyint' => '28',
                'columnDecimal' => '28.28',
                'columnVarchar' => '28Column Varchar',
                'columnLongtext' => '28Column Longtext',
                'columnText' => '28Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-28 02:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-28'),
                'columnDecimalPtBr' => '28.28',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email28@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc24214f3.44596395',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 28, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-28'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-29'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-29 01:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '01:00:02'),
                'columnInt' => '29',
                'columnTinyint' => '29',
                'columnDecimal' => '29.29',
                'columnVarchar' => '29Column Varchar',
                'columnLongtext' => '29Column Longtext',
                'columnText' => '29Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-29 01:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-29'),
                'columnDecimalPtBr' => '29.29',
                'columnIntCheckbox' => '1',
                'columnTinyintCheckbox' => '1',
                'columnVarcharEmail' => 'column.varchar.email29@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc2427e73.94938283',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 29, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-29'),
            ),
            array(
                'columnDate' => \DateTime::createFromFormat('Y-m-d', '2020-12-30'),
                'columnDatetime' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-30 00:00:02'),
                'columnTime' => \DateTime::createFromFormat('H:i:s', '00:00:02'),
                'columnInt' => '30',
                'columnTinyint' => '30',
                'columnDecimal' => '30.30',
                'columnVarchar' => '30Column Varchar',
                'columnLongtext' => '30Column Longtext',
                'columnText' => '30Column Text',
                'columnDatetimePtBr' => \DateTime::createFromFormat('Y-m-d H:i:s', '2020-12-30 00:00:02'),
                'columnDatePtBr' => \DateTime::createFromFormat('Y-m-d', '2020-12-30'),
                'columnDecimalPtBr' => '30.30',
                'columnIntCheckbox' => '0',
                'columnTinyintCheckbox' => '0',
                'columnVarcharEmail' => 'column.varchar.email30@gmail.com',
                'columnVarcharPasswordVerify' => '$2y$14$fsnuvWLBU4JH1ygNyGQAn.r2FvXNKD/RwcDj0Zcpmoj5CW6.RfLHG',
                'columnVarcharUniqueId' => '1553c9bc242e1f4.07953187',
                'columnVarcharUploadImage' => $this->createUploadImageFixture('columns', 'columnVarcharUploadImage', 30, $moduleDir),
                'columnForeignKey' => $this->getReference('foreign-keys-30'),
            ),

        );

    }

/**
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 */
    public function getReferenceToEntity($referenced = 1)
    {
        $referenced = 1;
        $referencedName = sprintf('usuariogear%d', $referenced);

        $userId = $this->getReference($referencedName);
        return $this->manager
          ->getRepository('Security\Entity\User')
          ->findOneBy(array('idUser' => $userId->getIdUser()));
    }

    public function getOrder()
    {
        return 9997;
    }
}
