namespace <?php echo $this->module;?>Test\<?php echo $this->namespace; ?>;

use PHPUnit_Framework_TestCase as TestCase;
use <?php echo $this->fullclass;?>Trait;
use <?php echo $this->fullclass;?>;

/**
 * @group <?php echo $this->module.PHP_EOL; ?>
 * @group <?php echo $this->class.PHP_EOL; ?>
 * @group <?php echo $this->group.PHP_EOL; ?>
 */
class <?php echo $this->class;?>TraitTest extends TestCase
{
    use <?php echo $this->class;?>Trait;

    public function setUp()
    {
        $this-><?php echo $this->var;?>Mock = $this->prophesize(<?php echo $this->class;?>::class);
    }

    public function testGetEmpty()
    {
        $<?php echo $this->length;?> = $this->get<?php echo $this->class;?>();
        $this->assertNull($<?php echo $this->length;?>);
    }

    public function testSet()
    {
        $this->set<?php echo $this->class;?>($this-><?php echo $this->var;?>Mock->reveal());
        $<?php echo $this->length;?> = $this->get<?php echo $this->class;?>();

        $this->assertInstanceOf(
            <?php echo $this->class;?>::class,
            $<?php echo $this->length.PHP_EOL;?>
        );

        $this->assertEquals(
            $this-><?php echo $this->var;?>Mock->reveal(),
            $<?php echo $this->length.PHP_EOL;?>
        );
    }
}
