namespace <?php echo $this->namespace;?>;

use <?php echo $this->callable; ?>;

<?php echo $this->classDocs;?>
trait <?= $this->srcName;?>Trait
{
    protected $<?= $this->var;?>;

    /**
     * Get <?php echo $this->label.PHP_EOL;?>
     *
     * @return <?php echo $this->namespace;?>\<?= $this->srcName.PHP_EOL;?>
     */
    public function get<?= $this->srcName;?>()
    {
        return $this-><?= $this->var;?>;
    }

    /**
     * Set <?php echo $this->label.PHP_EOL;?>
     *
     * @param <?= $this->srcName;?> $<?= $this->lenght;?> <?php echo $this->label.PHP_EOL;?>
     *
     * @return \<?php echo $this->namespace;?>\<?= $this->srcName.PHP_EOL;?>
     */
    public function set<?= $this->srcName;?>(
        <?= $this->srcName;?> $<?= $this->lenght.PHP_EOL;?>
    ) {
        $this-><?= $this->var;?> = $<?= $this->lenght;?>;
        return $this;
    }
}
