namespace <?php echo $this->namespace;?>;

use <?php echo $this->callable; ?>;

trait <?= $this->srcName;?>Trait
{
    protected $<?= $this->var;?>;

    public function get<?= $this->srcName;?>()
    {
        if (!isset($this-><?= $this->var;?>)) {
            $name = '<?= $this->service;?>';
            $this-><?= $this->var;?> = $this->getServiceLocator()->get($name);
        }
        return $this-><?= $this->var;?>;
    }

    public function set<?= $this->srcName;?>(
        <?= $this->srcName;?> $<?= $this->lenght.PHP_EOL;?>
    ) {
        $this-><?= $this->var;?> = $<?= $this->lenght;?>;
        return $this;
    }
}
