<?php
return array(
    'factories' => array(
        'navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory',
        'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
    ),
    'aliases' => array(
        'translator' => 'MvcTranslator'
    ),
    'invokables' => array(
    ),
    'factories' => array(
        'MyFolder\MyOtherFolder\PrimeiroTeste' =>
            'MyFolder\MyOtherFolder\PrimeiroTesteFactory'
    ),
);
