<?php
namespace SchemaModule\Service;

use SchemaModule\Service\MyServiceMultiDependency;

trait MyServiceMultiDependencyTrait
{
    protected $myServiceMultiDependency;

    public function getMyServiceMultiDependency()
    {
        if (!isset($this->myServiceMultiDependency)) {
            $serviceName = 'SchemaModule\Service\MyServiceMultiDependency';
            $this->myServiceMultiDependency = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myServiceMultiDependency;
    }

    public function setMyServiceMultiDependency(
        MyServiceMultiDependency $myServiceMulti
    ) {
        $this->myServiceMultiDependency = $myServiceMulti;
        return $this;
    }
}
