<?php
namespace SchemaModule\Repository;

use SchemaModule\Repository\MyRepositoryExtends;

trait MyRepositoryExtendsTrait
{
    protected $myRepositoryExtends;

    public function getMyRepositoryExtends()
    {
        if (!isset($this->myRepositoryExtends)) {
            $serviceName = 'SchemaModule\Repository\MyRepositoryExtends';
            $this->myRepositoryExtends = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myRepositoryExtends;
    }

    public function setMyRepositoryExtends(
        MyRepositoryExtends $myRepositoryExtends
    ) {
        $this->myRepositoryExtends = $myRepositoryExtends;
        return $this;
    }
}
