<?php
namespace SchemaModule\Service;

use SchemaModule\Service\MyService;

trait MyServiceTrait
{
    protected $myService;

    public function getMyService()
    {
        if (!isset($this->myService)) {
            $serviceName = 'SchemaModule\Service\MyService';
            $this->myService = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myService;
    }

    public function setMyService(
        MyService $myService
    ) {
        $this->myService = $myService;
        return $this;
    }
}
