<?php
namespace SchemaModule\Repository;

use SchemaModule\Repository\MyRepositoryExtendsDependency;

trait MyRepositoryExtendsDependencyTrait
{
    protected $myRepositoryExtendsDependency;

    public function getMyRepositoryExtendsDependency()
    {
        if (!isset($this->myRepositoryExtendsDependency)) {
            $serviceName = 'SchemaModule\Repository\MyRepositoryExtendsDependency';
            $this->myRepositoryExtendsDependency = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myRepositoryExtendsDependency;
    }

    public function setMyRepositoryExtendsDependency(
        MyRepositoryExtendsDependency $myRepositoryExtends
    ) {
        $this->myRepositoryExtendsDependency = $myRepositoryExtends;
        return $this;
    }
}
