<?php
namespace SchemaModule\Service;

use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorAwareTrait;
use SchemaModule\Service\OtherServiceTrait;
use SchemaModule\Service\AnotherServiceTrait;
use SchemaModule\Repository\OtherRepositoryTrait;

class MyServiceMultiDependency implements ServiceLocatorAwareInterface
{
    use ServiceLocatorAwareTrait;
    use OtherServiceTrait;
    use AnotherServiceTrait;
    use OtherRepositoryTrait;
}
