<?php
namespace SchemaModule\Repository;

use SchemaModule\Repository\MyRepository;

trait MyRepositoryTrait
{
    protected $myRepository;

    public function getMyRepository()
    {
        if (!isset($this->myRepository)) {
            $serviceName = 'SchemaModule\Repository\MyRepository';
            $this->myRepository = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myRepository;
    }

    public function setMyRepository(
        MyRepository $myRepository
    ) {
        $this->myRepository = $myRepository;
        return $this;
    }
}
