<?php
namespace SchemaModule\Service;

use SchemaModule\Service\MyServiceExtendsDependency;

trait MyServiceExtendsDependencyTrait
{
    protected $myServiceExtendsDependency;

    public function getMyServiceExtendsDependency()
    {
        if (!isset($this->myServiceExtendsDependency)) {
            $serviceName = 'SchemaModule\Service\MyServiceExtendsDependency';
            $this->myServiceExtendsDependency = $this->getServiceLocator()->get($serviceName);
        }
        return $this->myServiceExtendsDependency;
    }

    public function setMyServiceExtendsDependency(
        MyServiceExtendsDependency $myServiceExtendsDependency
    ) {
        $this->myServiceExtendsDependency = $myServiceExtendsDependency;
        return $this;
    }
}
