namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;

/**
 * @SuppressWarnings(PHPMD)
 * @guy <?php echo $this->module;?>\AcceptanceTester\ListSteps
 */
class <?php echo $this->class;?>ListCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    public function listSuccessful(AcceptanceTester $I)
    {
        $I->wantTo('List <?php echo $this->classLabel;?> Successful');
        $I->verifyOnPage('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', '<?php echo $this->classLabel;?>');
        $I->verifyHeadTable('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', <?php echo $this->tableHeadCount;?>);
        $I->verifyFirstListing('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', 5, false);
        $I->verifyFilterByLike('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', array(3,5));
        $I->verifyResetFilter('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', 5, 5);
        $I->verifyPaginator('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', false);
        $I->verifyOrdenationById('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', 1, 5, 5, 1, 5);
    }
}
