namespace <?php echo $this->module;?>\Form\Search;

use GearBase\Form\Search\AbstractSearchForm;
use Doctrine\ORM\EntityManager;
use Zend\Form\Element;

/**
 * Search Form for <?php echo $this->tableLabel;?> Controller.
 *
 * PHP Version 5
 *
 * @category Form
 * @package <?php echo $this->package.PHP_EOL;?>
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class <?php echo $this->class;?>SearchForm extends AbstractSearchForm
{

    /**
     * Construct Controller
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @param EntityManager $entityManager EntityManager
     *
     * @return <?php echo $this->class;?>SearchForm
     */
    public function __construct(EntityManager $entityManager)
    {
        parent::__construct('<?php echo $this->var;?>SearchForm');
        $this->setAttribute('method', 'post');
        $this->setAttribute('id', '<?php echo $this->var;?>Search');
        $this->setAttribute('class', 'form-inline');
        $this->setEntityManager($entityManager);

<?php
foreach ($this->elements as $element):
echo $element;
endforeach;
?>

        $nome = new Element('likeField');
        $nome->setAttributes(array(
            'name' => 'likeField',
            'id' => 'likeField',
            'type' => 'text',
            'data-ng-model' => 'list.search'
        ));
        $nome->setLabel('Palavra Chave');
        $this->add($nome);


        $submit = new Element('clear');
        $submit->setValue('Limpar');
        $submit->setAttributes(array(
            'type'  => 'button',
            'data-ng-click' => 'list.clearSearch()'
        ));
        $this->add($submit);

        return $this;
    }
}
