namespace <?php echo $this->module;?>\<?php echo $this->module;?>Test\EntityTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->className.PHP_EOL;?>
 * @group Entity
 */
class <?php echo $this->className;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->entity = new \<?php echo $this->module;?>\Entity\<?php echo $this->className;?>;
    }

    public function test<?php echo $this->className;?>FieldsStartWithNull()
    {
<?php foreach ($this->fieldsNullMethod as $line) : ?>
        <?php echo $line.PHP_EOL;?>
<?php endforeach;?>
    }

    /**
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     *
     * @dataProvider get<?php echo $this->className;?>FieldsProvider
     */
    public function test<?php echo $this->className;?>Fields(
<?php echo implode(','.PHP_EOL, $this->fieldsMethod['params'***REMOVED***);echo PHP_EOL;?>
    ) {
<?php foreach ($this->fieldsMethod['asserts'***REMOVED*** as $line) : ?>
        <?php echo $line.PHP_EOL;?>
<?php endforeach;?>
    }

    public function get<?php echo $this->className;?>FieldsProvider()
    {
<?php foreach ($this->fieldsProviderMethod['mocks'***REMOVED*** as $mock) : ?>
<?php echo $mock.PHP_EOL;?>
<?php endforeach;?>
        return array(
            array(
<?php echo implode(','.PHP_EOL, $this->fieldsProviderMethod['exports'***REMOVED***);echo PHP_EOL;?>
            )
        );
    }
}
