namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
<?php echo $this->use;?>

class <?php echo $this->class;?>Factory extends FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $<?php echo $this->var;?> = new <?php echo $this->class;?>();
        return $<?php echo $this->var;?>;
    }
}
