<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo $this->translate('Create');?>&nbsp;<?php echo $this->translate('Card');?></h3>
	</div>
</div>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('admin-coola/card/create'));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idCard'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idLearn'));?>
        </div>
                <div class="form-group">
            <?php echo $this->formRow($form->get('idCardTheme'));?>
        </div>
                <div class="form-group">
            <?php echo $this->formRow($form->get('idCardLevel'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('title'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('imageDescription')); ?>
            <?php echo $this->formFile($form->get('imageDescription')); ?>
            <?php echo $this->formElementErrors($form->get('imageDescription')); ?>
        </div>
        <div class="form-group">
            <?php if ($this->imageDescription) : ?>
                <img src="<?php echo $this->imageDescription;?>" height="100" width="100"/>
            <?php endif;?>
        </div>        <div class="form-group">
            <?php echo $this->formRow($form->get('textDescription'));?>
        </div>
<!-- Image Container -->
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default reset" href="<?php echo $this->url('admin-coola/card/list');?>">Voltar</a>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>