version: '3.1'
services:
  main:
    image: registry.piber.network/dev-php:v1.0.7
    tty: true
    volumes:
      - /opt/composer-cache:/root/.composer/cache
      - .:/var/www/module
      - /var/www/gear-factory:/var/www/gear-package
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
    networks:
      - satis
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: gear
    volumes:
      - gear-database:/var/lib/mysql
    networks:
      - satis
networks:
  satis:
    external: true
volumes:
  gear-database:
