version: '3.1'
services:
  main:
    image: registry.piber.network/dev-php:v1.0.9
    tty: true
    volumes:
      - /opt/composer-cache:/root/.composer/cache
      - .:/var/www/module
      - /var/www/factory:/var/www/gear-package
      - ~/.composer/auth.json:/root/.composer/auth.json
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
      - DB_NAME=gear
      - DB_USER=root
      - DB_PASS=gear
      - DB_HOST=mysql
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: gear
    volumes:
      - gear-database:/var/lib/mysql
volumes:
  gear-database:
