site_name: Gear 1.0.0
theme: readthedocs
pages:
    - 'Introdução': 'index.md'
    - 'Module': 
      - 'Geral' : 'module.md'
      - 'Column' : 'column.md'
      - 'Schema': 'schema.md'
      - 'Table': 'table.md'
      - 'Mvc':
        - 'Entity' : 'mvc/entity.md'
        - 'Spec' : 'mvc/spec.md'
    - 'Project': 'project.md'
    - 'Cache': 'cache.md'    
    - 'Database': 'database.md'
    - 'Constructor': 'constructor.md'
    - 'Benchmark': 'benchmark.md'
    - 'Edge': 'edge.md'
    - 'Integration Tests': 'integration.md'    
markdown_extensions:
    - pymdownx.tasklist
extra_css:
    - css/custom.css    
