site_name: Gear 1.0.0
pages:
    - 'Introdução': 'index.md'
    - 'Module': 'module.md'
    - 'Project': 'project.md'
    - 'Cache': 'cache.md'    
    - 'Database': 'database.md'
    - 'Constructor': 'constructor.md'


