
    /**
     * Create Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function createAction()
    {
        $this->error = false;
<?php if ($this->hasImage) { ?>
        $this->getImageService()->dropUploadImageSession();
<?php };?>

        $this->form    = $this->get<?= $this->data?>Form();
        $this->service = $this->get<?= $this->data?>Service();
        $this->url     = self::CREATE;

<?php echo $this->preValidate;?>
<?php echo $this->requestPluginCreate;?>


        if ($create instanceof Response) {
            return $create;
        }

        if ($create) {
<?php if ($this->hasImage) { ?>
            $this->getImageService()->dropUploadImageSession();
<?php } ?>
            return $this->redirect()->toRoute(
                self::EDIT,
                array('id' => $create->getId<?= $this->data?>(), 'success' => 1)
            );
        }

<?php echo isset($this->create[0***REMOVED***) ? $this->create[0***REMOVED*** : PHP_EOL;?>
<?php echo isset($this->create[1***REMOVED***) ? $this->create[1***REMOVED*** : PHP_EOL;?>

        return new ViewModel(
            array(
                'error' => $this->error,
<?php echo isset($this->create[2***REMOVED***) ? $this->create[2***REMOVED*** : PHP_EOL;?>
                'form' => $this->form,
            )
        );
    }
