
    public function editAction()
    {
        $this->error = false;

        $<?php echo $this->idVar;?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$<?php echo $this->idVar;?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->data = $this->get<?= $this->data?>Service()->selectById($<?php echo $this->idVar;?>);

        if (!$this->data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->form      = $this->get<?= $this->data?>Form();
        $this->service   = $this->get<?= $this->data?>Service();
        $this->url       = self::EDIT;
        $this->requestId = $<?php echo $this->idVar;?>;

<?php echo $this->preValidate;?>
<?php echo $this->requestPluginUpdate;?>

        if ($update instanceof Response) {
            return $update;
        }

        if ($update) {
<?php if ($this->imagemService) :?>
            $this->getImagemService()->clearCache();
<?php endif;?>
            return $this->redirect()->toRoute(
                self::EDIT,
                array('id' => $update->getId<?= $this->data?>(), 'success' => 1)
            );
        }

        $this->data = $this->get<?= $this->data?>Service()->selectById($<?php echo $this->idVar;?>);
<?php echo $this->preShow;?>
        $this->form->bind($this->data);

<?php echo isset($this->update[1***REMOVED***) ? $this->update[1***REMOVED*** : PHP_EOL;?>

        $sucesso = $this->getEvent()->getRouteMatch()->getParam('success', null);

        return new ViewModel(
            array(
                'form' => $this->form,
                'error' => $this->error,
                'success' => $sucesso,
<?php echo isset($this->update[2***REMOVED***) ? $this->update[2***REMOVED*** : PHP_EOL;?>
<?php if ($this->imagemService) :?>
                'contexto' => '<?php echo $this->str('url', $this->data);?>',
<?php endif; ?>
                'id<?= $this->data?>' => $<?php echo $this->idVar.PHP_EOL;?>
            )
        );
    }
