namespace <?php echo $this->namespace;?>;

use Zend\View\Model\ViewModel;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\View\Model\JsonModel;
<?php echo $this->use;?>

<?php echo $this->classDocs;?>
class <?php echo $this->controllerName;?> extends AbstractActionController
{
    const CREATE = '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/create';
    const EDIT   = '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit';
    const LISTS  = '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/list';
    const IMAGE  = '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/upload-image';

<?php echo $this->attribute;?>
<?php echo ($this->constructor) ? PHP_EOL.$this->constructor : '';?>
<?php echo $this->createAction;?>
<?php echo $this->editAction;?>
<?php echo $this->viewAction;?>
<?php echo $this->deleteAction;?>
<?php echo $this->uploadImageAction;?>
<?php echo $this->listAction;?>
<?php echo $this->injections;?>
}
