
    /**
     * List Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function listAction()
    {
        $data = $this->getRequestPlugin()->prepareJson(
            $this->get<?php echo $this->data;?>Service()->selectAll()
        );

        return new ViewModel(
            [
                'search'    => $this->get<?php echo $this->data;?>SearchForm(),
                'tableService' => $this->get<?php echo $this->data;?>Service(),
                'data'      => $data,
            ***REMOVED***
        );
    }
