
    public function uploadImageAction()
    {
        $this->getImageService()->appendPlugin();

        $<?php echo $this->idVar;?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$<?php echo $this->idVar;?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->get<?= $this->data?>Service()->selectById($<?php echo $this->idVar;?>);

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $redirectUrl = $this->url()->fromRoute(self::IMAGE, array('id' => $<?php echo $this->idVar;?>));
        $prg = $this->prg($redirectUrl, true);

        $success = 0;

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;
            $imageService = $this->getImageService();
            $imageService->updateImages('<?= $this->str('url', $this->data)?>', $<?php echo $this->idVar;?>);
            $success = $imageService->updatePosition($post);
            $this->getImageService()->clearCache();
        }

        return new ViewModel(
            array(
                'id<?= $this->data?>' => $<?php echo $this->idVar;?>,
                'contexto' => '<?php echo $this->str('url', $this->data);?>',
                'success' => $success
            )
        );
    }
