
    /**
     * View Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function viewAction()
    {
        $<?php echo $this->idVar;?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$<?php echo $this->idVar;?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->get<?= $this->data?>Service()->selectById($<?php echo $this->idVar;?>);
<?php echo $this->imageQuery;?>

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        return new ViewModel(
            array_merge(
                array(
                    'id' => $data->getId<?= $this->data?>(),
<?php echo $this->imageView;?>
                ),
                $this->get<?= $this->data?>Service()->extract($data)
            )
        );
    }
