
    public function viewAction()
    {
        $id<?= $this->data?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$id<?= $this->data?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->get<?= $this->data?>Service()->selectViewById($id<?= $this->data?>);
<?php echo $this->imageQuery;?>

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        return new ViewModel(
            array_merge(
                array(
                    'id' => $data->getId<?= $this->data?>(),
<?php echo $this->imageView;?>
                ),
                $this->get<?= $this->data?>Service()->extract($data)
            )
        );
    }
