<?php
//[STAMP***REMOVED*** 381daa60898c04683bd6a9d3ff05729b

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile


use Codeception\Module\WebDriver;
use Codeception\Module\Db;

/**
 * Inherited Methods
 * @method void wantToTest($text)
 * @method void wantTo($text)
 * @method void execute($callable)
 * @method void expectTo($prediction)
 * @method void expect($prediction)
 * @method void amGoingTo($argumentation)
 * @method void am($role)
 * @method void lookForwardTo($achieveValue)
 * @method void comment($description)
 * @method void haveFriend($name)
 * @SuppressWarnings(PHPMD)
*/
class AcceptanceTester extends \PiberNetwork\GuyTester
{

}
