namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use PHPUnit\Framework\TestCase;
use <?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->class;?>;

/**
 * @group Service
 */
class <?php echo $this->class;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this-><?php echo $this->var;?> = new <?php echo $this->class;?>();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->class;?>', $this-><?php echo $this->var;?>);
    }
}
