<div class="row">
    <div class="col-lg-4">
    <?php echo $this->translate('Já existe uma pasta criada com esse mesmo nome, deseja prosseguir e perder os dados da pasta atual? lembre-se de desmontar a unidade se estiver utilizando máquina virtual.');?>
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('gear',array('controller' => 'index','action' => 'confirmation')));
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
        <?php
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>