<div class="row">
    <div class="col-lg-4">
        <input type="hidden" id="project_name" value="<?php echo $this->project_name;?>"  />
        <?php

            $form = $this->form;
            $form->setAttribute('action', $this->url('gear',array('controller' => 'index','action' => 'create-new-project')));
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
        <?php
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>