<div class="row">
    <div class="col-lg-4">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('gear',array('controller' => 'index','action' => 'create-new-module-in-existing-project')));
            $form->setAttribute('method', 'post');
            echo $this->form()->openTag($form);
        ?>
        <?php
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
</div>