<script>
function toggle(source) {
    checkboxes = document.getElementsByClassName('check-input');
    for(var i=0, n=checkboxes.length;i<n;i++) {
        checkboxes[i***REMOVED***.checked = source.checked;
    }
}
</script>
<div class="row">
    <div class="col-lg-4">
        <?php
            echo $this->form()->openTag($form);
        ?>
        <?php 
            $form = $this->form;
            $form->setAttribute('action', $this->url('gear',array('controller' => 'index','action' => 'from-db')));
            $form->setAttribute('method', 'post');
            echo $this->formCollection($form);
            echo $this->form()->closeTag();
        ?>
    </div>
    <div class="col-lg-4">
        <?php
        if(isset($this->form_gear))
        {
            $form = $this->form_gear;
            $form->setAttribute('action', $this->url('gear',array('controller' => 'index','action' => 'post-db')));
            $form->setAttribute('method', 'post');
            
            echo $this->form()->openTag($form);
            ?>
            <input type="checkbox" onClick="toggle(this)" /> Toggle All<br/>
            <?php 
                echo $this->formCollection($form);
                echo $this->form()->closeTag();
        }
            ?>
    </div>
</div>