<div class="row">
	<div class="col-lg-12">
        <a href="<?php echo $this->url('gear',array('action' => 'create-new-project'));?>" class="btn btn-default btn-lg">
            <?php echo $this->translate('Criar Skeleton');?>
        </a>
        <a href="<?php echo $this->url('gear',array('action' => 'create-new-module-in-new-project'));?>" class="btn btn-default btn-lg">
            <?php echo $this->translate('Criar Módulo em Novo Projeto');?>
        </a>
        <a href="<?php echo $this->url('gear',array('action' => 'create-new-module-in-existing-project'));?>" class="btn btn-default btn-lg">
            <?php echo $this->translate('Criar Módulo em Projeto Existente');?>
        </a>
        <a href="<?php echo $this->url('gear',array('action' => 'create-crud-into-module'));?>" class="btn btn-default btn-lg">
            <?php echo $this->translate('Criar Crud em Módulo');?>
        </a>
	</div>
</div>