<div class="row">
    <div class="col-lg-12">
        <ul>
            <li id="opt1"><a href="<?php echo $this->url('gear',array('controller' => 'index','action' => 'from-db'));?>"><?php echo $this->translate('Criar Módulo à Partir do Banco de Dados');?></a></li>
            <li id="opt2"><a href="<?php echo $this->url('gear',array('controller' => 'index','action' => 'from-yml'));?>"><?php echo $this->translate('Criar Módulo à Partir de Estrutura Yml');?></a></li>
        </ul>
    </div>
</div>