namespace <?php echo $this->module;?>Test\FilterTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->className.PHP_EOL;?>
 * @group Filter
 */
class <?php echo $this->className;?>Test extends TestCase
{
    public static $validate = 'vendor/zendframework/zend-i18n-resources/languages/pt_BR/Zend_Validate.php';

    public function setUp()
    {
        $this->filter = new \<?php echo $this->module;?>\Filter\<?php echo $this->className;?>();
        $this->filter->setAdapter($this->getAdapterMock());

        $this->translator = new \Zend\I18n\Translator\Translator();
        $this->translator->addTranslationFile(
            'phpArray',
            \GearBase\Module::getProjectFolder().'/'.static::$validate,
            'default',
            'pt_BR'
        )->setLocale('pt_BR');
    }

<?php echo $this->functions;?>

    protected function getAdapterMock()
    {
        $adapter = $this->prophesize('Zend\Db\Adapter\Adapter');
        $driver = $this->prophesize('Zend\Db\Adapter\Driver\DriverInterface');

        $platform = $this->prophesize('Zend\Db\Adapter\Platform\Mysql');

        $adapter->getDriver()->willReturn($driver->reveal());
        $adapter->getPlatform()->willReturn($platform->reveal());

        $stmt = $this->prophesize('Zend\Db\Adapter\Driver\Pdo\Statement');

        $driver->createStatement()->willReturn($stmt->reveal());
        $driver->formatParameterName('where1')->willReturn(null);

        $resultSet = $this->prophesize('Zend\Db\ResultSet\ResultSetInterface');
        $resultSet->current()->willReturn(false);

        $paramContainer = $this->prophesize('Zend\Db\Adapter\ParameterContainer');

        $stmt->execute()->willReturn($resultSet->reveal());
        $stmt->getParameterContainer()->willReturn($paramContainer->reveal());
        $stmt->setSql("SELECT  WHERE  =")->willReturn($stmt->reveal());

        return $adapter->reveal();
    }
}
