
    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->class.PHP_EOL;?>
     */
    public function testReturnTrueWithValidPost()
    {
        $data = [
<?php echo $this->fixture;?>
        ***REMOVED***;

        $inputFilter = $this->filter->getInputFilter();
<?php echo $this->columns;?>
        $inputFilter->setData($data);
        $this->assertTrue($inputFilter->isValid());
    }
