
    public function validPost()
    {
        return array(
            array(
                array(
<?php echo $this->fixture;?>
                ),
            ),
        );
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->class.PHP_EOL;?>
     * @dataProvider validPost
     */
    public function testReturnTrueWithValidPost($data)
    {
        $<?php echo $this->var;?> = $this->get<?php echo $this->class;?>();
        $inputFilter = $<?php echo $this->var;?>->getInputFilter();
<?php echo $this->columns;?>
        $inputFilter->setData($data);
        $this->assertTrue($inputFilter->isValid());
    }
