
    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->class.PHP_EOL;?>
     */
    public function testGetRequiredInvalidPost()
    {
        $inputFilter = $this->filter->getInputFilter();
        $inputFilter->setData(array());
        $this->assertFalse($inputFilter->isValid());
        $this->messages = $inputFilter->getMessages();
<?php echo $this->messages;?>
    }

    public function assertMessage($column, $filter, $message)
    {
        $this->assertArrayHasKey($column, $this->messages);
        $this->assertArrayHasKey($filter, $this->messages[$column***REMOVED***);
        $this->assertEquals(
            $message,
            $this->translator->translate($this->messages[$column***REMOVED***[$filter***REMOVED***)
        );
    }
