namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use <?php echo $this->namespace;?>\<?php echo $this->className;?>;
<?php echo $this->use; ?>

<?php echo $this->classDocs;?>
class <?php echo $this->className;?>Factory implements FactoryInterface
{
    /**
     * Create <?php echo $this->className.PHP_EOL;?>
     *
     * @param ContainerInterface $container Controller Manager
     *
     * @return <?php echo $this->className.PHP_EOL;?>
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        

        $factory = new <?php echo $this->className;?>(
<?php echo $this->dependency;?>
        );
        
        return $factory;
    }
}
