namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
<?php echo $this->use; ?>

<?php echo $this->classDocs;?>
class <?php echo $this->className;?>Factory implements FactoryInterface
{
    /**
     * Create <?php echo $this->className.PHP_EOL;?>
     *
     * @param ServiceLocatorInterface $controllerManager Controller Manager
     * @return \<?php echo $this->namespace;?>\<?php echo $this->className.PHP_EOL;?>
     */
    public function createService(ServiceLocatorInterface $controllerManager)
    {
        $serviceLocator = $controllerManager->getServiceLocator();

        $factory = new <?php echo $this->className;?>(
<?php echo $this->dependency;?>
        );
        unset($serviceLocator);
        return $factory;
    }
}
