namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\ServiceLocatorInterface;
use GearBase\Hydrator\DateHydrator;
use GearBase\Factory\AbstractFactory;
use <?php echo $this->namespace;?>\<?php echo $this->class;?>;
use <?php echo $this->filter;?>;
use <?php echo $this->entity;?>;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package <?php echo $this->package.PHP_EOL;?>
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class <?php echo $this->class;?>Factory extends AbstractFactory
{

    /**
     * Create <?php echo $this->class.PHP_EOL;?>
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     *
     * @return <?php echo $this->class.PHP_EOL;?>
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new <?php echo $this->class;?>(
            $serviceLocator->get('doctrine.entitymanager.orm_default')
        );

        $<?php echo $this->var;?> = null;
<?php echo $this->setId;?>

        $filter = $serviceLocator->get(<?php echo $this->filterName;?>::class);
        $form->setInputFilter($filter->getInputFilter($<?php echo $this->var;?>));

        $entityManager = $serviceLocator->get('doctrine.entitymanager.orm_default');
        $hydrator = new DateHydrator($entityManager, <?php echo $this->entityName;?>::class);

        $form->setHydrator($hydrator);

        return $form;
    }
}
