namespace <?php echo $this->module;?>Test\<?php echo $this->namespace; ?>;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->basename;?>Form
 * @group Form
 */
class <?php echo $this->basename;?>FormFactoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->serviceLocator = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');
        $this->entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->filter = $this->prophesize('<?php echo $this->filter;?>');
        $this->request = $this->prophesize('Zend\Http\Request');
        $this->translator = $this->prophesize('Zend\Mvc\I18n\Translator');
        $this->uri = $this->prophesize('Zend\Uri\Uri');
        $this->adapter = $this->prophesize('Zend\Db\Adapter\Adapter');
    }

    public function testCreateFactory()
    {
        $this->uri->getPath()->willReturn('<?php echo $this->moduleUrl;?>/<?php echo $this->basenameUrl;?>/edit/30');
        $this->request->getUri()->willReturn($this->uri->reveal());

        $this->filter->setAdapter($this->adapter->reveal())->shouldNotBeCalled();
        $this->filter->getInputFilter(30)->willReturn($this->filter->reveal());

        $this->serviceLocator->get('doctrine.entitymanager.orm_default')
          ->willReturn($this->entityManager->reveal())
          ->shouldBeCalled();

        $this->serviceLocator->get('<?php echo $this->filter;?>')
          ->willReturn($this->filter->reveal())
          ->shouldBeCalled();

        $this->serviceLocator->get('Zend\Db\Adapter\Adapter')->willReturn($this->adapter->reveal());
        $this->serviceLocator->get('Request')->willReturn($this->request->reveal())->shouldBeCalled();
        $this->serviceLocator->get('Translator')->willReturn($this->translator->reveal())->shouldBeCalled();

        $factory = new \<?php echo $this->form;?>Factory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('<?php echo $this->form;?>', $instance);
    }
}
