        $request = $serviceLocator->get('Request');
        $translate = $serviceLocator->get('Translator');
        if ($request instanceof \Zend\Http\Request
            && preg_match('/'.$translate->translate('edit').'/', $request->getUri()->getPath())
        ) {
            if (preg_match('/[0-9***REMOVED****$/', $request->getUri()->getPath(), $match)) {
                $<?php echo $this->var;?> = $match[0***REMOVED***;
            }
        }
        $filter->setAdapter($serviceLocator->get('Zend\Db\Adapter\Adapter'));
