namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use GearBase\Hydrator\DateHydrator;
use GearBase\Factory\AbstractFactory;

class <?php echo $this->class;?>Factory extends AbstractFactory
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new \<?php echo $this->form;?>(
            $serviceLocator->get('doctrine.entitymanager.orm_default')
        );
        $filter = $serviceLocator->get('<?php echo $this->filter;?>');

        $<?php echo $this->var;?> = null;
<?php echo $this->setId;?>
        $form->setInputFilter($filter->getInputFilter($<?php echo $this->var;?>));

        $entityManager = $serviceLocator->get('doctrine.entitymanager.orm_default');
        $hydrator = new DateHydrator($entityManager, '<?php echo $this->entity;?>');

        $form->setHydrator($hydrator);

        return $form;
    }
}
