namespace <?php echo $this->namespace;?>;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
<?php echo $this->use; ?>

class <?php echo $this->className;?>Factory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new <?php echo $this->className;?>(
<?php echo $this->dependency;?>
        );
        unset($serviceLocator);
        return $factory;
    }
}
