<?php
namespace MyModule\Custom\CustomNamespace;

use Zend\View\Model\ViewModel;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\View\Model\JsonModel;
use MyModule\Custom\CustomNamespace\UploadImageColumnServiceTrait;
use MyModule\Custom\CustomNamespace\UploadImageColumnFormTrait;
use MyModule\Custom\CustomNamespace\UploadImageColumnSearchFormTrait;
use GearImage\Service\ImageServiceTrait;
use Zend\Mvc\Controller\AbstractActionController;
use MyModule\Custom\CustomNamespace\UploadImageColumnService;
use MyModule\Custom\CustomNamespace\UploadImageColumnForm;
use MyModule\Custom\CustomNamespace\UploadImageColumnSearchForm;
use GearImage\Service\ImageService;

/**
 * Upload Image Column Controller
 *
 * Actions for Upload Image Column Table
 *
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class UploadImageColumnController extends AbstractActionController
{
    const CREATE = 'my-module/upload-image-column/create';
    const EDIT   = 'my-module/upload-image-column/edit';
    const LISTS  = 'my-module/upload-image-column/list';
    const IMAGE  = 'my-module/upload-image-column/upload-image';

    use UploadImageColumnServiceTrait;

    use UploadImageColumnFormTrait;

    use UploadImageColumnSearchFormTrait;

    use ImageServiceTrait;

    /**
     * Constructor
     *
     * @param UploadImageColumnService    $imageColumnService Upload Image Column Service
     * @param UploadImageColumnForm       $imageColumnForm    Upload Image Column Form
     * @param UploadImageColumnSearchForm $columnSearchForm   Upload Image Column Search Form
     * @param ImageService                $imageService       Image Service
     *
     * @return UploadImageColumnController
     */
    public function __construct(
        UploadImageColumnService $imageColumnService,
        UploadImageColumnForm $imageColumnForm,
        UploadImageColumnSearchForm $columnSearchForm,
        ImageService $imageService
    ) {
        $this->uploadImageColumnService = $imageColumnService;
        $this->uploadImageColumnForm = $imageColumnForm;
        $this->uploadImageColumnSearchForm = $columnSearchForm;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Create Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function createAction()
    {
        $this->error = false;
        $this->getImageService()->dropUploadImageSession();

        $this->form    = $this->getUploadImageColumnForm();
        $this->service = $this->getUploadImageColumnService();
        $this->url     = self::CREATE;

        $create = $this->getRequestPlugin()->fileCreate();

        if ($create instanceof Response) {
            return $create;
        }

        if ($create) {
            $this->getImageService()->dropUploadImageSession();
            return $this->redirect()->toRoute(
                self::EDIT,
                ['id' => $create->getIdUploadImageColumn(), 'success' => 1***REMOVED***
            );
        }

        $this->getImageService()->verifyErrors($this->form, 'uploadImageColumn');
        $uploadImageColumn = $this->getImageService()->getTempUpload('uploadImageColumn');

        return new ViewModel(
            [
                'error' => $this->error,
                'uploadImageColumn' => $uploadImageColumn,
                'form' => $this->form,
            ***REMOVED***
        );
    }

    /**
     * Edit Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function editAction()
    {
        $this->error = false;

        $idUploadImageColumn = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$idUploadImageColumn) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->data = $this->getUploadImageColumnService()->selectById($idUploadImageColumn);

        if (!$this->data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->form      = $this->getUploadImageColumnForm();
        $this->service   = $this->getUploadImageColumnService();
        $this->url       = self::EDIT;
        $this->requestId = $idUploadImageColumn;

        $update = $this->getRequestPlugin()->fileUpdate();
        if ($update instanceof Response) {
            return $update;
        }

        if ($update) {
            $this->getImageService()->clearCache();
            return $this->redirect()->toRoute(
                self::EDIT,
                ['id' => $update->getIdUploadImageColumn(), 'success' => 1***REMOVED***
            );
        }

        $this->data = $this->getUploadImageColumnService()->selectById($idUploadImageColumn);
        $this->data->setPasswordVerifyColumn('');
        $this->form->bind($this->data);

        $uploadImageColumn = $this->getImageService()->getUploadImagePath($this->data, 'getUploadImageColumn');

        $success = $this->getEvent()->getRouteMatch()->getParam('success', null);

        return new ViewModel(
            [
                'form' => $this->form,
                'error' => $this->error,
                'success' => $success,
                'uploadImageColumn' => $uploadImageColumn,
                'contexto' => 'upload-image-column',
                'idUploadImageColumn' => $idUploadImageColumn
            ***REMOVED***
        );
    }

    /**
     * View Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function viewAction()
    {
        $idUploadImageColumn = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$idUploadImageColumn) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->getUploadImageColumnService()->selectById($idUploadImageColumn);

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        return new ViewModel(
            array_merge(
                [
                    'id' => $data->getIdUploadImageColumn(),
                ***REMOVED***,
                $this->getUploadImageColumnService()->extract($data)
            )
        );
    }

    /**
     * Delete Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function deleteAction()
    {
        $identifier = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$identifier) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $uploadImageColumn = $this->getUploadImageColumnService();

        $delete = $uploadImageColumn->delete($identifier);

        return new JsonModel(array_merge($delete, ['id' => $identifier***REMOVED***));
    }

    /**
     * List Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function listAction()
    {
        $data = $this->getRequestPlugin()->prepareJson(
            $this->getUploadImageColumnService()->selectAll()
        );

        return new ViewModel(
            [
                'search'    => $this->getUploadImageColumnSearchForm(),
                'tableService' => $this->getUploadImageColumnService(),
                'data'      => $data,
            ***REMOVED***
        );
    }
}
