<?php
namespace MyModule\Custom\CustomNamespace;

use Zend\View\Model\ViewModel;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\View\Model\JsonModel;
use MyModule\Custom\CustomNamespace\UploadImageTableServiceTrait;
use MyModule\Custom\CustomNamespace\UploadImageTableFormTrait;
use MyModule\Custom\CustomNamespace\UploadImageTableSearchFormTrait;
use GearImage\Service\ImageServiceTrait;
use Zend\Mvc\Controller\AbstractActionController;
use MyModule\Custom\CustomNamespace\UploadImageTableService;
use MyModule\Custom\CustomNamespace\UploadImageTableForm;
use MyModule\Custom\CustomNamespace\UploadImageTableSearchForm;
use GearImage\Service\ImageService;

/**
 * Upload Image Table Controller
 *
 * Actions for Upload Image Table Table
 *
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class UploadImageTableController extends AbstractActionController
{
    const CREATE = 'my-module/upload-image-table/create';
    const EDIT   = 'my-module/upload-image-table/edit';
    const LISTS  = 'my-module/upload-image-table/list';
    const IMAGE  = 'my-module/upload-image-table/upload-image';

    use UploadImageTableServiceTrait;

    use UploadImageTableFormTrait;

    use UploadImageTableSearchFormTrait;

    use ImageServiceTrait;

    /**
     * Constructor
     *
     * @param UploadImageTableService    $imageTableService    Upload Image Table Service
     * @param UploadImageTableForm       $uploadImageTableForm Upload Image Table Form
     * @param UploadImageTableSearchForm $imageTableSearchForm Upload Image Table Search Form
     * @param ImageService               $imageService         Image Service
     *
     * @return UploadImageTableController
     */
    public function __construct(
        UploadImageTableService $imageTableService,
        UploadImageTableForm $uploadImageTableForm,
        UploadImageTableSearchForm $imageTableSearchForm,
        ImageService $imageService
    ) {
        $this->uploadImageTableService = $imageTableService;
        $this->uploadImageTableForm = $uploadImageTableForm;
        $this->uploadImageTableSearchForm = $imageTableSearchForm;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Create Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function createAction()
    {
        $this->error = false;

        $this->form    = $this->getUploadImageTableForm();
        $this->service = $this->getUploadImageTableService();
        $this->url     = self::CREATE;

        $create = $this->getRequestPlugin()->create();

        if ($create instanceof Response) {
            return $create;
        }

        if ($create) {
            return $this->redirect()->toRoute(
                self::EDIT,
                ['id' => $create->getIdUploadImageTable(), 'success' => 1***REMOVED***
            );
        }


        return new ViewModel(
            [
                'error' => $this->error,
                'form' => $this->form,
            ***REMOVED***
        );
    }

    /**
     * Edit Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function editAction()
    {
        $this->error = false;

        $idUploadImageTable = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$idUploadImageTable) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->data = $this->getUploadImageTableService()->selectById($idUploadImageTable);

        if (!$this->data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $this->form      = $this->getUploadImageTableForm();
        $this->service   = $this->getUploadImageTableService();
        $this->url       = self::EDIT;
        $this->requestId = $idUploadImageTable;

        $update = $this->getRequestPlugin()->update();
        if ($update instanceof Response) {
            return $update;
        }

        if ($update) {
            return $this->redirect()->toRoute(
                self::EDIT,
                ['id' => $update->getIdUploadImageTable(), 'success' => 1***REMOVED***
            );
        }

        $this->data = $this->getUploadImageTableService()->selectById($idUploadImageTable);
        $this->form->bind($this->data);


        $success = $this->getEvent()->getRouteMatch()->getParam('success', null);

        return new ViewModel(
            [
                'form' => $this->form,
                'error' => $this->error,
                'success' => $success,
                'idUploadImageTable' => $idUploadImageTable
            ***REMOVED***
        );
    }

    /**
     * View Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function viewAction()
    {
        $idUploadImageTable = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$idUploadImageTable) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->getUploadImageTableService()->selectById($idUploadImageTable);
        $images = $this->getImageService()->findByContextId($idUploadImageTable, 'upload-image-table');

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        return new ViewModel(
            array_merge(
                [
                    'id' => $data->getIdUploadImageTable(),
                    'images' => $images,
                ***REMOVED***,
                $this->getUploadImageTableService()->extract($data)
            )
        );
    }

    /**
     * Delete Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function deleteAction()
    {
        $identifier = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$identifier) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $uploadImageTable = $this->getUploadImageTableService();

        $delete = $uploadImageTable->delete($identifier);

        return new JsonModel(array_merge($delete, ['id' => $identifier***REMOVED***));
    }

    /**
     * Upload Image Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function uploadImageAction()
    {
        $this->appendUploadImagePlugin();

        $idUploadImageTable = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$idUploadImageTable) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->getUploadImageTableService()->selectById($idUploadImageTable);

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $redirectUrl = $this->url()->fromRoute(self::IMAGE, array('id' => $idUploadImageTable));
        $prg = $this->prg($redirectUrl, true);

        $success = 0;

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;
            $imageService = $this->getImageService();
            $imageService->updateImages('upload-image-table', $idUploadImageTable);
            $success = $imageService->updateImageInfo($post);
            $this->getImageService()->clearCache();
        }

        return new ViewModel(
            [
                'idUploadImageTable' => $idUploadImageTable,
                'contexto' => 'upload-image-table',
                'success' => $success
            ***REMOVED***
        );
    }

    /**
     * List Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function listAction()
    {
        $data = $this->getRequestPlugin()->prepareJson(
            $this->getUploadImageTableService()->selectAll()
        );

        return new ViewModel(
            [
                'search'    => $this->getUploadImageTableSearchForm(),
                'tableService' => $this->getUploadImageTableService(),
                'data'      => $data,
            ***REMOVED***
        );
    }
}
