<?php
namespace ModuleUnitTwoTest\FreeTest\MyClassTwoTest;

use PHPUnit\Framework\TestCase;
use ModuleUnitTwo\Free\MyClassTwo\UnitSrcNameTwoTrait;

class UnitSrcNameTwoTest extends TestCase
{
    use UnitSrcNameTwoTrait;

    public function testSetUnitSrcNameTwo()
    {
        $mockUnitSrcNameTwo = $this->getMockSingleClass('ModuleUnitTwo\Free\MyClassTwo\UnitSrcNameTwo');
        $this->setUnitSrcNameTwo($mockUnitSrcNameTwo);
        $this->assertEquals($mockUnitSrcNameTwo, $this->getUnitSrcNameTwo());
    }

    public function testGetUnitSrcNameTwo()
    {
        $this->assertInstanceOf(
            'ModuleUnitTwo\Free\MyClassTwo\UnitSrcNameTwo',
            $this->getUnitSrcNameTwo()
        );
    }
}
