<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use MyModule\Controller\BasicManyRest;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;
use GearBaseTest\Assertions\AclAssertTrait;

/**
 * @group BasicManyRest
 * @group Controller
 */
class BasicManyRestTest extends TestCase
{
    use AclAssertTrait;

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp()
    {
        parent::setUp();

        $this->controller = new BasicManyRest();
        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'BasicManyRest'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this->schema = (new \MyModule\Module())->getLocation().'/../schema/module.json';
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }

    public function testGetAction()
    {
        $this->assertAcl(
            $this->schema,
            'MyModule',
            'BasicManyRest',
            'Controller',
            'Get'
        );

        $this->routeMatch->setParam('id', 1);
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    public function testGetListAction()
    {
        $this->assertAcl(
            $this->schema,
            'MyModule',
            'BasicManyRest',
            'Controller',
            'GetList'
        );

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    public function testUpdateAction()
    {
        $this->assertAcl(
            $this->schema,
            'MyModule',
            'BasicManyRest',
            'Controller',
            'Update'
        );

        $this->request->setMethod('PUT');
        $this->routeMatch->setParam('id', 1);
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    public function testDeleteAction()
    {
        $this->assertAcl(
            $this->schema,
            'MyModule',
            'BasicManyRest',
            'Controller',
            'Delete'
        );

        $this->request->setMethod('DELETE');
        $this->routeMatch->setParam('id', 1);
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    public function testCreateAction()
    {
        $this->assertAcl(
            $this->schema,
            'MyModule',
            'BasicManyRest',
            'Controller',
            'Create'
        );

        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }
}
