        $message = 'O valor é inválido';
        $this->add(
            array(
                'name' => 'myColumn',
                'required' => false,
                'filters'    => array(array('name' => 'StringTrim')),
                'validators' => array(
                    array(
                        'name' => 'EmailAddress',
                        'options' => array(
                            'messages' => array(
                                \Zend\Validator\EmailAddress::INVALID            => $message,
                                \Zend\Validator\EmailAddress::INVALID_FORMAT     => $message,
                                \Zend\Validator\EmailAddress::INVALID_HOSTNAME   => $message,
                                \Zend\Validator\EmailAddress::INVALID_MX_RECORD  => $message,
                                \Zend\Validator\EmailAddress::INVALID_SEGMENT    => $message,
                                \Zend\Validator\EmailAddress::DOT_ATOM           => $message,
                                \Zend\Validator\EmailAddress::QUOTED_STRING      => $message,
                                \Zend\Validator\EmailAddress::INVALID_LOCAL_PART => $message,
                                \Zend\Validator\EmailAddress::LENGTH_EXCEEDED    => $message,
                            ),
                        ),
                        'break_chain_on_failure' => true
                    )
                )
            )
        );
