<?php
namespace MyModuleTest\GreatestTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Greatest\AbstractCompleteFactoriesRepository;

/**
 * @group Repository
 */
class AbstractCompleteFactoriesRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->className = 'MyModule\Greatest\AbstractCompleteFactoriesRepository';

        $this->myDependencyOne = $this->prophesize('MyModule\Repository\MyDependencyOne');
        $this->myDependencyTwo = $this->prophesize('MyModule\Logic\MyDependencyTwo');
        $this->myDependencyThree = $this->prophesize('MyModule\Mvc\MyDependencyThree');

        $this->repository = $this->getMockBuilder($this->className)
            ->disableoriginalConstructor()
            ->getMockForAbstractClass();
    }

    public function testClassExists()
    {
        $reflectedClass = new \ReflectionClass($this->className);
        $constructor = $reflectedClass->getConstructor();
        $class = $constructor->invoke(
            $this->repository,
            $this->myDependencyOne->reveal(),
            $this->myDependencyTwo->reveal(),
            $this->myDependencyThree->reveal()
        );

        $this->assertInstanceOf('MyModule\Greatest\AbstractCompleteFactoriesRepository', $class);
    }
}
