<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit\Framework\TestCase;
use MyModule\Repository\BasicDependenciesRepository;

/**
 * @group Repository
 */
class BasicDependenciesRepositoryTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->repository = new BasicDependenciesRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicDependenciesRepository', $this->repository);
    }
}
