<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit\Framework\TestCase;
use MyModule\Repository\BasicDependencyRepository;

/**
 * @group Repository
 */
class BasicDependencyRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->repository = new BasicDependencyRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicDependencyRepository', $this->repository);
    }
}
