<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit\Framework\TestCase;
use MyModule\Repository\BasicDependencyFactoryRepository;

/**
 * @group Repository
 */
class BasicDependencyFactoryRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->myDependency = $this->prophesize('MyModule\Repository\MyDependency');

        $this->repository = new BasicDependencyFactoryRepository(
            $this->myDependency->reveal()
        );
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicDependencyFactoryRepository', $this->repository);
    }
}
