<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Repository\BasicFactoryRepository;

/**
 * @group Repository
 */
class BasicFactoryRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->repository = new BasicFactoryRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicFactoryRepository', $this->repository);
    }
}
