<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Repository\BasicDependenciesFactoryRepository;

/**
 * @group Repository
 */
class BasicDependenciesFactoryRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->myDependencyOne = $this->prophesize('MyModule\Repository\MyDependencyOne');
        $this->myDependencyTwo = $this->prophesize('MyModule\Repository\MyDependencyTwo');
        $this->myDependencyThree = $this->prophesize('MyModule\Repository\MyDependencyThree');

        $this->repository = new BasicDependenciesFactoryRepository(
            $this->myDependencyOne->reveal(),
            $this->myDependencyTwo->reveal(),
            $this->myDependencyThree->reveal()
        );
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicDependenciesFactoryRepository', $this->repository);
    }
}
