<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit\Framework\TestCase;
use MyModule\Repository\BasicRepository;

/**
 * @group Repository
 */
class BasicRepositoryTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->repository = new BasicRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicRepository', $this->repository);
    }
}
