<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit\Framework\TestCase;
use MyModule\Repository\BasicExtendsRepository;

/**
 * @group Repository
 */
class BasicExtendsRepositoryTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->repository = new BasicExtendsRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Repository\BasicExtendsRepository', $this->repository);
    }
}
