<?php
namespace MyModuleTest\BasicTest\FeatureTest\IssueTest\TaskTest;

use PHPUnit\Framework\TestCase;
use MyModule\Basic\Feature\Issue\Task\LongNamespaceRepository;

/**
 * @group Repository
 */
class LongNamespaceRepositoryTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->repository = new LongNamespaceRepository();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Basic\Feature\Issue\Task\LongNamespaceRepository', $this->repository);
    }
}
