// This is global bootstrap for autoloading
include 'ZendServiceLocator.php';

$zendServiceLocator = new \<?php echo $this->namespace;?>\ZendServiceLocator();

\Codeception\Util\Autoload::addNamespace('<?php echo $this->module;?>\Pages', __DIR__.DIRECTORY_SEPARATOR.'_pages');
require_once '_support/LoginCommons.php';
require_once 'acceptance/AbstractCest.php';
require_once 'functional/AbstractCest.php';






















