class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver
        - AcceptanceHelper
        - Db
        - UploadImageHelper
    config:
      WebDriver:
         url: 'http://<?php echo $this->url;?>'
         browser: phantomjs
         capabilities:
             webStorageEnabled: true
         window_size: 1024x768
      Db:
          dsn: 'mysql:dbname=<?php echo $this->dbName;?>;host=localhost'
          user: '<?php echo $this->dbUser;?>'
          password: '<?php echo $this->dbPass;?>'
          dump: data/<?php echo $this->moduleUrl;?>.mysql.sql