namespace: <?php echo $this->module.PHP_EOL;?>
actor: Tester
extensions:
    enabled: [Codeception\Extension\Recorder***REMOVED***
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
paths:
    tests: test
    log: build/coverage
    data: test/_data
    helpers: test/_support
settings:
    strict_xml: true
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 2048M
coverage:
    whitelist:
          include:
              - src/*
          exclude:
              - src/<?php echo $this->module;?>/Fixture/*
              - src/<?php echo $this->module;?>/Module.php*
    blacklist:
          include:
              - build/*
              - data/*
              - language/*
              - public/*
              - schema/*
              - test/*
              - view/*
              - src/<?php echo $this->module;?>/Fixture/*
modules:
    config:
      WebDriver:
         url: 'http://<?php echo $this->url;?>'
         browser: phantomjs
         capabilities:
             webStorageEnabled: true
         window_size: 1024x768
      Db:
          dsn: 'mysql:dbname=<?php echo $this->dbName;?>;host=localhost'
          user: '<?php echo $this->dbUser;?>'
          password: '<?php echo $this->dbPass;?>'
          dump: data/<?php echo $this->moduleUrl;?>.mysql.sql
      ZF2:
         config: '../../config/application.config.php'
      Doctrine2:
          cleanup: false