namespace: <?php echo $this->module.PHP_EOL;?>
actor: Tester
extensions:
    enabled: [Codeception\Extension\Recorder***REMOVED***
    config:
        Codeception\Extension\Recorder:
            delete_successful: false
paths:
    tests: test
    log: build
    data: test/_data
    helpers: test/_support
settings:
    strict_xml: true
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 2048M
coverage:
    whitelist:
          include:
              - src/*
          exclude:
              - src/<?php echo $this->module;?>/Fixture/*
              - src/<?php echo $this->module;?>/Module.php*
    blacklist:
          include:
              - build/*
              - data/*
              - language/*
              - public/*
              - schema/*
              - test/*
              - view/*
              - src/<?php echo $this->module;?>/Fixture/*
modules:
    config:
      Db:
          dsn: 'mysql:dbname=<?php echo $this->moduleUline;?>;host=localhost'
          user: 'root'
          password: 'gear'
          dump: data/<?php echo $this->moduleUrl;?>.mysql.sql
      Doctrine2:
          cleanup: false