class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, WebDriver, Db, Doctrine2, UploadImageHelper***REMOVED***
    config:
      WebDriver:
         url: 'http://<?php echo $this->url;?>'
         browser: phantomjs
         capabilities:
             webStorageEnabled: true
      Db:
          dsn: 'mysql:dbname=<?php echo $this->dbName;?>;host=localhost'
          user: '<?php echo $this->dbUser;?>'
          password: '<?php echo $this->dbPass;?>'
          dump: data/<?php echo $this->moduleUrl;?>.mysql.sql
      Doctrine2:
          cleanup: false