namespace <?php echo $this->module;?>\<?php echo $this->module;?>Test\ServiceTest;

class <?php echo $this->serviceNameClass;?>Test extends \<?php echo $this->module;?>\<?php echo $this->module;?>Test\AbstractTest
{
    protected $<?php echo $this->serviceNameUline;?>;

    public function get<?php echo $this->serviceNameClass;?>()
    {
        if (!isset($this-><?php echo $this->serviceNameUline;?>)) {
            $this-><?php echo $this->serviceNameUline;?> =
                $this->bootstrap->getServiceLocator()->get(
                    '<?php echo $this->module;?>\Service\<?php echo $this->serviceNameClass;?>'
                );
        }
        return $this-><?php echo $this->serviceNameUline;?>;
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->serviceNameClass;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
    */
    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->serviceNameUline;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Service\<?php echo $this->serviceNameClass;?>', $<?php echo $this->serviceNameUline;?>);
    }

<?php echo $this->partialLoop('template/miscellaneous/test-injection-partial.phtml', $this->injection);?>


    public function testSetSelectAllCache()
    {
        $this->mockIdentity();

        $this->get<?php echo $this->serviceNameClass;?>()->setSessionName('testing');

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem('testingResult')) {
            $cache->removeItem('testingResult');
        }

        $data = $this->get<?php echo $this->serviceNameClass;?>()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->get<?php echo $this->serviceNameClass;?>()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->mockIdentity();

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'DESC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy());
        $this->assertEquals('DESC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());

        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectAll();
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectAll();

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'ASC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy());
        $this->assertEquals('ASC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem($this->get<?php echo $this->serviceNameClass;?>()->getSessionName())) {
            $cache->removeItem($this->get<?php echo $this->serviceNameClass;?>()->getSessionName());
        }

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch($this->getRouteMatch(1, 'id<?php echo $this->class;?>', 'DESC'));
        $this->assertEquals('id<?php echo $this->class;?>', $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy());
        $this->assertEquals('DESC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());
    }

    public function testSelectById()
    {
        $<?php echo $this->serviceNameVar;?>Service = $this->get<?php echo $this->serviceNameClass;?>();
        $resultSet = $<?php echo $this->serviceNameVar;?>Service->selectById(1);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(1, $resultSet->getId<?php echo $this->class;?>());
    }
    <?php echo $this->partialLoop('template/test/unit/service/one-by.phtml', $this->oneBy);?>

    /**
     * @group Service.Create
     */
    public function testCreate()
    {
        $this->mockIdentity();
        $data = array(
<?php foreach ($this->insertArray as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        );
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->create($data);
        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(is_null($resultSet->getUpdated()));
<?php foreach ($this->insertAssert as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        return $resultSet;
    }

    /**
     * @depends testCreate
     */
    public function testUpdate($entityToUpdate)
    {
        $this->mockIdentity();
        $data = array(
<?php foreach ($this->updateArray as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        );
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->update($entityToUpdate->getId<?php echo $this->class;?>(), $data);
        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(!is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(!is_null($resultSet->getUpdated()));
<?php foreach ($this->updateAssert as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        return $resultSet;
    }

    /**
     * @depends testUpdate
     */
    public function testDelete($entityToDelete)
    {
        $this->mockIdentity();
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->delete($entityToDelete->getId<?php echo $this->class;?>());
        $this->assertTrue($resultSet);
    }

    public function mockIdentity()
    {
        $this->bootstrap
        ->getServiceManager()
        ->setAllowOverride(true);

        $zfcUserMock =  $this->bootstrap
          ->getEntityManager()
          ->getRepository('Security\Entity\User')
          ->findOneBy(array('email' => 'mauriciopiber@gmail.com'));

        $authMock = $this->getMock('ZfcUser\Controller\Plugin\ZfcUserAuthentication');

        $autenticationService = $this->getMock('Zend\Authentication\AuthenticationService');
        $autenticationService->expects($this->any())
        ->method('resetAdapter')
        ->will($this->returnValue(true));

        $autenticationService->expects($this->any())
        ->method('logoutAdapters')
        ->will($this->returnValue(true));


        $autenticationService->expects($this->any())
        ->method('getIdentity')
        ->will($this->returnValue($zfcUserMock));

        $authAdapterMock = $this->getMock('ZfcUser\Authentication\Adapter\AdapterChain');

        $authAdapterMock->expects($this->any())
        ->method('clearIdentity')
        ->will($this->returnValue(true));

        $authMock->expects($this->any())
        ->method('hasIdentity')
        -> will($this->returnValue(true));

        $authMock->expects($this->any())
        ->method('getIdentity')
        ->will($this->returnValue($zfcUserMock));

        $authMock->expects($this->any())
        ->method('getAuthAdapter')
        ->will($this->returnValue($authAdapterMock));

        $authMock->expects($this->any())
        ->method('getAuthService')
        ->will($this->returnValue($autenticationService));

        $this->bootstrap
        ->getServiceManager()
        ->get('ControllerPluginManager')->setService('zfcUserAuthentication', $authMock);

        $this->bootstrap
        ->getServiceManager()
        ->get('ServiceManager')->setService('zfcuser_auth_service', $autenticationService);
    }

    public function getRouteMatch($page, $orderBy = 'id<?php echo $this->class;?>', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => '<?php echo $this->module;?>\Controller\<?php echo $this->class;?>',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('<?php echo $this->str('url', $this->module)?>/<?php echo $this->str('url', $this->class)?>');
        return $routeMatch;
    }
}
