actor: Tester
paths:
    tests: tests
    log: build/coverage
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
    log: true
coverage:
    enabled: true
    remote: true
    exclude:
        - build/*
        - data/*
        - config/*
        - language/*
        - tests/*
        - view/*
    include:
        - src/*