class_name: FunctionalTester
modules:
    enabled: [Filesystem, FunctionalHelper, WebDriver, Db***REMOVED***
    config:
      WebDriver:
         url: '<?php echo $this->url;?>'
         browser: phantomjs
         capabilities:
             webStorageEnabled: true
      Db:
          dsn: 'sqlite:data/<?php echo $this->module;?>'
          user: 'root'
          password: 'gear'
          dump: tests/_data/<?php echo $this->module;?>.sqlite