namespace <?php echo $this->module;?>Test\FactoryTest;

/**
 * @group Factory
 */
class AbstractFactoryTest extends \PHPUnit_Framework_TestCase
{
    protected function setUp()
    {
        $this->bootstrap = new \<?php echo $this->module;?>\ZendServiceLocator();
    }

    protected function tearDown()
    {
        unset($this->bootstrap);
    }


    public function testSetEntityManager()
    {
        $abstract = $this->getMockBuilder('<?php echo $this->module;?>\Factory\AbstractFactory')
        ->disableOriginalConstructor()
        ->getMockForAbstractClass();

        $abstract->setServiceLocator($this->bootstrap->getServiceLocator());

        $this->assertEquals($this->bootstrap->getServiceLocator(), $abstract->getServiceLocator());
    }
}
