namespace <?php echo $this->module;?>\<?php echo $this->module;?>Test\FactoryTest;

use GearBaseTest\AbstractTestCase;
use <?php echo $this->module;?>\Factory\<?php echo $this->serviceNameClass;?>Trait;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Factory
 */
class <?php echo $this->serviceNameClass;?>Test extends AbstractTestCase
{
    use <?php echo $this->serviceNameClass;?>Trait;

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
    */
    public function testGet()
    {
        $<?php echo $this->serviceNameUline;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $this->assertNotNull($<?php echo $this->serviceNameUline;?>);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
    */
    public function testSet()
    {
        $<?php echo $this->mock;?> = $this->getMockSingleClass(
            '<?php echo $this->module;?>\Factory\<?php echo $this->serviceNameClass;?>'
        );
        $this->set<?php echo $this->serviceNameClass;?>($<?php echo $this->mock;?>);
        $this->assertEquals($<?php echo $this->mock;?>, $this->get<?php echo $this->serviceNameClass;?>());
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->serviceNameClass;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

<?php echo $this->template;?>
}
