<?php
namespace MyModule\Controller;

use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;
use Zend\Mvc\Controller\AbstractActionController;
use MyModule\Repository\MyRepositoryOneTrait;
use MyModule\Repository\MyRepositoryTwoTrait;
use MyModule\Repository\MyRepositoryThreeTrait;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependenciesAction extends AbstractActionController
{
    use MyRepositoryOneTrait;

    use MyRepositoryTwoTrait;

    use MyRepositoryThreeTrait;
}
