<?php
namespace MyModule\Another\Long\Namespaces;

use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;
use Zend\Mvc\Controller\AbstractActionController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Another/Long/Namespaces
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicAction extends AbstractActionController
{

}
