<?php
namespace MyModule\Controller;

use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;
use Zend\Mvc\Controller\AbstractActionController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicManyAction extends AbstractActionController
{

    /**
     * First Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function firstActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    /**
     * Second Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function secondActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    /**
     * Third Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function thirdActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    /**
     * Four Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function fourActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    /**
     * Five Action
     *
     * @return \Zend\View\Model\ViewModel
     */
    public function fiveActionAction()
    {
        return new ViewModel([***REMOVED***);
    }
}
