<?php
namespace MyModule\Service;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Service\MyTableService;
use MyModule\Repository\MyTableRepository;
use GearImage\Service\ImageService;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Service
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableServiceFactory implements FactoryInterface
{
    /**
     * Create MyTableService
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MyTableService
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $factory = new MyTableService(
            (extension_loaded('memcached'))
            ? $container->get('memcached')
            : $container->get('filesystem'),
            $container->get(MyTableRepository::class),
            $container->get(ImageService::class)
        );

        return $factory;
    }
}
