<?php
namespace MyModule\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use MyModule\Entity\MyTable;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use GearImage\Fixture;

/**
 * Fixture for My Table Entity.
 *
 * PHP Version 5
 *
 * @category Fixture
 * @package MyModule/Fixture
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableFixture extends AbstractFixture implements
    FixtureInterface,
    DependentFixtureInterface
{
    use Fixture;

    /**
     * Load Fixture
     *
     * @param ObjectManager $manager Object Manager
     *
     * @return void
     */
    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;
        foreach ($this->getFixture() as $i => $fixture) {
            $reference = $i+1;
            $myTable = new MyTable();
            $myTable->setColumnVarchar($fixture['columnVarchar'***REMOVED***);
            $myTable->setColumnUploadImage($fixture['columnUploadImage'***REMOVED***);
            $userReferenced = $this->getReferenceToEntity($reference);
            $myTable->setCreated(new \DateTime('now'));
            $myTable->setCreatedBy($userReferenced);
            $this->manager->persist($myTable);
            $this->manager->flush();
            $this->addReference("my-table-$reference", $myTable);
        }
    }

    /**
     * Return Fixture Data Generated.
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @return array
     */
    public function getFixture()
    {
        $module = new \MyModule\Module();
        $moduleDir = $module->getLocation();
        return [
            [
                'columnVarchar' => '01Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '01',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '02Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '02',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '03Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '03',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '04Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '04',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '05Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '05',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '06Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '06',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '07Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '07',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '08Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '08',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '09Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '09',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '10Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '10',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '11Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '11',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '12Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '12',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '13Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '13',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '14Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '14',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '15Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '15',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '16Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '16',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '17Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '17',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '18Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '18',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '19Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '19',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '20Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '20',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '21Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '21',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '22Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '22',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '23Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '23',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '24Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '24',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '25Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '25',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '26Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '26',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '27Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '27',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '28Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '28',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '29Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '29',
                    $moduleDir
                ),
            ***REMOVED***,
            [
                'columnVarchar' => '30Column Varchar',
                'columnUploadImage' =>
                $this->createUploadImageFixture(
                    'my-table',
                    'columnUploadImage',
                    '30',
                    $moduleDir
                ),
            ***REMOVED***,
        ***REMOVED***;
    }

    /**
     * Load the User Entity.
     *
     * To be used on created_by and updated_by column.
     *
     * @param Integer $referenced Número de Referência
     *
     * @return GearAdmin\Entity\User
     */
    public function getReferenceToEntity($referenced = 1)
    {
        $referencedName = sprintf('usuariogear%d', ($referenced <= 6) ? $referenced : (($referenced%6)+1));
        $userId = $this->getReference($referencedName);
        return $this->manager
          ->getRepository('GearAdmin\Entity\User')
          ->findOneBy(['idUser' => $userId->getIdUser()***REMOVED***);
    }

    /**
     * Get The Table's Foreign Keys Dependencies.
     *
     * @return string[***REMOVED***
     */
    public function getDependencies()
    {
        return ['GearAdmin\Fixture\LoadUser'***REMOVED***;
    }
}
