<?php
namespace MyModule\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
use MyModule\Entity\Table;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;

/**
 * Fixture for Single Db Table Entity.
 *
 * PHP Version 5
 *
 * @category Fixture
 * @package MyModule/Fixture
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class TableFixture extends AbstractFixture implements
    FixtureInterface,
    DependentFixtureInterface
{

    /**
     * Load Fixture
     *
     * @param ObjectManager $manager Object Manager
     *
     * @return void
     */
    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;
        foreach ($this->getFixture() as $i => $fixture) {
            $reference = $i+1;
            $table = new Table();
            $singleDbTable->setSingleDbColumn($fixture['singleDbColumn'***REMOVED***);
            $userReferenced = $this->getReferenceToEntity($reference);
            $table->setCreated(new \DateTime('now'));
            $table->setCreatedBy($userReferenced);
            $this->manager->persist($table);
            $this->manager->flush();
            $this->addReference("table-$reference", $table);
        }
    }

    /**
     * Return Fixture Data Generated.
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @return array
     */
    public function getFixture()
    {
        return [
            [
                'singleDbColumn' => '01Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '02Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '03Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '04Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '05Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '06Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '07Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '08Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '09Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '10Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '11Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '12Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '13Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '14Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '15Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '16Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '17Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '18Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '19Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '20Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '21Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '22Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '23Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '24Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '25Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '26Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '27Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '28Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '29Single Db Column',
            ***REMOVED***,
            [
                'singleDbColumn' => '30Single Db Column',
            ***REMOVED***,
        ***REMOVED***;
    }

    /**
     * Load the User Entity.
     *
     * To be used on created_by and updated_by column.
     *
     * @param Integer $referenced Número de Referência
     *
     * @return GearAdmin\Entity\User
     */
    public function getReferenceToEntity($referenced = 1)
    {
        $referencedName = sprintf('usuariogear%d', ($referenced <= 6) ? $referenced : (($referenced%6)+1));
        $userId = $this->getReference($referencedName);
        return $this->manager
          ->getRepository('GearAdmin\Entity\User')
          ->findOneBy(array('idUser' => $userId->getIdUser()));
    }

    /**
     * Get The Table's Foreign Keys Dependencies.
     *
     * @return string[***REMOVED***
     */
    public function getDependencies()
    {
        return array('GearAdmin\Fixture\LoadUser');
    }
}
