<phpunit
    bootstrap="./../vendor/autoload.php"
    colors="true"
    convertErrorsToExceptions="true"
    convertNoticesToExceptions="true"
    convertWarningsToExceptions="true"
    verbose="true"
    backupGlobals="false"
    processIsolation="false"
    backupStaticAttributes="false"
>
    <testsuites>
        <testsuite name="sites">
            <directory suffix="Test.php">./unit/</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory suffix=".php">./../src</directory>
            <exclude>
                <file>./../src/Module.php</file>
            </exclude>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-html" target="./../build/coverage"/>
        <log type="junit" target="./../build/report.xml" />
    </logging>
</phpunit>
