<phpunit
    bootstrap="./../vendor/autoload.php"
    colors="true"
    backupGlobals="false"
    backupStaticAttributes="false"
    syntaxCheck="false"
>
    <testsuites>
        <testsuite name="sites">
            <directory suffix="Test.php">./unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist>
            <directory suffix=".php">./../src</directory>
            <exclude>
                <file>./../src/Module.php</file>
            </exclude>
        </whitelist>
    </filter>
    <logging>
        <log type="coverage-clover" target="./../build/logs/clover.xml" />
    </logging>
</phpunit>
