return [
  'modules' =>
  [
      'DoctrineModule',
      'DoctrineORMModule',
      'GearBase',
      'Gear',
      'GearJson',
      'GearDeploy',
      'GearJenkins',
      'GearVersion',
      '<?php echo $this->module; ?>'
  ***REMOVED***,
  'module_listener_options' =>
  [
    'module_paths' =>
    [
        '../.',
        './vendor',
    ***REMOVED***,
    'config_glob_paths' =>
    [
        'config/autoload/{,*.}{global,local}.php',
    ***REMOVED***,
  ***REMOVED***,
***REMOVED***; ?>