namespace <?php echo $this->module;?>;

return [
    'connection' => [
        'orm_default' => [
            'configuration' => 'orm_default',
            'eventmanager' => 'orm_default',
            'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
            'params' => [
                'host' => 'localhost',
                'port' => '3306',
                'dbname' => '<?php echo $this->moduleUline;?>',
                'user' => 'root',
                'password' => 'gear',
                'charset' => 'utf8'
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***,
    'driver' => [
        'orm_default' => [
            'drivers' => [
                __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_driver'
            ***REMOVED***
        ***REMOVED***,
        __NAMESPACE__ . '_driver' => [
            'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
            'paths' => [
                __DIR__ . '/../../src/Entity'
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***
***REMOVED***;
