namespace <?php echo $this->module;?>;

$db                 = require 'ext/db.config.php';
$doctrine           = require 'ext/doctrine.config.php';
$translator         = require 'ext/translator.config.php';
$route              = require 'ext/route.config.php';
$navigation         = require 'ext/navigation.config.php';
$view               = require 'ext/view.config.php';
$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$assetmanager       = require 'ext/asset.config.php';
$controllerplugins  = require 'ext/controllerplugins.config.php';
$uploadimage        = require 'ext/upload-image.config.php';
$cache              = require 'ext/cache.config.php';

return array(
    'gear'     => array('version' => '0.1.0', 'acl' => true, 'name' => __NAMESPACE__),
    'db' => $db,
    'doctrine' => $doctrine,
    'translator' => $translator,
    'view_manager' => $view,
    'controllers' => $controller,
    'router' => $route,
    'navigation' => $navigation,
    'service_manager' => $servicemanager,
    'asset_manager' => $assetmanager,
    'controller_plugins' => $controllerplugins,
    'fileUpload' => $uploadimage,
    'data-fixture' => array(
        __NAMESPACE__.'_fixture' => __DIR__ . '/../src/'.__NAMESPACE__.'/Fixture',
    ),
);
