return [
    'default' => [
        [
            'label' => '<?php echo $this->moduleLabel;?>',
            'route' => '<?php echo $this->moduleUrl;?>',
            'pages' => [
                [
                    'label' => 'Index',
                    'route' => '<?php echo $this->moduleUrl;?>'
                ***REMOVED***,

            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***
***REMOVED***;
