return [
    'router_class' => 'Zend\Mvc\Router\Http\TranslatorAwareTreeRouteStack',
    'routes' => [
        '<?php echo $this->moduleUrl;?>' => [
            'type' => 'literal',
            'options' => [
                'route' => '/<?php echo $this->moduleUrl;?>',
                'defaults' => [
                    'controller' => '<?php echo $this->namespace;?>\Controller\Index',
                    'action' => 'index'
                ***REMOVED***
            ***REMOVED***,
            'may_terminate' => true,
        ***REMOVED***
    ***REMOVED***
***REMOVED***;
