
    public function testCreateAction()
    {
        $this->assertAcl(
            $this->schema,
            '<?php echo $this->module;?>',
            '<?php echo $this->controllerName;?>',
            '<?php echo $this->namespace;?>',
            '<?php echo $this->actionName;?>'
        );

        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }
