return array(
    'db' => array(
        'driver' => 'Pdo_Sqlite',
        'database' => __DIR__ . '/../../data/<?php echo $this->dbname;?>',
    ),
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'driverClass' => 'Doctrine\DBAL\Driver\PDOSqlite\Driver',
                'params' => array(
                    'path' => __DIR__.'/../../data/<?php echo $this->dbname;?>',
                )
            )
        )
    )
);
