return [
    'gear' => [
        'project' => [
            'name' => '<?php echo $this->name;?>',
            'project' => true,
            'version' => '<?php echo $this->version;?>',
            'git' => '<?php echo $this->git;?>',
            'label' => '<?php echo $this->label;?>',
            'environment' => [
                'DEVELOPMENT' => '<?php echo $this->development;?>',
                'TESTING' => '<?php echo $this->testing;?>',
                'STAGING' => '<?php echo $this->staging;?>',
                'PRODUCTION' => '<?php echo $this->production;?>'
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'bjyauthorize' => ['acl_key' => '<?php echo $this->aclKey;?>'***REMOVED***,
    'admin' => [
        'name' => '<?php echo $this->adminName;?>',
        'title' => '<?php echo $this->adminTitle;?>',
        'welcome' => '<?php echo $this->adminWelcome;?>'
     ***REMOVED***,
    'db' => [
        'dsn' => 'mysql:dbname=<?php echo $this->dbname;?>;host=localhost',
        'driver' => 'Pdo',
        'charset' => 'UTF8'
    ***REMOVED***,
    'phinx' => [
        'adapter' => 'mysql',
        'host' => 'localhost',
        'name' => '<?php echo $this->dbname;?>'
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host' => 'localhost',
                    'port' => '3306',
                    'dbname' => '<?php echo $this->dbname;?>',
                    'charset' => 'utf8'
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***,
        'configuration' => [
        	'orm_default' => [
        	    'metadata_cache' => 'filesystem',
        	    'query_cache' => 'filesystem',
        	    'result_cache' => 'filesystem',
        	    'hydration_cache' => 'filesystem',
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'session_manager' => [***REMOVED***,
    'session_config' => [
        'cache_expire' => 3600,
        'cookie_lifetime' => 3600,
        'save_path' => __DIR__.'/../../data/session'
    ***REMOVED***
***REMOVED***;