return array(
    'gear' => array(
        'project' => true,
        'version' => '<?php echo $this->version;?>'
    ),
    'db' => array(
        'driver' => 'Pdo',
        'dsn' => 'mysql:dbname=<?php echo $this->dbname;?>;host=<?php echo $this->dbhost;?>',
        'driver_options' => array(
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        )
    ),
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => array(
                    'host' => '<?php echo $this->dbhost;?>',
                    'port' => '3306',
                    'dbname' => '<?php echo $this->dbname;?>',
                    'charset' => 'utf8'
                )
            )
        ),
        'configuration' => array(
        	'orm_default' => array(
        	    'metadata_cache' => 'filesystem', // 2
        	    'query_cache' => 'filesystem', // 3
        	    'result_cache' => 'filesystem', // 4
        	    'hydration_cache' => 'filesystem', // 5
            )
        ),
    ),
    'phinx' => array(
        'adapter' => 'mysql',
        'host' => '<?php echo $this->dbhost;?>',
        'name'=> '<?php echo $this->dbname;?>'
    ),
);
