return array(
    'db' => array(
        'driver' => 'Pdo_Sqlite',
        'database' => 'file:::memory:?cache=shared',
        'file' => __DIR__.'/../../data/schema.sqlite.sql'
    ),
    'phinx' => array(
        'name' => __DIR__ . '/../../data/schema.sqlite',
    ),
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'driverClass' => 'Doctrine\DBAL\Driver\PDOSqlite\Driver',
                'params' => array(
                    'path' => 'file:::memory:?cache=shared',
                )
            )
        )
    )
);
