return [
    'db' => [
        'username' => '<?php echo $this->username; ?>',
        'password' => '<?php echo $this->password; ?>',
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
               'params' => [
                    'user'     => '<?php echo $this->username; ?>',
                    'password' => '<?php echo $this->password; ?>',
               ***REMOVED***,
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***,
    'phinx' => [
        'user' => '<?php echo $this->username; ?>',
        'pass' => '<?php echo $this->password; ?>',
    ***REMOVED***,
***REMOVED***;
