return array(
    'connection' => array(
        'orm_default' => array(
            'configuration' => 'orm_default',
            'eventmanager' => 'orm_default',
            'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
            'params' => array(
                'host' => 'localhost',
                'port' => '3306',
                'dbname' => '<?php echo $this->dbname;?>',
                'charset' => 'utf8'
            )
        )
    ),
);
