<?php
namespace MyModule\Custom\CustomNamespace;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Custom\CustomNamespace\MyTableNamespaceController;
use MyModule\Custom\CustomNamespace\MyTableService;
use MyModule\Custom\CustomNamespace\MyTableForm;
use MyModule\Custom\CustomNamespace\MyTableSearchForm;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableNamespaceControllerFactory implements FactoryInterface
{
    /**
     * Create MyTableNamespaceController
     *
     * @param ContainerInterface $container Controller Manager
     *
     * @return MyTableNamespaceController
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        

        $factory = new MyTableNamespaceController(
            $container->get(MyTableService::class),
            $container->get(MyTableForm::class),
            $container->get(MyTableSearchForm::class)
        );
        
        return $factory;
    }
}
