<?php
namespace MyModule\Controller;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Controller\MyTableController;
use MyModule\Service\MyTableService;
use MyModule\Form\MyTableForm;
use MyModule\Form\Search\MyTableSearchForm;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableControllerFactory implements FactoryInterface
{
    /**
     * Create MyTableController
     *
     * @param ContainerInterface $container Controller Manager
     *
     * @return MyTableController
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        

        $factory = new MyTableController(
            $container->get(MyTableService::class),
            $container->get(MyTableForm::class),
            $container->get(MyTableSearchForm::class)
        );
        
        return $factory;
    }
}
