<?php
namespace MyModule\Custom\CustomNamespace;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Custom\CustomNamespace\MyTableNamespaceController;
use MyModule\Custom\CustomNamespace\MyTableService;
use MyModule\Custom\CustomNamespace\MyTableForm;
use MyModule\Custom\CustomNamespace\MyTableSearchForm;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableNamespaceControllerFactory implements FactoryInterface
{
    /**
     * Create MyTableNamespaceController
     *
     * @param ServiceLocatorInterface $controllerManager Controller Manager
     *
     * @return MyTableNamespaceController
     */
    public function createService(ServiceLocatorInterface $controllerManager)
    {
        $serviceLocator = $controllerManager->getServiceLocator();

        $factory = new MyTableNamespaceController(
            $serviceLocator->get(MyTableService::class),
            $serviceLocator->get(MyTableForm::class),
            $serviceLocator->get(MyTableSearchForm::class)
        );
        unset($serviceLocator);
        return $factory;
    }
}
