namespace <?php echo $this->module;?>\Pages;

/**
 * @author Maurício Piber Fão
 * @SuppressWarnings(PHPMD)
 */
class <?php echo $this->class;?>DeletePage extends LayoutPage
{
    public static $URL = '/<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl?>/excluir';

    public static $title = '#pageTitle';

    public static $modalTitle = '.modal-title';

    public static $modalText = '.modal-body p';

    public static $btnConfirm = '#confirm';

    public static $btnCancel = '#cancelDelete';

    public static function route($param)
    {
        return static::$URL.$param;
    }
}
