namespace <?php echo $this->module;?>\Pages;

/**
 * @SuppressWarnings(PHPMD)
 */
class <?php echo $this->class;?>ListPage extends ListLayoutPage
{
    public static $URL = '/<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl;?>/listar';

    public static $table = '#<?php echo $this->classVar;?>Table';

    public static $tableHeadRow = '#<?php echo $this->classVar;?>Table > thead > tr > th';

    public static $tableBodyRow = '#<?php echo $this->classVar;?>Table > tbody > tr';

    public static $tableBodyRowColumn = '#<?php echo $this->classVar;?>Table > tbody > tr:nth-child(%d) td';
}
