namespace <?php echo $this->module;?>\Pages;

/**
 * @SuppressWarnings(PHPMD)
 */
class LayoutPage
{
    public static $url = '/';

    public static $title = '#pageTitle';

    public static $breadscrumb = 'ul.breadcrumb li';

    public static function getBreadcrumbByIndex($index)
    {
        return self::$breadscrumb.':nth-child('.$index.')';
    }

    public static function route($param)
    {
        return static::$URL.$param;
    }
}
