<?php $this->partialLoop()->setObjectKey('object'); ?>
<div class="row">
	<div class="col-lg-4">
        <h3 id="pageTitle">Tipo Custo</h3>
	</div>
	<div class="col-lg-4 col-lg-offset-4">
	    <a class="btn btn-success pull-left" href="<?php echo $this->url('piber-network/tipo-custo/create');?>"">
            <?php echo $this->translate('Criar');?>
        </a>&nbsp;
        <a href="#" id="toggleFilter" class="btn btn-primary linkFilter">Exibir Filtro</a>
	</div>
</div>
<?php echo ($this->sucesso) ? $this->render($this->sucesso) : '';?>
<br>
<?php echo $this->render('piber-network/tipo-custo/search-form.phtml');?>
<table class="table">
    <thead>
        <tr>
            <?php echo $this->tableHead($this->tableService);?>
            <th>
                 <?php echo $this->translate('Actions');?>
            </th>
        </tr>
    </thead>
    <tbody>
        <?php echo $this->partialLoop('piber-network/tipo-custo/row.phtml', $this->data); ?>
    </tbody>
</table>
<?php echo $this->paginationControl($this->data, 'Sliding', 'layout/paginator', array('route' => 'piber-network/tipo-custo/list', 'orderBy' => $this->orderBy, 'order' => $this->order))  ; ?>
<?php echo $this->render('layout/delete');?>