<?php
namespace MyModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group MyModule
 * @group TableService
 * @group Service
 */
class TableServiceTest extends AbstractTestCase
{
    protected $tableService;

    public function setUp()
    {
        parent::setUp();
        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
        $this->imageService = $this->prophesize('GearImage\Service\ImageService');
        $this->getTableService()->setImageService($this->imageService->reveal());
    }

    public function getTableService()
    {
        if (!isset($this->tableService)) {
            $this->tableService =
                $this->bootstrap->getServiceLocator()->get(
                    'MyModule\Service\TableService'
                );
        }
        return $this->tableService;
    }

    public function mockUploadImage()
    {
        $maker = new \GearBaseTest\UploadImageMock();
        return $maker->mockUploadFile(\MyModule\Module::getLocation());
    }

    public function testSetSelectAllCache()
    {
        $this->getTableService()->setSessionName('testing');

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem('testingResult')) {
            $cache->removeItem('testingResult');
        }

        $data = $this->getTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->getTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->getTableService()->setRouteMatch($this->getRouteMatch(1, 'idTable', 'DESC'));

        $this->assertEquals('idTable', $this->getTableService()->getOrderBy());
        $this->assertEquals('DESC', $this->getTableService()->getOrder());

        $this->getTableService()->selectAll();

        $this->getTableService()->setRouteMatch($this->getRouteMatch(1, 'idTable', 'ASC'));

        $this->assertEquals('idTable', $this->getTableService()->getOrderBy());
        $this->assertEquals('ASC', $this->getTableService()->getOrder());

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem($this->getTableService()->getSessionName())) {
            $cache->removeItem($this->getTableService()->getSessionName());
        }

        $this->getTableService()->setRouteMatch(
            $this->getRouteMatch(1, 'idTable', 'DESC')
        );

        $this->assertEquals(
            'idTable',
            $this->getTableService()->getOrderBy()
        );
        $this->assertEquals('DESC', $this->getTableService()->getOrder());
    }

    public function testTableHead()
    {
        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->getMapReferences()->willReturn([***REMOVED***)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());


        $allColumnsDbNotNul = $this->getTableService();
        $resultSet = $allColumnsDbNotNul->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $this->entity = $this->prophesize('MyModule\Entity\Table');
        $this->entity->getIdTable()->willReturn(1);

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectById(1)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $resultSet = $this->getTableService()->selectById(1);
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(1, $resultSet->getIdTable());
    }

    public function testSelectOne()
    {
        $this->entity = $this->prophesize('MyModule\Entity\Table');
        $this->entity->getIdTable()->willReturn(30);

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectOneBy(['idTable' => 30***REMOVED***)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'idTable' =>
                    30
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            30,
            $resultSet->getIdTable()
        );
    }

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
            'uploadImageColumn' => 'image123',
        );

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->createUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->getTableService()->create($data);

        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
            'uploadImageColumn' => 'image123',
        );

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $this->getTableService()->setCache($this->cache->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->updateUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->getTableService()
            ->update(31, $data);


        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->getTableService()->setCache($this->cache->reveal());
        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = ['idTableService' => 31***REMOVED***;
        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();


        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'idTable', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => 'MyModule\Controller\Table',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('my-module/table');
        return $routeMatch;
    }
}
