<?php
namespace MyModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group MyModule
 * @group TableService
 * @group Service
 */
class TableServiceTest extends AbstractTestCase
{
    protected $tableService;

    public function setUp()
    {
        parent::setUp();
        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
        $this->imageService = $this->prophesize('GearImage\Service\ImageService');
        $this->getTableService()->setImageService($this->imageService->reveal());
    }

    public function getTableService()
    {
        if (!isset($this->tableService)) {
            $this->tableService =
                $this->bootstrap->getServiceLocator()->get(
                    'MyModule\Service\TableService'
                );
        }
        return $this->tableService;
    }

    /**
     * @group MyModule
     * @group TableService
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getTableService()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group MyModule
     * @group TableService
    */
    public function testCallUsingServiceLocator()
    {
        $tableService = $this->getTableService();
        $this->assertInstanceOf('MyModule\Service\TableService', $tableService);
    }


    public function mockUploadImage()
    {
        $maker = new \GearBaseTest\UploadImageMock();
        return $maker->mockUploadFile(\MyModule\Module::getLocation());
    }

    public function testSetSelectAllCache()
    {
        $this->getTableService()->setSessionName('testing');

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem('testingResult')) {
            $cache->removeItem('testingResult');
        }

        $data = $this->getTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->getTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->getTableService()->setRouteMatch($this->getRouteMatch(1, 'idTable', 'DESC'));

        $this->assertEquals('idTable', $this->getTableService()->getOrderBy());
        $this->assertEquals('DESC', $this->getTableService()->getOrder());

        $this->getTableService()->selectAll();

        $this->getTableService()->setRouteMatch($this->getRouteMatch(1, 'idTable', 'ASC'));

        $this->assertEquals('idTable', $this->getTableService()->getOrderBy());
        $this->assertEquals('ASC', $this->getTableService()->getOrder());

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem($this->getTableService()->getSessionName())) {
            $cache->removeItem($this->getTableService()->getSessionName());
        }

        $this->getTableService()->setRouteMatch(
            $this->getRouteMatch(1, 'idTable', 'DESC')
        );

        $this->assertEquals(
            'idTable',
            $this->getTableService()->getOrderBy()
        );
        $this->assertEquals('DESC', $this->getTableService()->getOrder());
    }

    public function testGetMappingInfo()
    {
        $tableService = $this->getTableService();
        $resultSet = $tableService->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $tableService = $this->getTableService();

        $resultSet = $tableService->selectById(1);
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(1, $resultSet->getIdTable());
    }

    public function testSelectOneByIdMyController()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'idMyController' =>
                    15
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            15,
            $resultSet->getIdMyController()
        );
    }
    public function testSelectOneByHtmlColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'htmlColumn' =>
                    '15Html Column'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            '15Html Column',
            $resultSet->getHtmlColumn()
        );
    }
    public function testSelectOneByTextColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'textColumn' =>
                    '15Text Column'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            '15Text Column',
            $resultSet->getTextColumn()
        );
    }
    public function testSelectOneByEmailColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'emailColumn' =>
                    'email.column15@gmail.com'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            'email.column15@gmail.com',
            $resultSet->getEmailColumn()
        );
    }
    public function testSelectOneByTelephoneColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'telephoneColumn' =>
                    '(51) 9999-9915'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            '(51) 9999-9915',
            $resultSet->getTelephoneColumn()
        );
    }
    public function testSelectOneByUploadImageColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'uploadImageColumn' =>
                    '/upload/table-uploadImageColumn/%s15uploadImageColumn.gif'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            '/upload/table-uploadImageColumn/%s15uploadImageColumn.gif',
            $resultSet->getUploadImageColumn()
        );
    }
    public function testSelectOneByUrlColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'urlColumn' =>
                    'url.column15.com.br'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            'url.column15.com.br',
            $resultSet->getUrlColumn()
        );
    }
    public function testSelectOneByVarcharColumn()
    {
        $resultSet = $this->getTableService()->selectOneBy(
            array(
                'varcharColumn' =>
                    '15Varchar Column'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            '15Varchar Column',
            $resultSet->getVarcharColumn()
        );
    }

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->createUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->getTableService()->create($data);

        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $this->getTableService()->setCache($this->cache->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->updateUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->getTableService()
            ->update(31, $data);


        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->getTableService()->setCache($this->cache->reveal());
        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {

        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = ['idTableService' => 31***REMOVED***;
        $this->repository = $this->prophesize('MyModule\Repository\TableRepository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();


        $this->getTableService()->setTableRepository($this->repository->reveal());

        $tableService = $this->getTableService();

        $resultSet = $tableService->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'idTable', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => 'MyModule\Controller\Table',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('my-module/table');
        return $routeMatch;
    }
}
