<?php
namespace MyModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group MyModule
 * @group SingleDbTableService
 * @group Service
 */
class SingleDbTableServiceTest extends AbstractTestCase
{
    protected $singleDbTableServi;

    public function setUp()
    {
        parent::setUp();
        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
    }

    public function getSingleDbTableService()
    {
        if (!isset($this->singleDbTableServi)) {
            $this->singleDbTableServi =
                $this->bootstrap->getServiceLocator()->get(
                    'MyModule\Service\SingleDbTableService'
                );
        }
        return $this->singleDbTableServi;
    }

    /**
     * @group MyModule
     * @group SingleDbTableService
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getSingleDbTableService()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group MyModule
     * @group SingleDbTableService
    */
    public function testCallUsingServiceLocator()
    {
        $singleDbTableServi = $this->getSingleDbTableService();
        $this->assertInstanceOf('MyModule\Service\SingleDbTableService', $singleDbTableServi);
    }


    public function testSetSelectAllCache()
    {
        $this->getSingleDbTableService()->setSessionName('testing');

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem('testingResult')) {
            $cache->removeItem('testingResult');
        }

        $data = $this->getSingleDbTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->getSingleDbTableService()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->getSingleDbTableService()->setRouteMatch($this->getRouteMatch(1, 'idSingleDbTable', 'DESC'));

        $this->assertEquals('idSingleDbTable', $this->getSingleDbTableService()->getOrderBy());
        $this->assertEquals('DESC', $this->getSingleDbTableService()->getOrder());

        $this->getSingleDbTableService()->selectAll();

        $this->getSingleDbTableService()->setRouteMatch($this->getRouteMatch(1, 'idSingleDbTable', 'ASC'));

        $this->assertEquals('idSingleDbTable', $this->getSingleDbTableService()->getOrderBy());
        $this->assertEquals('ASC', $this->getSingleDbTableService()->getOrder());

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem($this->getSingleDbTableService()->getSessionName())) {
            $cache->removeItem($this->getSingleDbTableService()->getSessionName());
        }

        $this->getSingleDbTableService()->setRouteMatch(
            $this->getRouteMatch(1, 'idSingleDbTable', 'DESC')
        );

        $this->assertEquals(
            'idSingleDbTable',
            $this->getSingleDbTableService()->getOrderBy()
        );
        $this->assertEquals('DESC', $this->getSingleDbTableService()->getOrder());
    }

    public function testGetMappingInfo()
    {
        $singleDbTableServi = $this->getSingleDbTableService();
        $resultSet = $singleDbTableServi->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $singleDbTableServi = $this->getSingleDbTableService();

        $resultSet = $singleDbTableServi->selectById(1);
        $this->assertInstanceOf('MyModule\Entity\SingleDbTable', $resultSet);
        $this->assertEquals(1, $resultSet->getIdSingleDbTable());
    }

    public function testSelectOneBySingleDbColumn()
    {
        $resultSet = $this->getSingleDbTableService()->selectOneBy(
            array(
                'singleDbColumn' =>
                    '15Single Db Column'
            )
        );
        $this->assertInstanceOf('MyModule\Entity\SingleDbTable', $resultSet);
        $this->assertEquals(
            '15Single Db Column',
            $resultSet->getSingleDbColumn()
        );
    }

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('MyModule\Entity\SingleDbTable');
        $entity->getIdSingleDbTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\Repository\SingleDbTableRepository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->getSingleDbTableService()->setSingleDbTableRepository($this->repository->reveal());


        $resultSet = $this->getSingleDbTableService()->create($data);

        $this->assertInstanceOf('MyModule\Entity\SingleDbTable', $resultSet);
        $this->assertEquals(31, $resultSet->getIdSingleDbTable());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('MyModule\Entity\SingleDbTable');
        $entity->getIdSingleDbTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\Repository\SingleDbTableRepository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->getSingleDbTableService()->setSingleDbTableRepository($this->repository->reveal());

        $this->getSingleDbTableService()->setCache($this->cache->reveal());


        $resultSet = $this->getSingleDbTableService()
            ->update(31, $data);


        $this->assertInstanceOf('MyModule\Entity\SingleDbTable', $resultSet);
        $this->assertEquals(31, $resultSet->getIdSingleDbTable());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('MyModule\Entity\SingleDbTable');
        $entity->getIdSingleDbTable()->willReturn(31);

        $this->repository = $this->prophesize('MyModule\Repository\SingleDbTableRepository');
        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->getSingleDbTableService()->setCache($this->cache->reveal());
        $this->getSingleDbTableService()->setSingleDbTableRepository($this->repository->reveal());

        $singleDbTableServi = $this->getSingleDbTableService();

        $resultSet = $singleDbTableServi->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {

        $this->repository = $this->prophesize('MyModule\Repository\SingleDbTableRepository');
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $this->getSingleDbTableService()->setSingleDbTableRepository($this->repository->reveal());

        $singleDbTableServi = $this->getSingleDbTableService();

        $resultSet = $singleDbTableServi->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('MyModule\Entity\SingleDbTable');
        $entity->getIdSingleDbTable()->willReturn(31);

        $data = ['idSingleDbTableService' => 31***REMOVED***;
        $this->repository = $this->prophesize('MyModule\Repository\SingleDbTableRepository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();


        $this->getSingleDbTableService()->setSingleDbTableRepository($this->repository->reveal());

        $singleDbTableServi = $this->getSingleDbTableService();

        $resultSet = $singleDbTableServi->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'idSingleDbTable', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => 'MyModule\Controller\SingleDbTable',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('my-module/single-db-table');
        return $routeMatch;
    }
}
