namespace <?php echo $this->module;?>\Factory;

use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use <?php echo $this->module;?>\Factory\AbstractFactory;
use <?php echo $this->module;?>\Form\Search\<?php echo str_replace('Factory', '', $this->class)?>Form;

class <?php echo $this->class;?> extends AbstractFactory
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $form = new <?php echo str_replace('Factory', '', $this->class)?>Form(
            $serviceLocator->get('doctrine.entitymanager.orm_default')
        );
        return $form;
    }
}
