<?php
namespace MyModule\Custom\CustomNamespace;

use GearBase\Service\AbstractService;
use MyModule\Custom\CustomNamespace\AllColumnsDbRepositoryTrait;
use GearImage\Service\ImageServiceTrait;
use MyModule\Custom\CustomNamespace\AllColumnsDbRepository;
use Zend\Cache\Storage\Adapter\Memcached;
use Zend\Authentication\AuthenticationService;
use GearImage\Service\ImageService;
use GearBase\Service\PasswordVerifyTrait;

/**
 * Interaction between AllColumnsDbController and Services
 *
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class AllColumnsDbService extends AbstractService
{
    use AllColumnsDbRepositoryTrait;

    use ImageServiceTrait;

    use PasswordVerifyTrait;

    protected $sessionName;

    protected $authService;

    /**
     * Constructor
     *
     * @param AllColumnsDbRepository $allColumnsDb       All Columns Db Repository
     * @param Memcached              $cache              Memcached
     * @param AuthenticationService  $zfcuserAuthService Authentication Service
     * @param ImageService           $imageService       Image Service
     *
     * @return \MyModule\Custom\CustomNamespace\AllColumnsDbService
     */
    public function __construct(
        AllColumnsDbRepository $allColumnsDb,
        Memcached $cache,
        AuthenticationService $zfcuserAuthService,
        ImageService $imageService
    ) {
        $this->allColumnsDbRepository = $allColumnsDb;
        $this->cache = $cache;
        $this->zfcuserAuthService = $zfcuserAuthService;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Get the values used to generate Html Table on List Action.
     *
     * @return array
     */
    public function getTableHead()
    {
        $map = $this->getAllColumnsDbRepository()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    /**
     * Get the Service session name.
     *
     * @return string
     */
    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = 'allColumnsDbSession';
        }
        return $this->sessionName;
    }

    /**
     * Select one row based on criteria.
     *
     * @param array $data Criteria
     *
     * @return null|MyModule\Entity\AllColumnsDb
     */
    public function selectOneBy(array $data)
    {
        return $this->getAllColumnsDbRepository()->selectOneBy($data);
    }

    /**
     * Select All Rows from All Columns Db table.
     *
     * Use cache to store data until change.
     *
     * @param array $select Criteria
     *
     * @return array
     */
    public function selectAll($select = array())
    {
        $this->cache      = $this->getCache();
        $this->repository = $this->getAllColumnsDbRepository();

        return parent::selectAll($select);
    }

    /**
     * Create a new All Columns Db on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful created.
     *
     * @param array $data Valid $_POST
     *
     * @return null|MyModule\Entity\AllColumnsDb
     */
    public function create($data)
    {
        $repository = $this->getAllColumnsDbRepository();

        $this->createPassword('passwordVerifyColumn');
        $uploadImageColumn = $this->getImageService()->overwriteImage(
            $data,
            'table',
            'uploadImageColumn'
        );

        $allColumnsDb = $repository->insert($data);
        if ($allColumnsDb) {
            if (isset($data['uploadImageColumn'***REMOVED***)) {
                $this->getImageService()->createUploadImage(
                    $uploadImageColumn,
                    'table-uploadImageColumn',
                    $data['uploadImageColumn'***REMOVED***
                );
            }
            $this->clearCache();
        }
        return $allColumnsDb;
    }

    /**
     * Update a existing All Columns Db on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful updated.
     *
     * @param integer $idTable Id
     * @param array   $data    Valid $_POST
     *
     * @return null|MyModule\Entity\AllColumnsDb
     */
    public function update($idTable, $data = array())
    {
        $repository = $this->getAllColumnsDbRepository();

        $this->createPassword('passwordVerifyColumn');
        $uploadImageColumn = $this->getImageService()->overwriteImage(
            $data,
            'table',
            'uploadImageColumn'
        );

        $allColumnsDb = $repository->update($idTable, $data);
        if ($allColumnsDb) {
            if (isset($data['uploadImageColumn'***REMOVED***)) {
                $this->getImageService()->updateUploadImage(
                    $uploadImageColumn,
                    'table-uploadImageColumn',
                    $data['uploadImageColumn'***REMOVED***
                );
            }
            $this->clearCache();
        }
        return $allColumnsDb;
    }

    /**
     * Delete a existing All Columns Db by Id.
     *
     * @param integer $idTable Id
     *
     * @return array
     */
    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return ['success' => false, 'error' => 'EntityNotFound'***REMOVED***;
        }

        $repository = $this->getAllColumnsDbRepository();
        $allColumnsDb = $repository->deleteSafe($entity);


        if ($allColumnsDb) {
            $this->getImageService()->deleteImages($idTable, 'allColumnsDb');
            $this->getImageService()->deleteUploadImage($idTable, 'table');
            $this->clearCache();
        }
        return $allColumnsDb;
    }

    /**
     * Convert Entity to Array.
     *
     * @param \MyModule\Entity\AllColumnsDb $data All Columns Db Entity
     *
     * @return array
     */
    public function extract(\MyModule\Entity\AllColumnsDb $data)
    {
        $repository = $this->getAllColumnsDbRepository();
        return $repository->extract($data);
    }

    /**
     * Select one All Columns Db by Id.
     *
     * @param array $idToSelect Id
     *
     * @return null|MyModule\Entity\AllColumnsDb
     */
    public function selectById($idToSelect)
    {
        $repository = $this->getAllColumnsDbRepository();
        return $repository->selectById($idToSelect);
    }
}
