<?php
namespace MyModule\Custom\CustomNamespace;

use GearBase\Service\AbstractService;
use MyModule\Entity\DbUploadImage;
use MyModule\Custom\CustomNamespace\DbUploadImageRepositoryTrait;
use GearImage\Service\ImageServiceTrait;
use MyModule\Custom\CustomNamespace\DbUploadImageRepository;
use Zend\Cache\Storage\Adapter\Memcached;
use Zend\Authentication\AuthenticationService;
use GearImage\Service\ImageService;

/**
 * Interaction between DbUploadImageController and Services
 *
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class DbUploadImageService extends AbstractService
{
    use DbUploadImageRepositoryTrait;

    use ImageServiceTrait;

    protected $sessionName;

    protected $authService;

    /**
     * Constructor
     *
     * @param DbUploadImageRepository $imageRepository    Db Upload Image Repository
     * @param Memcached               $cache              Memcached
     * @param AuthenticationService   $zfcuserAuthService Authentication Service
     * @param ImageService            $imageService       Image Service
     *
     * @return DbUploadImageService
     */
    public function __construct(
        DbUploadImageRepository $imageRepository,
        Memcached $cache,
        AuthenticationService $zfcuserAuthService,
        ImageService $imageService
    ) {
        $this->dbUploadImageRepository = $imageRepository;
        $this->cache = $cache;
        $this->zfcuserAuthService = $zfcuserAuthService;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Get the values used to generate Html Table on List Action.
     *
     * @return array
     */
    public function getTableHead()
    {
        $map = $this->getDbUploadImageRepository()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    /**
     * Get the Service session name.
     *
     * @return string
     */
    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = 'dbUploadImageSession';
        }
        return $this->sessionName;
    }

    /**
     * Select one row based on criteria.
     *
     * @param array $data Criteria
     *
     * @return null|MyModule\Entity\DbUploadImage
     */
    public function selectOneBy(array $data)
    {
        return $this->getDbUploadImageRepository()->selectOneBy($data);
    }

    /**
     * Select All Rows from Db Upload Image table.
     *
     * Use cache to store data until change.
     *
     * @param array $select Criteria
     *
     * @return array
     */
    public function selectAll($select = [***REMOVED***)
    {
        $this->cache      = $this->getCache();
        $this->repository = $this->getDbUploadImageRepository();

        return parent::selectAll($select);
    }

    /**
     * Create a new Db Upload Image on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful created.
     *
     * @param array $data Valid $_POST
     *
     * @return null|MyModule\Entity\DbUploadImage
     */
    public function create($data)
    {
        $repository = $this->getDbUploadImageRepository();


        $dbUploadImage = $repository->insert($data);
        if ($dbUploadImage) {
            $this->clearCache();
        }
        return $dbUploadImage;
    }

    /**
     * Update a existing Db Upload Image on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful updated.
     *
     * @param integer $idTable Id
     * @param array   $data    Valid $_POST
     *
     * @return null|MyModule\Entity\DbUploadImage
     */
    public function update($idTable, $data = [***REMOVED***)
    {
        $repository = $this->getDbUploadImageRepository();


        $dbUploadImage = $repository->update($idTable, $data);
        if ($dbUploadImage) {
            $this->clearCache();
        }
        return $dbUploadImage;
    }

    /**
     * Delete a existing Db Upload Image by Id.
     *
     * @param integer $idTable Id
     *
     * @return array
     */
    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return ['success' => false, 'error' => 'EntityNotFound'***REMOVED***;
        }

        $repository = $this->getDbUploadImageRepository();
        $dbUploadImage = $repository->deleteSafe($entity);


        if ($dbUploadImage) {
            $this->getImageService()->deleteImagesTableContext(
                $idTable,
                'db-upload-image'
            );
            $this->clearCache();
        }
        return $dbUploadImage;
    }

    /**
     * Convert Entity to Array.
     *
     * @param DbUploadImage $data Db Upload Image Entity
     *
     * @return array
     */
    public function extract(DbUploadImage $data)
    {
        $repository = $this->getDbUploadImageRepository();
        return $repository->extract($data);
    }

    /**
     * Select one Db Upload Image by Id.
     *
     * @param array $idToSelect Id
     *
     * @return null|MyModule\Entity\DbUploadImage
     */
    public function selectById($idToSelect)
    {
        $repository = $this->getDbUploadImageRepository();
        return $repository->selectById($idToSelect);
    }
}
