<?php
namespace MyModule\MyTableTable;

use GearBase\Service\AbstractService;
use MyModule\Entity\MyTableTable;
use MyModule\MyTableTable\MyTableTableRepositoryTrait;
use GearImage\Service\ImageServiceTrait;
use MyModule\MyTableTable\MyTableTableRepository;
use Zend\Cache\Storage\Adapter\Memcached;
use Zend\Authentication\AuthenticationService;
use GearImage\Service\ImageService;

/**
 * Interaction between MyTableTableController and Services
 *
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/MyTableTable
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableTableService extends AbstractService
{
    use MyTableTableRepositoryTrait;

    use ImageServiceTrait;

    protected $sessionName;

    protected $authService;

    /**
     * Constructor
     *
     * @param MyTableTableRepository $tableTableRepository My Table Table Repository
     * @param Memcached              $cache                Memcached
     * @param AuthenticationService  $zfcuserAuthService   Authentication Service
     * @param ImageService           $imageService         Image Service
     *
     * @return MyTableTableService
     */
    public function __construct(
        MyTableTableRepository $tableTableRepository,
        Memcached $cache,
        AuthenticationService $zfcuserAuthService,
        ImageService $imageService
    ) {
        $this->myTableTableRepository = $tableTableRepository;
        $this->cache = $cache;
        $this->zfcuserAuthService = $zfcuserAuthService;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Get the values used to generate Html Table on List Action.
     *
     * @return array
     */
    public function getTableHead()
    {
        $map = $this->getMyTableTableRepository()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    /**
     * Get the Service session name.
     *
     * @return string
     */
    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = 'myTableTableSession';
        }
        return $this->sessionName;
    }

    /**
     * Select one row based on criteria.
     *
     * @param array $data Criteria
     *
     * @return null|MyModule\Entity\MyTableTable
     */
    public function selectOneBy(array $data)
    {
        return $this->getMyTableTableRepository()->selectOneBy($data);
    }

    /**
     * Select All Rows from My Table Table table.
     *
     * Use cache to store data until change.
     *
     * @param array $select Criteria
     *
     * @return array
     */
    public function selectAll($select = [***REMOVED***)
    {
        $this->cache      = $this->getCache();
        $this->repository = $this->getMyTableTableRepository();

        return parent::selectAll($select);
    }

    /**
     * Create a new My Table Table on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful created.
     *
     * @param array $data Valid $_POST
     *
     * @return null|MyModule\Entity\MyTableTable
     */
    public function create($data)
    {
        $repository = $this->getMyTableTableRepository();


        $myTableTable = $repository->insert($data);
        if ($myTableTable) {
            $this->clearCache();
        }
        return $myTableTable;
    }

    /**
     * Update a existing My Table Table on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful updated.
     *
     * @param integer $idTable Id
     * @param array   $data    Valid $_POST
     *
     * @return null|MyModule\Entity\MyTableTable
     */
    public function update($idTable, $data = [***REMOVED***)
    {
        $repository = $this->getMyTableTableRepository();


        $myTableTable = $repository->update($idTable, $data);
        if ($myTableTable) {
            $this->clearCache();
        }
        return $myTableTable;
    }

    /**
     * Delete a existing My Table Table by Id.
     *
     * @param integer $idTable Id
     *
     * @return array
     */
    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return ['success' => false, 'error' => 'EntityNotFound'***REMOVED***;
        }

        $repository = $this->getMyTableTableRepository();
        $myTableTable = $repository->deleteSafe($entity);


        if ($myTableTable) {
            $this->getImageService()->deleteImages($idTable, 'myTableTable');
            $this->clearCache();
        }
        return $myTableTable;
    }

    /**
     * Convert Entity to Array.
     *
     * @param MyTableTable $data My Table Table Entity
     *
     * @return array
     */
    public function extract(MyTableTable $data)
    {
        $repository = $this->getMyTableTableRepository();
        return $repository->extract($data);
    }

    /**
     * Select one My Table Table by Id.
     *
     * @param array $idToSelect Id
     *
     * @return null|MyModule\Entity\MyTableTable
     */
    public function selectById($idToSelect)
    {
        $repository = $this->getMyTableTableRepository();
        return $repository->selectById($idToSelect);
    }
}
