<?php
namespace MyModule\MyTableColumn;

use GearBase\Service\AbstractService;
use MyModule\Entity\MyTableColumn;
use MyModule\MyTableColumn\MyTableColumnRepositoryTrait;
use GearImage\Service\ImageServiceTrait;
use MyModule\MyTableColumn\MyTableColumnRepository;
use Zend\Cache\Storage\Adapter\Memcached;
use Zend\Authentication\AuthenticationService;
use GearImage\Service\ImageService;

/**
 * Interaction between MyTableColumnController and Services
 *
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/MyTableColumn
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableColumnService extends AbstractService
{
    use MyTableColumnRepositoryTrait;

    use ImageServiceTrait;

    protected $sessionName;

    protected $authService;

    const IMAGES = [
        'myImageOne',
        'myImageTwo'
    ***REMOVED***;

    /**
     * Constructor
     *
     * @param MyTableColumnRepository $columnRepository   My Table Column Repository
     * @param Memcached               $cache              Memcached
     * @param AuthenticationService   $zfcuserAuthService Authentication Service
     * @param ImageService            $imageService       Image Service
     *
     * @return MyTableColumnService
     */
    public function __construct(
        MyTableColumnRepository $columnRepository,
        Memcached $cache,
        AuthenticationService $zfcuserAuthService,
        ImageService $imageService
    ) {
        $this->myTableColumnRepository = $columnRepository;
        $this->cache = $cache;
        $this->zfcuserAuthService = $zfcuserAuthService;
        $this->imageService = $imageService;

        return $this;
    }

    /**
     * Get the values used to generate Html Table on List Action.
     *
     * @return array
     */
    public function getTableHead()
    {
        $map = $this->getMyTableColumnRepository()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    /**
     * Get the Service session name.
     *
     * @return string
     */
    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = 'myTableColumnSession';
        }
        return $this->sessionName;
    }

    /**
     * Select one row based on criteria.
     *
     * @param array $data Criteria
     *
     * @return null|MyModule\Entity\MyTableColumn
     */
    public function selectOneBy(array $data)
    {
        return $this->getMyTableColumnRepository()->selectOneBy($data);
    }

    /**
     * Select All Rows from My Table Column table.
     *
     * Use cache to store data until change.
     *
     * @param array $select Criteria
     *
     * @return array
     */
    public function selectAll($select = [***REMOVED***)
    {
        $this->cache      = $this->getCache();
        $this->repository = $this->getMyTableColumnRepository();

        return parent::selectAll($select);
    }

    /**
     * Create a new My Table Column on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful created.
     *
     * @param array $data Valid $_POST
     *
     * @return null|MyModule\Entity\MyTableColumn
     */
    public function create($data)
    {
        $repository = $this->getMyTableColumnRepository();

        $images = $this->getImageService()->replaceDataForm(
            $data,
            'my-table-columns',
            self::IMAGES
        );

        $myTableColumn = $repository->insert($data);
        if ($myTableColumn) {
            $this->getImageService()->saveImageColumns(
                $images,
                'my-table-columns'
            );
            $this->clearCache();
        }
        return $myTableColumn;
    }

    /**
     * Update a existing My Table Column on database.
     *
     * Apply additional logic and then send forward to Repository. Clear Service Cache if successful updated.
     *
     * @param integer $idTable Id
     * @param array   $data    Valid $_POST
     *
     * @return null|MyModule\Entity\MyTableColumn
     */
    public function update($idTable, $data = [***REMOVED***)
    {
        $repository = $this->getMyTableColumnRepository();

        $images = $this->getImageService()->replaceDataForm(
            $data,
            'my-table-columns',
            self::IMAGES
        );

        $myTableColumn = $repository->update($idTable, $data);
        if ($myTableColumn) {
            $this->getImageService()->saveImageColumns(
                $images,
                'my-table-columns'
            );
            $this->clearCache();
        }
        return $myTableColumn;
    }

    /**
     * Delete a existing My Table Column by Id.
     *
     * @param integer $idTable Id
     *
     * @return array
     */
    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return ['success' => false, 'error' => 'EntityNotFound'***REMOVED***;
        }

        $repository = $this->getMyTableColumnRepository();
        $myTableColumn = $repository->deleteSafe($entity);


        if ($myTableColumn) {
            $this->getImageService()->deleteImagesTableColumn(
                $entity,
                self::IMAGES,
                'my-table-columns'
            );
            $this->clearCache();
        }
        return $myTableColumn;
    }

    /**
     * Convert Entity to Array.
     *
     * @param MyTableColumn $data My Table Column Entity
     *
     * @return array
     */
    public function extract(MyTableColumn $data)
    {
        $repository = $this->getMyTableColumnRepository();
        return $repository->extract($data);
    }

    /**
     * Select one My Table Column by Id.
     *
     * @param array $idToSelect Id
     *
     * @return null|MyModule\Entity\MyTableColumn
     */
    public function selectById($idToSelect)
    {
        $repository = $this->getMyTableColumnRepository();
        return $repository->selectById($idToSelect);
    }
}
