namespace <?php echo $this->module;?>\Form\Search;

use GearBase\Form\Search\AbstractSearchForm;
use Zend\Form\Element;

class <?php echo $this->class;?>SearchForm extends AbstractSearchForm
{
    public function __construct($entityManager)
    {
        parent::__construct('<?php echo $this->var;?>SearchForm');
        $this->setAttribute('method', 'post');
        $this->setAttribute('id', '<?php echo $this->var;?>Search');
        $this->setAttribute('class', 'form-inline');
        $this->setEntityManager($entityManager);

<?php
foreach ($this->elements as $element):
echo $element;
endforeach;
?>
    }
}
