        $<?php echo $this->data;?> = new Element('<?php echo $this->data;?>Pre');
        $<?php echo $this->data;?>->setAttributes(array(
            'name' => '<?php echo $this->data;?>Pre',
            'id' => '<?php echo $this->data;?>Pre',
            'type' => 'int',
        ));
        $<?php echo $this->data;?>->setLabel('<?php echo $this->str('label', $this->data);?> de');
        $this->add($<?php echo $this->data;?>);

        $<?php echo $this->data;?> = new Element('<?php echo $this->data;?>Pos');
        $<?php echo $this->data;?>->setAttributes(array(
            'name' => '<?php echo $this->data;?>Pos',
            'id' => '<?php echo $this->data;?>Pos',
            'type' => 'int',
        ));
        $valor->setLabel('até');
        $this->add($<?php echo $this->data;?>);