<?php
return array(
    'module-construct'                 => 'Construct %s %s',
    'module-autoload'                  => 'Creating autoload namespace for %s %s',
    'module-upgrade'                   => 'Upgrading %s',
    'module-diagnostic'                => 'Diagnosting %s',
    'module-create'                    => 'Creating new module %s %s',
    'module-fixture'                   => 'Importing fixture for %s %s',
    'module-delete'                    => 'Deleting old module %s %s',
    'module-load'                      => 'Loading module %s %s',
    'module-unload'                    => 'Unloading module %s %s',
    'module-entity'                    => 'Creating entity %s %s',
    'module-entities'                  => 'Creating entities %s %s',

    'project-autoload'                 => 'Autoload %s',
    'project-diagnostics'              => 'Checking project diagnostics %s',
    'project-upgrade'                  => 'Upgrading project %s',
    'project-nfs'                      => 'Exporting project on Nfs',
    'project-virtual-host'             => 'Enabling project on apache2',
    'project-git'                      => 'Set a git to project',
    'project-cache'                    => 'Renew cache in project %s',
    'project-fixture'                  => 'Importing fixture for %s',
    'project-create'                   =>  'Creating new project %s %s',
    'project-delete'                   => 'Delete Project %s',
    'project-local'                    => 'Creating local config %s',
    'project-global'                   => 'Creating global config %s',
    'project-config'                   => 'Creating config %s',
    'project-environment'              => 'Creating environment %s',

    'database-project-load'            => 'Carregar banco de dados de Projeto em %s',
    'database-module-load'             => 'Carregando banco de dados para %s em %s',
    'database-truncate'                => 'Truncating database %s',
    'database-drop-table'              => 'Droping table %s',
    'database-fix-table'               => 'Fixing table %s',
    'database-mock-table'              => 'Creating mock trait for table %s',
    'database-project-dump'            => 'Dumping database to project %s',
    'database-module-dump'             => 'Creating database for module %s %s',
    'create-module-mvc'                => 'Creating a new mvc module %s on project %s on %s',
    'create-module-light'              => 'Ready to create light module "%s" on project "%s" on %s',
    'db-create'                        => 'Creating db %s %s',
    'db-delete'                        => 'Deleting db %s %s',
    'src-create'                       => 'Creating src %s %s',
    'src-delete'                       => 'Deleteing src %s %s',
    'view-create'                      => 'Creating view %s %s',
    'test-create'                      => 'Creating test %s %s',
    'controller-create'                => 'Creating controller %s %s',
    'console-controller-create'        => 'Creating controller %s %s',
    'console-controller-action-create' => 'Creating console activity %s %s',
    'controller-action-create'         => 'Creating activity %s %s',
    'finished'                         => 'Script ended by %s at %s',


);
