<?php
return array_merge_recursive(array(
    'initializers' => array(
        'Gear\Initializer\DirInitializer',
        'Gear\Initializer\ClassInitializer',
        'Gear\Initializer\ModuleInitializer',
        'Gear\Initializer\TemplateInitializer'
    ),
    'factories' => array(
        'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
        'moduleService'   => 'Gear\Factory\ModuleServiceFactory',
        'Gear\Schema'         => 'Gear\Factory\SchemaFactory',
        'Gear\Factory\Metadata' => 'Gear\Factory\MetadataFactory',
        'fileCreatorFactory' => 'Gear\Factory\FileCreatorFactory'
    ),
    'invokables' => array(
        'Gear\Module\GitIgnore' => 'Gear\Module\GitIgnore',
        'Gear\Javascript\Module\Package' => 'Gear\Javascript\Module\Package',
        'Gear\Javascript\Module\Gulpfile' => 'Gear\Javascript\Module\Gulpfile',
        'Gear\Javascript\Module\Protractor' => 'Gear\Javascript\Module\Protractor',
        'Gear\Javascript\Module\Karma' => 'Gear\Javascript\Module\Karma',
        'Gear\Autoload\Namespaces'    => 'Gear\Autoload\Namespaces',
        'Gear\ContinuousIntegration\Jenkins' => 'Gear\ContinuousIntegration\Jenkins',
        'backupService'      => 'Gear\Service\Db\BackupService',
        'Gear\Service\Db\SchemaTool' => 'Gear\Service\Db\SchemaToolService',
        'RepositoryService\MappingService' => 'Gear\Service\Mvc\RepositoryService\MappingService',
        'Gear\Speciality\SimpleCheckbox' => 'Gear\Service\Speciality\SimpleCheckbox',
        'Gear\Speciality\MetaTags' => 'Gear\Service\Speciality\MetaTags',
        'Gear\Speciality\MetaImagem' => 'Gear\Service\Speciality\MetaImagem',
        'Gear\Service\Db\Table' => 'Gear\Service\Db\TableService',

        'Gear\Service\Deploy' => 'Gear\Service\DeployService',
        'Gear\Service\Version' => 'Gear\Service\VersionService',
        'Gear\Config\AssetManager' => 'Gear\Config\AssetManager',
        'Gear\Service\Fixture' => 'Gear\Service\FixtureService',
        'Gear\Service\Config' => 'Gear\Service\ConfigService',
        'Gear\Service\Mvc\SearchService' => 'Gear\Service\Mvc\SearchService',
        'SchemaListener' => 'Gear\Event\SchemaListener',
        'LogListener' => 'Gear\Event\LogListener',
        'templateService'       => 'Gear\Service\TemplateService',
        'autoincrementService'  => 'Gear\Service\Db\AutoincrementService',
        'Gear\Service\Mvc\FixtureService'        => 'Gear\Service\Mvc\FixtureService',
        'doctrineService'           => 'Gear\Service\DoctrineService',
        'versionService'            => 'Gear\Service\VersionService',
        'moduleStructure'           => 'Gear\ValueObject\BasicModuleStructure',
        'aclService'                => 'Gear\Service\AclService',
        'scriptService'             => 'Gear\Service\Module\ScriptService',
        'migrateService'            => 'Gear\Service\MigrateService',
        'gearingService'            => 'Gear\Service\GearingService',
        'projectService'            => 'Gear\Service\ProjectService',
        'Gear\Project\Upgrade'      => 'Gear\Project\Upgrade',
        'buildService'              => 'Gear\Service\BuildService',
        'cacheService'              => 'Gear\Cache\CacheService',
        'srcFactory'                => 'Gear\Factory\SrcFactory',
        'creatorService'            => 'Gear\Service\CreatorService',
        'layoutService'             => 'Gear\Service\Mvc\LayoutService',
        'testService'               => 'Gear\Service\Module\TestService',
        'composerService'           => 'Gear\Service\Module\ComposerService',
        'classService'              => 'Gear\Service\Type\ClassService',
        'dirService'                => 'Gear\Service\Filesystem\DirService',
        'fileService'               => 'Gear\Service\Filesystem\FileService',
        'stringService'             => 'Gear\Service\Type\StringService',
        'moduleFileService'         => 'Gear\Service\Module\ModuleFileService',
        'filesystemService'         => 'Gear\Service\FilesystemService',
        'tableService'              => 'Gear\Service\TableService',
        'specialityService'         => 'Gear\Service\SpecialityService',
        'consoleService'            => 'Gear\Service\ConsoleService',
        'integrationService'        => 'Gear\Service\IntegrationService',
    ),
    'aliases' => array(
    	'Gear\Service\Mvc\ConfigService' => 'configService',
        'Gear\Service\Type\String' => 'stringService',
        'Gear\Service\Filesystem\Dir' => 'dirService',
        'Gear\Service\Filesystem\File' => 'fileService',
        'Gear\Service\Template'    => 'templateService',
        'Gear\Service\Constructor\Json'    => 'jsonService',
        'fileCreator' => 'fileCreatorFactory'
    ),
    'shared' => array(
	    'fileCreatorFactory' => false,
        'Gear\Autoload\Namespaces' => false,
    ),
),
    require __DIR__.'/servicemanager/mvc.php',
    require __DIR__.'/servicemanager/constructor.php'
);
