<?php
namespace MyModule\Custom\CustomNamespace;

use Interop\Container\ContainerInterface;
use GearBase\Hydrator\DateHydrator;
use GearBase\Factory\AbstractFactory;
use MyModule\Custom\CustomNamespace\MyTableForm;
use MyModule\Custom\CustomNamespace\MyTableFilter;
use MyModule\Entity\MyTable;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Custom/CustomNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableFormFactory extends AbstractFactory
{

    /**
     * Create MyTableForm
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MyTableForm
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $form = new MyTableForm(
            $container->get('doctrine.entitymanager.orm_default')
        );

        $idMyTable = null;
        $request = $container->get('Request');
        $translate = $container->get('Translator');
        if ($request instanceof \Zend\Http\Request
            && preg_match('/'.$translate->translate('edit').'/', $request->getUri()->getPath())
        ) {
            if (preg_match('/[0-9***REMOVED****$/', $request->getUri()->getPath(), $match)) {
                $idMyTable = $match[0***REMOVED***;
            }
        }

        $filter = $container->get(MyTableFilter::class);
        $form->setInputFilter($filter->getInputFilter($idMyTable));

        $entityManager = $container->get('doctrine.entitymanager.orm_default');
        $hydrator = new DateHydrator($entityManager, MyTable::class);

        $form->setHydrator($hydrator);

        return $form;
    }
}
