namespace FunctionalTester;

/**
 * @SuppressWarnings(PHPMD)
 */
class AbstractCest
{
// @codingStandardsIgnoreStart
    public function _before(\FunctionalTester $I)
    {
// @codingStandardsIgnoreEnd
        \TesteTest\LoginCommons::logMeIn($I);
    }

// @codingStandardsIgnoreStart
    public function _after(\FunctionalTester $I)
    {
// @codingStandardsIgnoreEnd
        \TesteTest\LoginCommons::logMeOut($I);
    }
}
