namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;
use <?php echo $this->module;?>\Functional\AbstractCest;
use <?php echo $this->module;?>\Pages\<?php echo $this->className;?>Page;

/**
 * @SuppressWarnings(PHPMD)
 */
class <?php echo $this->className;?>Cest extends AbstractCest
{
    public function see<?php echo $this->className;?>(FunctionalTester $I)
    {
        $I->wantTo('Do Anything Else With <?php echo $this->className;?>');
        $I->amOnPage(<?php echo $this->className;?>Page::$URL);

        $I->see('<?php echo $this->moduleLabel;?>', <?php echo $this->className;?>Page::getBreadcrumbByIndex(1));
        $I->see('<?php echo $this->controllerLabel;?>', <?php echo $this->className;?>Page::getBreadcrumbByIndex(2));
        $I->see('<?php echo $this->actionLabel;?>', <?php echo $this->className;?>Page::getBreadcrumbByIndex(3));
        $I->seeNumberOfElements(<?php echo $this->className;?>Page::$breadscrumb, 3);

    }
}
