/**
* @SuppressWarning(PHPMD)
* @guy FunctionalTester\ListSteps
*/
class <?php echo $this->class;?>DeleteCest extends \FunctionalTester\AbstractCest
{
    public function returnToListWithoutId(\FunctionalTester $I)
    {
        $I->wantTo('<?php echo $this->classLabel;?> Test return to list when try to delete without id');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage::$URL);
        $I->see(
            '<?php echo $this->classLabel;?>,
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage::$title
        );
    }
}