namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;

/**
* @SuppressWarnings(PHPMD)
* @guy <?php echo $this->module;?>\FunctionalTester\CreateSteps
*/
class <?php echo $this->class;?>CreateCest extends \<?php echo $this->module;?>\Functional\AbstractCest
{
    public function onPage(FunctionalTester $I)
    {
        $I->wantTo('Test Access Create Email');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage::$URL);
        $I->see(
            'Criar <?php echo $this->classLabel;?>',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage::$title
        );
    }

    public function breadcrumb(FunctionalTester $I)
    {
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage::$URL);
        $I->verifyBreadcrumb(
            '\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>CreatePage',
            '<?php echo $this->moduleLabel;?>',
            '<?php echo $this->classLabel;?>',
            'Criar'
        );
    }
}
