
/**
 * @author Maurício Piber Fão
 * @SuppressWarning(PHPMD)
 */
$I = new \FunctionalTester($scenario);
\<?php echo $this->module;?>Test\LoginCommons::logMeIn($I);

$I->wantTo('List <?php echo $this->class?>');
$I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$URL);
$I->see(
    '<?php echo $this->class;?>',
    '#pageTitle'
);

$I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableHead, 6);
$I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableBodyRows, 10);

$I->see(
    '<?php echo $this->class;?>',
    \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$title
);

$I->see(
    'Criar',
    \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$createBtn
);

/** Breadscrumb */
$breadscrumb = new FunctionalTester\BreadcrumbSteps($scenario);

$breadscrumb->validate(new \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage, '<?php echo $this->module;?>', '<?php echo $this->class;?>', 'Listar');

/** Filter */
/** Breadscrumb */
$filter = new FunctionalTester\FilterSteps($scenario);
$filter->validate(new \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage);


$paginator = new \FunctionalTester\PaginatorSteps($scenario);
$paginator->validate(new \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage);
/** Paginator */


\<?php echo $this->module;?>Test\LoginCommons::logMeOut($I);

