namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage;

/**
 * @SuppressWarnings(PHPMD)
 * @guy <?php echo $this->module;?>\FunctionalTester\EditSteps
 * @group <?php echo $this->class;?>
 * @group UploadImage
*/
class <?php echo $this->class;?>UploadImageCest extends \<?php echo $this->module;?>\Functional\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(FunctionalTester $I)
    {
// @codingStandardsIgnoreEnd
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixtureHaveInDatabase;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );
<?php echo $this->posFixture;?>
        parent::_before($I);
    }

    public function onPage(FunctionalTester $I)
    {
        $I->wantTo('Test can see Upload Image Page');
        $I->amOnPage(<?php echo $this->class;?>UploadImagePage::$URL.'/'.$this->fixture);
        $I->see(
            'Imagens - <?php echo $this->classLabel;?> - '.$this->fixture,
            <?php echo $this->class;?>UploadImagePage::$title
        );
    }

    public function breadcrumb(FunctionalTester $I)
    {
        $I->amOnPage(<?php echo $this->class;?>UploadImagePage::$URL.'/'.$this->fixture);
        $I->verifyBreadcrumb(
            '\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage',
            '<?php echo $this->moduleLabel;?>',
            '<?php echo $this->classLabel;?>',
            'Upload Imagem'
        );
    }

<?php echo $this->functions;?>
}
