/**
* @SuppressWarning(PHPMD)
* @guy FunctionalTester\ListSteps
*/
class <?php echo $this->class;?>ListCest extends \FunctionalTester\AbstractCest
{
    public function structure(\FunctionalTester $I)
    {
        $I->wantTo('Test Access List Email');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$URL);


        $I->see(
            '<?php echo $this->classLabel;?>',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$title
        );

        $I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableHeadRow, <?php echo $this->tableHeadCount;?>);
        $I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableBodyRow, 10);


        $I->see(
            'Criar',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$createBtn
        );

        $I->verifyBreadcrumb('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', '<?php echo $this->moduleLabel;?>', '<?php echo $this->classLabel;?>', 'Listar');
        $I->verifyFilter('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyPaginator('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
    }
}
