namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage;

/**
* @SuppressWarnings(PHPMD)
* @guy <?php echo $this->module;?>\FunctionalTester\ViewSteps
*/
class <?php echo $this->class;?>ViewCest extends \<?php echo $this->module;?>\Functional\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(FunctionalTester $I)
    {
// @codingStandardsIgnoreEnd
<?php echo $this->preFixture;?>

        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixture;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );

<?php echo $this->posFixture;?>

        parent::_before($I);
    }

    public function returnToListWithId(FunctionalTester $I)
    {
        $I->wantTo('Test return to list when try to view without id');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage::$URL);
        $I->see(
            '<?php echo $this->classLabel;?>',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage::$title
        );
    }

    public function breadcrumb(FunctionalTester $I)
    {
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage::$URL.'/'.$this->fixture);
        $I->verifyBreadcrumb(
            '\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage',
            '<?php echo $this->moduleLabel;?>',
            '<?php echo $this->classLabel;?>',
            'Visualizar'
        );
    }
    <?php echo $this->functions;?>

    public function verifyLabelsInRightPosition(FunctionalTester $I)
    {
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage::$URL.'/'.$this->fixture);
<?php echo $this->seeLabel;?>
    }

    public function verifyValuesInRightPosition(FunctionalTester $I)
    {
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage::$URL.'/'.$this->fixture);
<?php echo $this->seeValue;?>
    }


}
