namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;

/**
 * @SuppressWarnings(PHPMD)
 * @guy <?php echo $this->module;?>\FunctionalTester\ListSteps
 * @group <?php echo $this->class;?>
 * @group Delete
*/
class <?php echo $this->class;?>DeleteCest extends \<?php echo $this->module;?>\Functional\AbstractCest
{
    public function returnToListWithoutId(FunctionalTester $I)
    {
        $I->wantTo('<?php echo $this->classLabel;?> Test return to list when try to delete without id');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage::$URL);
        $I->see(
            '<?php echo $this->classLabel;?>',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>DeletePage::$title
        );
    }
}
