namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;

/**
* @SuppressWarnings(PHPMD)
* @guy <?php echo $this->module;?>\FunctionalTester\EditSteps
*/
class <?php echo $this->class;?>UploadImageCest extends \<?php echo $this->module;?>\Functional\AbstractCest
{
    protected $fixture;

    public function _before(FunctionalTester $I)
    {
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixtureHaveInDatabase;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 1
            )
        );
        parent::_before($I);
    }

    public function onPage(FunctionalTester $I)
    {
        $I->wantTo('Test return to list when try to edit without id');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage::$URL.'/'.$this->fixture);
        $I->see(
            'Imagens - <?php echo $this->classLabel;?> '.$this->fixture,
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage::$title
        );
    }

    public function breadcrumb(FunctionalTester $I)
    {
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage::$URL.'/'.$this->fixture);
        $I->verifyBreadcrumb('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage', '<?php echo $this->moduleLabel;?>', '<?php echo $this->classLabel;?>', 'Editar Imagem');
    }
}