namespace <?php echo $this->module?>;

class Module
{

    public function init(\Zend\ModuleManager\ModuleManager $moduleManager)
    {
        $moduleManager->getEventManager()->getSharedManager()->attach(__NAMESPACE__, 'dispatch', function ($event) {
            $event->getTarget()->layout('layout/<?php echo $this->moduleUrl;?>');
        });
    }

    public function getAutoloaderConfig()
    {
        return array(
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/../../src/' . __NAMESPACE__,
                ),
            ),
        );
    }

    public function getConfig()
    {
        return include __DIR__ . '/../../config/module.config.php';
    }

    /**
     * @codeCoverageIgnore
     */
    public function getServiceConfig()
    {
        return array(
            'factories' => array(
                'Zend\Log\Logger' => function () {
                    $logger = new \Zend\Log\Logger;
                    $writer = new \Zend\Log\Writer\Stream(
                        __DIR__.'/../../../../data/logs/'.date('Y-m-d-H-i').'-error.txt'
                    );
                    $logger->addWriter($writer);
                    return $logger;
                },
            ),
        );
    }
}
