#!/bin/bash

cp config/autoload/local.php.dist config/autoload/local.php

echo "Deploy Develoment - Composer"

ls -l vendor/autoload.php &> /dev/null

if [ "$?" != "0" ***REMOVED***; then
    composer update
fi;

echo "Deploy Develoment - NodeJS"
vendor/bin/install-nodejs


echo "Deploy Develoment - VirtualHost"

ls -l /etc/apache2/sites-enabled/<?php echo $this->projectUrl;?>.gear.dev.conf > /dev/null

if [ "$?" != "0" ***REMOVED***; then
    vendor/bin/virtualhost  $(pwd) <?php echo $this->projectUrl;?>.gear.dev development
fi

echo "Deploy Development - Database"
vendor/bin/install-db <?php echo $this->projectUrl;?>.mysql.sql

echo "Deploy Development - Gulp"
vendor/bin/gulp
