<tr>
            <td>
                <?php echo $this->escapeHtml($this->object->getIdTipoServico()); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getNome()); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getDescricao()); ?>
            </td>
    <td>
        <a href="<?php echo $this->url('piber-network/tipo-servico/edit', array('id' => $this->object->getIdTipoServico())); ?>">            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('piber-network/tipo-servico/delete', array('id' => $this->object->getIdTipoServico())); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Tipo Servico" data-message="<?php echo $this->translate('Desejas realmente deletar Tipo Servico?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>