$modules = [
  '<?php echo $this->module; ?>'
***REMOVED***;

if (getenv('PHINX_ENVIRONMENT') !== 'PRODUCTION') {
  $modules = array_merge([
    'Gear\Config',
    'Gear\Git',
    'Gear\Util',
    'Gear\Console',
    'Gear\Jira',
  ***REMOVED***, $modules);
}

return [
  'modules' => $modules,
  'module_listener_options' =>
  [
    'module_paths' =>
    [
        '../.',
        './vendor',
    ***REMOVED***,
    'config_glob_paths' =>
    [
        'config/autoload/{,*.}{global,local}.php',
    ***REMOVED***,
  ***REMOVED***,
***REMOVED***; ?>
