return [
  'modules' =>
  [
      'AssetManager',
      'DoctrineModule',
      'DoctrineORMModule',
      'DoctrineDataFixtureModule',
      'ZfcBase',
      'ZfcUser',
      'ZfcUserDoctrineORM',
      'BjyAuthorize',
      'GearBase',
      'Gear',
      'GearEmail',
      'GearJson',
      'GearAcl',
      'GearDeploy',
      'GearJenkins',
      'GearVersion',
      'GearImage',
      'GearAdmin',
      '<?php echo $this->module; ?>'
  ***REMOVED***,
  'module_listener_options' =>
  [
    'module_paths' =>
    [
        '../.',
        './vendor',
    ***REMOVED***,
    'config_glob_paths' =>
    [
        'config/autoload/{,*.}{global,local}.php',
    ***REMOVED***,
  ***REMOVED***,
***REMOVED***; ?>