<?php
namespace SchemaModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;
use SchemaModule\Service\MyServiceDependencyTrait;

/**
 * @group Service
 */
class MyServiceDependencyTest extends AbstractTestCase
{
    use MyServiceDependencyTrait;

    /**
     * @group SchemaModule
     * @group MyServiceDependency
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getMyServiceDependency()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group SchemaModule
     * @group MyServiceDependency
    */
    public function testGet()
    {
        $myService = $this->getMyServiceDependency();
        $this->assertInstanceOf('SchemaModule\Service\MyServiceDependency', $myService);
    }

    /**
     * @group SchemaModule
     * @group MyServiceDependency
    */
    public function testSet()
    {
        $mockMyService = $this->getMockSingleClass(
            'SchemaModule\Service\MyServiceDependency'
        );
        $this->setMyServiceDependency($mockMyService);
        $this->assertEquals($mockMyService, $this->getMyServiceDependency());
    }
    public function testSetOtherService()
    {
        $mockOtherService = $this->getMockSingleClass('SchemaModule\Service\OtherService');
        $this->getMyServiceDependency()->setOtherService($mockOtherService);
        $this->assertEquals($mockOtherService, $this->getMyServiceDependency()->getOtherService());
    }

    public function testGetOtherService()
    {
        $this->assertInstanceOf(
            'SchemaModule\Service\OtherService',
            $this->getMyServiceDependency()->getOtherService()
        );
    }
}
