var fs = require('fs-extra');
var path = require('path');

var basepath = null;

var tryModule = path.join(__dirname, '../../../../../vendor/mauriciopiber/gear-admin');
var tryProject = path.join(__dirname, '../../../../../../../vendor/mauriciopiber/gear-admin');

if (!fs.existsSync(tryModule) && !fs.existsSync(tryProject)) {

    if (basepath == null) {
        throw new Error('Can\'t found basepath of support files');
    }
}

basepath = (fs.existsSync(tryModule)) ? tryModule : null;
basepath = (basepath == null && fs.existsSync(tryProject)) ? tryProject : basepath;

var database = require(basepath + '/public/js/spec/e2e/support/database/database.js');
var memcached = require(basepath + '/public/js/spec/e2e/support/memcached/memcached.js');
var admin = require(basepath + '/public/js/spec/e2e/support/helper/admin.js');

module.exports = function () {

    this.Before({tags: ["@<?php echo $this->tableUrl;?>-fixture"***REMOVED***}, function (scenario, callback) {

        var Q = require('q');
        Q.fcall(function() {

            return database.query(
                'insert into <?php echo $this->tableUline;?> set ?',
                {
<?php echo $this->columns;?>
                    created: '2016-12-01 01:00:00',
                    updated: null,
                    created_by: 2,
                    updated_by: null
                }
            );
        }).then(function(text) {
            memcached.flush();
        }).then(function() {
            callback();
        });
    });

    this.Given(/^que eu estou na página de editar de <?php echo $this->module;?> - <?php echo $this->table;?> "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar', 30, callback);
    });

    this.Given(/^que eu estou na página de visualizar imagens de <?php echo $this->module;?> - <?php echo $this->table;?> "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/visualizar', 30, callback);
    });

    this.Given(/^que eu estou na página de editar imagens de <?php echo $this->module;?> - <?php echo $this->table;?> "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/upload-image', 30, callback);
    });
};
