<?php
namespace MyModuleTest\FormTest;

use PHPUnit\Framework\TestCase;
use MyModule\Form\BasicExtendsForm;

/**
 * @group Form
 */
class BasicExtendsFormTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->form = new BasicExtendsForm();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf(
            'MyModule\Form\BasicExtendsForm',
            $this->form
        );
    }
}
