<?php
namespace MyModule\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;

class MyController extends AbstractActionController
{

    public function myOneActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    public function myTwoActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    public function myThreeActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    public function myFourActionAction()
    {
        return new ViewModel([***REMOVED***);
    }

    public function myFiveActionAction()
    {
        return new ViewModel([***REMOVED***);
    }
}
