        <div class="form-group">
            <?php echo sprintf('<?php echo $this->formLabel($form->get(\'%s\')); ?>', $this->name).PHP_EOL; ?>
            <?php echo sprintf('<?php echo $this->formFile($form->get(\'%s\')->setAttribute(\'class\', \'form-control\')); ?>', $this->name).PHP_EOL; ?>
            <?php echo sprintf('<?php echo $this->formElementErrors($form->get(\'%s\')); ?>', $this->name).PHP_EOL; ?>
        </div>
        <div class="form-group">
            <?php  echo sprintf('<?php if ($this->%s) : ?>', $this->name).PHP_EOL; ?>
                <img src="<?php  echo sprintf('<?php echo $this->%s;?>', $this->name); ?>" height="100" width="100"/>
            <?php  echo '<?php endif;?>'.PHP_EOL;?>
        </div>