        <div class="form-group">
            <?php echo sprintf('<?php echo $this->formLabel($form->get(\'%s\')); ?>', $this->name); ?>
            <?php echo sprintf('<?php echo $this->formFile($form->get(\'%s\')->setAttribute(\'class\', \'form-control\')); ?>', $this->name); ?>
            <?php echo sprintf('<?php echo $this->formElementErrors($form->get(\'%s\')); ?>', $this->name); ?>
        </div>