(function () {
    'use strict';

    angular.module('GearApp').controller('MyListController', MyListController);

    function MyListController(exclude, filter, order) {

        var vm;
        vm = this;

        vm.data                  = data;
        vm.id                    = id;

        vm.order                 = order.order;
        vm.order.sortKey         = 'idMy';
        vm.order.reverse         = true;

        vm.filter                = filter.filter;

        vm.exclude               = exclude.exclude;
        vm.exclude.url           = '/my-module/my/excluir';
        vm.exclude.id            = 'idMy';
        vm.exclude.name          = 'My';
        vm.exclude.successDelete = successDelete;

        vm.getLastExclude        = vm.exclude.getLastExclude;
        vm.closeDialogDelete     = vm.exclude.closeDialog;
        vm.confirmDialogDelete   = vm.exclude.confirmExclude;

        function successDelete()
        {
            vm.data = vm.data.filter(function( obj ) {
                return obj[vm.exclude.id***REMOVED*** !== vm.exclude.lastExclude;
            });
            vm.exclude.showSuccessMessage();
        }
    }

    MyListController.$inject = ['exclude', 'filter', 'order'***REMOVED***;
}());