<?php
namespace MyModule;

$db                 = require 'ext/db.config.php';
$doctrine           = require 'ext/doctrine.config.php';
$translator         = require 'ext/translator.config.php';
$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$controllerPlugins  = require 'ext/controller.plugin.config.php';
$cache              = require 'ext/cache.config.php';
$console            = require 'ext/console.route.config.php';
$fixture            = array(
    __NAMESPACE__.'_fixture' => __DIR__ . '/../src/'.__NAMESPACE__.'/Fixture'
);
$gear               = [
    'modules' => [
        'my-module' => [
            'version' => '0.1.0',
            'acl' => true,
            'name' => __NAMESPACE__
        ***REMOVED***
    ***REMOVED***
***REMOVED***;

return [
    'session_config' => [
        'save_path' => __DIR__.'/../../data/session'
    ***REMOVED***,
    'gear'               => $gear,
    'db'                 => $db,
    'console'            => $console,
    'doctrine'           => $doctrine,
    'translator'         => $translator,
    'controllers'        => $controller,
    'service_manager'    => $servicemanager,
    'controller_plugins' => $controllerPlugins,
    'data-fixture'       => $fixture,
***REMOVED***;
