<?php
namespace MyModule;

$db                 = require 'ext/db.config.php';
$doctrine           = require 'ext/doctrine.config.php';
$translator         = require 'ext/translator.config.php';
$route              = require 'ext/route.config.php';
$navigation         = require 'ext/navigation.config.php';
$view               = require 'ext/view.config.php';
$viewHelper         = require 'ext/view.helper.config.php';
$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$assetmanager       = require 'ext/asset.config.php';
$controllerPlugins  = require 'ext/controller.plugin.config.php';
$uploadimage        = require 'ext/upload-image.config.php';
$cache              = require 'ext/cache.config.php';
$fixture            = array(
    __NAMESPACE__.'_fixture' => __DIR__ . '/../src/'.__NAMESPACE__.'/Fixture'
);
$gear = [
    'modules' => [
        'my-module' => [
            'version' => '0.1.0',
            'acl' => true,
            'name' => __NAMESPACE__,
            'git' => 'git@bitbucket.org:mauriciopiber/my-module.git',
            'environment' => [
                'DEVELOPMENT' => 'my-module.gear.dev',
                'TESTING' => 'my-module.gear.dev',
                'STAGING' => 'my-module.stag01.pibernetwork.com'
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***
***REMOVED***;

return [
    'bjyauthorize' => [
        'acl_key' => __NAMESPACE__
    ***REMOVED***,
    'session_config' => [
        'save_path' => __DIR__.'/../data/session'
    ***REMOVED***,
    'gear'               => $gear,
    'view_helpers'       => $viewHelper,
    'db'                 => $db,
    'doctrine'           => $doctrine,
    'translator'         => $translator,
    'view_manager'       => $view,
    'controllers'        => $controller,
    'router'             => $route,
    'navigation'         => $navigation,
    'service_manager'    => $servicemanager,
    'asset_manager'      => $assetmanager,
    'controller_plugins' => $controllerPlugins,
    'fileUpload'         => $uploadimage,
    'data-fixture'       => $fixture,
***REMOVED***;
