<?php echo $this->headTitle()->prepend('My Module - My Controller - My Action');?>
<div class="row" ng-controller="MyControllerMyActionAction as view">
	<div class="col-lg-12">
        <h3 class="page-header">MyModule\MyController\MyAction</h3>
        <div class="panel">
            <div class="panel-body">
                <p>Created by Gear <span ng-bind="view.version"</p>
            </div>
        </div>
	</div>
</div>