<?php echo $this->headTitle()->prepend('My Module - My - My Action');?>
<div class="row" ng-controller="MyControllerMyActionAction as view">
    <div class="col-lg-12">
        <h3 class="page-header">MyModule\My\MyAction</h3>
        <div class="panel">
            <div class="panel-body">
                <p>Created by Gear <span ng-bind="view.version"></span></p>
            </div>
        </div>
    </div>
</div>