<?php $this->headTitle()->prepend('Criar My');?>
<div ng-controller="MyCreateController as create">
    <div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header"><?php echo $this->translate('Create');?>&nbsp;<?php echo $this->translate('My');?></h3>
    	</div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('my-module/my/create'));
                $form->prepare();
                echo $this->form()->openTag($form);
            ?>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('depName'));?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <?php
                                echo $this->formSubmit(
                                    $form->get('submit')->setAttribute('class', 'btn btn-default')->setAttribute('id', 'btn-save')
                                );
                            ?>
                            <a id="btn-back" class="btn btn-default reset" href="<?php echo $this->url('my-module/my/list');?>">Voltar</a>
                        </div>
                    </div>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>