<?php $this->headTitle()->prepend('Editar My');?>
<div ng-controller="MyEditController as edit">
    <div class="row">
    	<div class="col-lg-6">
            <h3 class="page-header">
                <?php echo $this->translate('Edit');?>&nbsp;<?php echo $this->translate('My');?> - <?php echo $this->idMy;?>
            </h3>
    	</div>
    </div>
    <?php if($this->success) : echo $this->render('layout/success'); endif; ?>
    <?php if($this->error) : echo $this->render('layout/error'); endif; ?>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
            <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('my-module/my/edit', array('id' => $this->idMy)));
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formHidden($form->get('idMy')->setAttribute('class','form-control'));
    	    ?>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <?php echo $this->formRow($form->get('depName'));?>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')->setAttribute('id', 'btn-save')); ?>
                            <a class="btn btn-default reset"
                               id="btn-back"
                                href="<?php echo $this->url('my-module/my/list');?>">
                	            <?php echo $this->translate('Back');?>
                	        </a>
                            <a id="btn-view" class="btn btn-info"
                                href="<?php echo $this->url('my-module/my/view', array('id' => $this->idMy));?>">
                                <?php echo $this->translate('View');?>
                            </a>
                            <a id="createBtn" class="btn btn-success"
                                href="<?php echo $this->url('my-module/my/create');?>">
                                <?php echo $this->translate('Create');?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>