<?php $this->headTitle()->prepend('Visualizar My');?>
<div ng-controller="MyViewController as view">
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">
                <?php echo $this->translate('View');?>&nbsp;<?php echo $this->translate('My');?> - <?php echo $this->idMy;?>
            </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
            <div class="form-group">
                <table class="table table-bordered table-hover">
                    <tbody>
                        <tr>
                            <td>
                                <?php echo $this->translate('ID');?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($this->idMy);?>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <?php echo $this->translate('Dep Name');?>
                            </td>
                            <td>
                                <?php echo $this->escapeHtml($this->depName);?>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="form-group">
                <a id="btn-back"
                    class="btn btn-default"
                    href="<?php echo $this->url('my-module/my/list');?>">
                    <?php echo $this->translate('Back');?>
                </a>
                <a id="btn-create"
                    class="btn btn-success"
                    href="<?php echo $this->url('my-module/my/create');?>">
                    <?php echo $this->translate('New');?>
                </a>
                <a id="btn-edit"
                    class="btn btn-primary"
                    href="<?php echo $this->url('my-module/my/edit', array('id' => $this->id));?>">
                    <?php echo $this->translate('Edit');?>
                </a>
                <a id="btn-delete"
                    class="btn btn-danger"
                    ng-click="$event.preventDefault();view.exclude.showDialog(<?php echo $this->id;?>);"
                    ng-href="<?php echo $this->url('my-module/my/delete', array('id' => $this->id));?>/{{<?php echo $this->id?>}}"
                >
                    <?php echo $this->translate('Delete');?>
                </a>
            </div>
        </div>
    </div>
    <gear-delete-dialog
        title="Deletar My"
        body="Desejas deletar o My #{{view.getLastExclude()}}?"
        confirm="Deletar"
        close-dialog-delete="view.closeDialogDelete()"
        confirm-dialog-delete="view.confirmDialogDelete()"
    >
    </gear-delete-dialog>
</div>