namespace <?php echo $this->module;?>\Form;

use Interop\Container\ContainerInterface;
use Zend\Form\Form;

abstract class AbstractForm extends Form implements
{
    protected $serviceLocator;

    protected $entityManager;

    public function __construct($formName)
    {
        parent::__construct($formName);
    }

    public function setServiceLocator(ContainerInterface $serviceLocator)
    {
        $this->container = $serviceLocator;
    }


    {
        return $this->container;
    }

    public function setEntityManager($entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function getEntityManager()
    {
        if (!isset($this->entityManager)) {
            $this->entityManager = $this->get('doctrine.entitymanager.orm_default');
        }
        return $this->entityManager;
    }
}
