namespace <?php echo $this->module;?>\Form;

use GearBase\Form\AbstractForm;
use Zend\Form\Element;

class <?php echo $this->class;?> extends AbstractForm
{
    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function __construct($entityManager)
    {
        parent::__construct('<?php echo $this->var;?>');
        $this->setAttribute('method', 'post');
        $this->setAttribute('id', 'fileupload');

        $this->setEntityManager($entityManager);

<?php
foreach ($this->elements as $element):
echo $element;
endforeach;
?>
        $submit = new Element('submit');
        $submit->setValue('Salvar');
        $submit->setAttributes(array(
            'type'  => 'submit'
        ));
        $this->add($submit);
    }
}
