namespace <?php echo $this->namespace;?>;

use GearBase\Form\AbstractForm;
use Doctrine\ORM\EntityManager;
use Zend\Form\Element;

/**
 * Form for <?php echo $this->tableLabel;?> Controller.
 *
 * PHP Version 5
 *
 * @category Form
 * @package <?php echo $this->package.PHP_EOL;?>
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class <?php echo $this->class;?> extends AbstractForm
{

    /**
     * Construct Form
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @param EntityManager $entityManager EntityManager
     *
     * @return <?php echo $this->class.PHP_EOL;?>
     */
    public function __construct(EntityManager $entityManager)
    {
        parent::__construct('<?php echo $this->var;?>');
        $this->setAttribute('method', 'post');
        $this->setAttribute('id', 'fileupload');

        $this->setEntityManager($entityManager);

<?php
foreach ($this->elements as $element):
echo $element;
endforeach;
?>
        $submit = new Element('submit');
        $submit->setValue('Salvar');
        $submit->setAttributes(array(
            'type'  => 'submit'
        ));
        $this->add($submit);

        return $this;
    }
}
