namespace <?php echo $this->module;?>Test\<?php echo $this->namespace;?>;

use PHPUnit\Framework\TestCase;
use <?php echo $this->module;?>\<?php echo $this->testNamespace;?>\<?php echo $this->serviceNameClass;?>;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Form
 */
class <?php echo $this->serviceNameClass;?>Test extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->form = new <?php echo $this->serviceNameClass;?>($entityManager->reveal());
    }

    public function testHasColumn()
    {
<?php echo $this->columns;?>
    }
}
