namespace <?php echo $this->module;?>Test\FormTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Form
 */
class <?php echo $this->serviceNameClass;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->form = new \<?php echo $this->module;?>\Form\<?php echo $this->serviceNameClass;?>($entityManager->reveal());
    }

    public function testHasColumn()
    {
<?php echo $this->columns;?>
    }
}
