
version: '3.1'
services:
  main:
    image: registry.piber.network/dev-php:v1.0.7
    tty: true
    volumes:
      - .:/var/www/module
      - ~/.composer:/root/.composer
      #- ~/.composer:
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
    ports:
      - 8006:80
    networks:
      - satis
networks:
  satis:
    external: true
