version: '3.1'
services:
  <?php echo $this->module;?>:
    image: pbr/dev-php-apache:v1.0.2
    tty: true
    volumes:
      - /opt/composer-cache:/root/.composer/cache
      - .:/var/www/module
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
    ports:
      - 8006:80
  <?php echo $this->module;?>-mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: gear
    volumes:
      - <?php echo $this->module;?>-database:/var/lib/mysql
volumes:
  <?php echo $this->module;?>-database:
