version: '3.1'
services:
  main:
    image: registry.piber.network/dev-php:v1.0.7
    tty: true
    volumes:
      - /opt/composer-cache:/root/.composer/cache
      - .:/var/www/module
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
