version: '3.1'
services:
  main:
    image: registry.piber.network/dev-apache-php:v1.0.7
    tty: true
    volumes:
      - /opt/composer-cache:/root/.composer/cache
      - .:/var/www/module
      - ~/.composer/auth.json:/root/.composer/auth.json
    environment:
      - PHINX_ENVIRONMENT=DEVELOPMENT
    ports:
      - 8006:80
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: gear
    volumes:
      - gear-database:/var/lib/mysql
volumes:
  gear-database:
