/**
 * Global Configuration Override
 *
 * You can use this file for overriding configuration values from modules, etc.
 * You would place values in here that are agnostic to the environment and not
 * sensitive to security.
 *
 * @NOTE: In practice, this file will typically be INCLUDED in your source
 * control, so do not include passwords or other sensitive information in this
 * file.
 */
$env = getenv('APP_ENV');

if (in_array($env, array('development', 'production', 'staging', 'testing'))) {

    $db                 = require __DIR__.'/'.sprintf('db.%s.config.php', $env);
    $doctrine           = require __DIR__.'/'.sprintf('doctrine.%s.config.php', $env);
}
  else {
    $db                 = require __DIR__.'/'.sprintf('db.development.config.php', $env);
    $doctrine           = require __DIR__.'/'.sprintf('doctrine.development.config.php', $env);
}

return array(
    'baseUrl' => array('url' => '<?php echo $this->host;?>'),
    'db' => $db,
    'doctrine' => $doctrine
);
