<?php
namespace MyModule\Controller;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Controller\IndexController;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class IndexControllerFactory implements FactoryInterface
{
    /**
     * Create Index Controller
     *
     *
     * @return MyModule\Controller\IndexController
     */
    {
        $indexController = new IndexController();
        return $indexController;
    }
}
