<tr>
            <td>
                <?php echo $this->escapeHtml($this->object->getIdTipoCusto()); ?>
            </td>
            <td>
                <?php echo ($this->object->getIdGrupoCusto() !== null) ? $this->escapeHtml($this->object->getIdGrupoCusto()->getNome()) : ''; ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getNome()); ?>
            </td>
    <td>
        <a href="<?php echo $this->url('piber-network/tipo-custo/edit', array('id' => $this->object->getIdTipoCusto())); ?>">            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('piber-network/tipo-custo/delete', array('id' => $this->object->getIdTipoCusto())); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Tipo Custo" data-message="<?php echo $this->translate('Desejas realmente deletar Tipo Custo?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>