error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);
ini_set('display_errors',1);

chdir(dirname(__DIR__));

// Decline static file requests back to the PHP built-in webserver
if (php_sapi_name() === 'cli-server') {
    $path = realpath(__DIR__ . parse_url($_SERVER['REQUEST_URI'***REMOVED***, PHP_URL_PATH));
    if (__FILE__ !== $path && is_file($path)) {
        return false;
    }
    unset($path);
}

$env = getenv('PHINX_ENVIRONMENT');
$envs = [
  'DEVELOPMENT',
  'PRODUCTION'
***REMOVED***;
if (empty($env) || !in_array($env, $envs)) {
  try {
    throw new Exception(sprintf("Unable to start.\nCause: Invalid env: %s\nMust be %s", $env, implode(', ', $envs)));
  } catch (Exception $e) {
    echo $e->getMessage()."\n";
    exit;
  }
}

// Setup autoloading
require 'init_autoloader.php';

// Run the application!
Zend\Mvc\Application::init(require 'config/application.config.php')->run();
