namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;
use <?php echo $this->module;?>\FunctionalTester\ListSteps;
use <?php echo $this->module;?>\Functional\AbstractCest;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage;
/**
 * @SuppressWarnings(PHPMD)
*/
class <?php echo $this->class;?>ListCest extends AbstractCest
{
    public function structure(ListSteps $I)
    {
        $I->wantTo('Test <?php echo $this->module;?> <?php echo $this->class;?> List');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$URL);


        $I->see(
            '<?php echo $this->classLabel;?>',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$title
        );

        $I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableHeadRow, <?php echo $this->tableHeadCount;?>);
        $I->seeNumberOfElements(\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$tableBodyRow, <?php echo $this->exibir;?>);


        $I->see(
            'Criar',
            \<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage::$createBtn
        );

        $I->verifyBreadcrumb(
            '\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage',
            '<?php echo $this->moduleLabel;?>',
            '<?php echo $this->classLabel;?>',
            'Listar'
        );

        $I->verifyFilter('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage');
        $I->verifyPaginator('\<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ListPage', <?php echo $this->exibir;?>, <?php echo $this->maximo;?>, <?php echo $this->paginar;?>);
    }
}
