#!/bin/bash

cp config/autoload/local.php.dist config/autoload/local.php

echo "Deploy Testing - Composer"

ls -l vendor/autoload.php &> /dev/null

if [ "$?" != "0" ***REMOVED***; then
    composer update
fi;

echo "Deploy Testing - NodeJS"
vendor/bin/install-nodejs

echo "Deploy Testing - VirtualHost"

ls -l /etc/apache2/sites-enabled/my-project.gear.dev.conf > /dev/null
if [ "$?" != "0" ***REMOVED***; then
    sudo vendor/bin/virtualhost  $(pwd) my-project.gear.dev testing
fi

echo "Deploy Testing - Database"
vendor/bin/install-db-project my-project.mysql.sql

echo "Deploy Testing - Gulp"
vendor/bin/gulp