#!/bin/bash

cp config/autoload/local.php.dist config/autoload/local.php

echo "Deploy Develoment - Composer"

ls -l vendor/autoload.php &> /dev/null

if [ "$?" != "0" ***REMOVED***; then
    composer update
fi;

echo "Deploy Develoment - NodeJS"
sudo vendor/bin/install-nodejs


echo "Deploy Develoment - VirtualHost"

ls -l /etc/apache2/sites-enabled/my-project.gear.dev.conf > /dev/null

if [ "$?" != "0" ***REMOVED***; then
    sudo vendor/bin/virtualhost  $(pwd) my-project.gear.dev development
fi

echo "Deploy Development - Database"
sudo vendor/bin/install-db my-project.mysql.sql

echo "Deploy Development - Gulp"
sudo vendor/bin/gulp
