#!/bin/bash

ssh -o "StrictHostKeyChecking no" deployer@my-project.stag01.pibernetwork.com << EOF
    cd /var/www/staging
    sudo git clone git@bitbucket.org:mauriciopiber/my-project.git
    cd my-project
    sudo git pull
    sudo composer install -o
    export PHINX_ENVIRONMENT=STAGING
    sudo cp config/autoload/local.php.dist config/autoload/local.php

    sudo vendor/bin/virtualhost  /var/www/staging/my-project my-project.stag01.pibernetwork.com STAGING
    sudo chmod 777 -R data/DoctrineModule/cache
    sudo chmod 777 -R data/DoctrineORMModule/Proxy
    sudo chmod 777 -R data/cache/configcache
    sudo chmod 777 -R data/session
    sudo chmod 777 -R data/logs
    
    sudo vendor/bin/install-db-project my-project.mysql.sql MyProject
    
    sudo vendor/bin/phinx migrate
EOF
