<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo $this->translate('Create');?>&nbsp;<?php echo $this->translate('Foreign Keys');?></h3>
	</div>
</div>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('column/foreign-keys/create'));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idForeignKeys'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('name'));?>
        </div>
<!-- Image Container -->
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default reset" href="<?php echo $this->url('column/foreign-keys/list');?>">Voltar</a>
        </div>
        <?php echo $this->form()->closeTag(); ?>
    </div>
</div>