<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle"><?php echo $this->translate('Edit');?>&nbsp;<?php echo $this->translate('Foreign Keys');?> - <?php echo $this->idForeignKeys;?></h3>
	</div>
</div>
<?php if($this->success) :?>
<?php echo $this->render('layout/success');?>
<?php endif;?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('column/foreign-keys/edit', array('id' => $this->idForeignKeys)));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <?php echo $this->formHidden($form->get('idForeignKeys')->setAttribute('class','form-control')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idForeignKeys'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('name'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default" href="<?php echo $this->url('column/foreign-keys/view', array('id' => $this->idForeignKeys));?>"><?php echo $this->translate('View');?></a>
            <a class="btn btn-primary" href="<?php echo $this->url('column/foreign-keys/create');?>"><?php echo $this->translate('Create');?></a>
            <a class="btn btn-default reset" href="<?php echo $this->url('column/foreign-keys/list');?>"><?php echo $this->translate('Back');?></a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>