<?php
namespace MyModule\ConsolistsNamespace;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/ConsolistsNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class SpecialDependencyConsoleFactory implements FactoryInterface
{
    /**
     * Create SpecialDependencyConsole
     *
     * @param ServiceLocatorInterface $controllerManager Controller Manager
     * @return SpecialDependencyConsole
     */
    public function createService(ServiceLocatorInterface $controllerManager)
    {
        $serviceLocator = $controllerManager->getServiceLocator();

        $factory = new SpecialDependencyConsole(
            $serviceLocator->get('GearBase\Util\String'),
            $serviceLocator->get('console'),
            $serviceLocator->get('Zend\Db\Adapter\Adapter')
        );
        unset($serviceLocator);
        return $factory;
    }
}
