<?php
namespace MyModule\ConsolistsNamespace;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;
use Zend\Db\Adapter\Adapter;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/ConsolistsNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class SpecialDependencyConsoleFactory implements FactoryInterface
{
    /**
     * Create SpecialDependencyConsole
     *
     * @param ContainerInterface $container Controller Manager
     *
     * @return SpecialDependencyConsole
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        

        $factory = new SpecialDependencyConsole(
            $container->get('Gear\Util\String\StringService'),
            $container->get('console'),
            $container->get(Adapter::class)
        );
        
        return $factory;
    }
}
