namespace <?php echo $this->module;?>Test\FilterTest;

use GearBaseTest\AbstractTestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->className.PHP_EOL;?>
 * @group Filter
 */
class <?php echo $this->className;?>Test extends AbstractTestCase
{
    protected $<?php echo $this->var;?>;

    public function get<?php echo $this->className;?>()
    {
        if (!isset($this-><?php echo $this->var;?>)) {
            $this-><?php echo $this->var;?> = $this->bootstrap->getServiceLocator()->get('<?php echo $this->module;?>\Filter\<?php echo $this->className;?>');
        }
        return $this-><?php echo $this->var;?>;
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->className;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
     */
    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->var;?> = $this->get<?php echo $this->className;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Filter\<?php echo $this->className;?>', $<?php echo $this->var;?>);
    }


    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
    */
    public function testGetInputFilter()
    {
        $<?php echo $this->var;?> = $this->get<?php echo $this->className;?>();
        $className = $<?php echo $this->var;?>->getInputFilter();
        $this->assertInstanceOf('<?php echo $this->module;?>\Filter\<?php echo $this->className;?>', $className);
    }
}
