namespace <?php echo $this->module;?>\Controller;

use Zend\Mvc\Controller\AbstractConsoleController;
use Zend\View\Model\ConsoleModel;

class <?php echo $this->controllerName;?> extends AbstractConsoleController
{
<?php foreach ($this->actions as $i => $action) : ?>
    public function <?php echo $this->str('var', $action->getName());?>Action()
    {
        return new ViewModel(
            array(
            )
        );
    }<?php echo ($i < count($this->actions)-1) ? PHP_EOL : '';; endforeach; echo PHP_EOL;?>
}
