<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle"><?php echo '<?php echo $this->translate(\'Edit\');?>&nbsp;';?><?php echo sprintf('<?php echo $this->translate(\'%s\');?>', $this->label);?> - <?php echo sprintf('<?php echo $this->id%s;?>', $this->class);?></h3>
	</div>
<?php if ($this->imageContainer) :?>
    <div class="row">
    	<div class="col-lg-4 col-lg-offset-2">
    	    <a class="btn btn-primary" href="<?php echo sprintf('<?php echo $this->url(\'%s\', array(\'id\' => %s));?>', $this->routeImage, '$this->id'.$this->class).PHP_EOL;?>"><?php echo '<?php echo $this->translate(\'Editar Imagens\');?>';?></a>
    	</div>
    </div>
<?php endif;?>
</div>
<?php echo '<?php if($this->success) :?>'.PHP_EOL; ?>
<?php echo '<?php echo $this->render(\'layout/success\');?>'.PHP_EOL; ?>
<?php echo '<?php endif;?>'.PHP_EOL; ?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php echo '<?php'.PHP_EOL; ?>
        <?php echo '    $form = $this->form;'.PHP_EOL; ?>
        <?php echo sprintf('    $form->setAttribute(\'action\', $this->url(\'%s\', array(\'id\' => %s)));', $this->route, '$this->id'.$this->class).PHP_EOL; ?>
        <?php echo '    $form->prepare();'.PHP_EOL; ?>
        <?php echo '    echo $this->form()->openTag($form);'.PHP_EOL; ?>
        <?php echo '?>'.PHP_EOL; ?>
        <?php echo sprintf('<?php echo $this->formHidden($form->get(\'id%s\')->setAttribute(\'class\',\'form-control\')); ?>', $this->class).PHP_EOL; ?>
<?php echo $this->partialLoop('template/src/form/element.phtml', $this->elements);?>

        <div class="form-group">
            <?php echo '<?php echo $this->formSubmit($form->get(\'submit\')->setAttribute(\'class\',\'btn btn-default\')); ?>'.PHP_EOL; ?>
            <a class="btn btn-default" href="<?php echo sprintf('<?php echo $this->url(\'%s\', array(\'id\' => %s));?>', $this->routeView, '$this->id'.$this->class);?>"><?php echo '<?php echo $this->translate(\'View\');?>';?></a>
            <a class="btn btn-primary" href="<?php echo sprintf('<?php echo $this->url(\'%s\');?>', $this->routeNew);?>"><?php echo '<?php echo $this->translate(\'Create\');?>';?></a>
            <a class="btn btn-default reset" href="<?php echo sprintf('<?php echo $this->url(\'%s\');?>', $this->routeBack);?>"><?php echo '<?php echo $this->translate(\'Back\');?>';?></a>
        </div>
        <?php echo '<?php echo $this->form()->closeTag(); ?>'.PHP_EOL; ?>

    </div>
</div>