<?= '<?php $this->partialLoop()->setObjectKey(\'object\');?>';?>
<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo $this->label;?></h3>
	</div>
</div>
<a class="btn btn-success" href="<?php echo sprintf('<?php echo $this->url(\'%s/%s/create\');?>"', $this->str('url', $this->module), $this->str('url', str_replace('Controller', '', $this->controller)));?>">
    <?php echo '<?php echo $this->translate(\'Criar\');?>'; ?>
</a>

<table class="table">
    <thead>
<?php echo $this->tableHead.PHP_EOL;?>
    </thead>
    <tbody>
<?php echo sprintf('<?php echo $this->partialLoop(\'%s/row.phtml\', $this->data); ?>', $this->controllerViewFolder).PHP_EOL; ?>
    </tbody>
</table>
<?php echo sprintf('<?php echo $this->render(\'layout/delete\');?>').PHP_EOL; ?>