<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo sprintf('%s::%s::%s by gear', $this->module, $this->controller, $this->action);?></h3>
	</div>
</div>
<a href="<?php echo sprintf('<?php echo $this->url(\'%s/%s/create\');?>"', $this->str('url', $this->module), $this->str('url', str_replace('Controller', '', $this->controller)));?>">
    <?php echo '<?php echo $this->translate(\'Create\');?>'; ?>
</a>
<?php echo sprintf('<?php var_dump($this->data); ?>');?>