            <div class="form-group">
                <a id="btnBack"
                    class="btn btn-default"
                    href="<?php echo sprintf('<?php echo $this->url(\'%s\');?>', $this->routeList);?>">
                    <?php echo '<?php echo $this->translate(\'Back\');?>'.PHP_EOL;?>
                </a>
                <a id="btnCreate"
                    class="btn btn-success"
                    href="<?php echo sprintf('<?php echo $this->url(\'%s\');?>', $this->routeCreate);?>">
                    <?php echo '<?php echo $this->translate(\'New\');?>'.PHP_EOL;?>
                </a>
                <a id="btnEdit"
                    class="btn btn-primary"
                    href="<?php echo sprintf('<?php echo $this->url(\'%s\', array(\'id\' => $this->id));?>', $this->routeEdit);?>">
                    <?php echo '<?php echo $this->translate(\'Edit\');?>'.PHP_EOL;?>
                </a>
                <a id="btnDelete"
                    class="btn btn-danger"
                    href="<?php echo sprintf('<?php echo $this->url(\'%s\', array(\'id\' => $this->id));?>', $this->routeDelete);?>">
                    <?php echo '<?php echo $this->translate(\'Delete\');?>'.PHP_EOL;;?>
                </a>
            </div>