<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo sprintf('<?php echo $this->translate(\'%s\');?>', $this->label);?></h3>
	</div>
</div>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <div class="form-group">
            <table class="viewData">
                <tbody>
    <?php foreach ($this->values as $value) :?>
    <?php echo $value; ?>
    <?php endforeach;?>
                </tbody>
            </table>
        </div>
<?php echo $this->actions;?>
    </div>
</div>
