<?php echo sprintf('<?php $this->headTitle()->prepend(\'Editar Imagens -  %s\');?>', $this->label); ?>
<div class="row">
    <div class="col-lg-8">
          <h3 class="page-header">
              <?php echo '<?php echo $this->translate(\'Edit Imagens\');?>';?> - <?php echo sprintf('<?php echo $this->translate(\'%s\');?>', $this->label);?> - <?php echo '<?php echo $this->id'.$this->class.';?>'.PHP_EOL;?>
          </h3>
    </div>
    <div class="col-lg-4">
        <a class="btn btn-primary" href="<?php echo sprintf('<?php echo $this->url(\'%s\', [\'id\' => %s***REMOVED***);?>', $this->route, '$this->id'.$this->class);?>">
            <?php echo sprintf('<?php echo $this->translate(\'Edit\').\' \'.$this->translate(\'%s\');?>', $this->str('label', $this->class));?>
        </a>
    </div>
</div>
<hr>
<?php echo sprintf('<?php echo $this->render(\'gear-image/imagem/form-upload\',[\'contexto\' => $this->contexto,\'id\' => %s***REMOVED***);?>', '$this->id'.$this->class).PHP_EOL; ?>
<?php echo '<?php echo $this->render(\'gear-image/index/template-control\');?>'.PHP_EOL; ?>
<?php echo '<?php echo $this->render(\'gear-image/index/template-download\');?>'.PHP_EOL; ?>
<?php echo '<?php echo $this->render(\'gear-image/index/template-upload\');?>'.PHP_EOL; ?>