namespace <?php echo $this->module;?>\Fixture;

use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\Common\DataFixtures\AbstractFixture;
<?php echo $this->use;?>

class <?php echo $this->name;?> extends AbstractFixture<?php echo $this->implements;?>
{
<?php echo $this->attribute;?>

    public function load(ObjectManager $manager)
    {
        $this->manager = $manager;
<?php echo $this->preLoad;?>
        foreach ($this->getFixture() as $i => $fixture) {
            $reference = $i+1;
            $<?php echo $this->var;?> = new \<?php echo $this->module?>\Entity\<?php echo str_replace('Fixture', '', $this->name);?>();
<?php foreach ($this->fields as $field):?>
<?php echo $field.PHP_EOL;?>
<?php endforeach;?>
            $userReferenced = $this->getReferenceToEntity($reference);
            $<?php echo $this->var;?>->setCreated(new \DateTime('now'));
            $<?php echo $this->var;?>->setCreatedBy($userReferenced);
            $this->manager->persist($<?php echo $this->var;?>);
            $this->manager->flush();
            $this->addReference("<?php echo $this->str('url', str_replace('Fixture', '', $this->name)); ?>-$reference", $<?php echo $this->var;?>);
<?php echo $this->load;?>
        }

    }

    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function getFixture()
    {
<?php echo $this->getFixture;?>
        return array(
<?php foreach ($this->data as $item):?>
<?php echo $item;?>
<?php endforeach;?>

        );

    }

    /**
     * @SuppressWarnings(PHPMD.CyclomaticComplexity)
     */
<?php echo $this->userlaw;?>
        $userId = $this->getReference($referencedName);
        return $this->manager
          ->getRepository('GearAdmin\Entity\User')
          ->findOneBy(array('idUser' => $userId->getIdUser()));
    }
<?php echo $this->dependency;?>
}
