<?php
namespace MyModule\Interfaces;

use MyModule\Repository\MyDependencyOne;
use MyModule\Repository\MyDependencyTwo;
use MyModule\Repository\MyDependencyThree;

interface SimpleDependenciesInterface
{
    public function setMyDependencyOne(MyDependencyOne $myDependencyOne);

    public function getMyDependencyOne();

    public function setMyDependencyTwo(MyDependencyTwo $myDependencyTwo);

    public function getMyDependencyTwo();

    public function setMyDependencyThree(MyDependencyThree $myDependencyThree);

    public function getMyDependencyThree();
}
