{
    "name" : "mauriciopiber/<?php echo $this->moduleUrl;?>",
    "require" : {
        "doctrine/doctrine-orm-module" : "0.8.*",
        "doctrine/doctrine-module" : "0.8.*",
        "php" : ">=5.3.3",
        "zendframework/zendframework" : "2.3.*"
    },
    "autoload" : {
        "psr-0" : {
            "<?php echo $this->module;?>" : "src",
            "<?php echo $this->module;?>Test" : "test/unit"
        }
    }
}