<?php
return [
    'gear' => [
        'project' => [
            'name' => 'GearProject',
            'project' => true,
            'version' => '0.1.1',
            'git' => 'git@bitbucket.org:mauriciopiber/gear-project.git',
            'label' => 'Gear Project'
        ***REMOVED***,
    ***REMOVED***,
    'bjyauthorize' => ['acl_key' => 'gear-project'***REMOVED***,
    'admin' => [
        'name' => 'Gear Project',
        'title' => 'Admin Gear Project',
        'welcome' => 'Bem Vindo ao Gear Project'
     ***REMOVED***,
    'db' => [
        'driver' => 'Pdo',
        'charset' => 'UTF8',
        'driver_options' => [
            \PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"
        ***REMOVED***
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
            ***REMOVED***
        ***REMOVED***,
        'configuration' => [
        	'orm_default' => [
        	    'metadata_cache' => 'filesystem',
        	    'query_cache' => 'filesystem',
        	    'result_cache' => 'filesystem',
        	    'hydration_cache' => 'filesystem',
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'session_manager' => [***REMOVED***,
    'session_config' => [
        'cache_expire' => 3600,
        'cookie_lifetime' => 3600,
        'save_path' => __DIR__.'/../../data/session'
    ***REMOVED***
***REMOVED***;