<?php
return [
    'gear' => [
        'project' => [
            'name' => 'GearProject',
            'project' => true,
            'version' => '0.1.0',
            'git' => 'git@bitbucket.org:mauriciopiber/gear-project.git',
            'label' => 'Gear Project',
            'environment' => [
                'DEVELOPMENT' => 'gear-project.gear.dev',
                'TESTING' => 'gear-project.gear.com',
                'STAGING' => 'gear-project.stag55.pibernetwork.com',
                'PRODUCTION' => 'gear-project.pibernetwork.com'
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'bjyauthorize' => ['acl_key' => 'gear_project'***REMOVED***,
    'admin' => [
        'name' => 'Gear Project',
        'title' => 'Admin Gear Project',
        'welcome' => 'Bem vindo ao Gear Project'
     ***REMOVED***,
    'db' => [
        'dsn' => 'mysql:dbname=database_for_development;host=localhost',
        'driver' => 'Pdo',
        'charset' => 'UTF8',
        'driver_options' => [
            \PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"
        ***REMOVED***
    ***REMOVED***,
    'phinx' => [
        'adapter' => 'mysql',
        'host' => 'localhost',
        'name' => 'database_for_development'
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host' => 'localhost',
                    'port' => '3306',
                    'dbname' => 'database_for_development',
                    'charset' => 'utf8'
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***,
        'configuration' => [
        	'orm_default' => [
        	    'metadata_cache' => 'filesystem',
        	    'query_cache' => 'filesystem',
        	    'result_cache' => 'filesystem',
        	    'hydration_cache' => 'filesystem',
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'session_manager' => [***REMOVED***,
    'session_config' => [
        'cache_expire' => 3600,
        'cookie_lifetime' => 3600,
        'save_path' => __DIR__.'/../../data/session'
    ***REMOVED***
***REMOVED***;