<?php
return [
    'db' => [
        'dsn' => 'mysql:dbname=database_for_development;host=localhost',
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'params' => [
                    'host' => 'localhost',
                    'port' => '3306',
                    'dbname' => 'database_for_development',
                    'charset' => 'utf8'
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***,
    'phinx' => [
        'adapter' => 'mysql',
        'host' => 'localhost',
        'name' => 'database_for_development'
    ***REMOVED***,
    'webhost' => 'gear-project.gear.com',
    'environment' => 'development'
***REMOVED***;