<?php
return [
    'db' => [
        'username' => 'my-username',
        'password' => 'my-password',
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
               'params' => [
                    'user'     => 'my-username',
                    'password' => 'my-password',
               ***REMOVED***,
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***,
    'phinx' => [
        'user' => 'my-username',
        'pass' => 'my-password',
    ***REMOVED***,
***REMOVED***;
