<div class="row">
    <div class="col-lg-12">
        <div class="container">
            <?php echo'<?php echo $this->render(\'gear-image/imagem/form-upload\', array(\'contexto\' => $this->contexto));?>'.PHP_EOL; ?>
            <br>
        </div>
        <?php echo'<?php echo $this->render(\'gear-image/index/template-control\');?>'.PHP_EOL; ?>
        <?php echo'<?php echo $this->render(\'gear-image/index/template-download\');?>'.PHP_EOL; ?>
        <?php echo'<?php echo $this->render(\'gear-image/index/template-upload\');?>'.PHP_EOL; ?>
    </div>
</div>