<div class="row">
    <div class="col-lg-12">
        <?php echo sprintf('<?php echo $this->render(\'%s/%s/template-form.phtml\');?>', $this->module, $this->controller).PHP_EOL;?>
        <?php echo sprintf('<?php echo $this->render(\'%s/%s/template-control.phtml\');?>', $this->module, $this->controller).PHP_EOL;?>
        <?php echo sprintf('<?php echo $this->render(\'%s/%s/template-upload.phtml\');?>', $this->module, $this->controller).PHP_EOL;?>
        <?php echo sprintf('<?php echo $this->render(\'%s/%s/template-download.phtml\');?>', $this->module, $this->controller).PHP_EOL;?>
    </div>
</div>