<?php
namespace MyModule\Repository;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Repository\MyTableRepository;
use GearBase\Repository\QueryBuilder;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableRepositoryFactory implements FactoryInterface
{
    /**
     * Create MyTableRepository
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     *
     * @return MyTableRepository
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new MyTableRepository(
            $serviceLocator->get('doctrine.entitymanager.orm_default'),
            $serviceLocator->get(QueryBuilder::class)
        );
        unset($serviceLocator);
        return $factory;
    }
}
