<?php
namespace MyModule\Repository;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Repository\MyTableRepository;
use GearBase\Repository\QueryBuilder;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableRepositoryFactory implements FactoryInterface
{
    /**
     * Create MyTableRepository
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MyTableRepository
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $factory = new MyTableRepository(
            $container->get('doctrine.entitymanager.orm_default'),
            $container->get(QueryBuilder::class)
        );

        return $factory;
    }
}
