return array(
    'resolver_configs' => array(
        'collections' => [
            'js/<?php echo $this->moduleJs;?>' => [
                '/js/app/<?php echo $this->moduleName?>Module.js'
            ***REMOVED***,
            'css/<?php echo $this->moduleCssName?>.css' => [
                '/css/<?php echo $this->moduleCssName?>.css'
            ***REMOVED***
        ***REMOVED***, 
        'paths' => array(
            __DIR__ . '/../../public',
        ),
    ),
);
