                                'constraints' => array(
                                    'action' => '(?!\bpage\b)(?!\borderBy\b)[a-zA-Z***REMOVED***[a-zA-Z0-9_-***REMOVED****',
                                    'page' => '[0-9***REMOVED***+',
                                    'orderBy' => '[a-zA-Z***REMOVED***[a-zA-Z0-9_-***REMOVED****',
                                    'order' => 'ASC|DESC',
                                ),
