namespace <?php echo $this->module;?>;

$servicemanager     = require 'ext/servicemanager.config.php';

return array(
<?php if (in_array('doctrine', $this->options)) :?>
    'doctrine' => array(
        'driver' => array(
            'orm_default' => array(
                'drivers' => array(
                    __NAMESPACE__ . '\Entity' => __NAMESPACE__ . '_driver'
                )
            ),
            __NAMESPACE__ . '_driver' => array(
                'class' => 'Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'paths' => array(
                    __DIR__ . '/../src/' . __NAMESPACE__ . '/Entity'
                )
            )
        )
    ),
<?php endif;?>
<?php if (in_array('doctrine-fixture', $this->options)) :?>
    'data-fixture' => array(
        __NAMESPACE__.'_fixture' => __DIR__ . '/../src/'.__NAMESPACE__.'/Fixture',
    ),
<?php endif;?>
    'service_manager' => $servicemanager
);
