namespace <?php echo $this->module;?>;

$route              = require 'ext/route.config.php';
$navigation         = require 'ext/navigation.config.php';
$view               = require 'ext/view.config.php';
$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$assetmanager       = require 'ext/asset.config.php';

return array(
    'gear'     => array('version' => '0.1.0', 'acl' => true, 'name' => __NAMESPACE__),
    'view_manager' => $view,
    'controllers' => $controller,
    'router' => $route,
    'navigation' => $navigation,
    'service_manager' => $servicemanager,
    'asset_manager' => $assetmanager,
);
