return array(
    'router_class' => 'Zend\Mvc\Router\Http\TranslatorAwareTreeRouteStack',
    'routes' => array(
        '<?php echo $this->moduleUrl;?>' => array(
            'type' => 'literal',
            'options' => array(
                'route' => '/<?php echo $this->moduleUrl;?>',
                'defaults' => array(
                    'controller' => '<?php echo $this->module;?>\Controller\Index',
                    'action' => 'index'
                )
            ),
            'may_terminate' => true,
            'child_routes' => array(
                <?php foreach ($this->controllers as $controller) : echo PHP_EOL;?>
                    '<?= $this->str('url', str_replace('Controller', '',$controller->getName()))?>' => array(
                        'type' => 'segment',
                        'options' => array(
                            'route' => '/{<?php echo $this->str('url', str_replace('Controller', '',$controller->getName()))?>}',
                            'defaults' => array(
                                'controller' => '<?php echo sprintf($controller->getService()->getObject(), $this->module);?>',
                                'action' => 'list'
                            )
                        ),
                        'may_terminate' => true,
                        'child_routes' => array(
                            <?php foreach($controller->getActions() as $action) : echo PHP_EOL;?>
                             '<?= $this->str('url', $action->getName())?>' => array(
                                'type' => 'segment',
                                'options' => array(
                                    'route' => '/{<?= $this->str('url', $action->getRoute())?>}',
                                    'defaults' => array(
                                        'controller' => '<?= sprintf($controller->getService()->getObject(), $this->module);?>',
                                        'action' => '<?= $this->str('url', $action->getName())?>'
                                    )
                                )

                            ),
                            <?php endforeach; echo PHP_EOL;?>
                        ),
                    ),
                <?php endforeach;  echo PHP_EOL;?>
            ),
        )
    )
);
