return array(
    'factories' => array(
        'navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory',
        'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
    ),
    'aliases' => array(
        'translator' => 'MvcTranslator'
    ),
    'invokables' => array(
<?php if (count($this->invokables)>0): foreach($this->invokables as $i => $v) :?>
        '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>' =>
            '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>',
<?php endforeach; endif;?>
    ),
    'factories' => array(
<?php if (count($this->factories)>0): foreach($this->factories as $i => $v) :?>
        '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>' =>
            '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>',
<?php endforeach; endif;?>
    ),
);
