return array(
    'factories' => array(
        'navigation' => 'Zend\Navigation\Service\DefaultNavigationFactory',
        'Zend\Db\Adapter\Adapter' => 'Zend\Db\Adapter\AdapterServiceFactory',
    ),
    'aliases' => array(
        'translator' => 'MvcTranslator'
    ),
    'invokables' => array(
<?php foreach($this->factories as $i => $v) :?>
        '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>' => '<?php echo sprintf('%s\%s\%s', $v['module'***REMOVED***, $v['type'***REMOVED***, $v['name'***REMOVED***);?>',
<?php endforeach;?>
    ),
);
