var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
  directConnect: true,

  // Capabilities to be passed to the webdriver instance.
 /* multiCapabilities: [{
    'browserName': 'chrome'
  },{
    'browserName': 'firefox'
  }***REMOVED***,*/

  capabilities: {
      'browserName': 'chrome'
  },
  rootElement: '[ng-app***REMOVED***',
  baseUrl:      'http://my-project.gear.dev',
  // Framework to use. Jasmine 2 is recommended.
  framework: 'custom',

  // path relative to the current config file
  frameworkPath: require.resolve('protractor-cucumber-framework'),

  // Spec patterns are relative to the current working directly when
  // protractor is called.
  specs: [
      'module/**/public/js/spec/e2e/**/*.feature',
  ***REMOVED***,

  cucumberOpts: {
    require: [
        'module/**/public/js/spec/e2e/**/*.stepDefinitions.js',
        'module/**/public/js/spec/e2e/support/*.js',
    ***REMOVED***,
    format: undefined,
    profile: false,
    'no-source': true
  },
  onPrepare: function() {
    'use strict';
    require('protractor-http-mock').config = {
      rootDirectory: __dirname, // default value: process.cwd()
      protractorConfig: 'end2end.conf.js' // default value: 'protractor.conf'
    };
  }
};