<?php
namespace MyModule\FastestNamespace;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\FastestNamespace\MySrcWithSpecialDependency;
use Zend\Db\Adapter\Adapter;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/FastestNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MySrcWithSpecialDependencyFactory implements FactoryInterface
{
    /**
     * Create MySrcWithSpecialDependency
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MySrcWithSpecialDependency
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $factory = new MySrcWithSpecialDependency(
            $container->get('Gear\Util\String\StringService'),
            $container->get('console'),
            $container->get(Adapter::class)
        );

        return $factory;
    }
}
