<?php
namespace MyModule\FastestNamespace;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\FastestNamespace\MySrcWithSpecialDependency;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/FastestNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MySrcWithSpecialDependencyFactory implements FactoryInterface
{
    /**
     * Create MySrcWithSpecialDependency
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     * @return \MyModule\FastestNamespace\MySrcWithSpecialDependency
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new MySrcWithSpecialDependency(
            $serviceLocator->get('GearBase\Util\String'),
            $serviceLocator->get('console'),
            $serviceLocator->get('Zend\Db\Adapter\Adapter')
        );
        unset($serviceLocator);
        return $factory;
    }
}
