namespace <?php echo $this->module;?>Test\ControllerTest;

use <?php echo $this->module?>Test\ControllerTest\AbstractConsoleControllerTestCase;

/**
 * @group Controller
 */
class IndexControllerTest extends AbstractConsoleControllerTestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->indexController = new \<?php echo $this->module?>\Controller\IndexController();
    }

    public function testCanAccessNewCreatedModule()
    {
        $resp = $this->indexController->indexAction();
        $this->assertInstanceOf('Zend\View\Model\ConsoleModel', $resp);
    }
}
