<?php
namespace MyModule\Service;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Service\MyService;

class MyServiceFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new MyService(
            $serviceLocator->get('MyModule\Repository\DependencyOne'),
            $serviceLocator->get('MyModule\Service\DependencyTwo')
        );
        unset($serviceLocator);
        return $factory;
    }
}
