<?php
namespace MyModule\Service;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Service\MyService;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Service
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyServiceFactory implements FactoryInterface
{
    /**
     * Create MyService
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     * @return \MyModule\Service\MyService
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new MyService(
            $serviceLocator->get('MyModule\Repository\DependencyOne'),
            $serviceLocator->get('MyModule\Service\DependencyTwo')
        );
        unset($serviceLocator);
        return $factory;
    }
}
