<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase as TestCase;
use MyModule\Custom\CustomNamespace\UploadImageColumnController;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;
use GearBaseTest\Assertions\AclAssertTrait;

/**
 * @group MyModule
 * @group UploadImageColumn
 * @group Controller
 * @group UploadImageColumnController
 */
class UploadImageColumnControllerTest extends TestCase
{
    use AclAssertTrait;

    public function mockUploadImage()
    {
        $maker = new \GearBaseTest\UploadImageMock();
        return $maker->mockUploadFile(\MyModule\Module::getLocation());
    }

    public function mockTestUploadImageFactory($columns)
    {
        $this->getApplication()
        ->getServiceManager()
        ->setAllowOverride(true);

        $mockFilter = $this->getMockSingleClass('MyModule\Filter\UploadImageColumnFilter', array('isValid'));
        $mockFilter->expects($this->any())->method('isValid')->willReturn(true);


        $factory = $this->getApplication()
        ->getServiceManager()
        ->get('ServiceManager')->get('MyModule\Form\UploadImageColumnForm');

        $factory->setUseInputFilterDefaults(false);

        $filter = $factory->getInputFilter();

        foreach ($columns as $column) {
            $mockFileInput = $this->getMockSingleClass('Zend\InputFilter\FileInput', array('isValid', 'getName'));
            $mockFileInput->expects($this->any())->method('isValid')->willReturn(true);
            $mockFileInput->expects($this->any())->method('getName')->willReturn($column);
            $filter->getInputFilter()->remove($column)->add($mockFileInput);
        }

        $factory->setInputFilter($filter);

        $this->getApplication()
        ->getServiceManager()
        ->get('ServiceManager')->setService('MyModule\Form\UploadImageColumnForm', $factory);
    }

    public function setUp()
    {
        $this->setApplicationConfig(
            include \GearBase\Module::getProjectFolder().'/config/application.config.php'
        );
        parent::setUp();

        $this->uploadImageColumnService = $this->prophesize('MyModule\Custom\CustomNamespace\UploadImageColumnService');
        $this->uploadImageColumnForm = $this->prophesize('MyModule\Custom\CustomNamespace\UploadImageColumnForm');
        $this->uploadImageColumnSearchForm = $this->prophesize('MyModule\Custom\CustomNamespace\UploadImageColumnSearchForm');
        $this->imageService = $this->prophesize('GearImage\Service\ImageService');

        $this->controller = new UploadImageColumnController(
            $this->uploadImageColumnService->reveal(),
            $this->uploadImageColumnForm->reveal(),
            $this->uploadImageColumnSearchForm->reveal(),
            $this->imageService->reveal()
        );

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'UploadImageColumnController'));
        $this->event      = new MvcEvent();

        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $requestPlugin = new \GearBase\Controller\Plugin\RequestPlugin();
        $this->controller->getPluginManager()->setService('getRequestPlugin', $requestPlugin);

        $this->url = $this->prophesize('Zend\Mvc\Controller\Plugin\Url');
        $this->controller->getPluginManager()->setService('url', $this->url->reveal());

        $this->schema = (new \MyModule\Module())->getLocation().'/../../schema/module.json';
    }

    protected function tearDown()
    {
        $refl = new \ReflectionObject($this);
        foreach ($refl->getProperties() as $prop) {
            if (!$prop->isStatic() && 0 !== strpos($prop->getDeclaringClass()->getName(), 'PHPUnit_')) {
                $prop->setAccessible(true);
                $prop->setValue($this, null);
            }
        }
    }

    /**
     * @group controller.create
     */
    public function testEnterCreatePage()
    {
        $this->assertAcl($this->schema, 'MyModule', 'UploadImageColumnController', 'Create');

        $this->routeMatch->setParam('action', 'create');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.create
     */
    public function testSendPostToCreatePageRedirectToGet()
    {
        $this->url->fromRoute(UploadImageColumnController::CREATE)->willReturn(UploadImageColumnController::CREATE);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->response = $this->prophesize('Zend\Http\PhpEnvironment\Response');
        $this->response->getStatusCode()->willReturn(303);
        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/create', true)->willReturn($this->response->reveal());
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());
        $this->routeMatch->setParam('action', 'create');
        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
        $this->assertEquals(303, $result->getStatusCode());
    }

    /**
     * @group controller.create
     */
    public function testSendPostToCreateShowValidation()
    {
        $this->url->fromRoute(UploadImageColumnController::CREATE)->willReturn(UploadImageColumnController::CREATE);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/create', true)->willReturn([***REMOVED***);
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());

        $this->routeMatch->setParam('action', 'create');
        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.create
     */
    public function testCreateSuccessful()
    {
        $this->url->fromRoute(UploadImageColumnController::CREATE)->willReturn(UploadImageColumnController::CREATE);
        $this->url->fromRoute("my-module/upload-image-column/edit", ["id" => 31, "success" => 1***REMOVED***, [***REMOVED***, false)
          ->willReturn(UploadImageColumnController::EDIT.'/31/1');

        $this->url->setController($this->controller)->shouldBeCalled();

        $data = array(
        );

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();

        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/create', true)->willReturn($data);

        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');
        $this->entity->getIdUploadImageColumn()->willReturn(31)->shouldBeCalled();

        $this->uploadImageColumnForm->setData($data)->shouldBeCalled();
        $this->uploadImageColumnForm->isValid()->willReturn(true)->shouldBeCalled();
        $this->uploadImageColumnForm->getData()->willReturn($data)->shouldBeCalled();
        $this->uploadImageColumnService->create($data)->willReturn($this->entity)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'create');
        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.edit
     */
    public function testWhenEditDisplaySuccessful()
    {
        $this->url->fromRoute(UploadImageColumnController::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'edit');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.edit
     */
    public function testWhenEditRedirectWithInvalidIdToListing()
    {
        $this->url->fromRoute(UploadImageColumnController::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->uploadImageColumnService->selectById(6000)->willReturn(null);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 6000);
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.edit
     */
    public function testDisplayEditSuccessful()
    {
        $this->assertAcl($this->schema, 'MyModule', 'UploadImageColumnController', 'Edit');

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');

        $this->uploadImageColumnService->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.edit
     */
    public function testWhenListRedirectSuccessfulPRGWithValidId()
    {
        $this->url->fromRoute(UploadImageColumnController::EDIT, ['id' => 31***REMOVED***)->willReturn(UploadImageColumnController::EDIT);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');

        $this->uploadImageColumnService->selectById(31)->willReturn($this->entity);


        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->response = $this->prophesize('Zend\Http\PhpEnvironment\Response');
        $this->response->getStatusCode()->willReturn(303);
        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/edit', true)->willReturn($this->response->reveal());
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());


        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);

        $this->assertEquals(303, $result->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);

    }

    /**
     * @group controller.edit
     */
    public function testWhenListRedirectSuccessfulPRGWithValidIdReturnValidation()
    {
        $this->url->fromRoute(UploadImageColumnController::EDIT, ['id' => 31***REMOVED***)->willReturn(UploadImageColumnController::EDIT.'/31');
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/edit/31', true)->willReturn([***REMOVED***);
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());

        $this->uploadImageColumnService->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.edit
     */
    public function testEditSuccessfull()
    {
        $this->url->fromRoute(UploadImageColumnController::EDIT, ['id' => 31***REMOVED***)->willReturn(UploadImageColumnController::EDIT);
        $this->url->fromRoute("my-module/upload-image-column/edit", ["id" => 31, "success" => 1***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::EDIT.'/31/1');
        $this->url->setController($this->controller)->shouldBeCalled();

        $data = array(
        );

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->prg->__invoke($this->uploadImageColumnForm, 'my-module/upload-image-column/edit', true)->willReturn([***REMOVED***);
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');
        $this->entity->getIdUploadImageColumn()->willReturn(31)->shouldBeCalled();

        $this->uploadImageColumnForm->setData($data)->shouldBeCalled();
        $this->uploadImageColumnForm->isValid()->willReturn(true)->shouldBeCalled();
        $this->uploadImageColumnForm->getData()->willReturn($data)->shouldBeCalled();
        $this->uploadImageColumnService->update(31, $data)->willReturn($this->entity)->shouldBeCalled();
        $this->uploadImageColumnService->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.list
     */
    public function testWhenListDisplaySuccessful()
    {
        $this->assertAcl($this->schema, 'MyModule', 'UploadImageColumnController', 'List');

        $this->uploadImageColumnService->selectAll()->willReturn([***REMOVED***)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'list');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.view
     */
    public function testWhenViewDisplaySuccessfulWithValidId()
    {
        $this->assertAcl($this->schema, 'MyModule', 'UploadImageColumnController', 'View');

        $this->entity = $this->prophesize('MyModule\Entity\UploadImageColumn');
        //$this->entity->getIdUploadImageColumn()->willReturn(31)->shouldBeCalled();

        $this->uploadImageColumnService->selectById(31)->willReturn($this->entity->reveal());
        $this->uploadImageColumnService->extract($this->entity->reveal())->willReturn([***REMOVED***);

        $this->routeMatch->setParam('action', 'view');
        $this->routeMatch->setParam('id', 31);

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.view
     */
    public function testViewSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->url->fromRoute(UploadImageColumnController::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->uploadImageColumnService->selectById(6000)->willReturn(null);

        $this->routeMatch->setParam('action', 'view');
        $this->routeMatch->setParam('id', 6000);

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.view
     */
    public function testWhenViewDisplaySuccessful()
    {
        $this->url->fromRoute(UploadImageColumnController::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'view');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.delete
     */
    public function testDeleteSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->assertAcl($this->schema, 'MyModule', 'UploadImageColumnController', 'Delete');

        $this->uploadImageColumnService->delete(6000)->willReturn(['success' => false, 'error' => 'EntityNotFound'***REMOVED***);

        $this->routeMatch->setParam('action', 'delete');
        $this->routeMatch->setParam('id', 6000);

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    /**
     * @group controller.delete
     */
    public function testDeleteSucessfullAndRedirectToListWithSuccessful()
    {
        $this->uploadImageColumnService->delete(6000)->willReturn(['success' => true***REMOVED***);

        $this->routeMatch->setParam('action', 'delete');
        $this->routeMatch->setParam('id', 6000);

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\JsonModel', $result);
    }

    /**
     * @group controller.delete
     */
    public function testWhenDeleteDisplaySuccessful()
    {
        $this->url->fromRoute(UploadImageColumnController::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(UploadImageColumnController::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'delete');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }
}
