<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group MyModule
 * @group MyTableController
 * @group Controller
 */
class MyTableControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $this->serviceLocator = $this->prophesize('Zend\ServiceManager\ServiceManager');

        $this->serviceLocator->get('MyModule\Service\MyTableService')
            ->willReturn($this->prophesize('MyModule\Service\MyTableService')->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('MyModule\Form\MyTableForm')
            ->willReturn($this->prophesize('MyModule\Form\MyTableForm')->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('MyModule\Form\Search\MyTableSearchForm')
            ->willReturn($this->prophesize('MyModule\Form\Search\MyTableSearchForm')->reveal())
            ->shouldBeCalled();

        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal());

        $factory = new \MyModule\Controller\MyTableControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('MyModule\Controller\MyTableController', $instance);
    }
}
