<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use MyModule\Controller\MyTableControllerFactory;
use MyModule\Controller\MyTableController;
use MyModule\Service\MyTableService;
use MyModule\Form\MyTableForm;
use MyModule\Form\Search\MyTableSearchForm;

/**
 * @group MyModule
 * @group MyTableController
 * @group Controller
 */
class MyTableControllerFactoryTest extends TestCase
{
    public function testMyTableControllerFactory()
    {


        $this->container = $this->prophesize(ServiceManager::class);

        $this->container->get(MyTableService::class)
            ->willReturn($this->prophesize(MyTableService::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(MyTableForm::class)
            ->willReturn($this->prophesize(MyTableForm::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(MyTableSearchForm::class)
            ->willReturn($this->prophesize(MyTableSearchForm::class)->reveal())
            ->shouldBeCalled();



        $factory = new MyTableControllerFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableController::class, $instance);
    }
}
