<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use MyModule\Controller\MyTableControllerFactory;
use MyModule\Controller\MyTableController;
use MyModule\Service\MyTableService;
use MyModule\Form\MyTableForm;
use MyModule\Form\Search\MyTableSearchForm;

/**
 * @group MyModule
 * @group MyTableController
 * @group Controller
 */
class MyTableControllerFactoryTest extends TestCase
{
    public function testMyTableControllerFactory()
    {
        $this->controllerManager = $this->prophesize(ControllerManager::class);

        $this->serviceLocator = $this->prophesize(ServiceManager::class);

        $this->serviceLocator->get(MyTableService::class)
            ->willReturn($this->prophesize(MyTableService::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(MyTableForm::class)
            ->willReturn($this->prophesize(MyTableForm::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(MyTableSearchForm::class)
            ->willReturn($this->prophesize(MyTableSearchForm::class)->reveal())
            ->shouldBeCalled();

        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal());

        $factory = new MyTableControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf(MyTableController::class, $instance);
    }
}
