<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use MyModule\Custom\CustomNamespace\MyTableNamespaceControllerFactory;
use MyModule\Custom\CustomNamespace\MyTableNamespaceController;
use MyModule\Custom\CustomNamespace\MyTableService;
use MyModule\Custom\CustomNamespace\MyTableForm;
use MyModule\Custom\CustomNamespace\MyTableSearchForm;

/**
 * @group MyModule
 * @group MyTableNamespaceController
 * @group Controller
 */
class MyTableNamespaceControllerFactoryTest extends TestCase
{
    public function testMyTableNamespaceControllerFactory()
    {


        $this->container = $this->prophesize(ServiceManager::class);

        $this->container->get(MyTableService::class)
            ->willReturn($this->prophesize(MyTableService::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(MyTableForm::class)
            ->willReturn($this->prophesize(MyTableForm::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(MyTableSearchForm::class)
            ->willReturn($this->prophesize(MyTableSearchForm::class)->reveal())
            ->shouldBeCalled();



        $factory = new MyTableNamespaceControllerFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableNamespaceController::class, $instance);
    }
}
