<?php
return array(
    'module-create'       => 'Creating new module %s %s',
    'module-light'       => 'Creating new light module %s %s',
    'module-delete'       => 'Deleting old module %s %s',
    'module-build'        => 'Executing build %s %s',
    'module-load'         => 'Loading module %s %s',
    'module-unload'       => 'Unloading module %s %s',
    'module-push'         => 'Pushing to git %s %s',
    'module-entity'       => 'Creating entity %s %s',
    'module-entities'       => 'Creating entities %s %s',
    'module-dump'           => 'Dumping json %s %s',
    'module-fixture'        => 'Importing fixture for %s %s',
    'module-jenkins'        => 'Creating job for %s %s',
    'module-autoload'       => 'Creating autoload namespace for %s %s',

    'config'                => 'List config for %s',
    'config-add'            => 'Add config for %s',
    'config-update'         => 'Update config for %s',
    'config-delete'         => 'Delete config for %s',

    'project-diagnostics'   => 'Checking project diagnostics %s',
    'project-create'        => 'Creating new project %s %s',
    'project-cache'         => 'Renew cache in project %s',
    'project-deploy'        => 'Executing deploy in %s %s',
    'project-fixture'       => 'Importing fixture for %s',
    'project-helper'       => 'Creating gear_help.sh for %s',
    'project-build'         => 'Executing build for %s',
    'project-push'          => 'Pushing to git for %s',
    'project-create-jenkins'     => 'Creating job for project %s',
    'project-delete-jenkins'     => 'Delete job for project %s',

    'project-nfs'          => 'Exporting project on Nfs',
    'project-virtual-host' => 'Enabling project on apache2',
    'project-git'          => 'Set a git to project',

    'database-truncate'   => 'Truncating database %s',
    'database-drop-table' => 'Droping table %s',
    'database-fix-table'  => 'Fixing table %s',
    'database-mock-table' => 'Creating mock trait for table %s',

    'db-create'           => 'Creating db %s %s',
    'db-delete'           => 'Deleting db %s %s',
    'src-create'          => 'Creating src %s %s',
    'view-create'         => 'Creating view %s %s',
    'test-create'         => 'Creating test %s %s',
    'controller-create'   => 'Creating controller %s %s',
    'activity-create'     => 'Creating activity %s %s',

    'finished' => 'Script ended by %s at %s',
	'create-module-mvc'   => 'Creating a new mvc module %s on project %s on %s',
    'create-module-light' => 'Ready to create light module "%s" on project "%s" on %s',
    'delete-module'       => 'Deleting module %s from %s at %s',
    'mysql2sqlite'        => 'Converting database in %s from %s to %s as %s',

);