namespace <?php echo $this->module;?>\Repository;

use GearBase\Repository\AbstractRepository;

class <?php echo $this->class;?> extends AbstractRepository
{
    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function getMapReferences()
    {
<?php echo $this->map.PHP_EOL;?>
    }

    public function getRepositoryName()
    {
        return '<?= $this->module;?>\Entity\<?= $this->baseClass;?>';
    }

    public function getAliase()
    {
        return '<?php echo $this->aliase;?>';
    }

    public function selectById($id<?= $this->baseClassCut;?>)
    {
        return $this->getRepository()->findOneBy(
            array('id<?= $this->baseClass;?>' => $id<?= $this->baseClassCut;?>)
        );
    }

    public function update($idTable, $data)
    {
        $entity = $this->selectById($idTable);
        $this->hydrate($data, $entity);
<?php echo $this->updateBefore;?>
        $entity->setUpdated(new \DateTime('now'));
        $entity->setUpdatedBy($this->getUser());
        $this->getEventManager()->trigger(__FUNCTION__.'.pre', $this, $entity);
        $this->persist($entity);
        $this->getEventManager()->trigger(__FUNCTION__.'.post', $this, $entity);
        return $entity;
    }

    public function insert($data)
    {
        $entity = new \<?= $this->module;?>\Entity\<?= $this->baseClass;?>();
        $this->hydrate($data, $entity);
<?php echo $this->insertBefore;?>
        $entity->setCreated(new \DateTime('now'));
        $entity->setCreatedBy($this->getUser());
        $this->getEventManager()->trigger(__FUNCTION__.'.pre', $this, $entity);
        $this->persist($entity);
        $this->getEventManager()->trigger(__FUNCTION__.'.post', $this, $entity);
        return $entity;
    }
}
