namespace <?php echo $this->namespace;?>;

<?php echo $this->uses;?>
<?= ($this->abstract) ? 'abstract ' : ''; ?>class <?php echo $this->class;?><?php echo ($this->extends) ? ' extends '.$this->extends.'' : ''; ?><?php echo $this->implements;?>
{
<?php echo ($this->attributes) ? $this->attributes : '';?>
<?php echo (!empty($attributes) && !empty($constructor)) ? PHP_EOL : '';?>
<?php echo $this->constructor;?>
<?php echo (empty($attributes) && empty($constructor)) ? PHP_EOL : '';?>
}
