namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use GearBaseTest\AbstractTestCase;
use <?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>Trait;

/**
 * @group Repository
 */
class <?php echo $this->className;?>Test extends AbstractTestCase
{
    use <?php echo $this->className;?>Trait;

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->className;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
    */
    public function testGet()
    {
        $<?php echo $this->var;?> = $this->get<?php echo $this->className;?>();
        $this->assertInstanceOf('<?php echo $this->callable;?>', $<?php echo $this->var;?>);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->className.PHP_EOL;?>
    */
    public function testSet()
    {
        $<?php echo $this->mock;?> = $this->getMockSingleClass(
            '<?php echo $this->callable;?>'
        );
        $this->set<?php echo $this->className;?>($<?php echo $this->mock;?>);
        $this->assertEquals($<?php echo $this->mock;?>, $this->get<?php echo $this->className;?>());
    }
<?php echo $this->functions;?>
}
