
    public function overwriteImage(&$data, $key)
    {
        if ($data[$key***REMOVED*** !== null) {
            $fileArray = $data[$key***REMOVED***;
            $data[$key***REMOVED*** = $this->getImageService()->defineLocation($data[$key***REMOVED***, '<?php echo $this->contexto;?>-'.$key);
            return $fileArray;
        } else {
            unset($data[$key***REMOVED***);
        }
    }
