namespace <?php echo $this->module;?>\Service;

use <?php echo $this->module;?>\Service\AbstractService;
<?php echo $this->partialLoop('template/miscellaneous/use-partial.phtml', $this->use);?>

class <?php echo $this->class;?> extends <?php echo $this->extends.PHP_EOL;?>
{
<?php echo $this->partialLoop('template/miscellaneous/attribute-partial.phtml', $this->attribute);?>

    public function selectAll()
    {
        $repository = $this->get<?php echo $this->repository;?>();
        return $repository->selectAll();
    }
<?php echo $this->partialLoop('template/miscellaneous/injection-partial.phtml', $this->injection);?>
}
