namespace <?php echo $this->module;?>\Service;

use <?php echo $this->module;?>\Service\AbstractService;
<?php echo $this->partialLoop('template/miscellaneous/use-partial.phtml', $this->use);?>

class <?php echo $this->class;?> extends <?php echo $this->extends.PHP_EOL;?>
{
<?php echo $this->partialLoop('template/miscellaneous/attribute-partial.phtml', $this->attribute);?>

    protected $sessionName;

    protected $authService;

    public function setAuthService($authService)
    {
        $this->authService = $authService;
    }

    public function getAuthService()
    {
        if (!$this->authService) {
            $this->authService = $this->getServiceLocator()->get('zfcuser_auth_service');
        }
        return $this->authService;
    }


    public function getTableHead()
    {
        $map = $this->get<?php echo $this->repository;?>()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = '<?= $this->str('var', $this->baseName)?>Session';
        }
        return $this->sessionName;
    }

    public function selectOneBy(array $data)
    {
        return $this->get<?php echo $this->repository;?>()->selectOneBy($data);
    }

<?php echo $this->selectbyid;?>

    public function selectAll($select = array())
    {
        $cache      = $this->getCache();
        $repository = $this->get<?php echo $this->repository;?>();

        if ($select == null) {
            $select = array();
        }

        $selectCache  = $this->cacheCompare(sprintf('%sSelect', $this->getSessionName()), $select);
        $orderByCache = $this->cacheCompare(sprintf('%sOrderBy', $this->getSessionName()), $this->getOrderBy());
        $orderCache   = $this->cacheCompare(sprintf('%sOrder', $this->getSessionName()), $this->getOrder());

        if ($selectCache && $orderByCache && $orderCache) {
            if ($cache->hasItem(sprintf('%sResult', $this->getSessionName()))) {
                $resultSet = $cache->getItem(sprintf('%sResult', $this->getSessionName()));
            }
        }
<?php echo $this->selectall;?>

        return $this->setSelectAllCache($resultSet);
    }

    public function create($data)
    {
        $repository = $this->get<?php echo $this->repository;?>();
        $<?= $this->str('var', $this->baseName)?> = $repository->insert($data);
        if ($<?= $this->str('var', $this->baseName)?>) {
            $this->clearCache();
        }
        return $<?= $this->str('var', $this->baseName)?>;
    }


    public function update($idTable, $data = array())
    {
        $repository = $this->get<?php echo $this->repository;?>();
        $<?= $this->str('var', $this->baseName)?> = $repository->update($idTable, $data);
        if ($<?= $this->str('var', $this->baseName)?>) {
            $this->clearCache();
        }
        return $<?= $this->str('var', $this->baseName)?>;
    }

    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return false;
        }

        $repository = $this->get<?php echo $this->repository;?>();
        $<?= $this->str('var', $this->baseName)?> = $repository->delete($entity);

<?php if ($this->imagemService) :?>
        $imagemService = $this->getImagemService();
        $imagemService->deleteImages($idTable, '<?= $this->str('url', $this->baseName)?>');
<?php endif;?>
        if ($<?= $this->str('var', $this->baseName)?>) {
            $this->clearCache();
        }
        return $<?= $this->str('var', $this->baseName)?>;
    }

    public function extract(\<?php echo $this->module;?>\Entity\<?= $this->str('class', $this->baseName)?> $data)
    {
        $repository = $this->get<?php echo $this->repository;?>();
        return $repository->extract($data);
    }

<?php if ($this->imagemService) :?>
    public function getImagemService()
    {
        if (!isset($this->imagemService)) {
            $this->imagemService =
            $this->getServiceLocator()->get('ImagemUpload\Service\ImagemService');
        }
        return $this->imagemService;
    }
<?php endif;?>

<?php echo $this->partialLoop('template/miscellaneous/injection-partial.phtml', $this->injection);?>
}
