namespace <?php echo $this->module;?>\Service;

use <?php echo $this->module;?>\Service\AbstractService;
<?php echo $this->partialLoop('template/miscellaneous/use-partial.phtml', $this->use);?>

class <?php echo $this->class;?> extends <?php echo $this->extends.PHP_EOL;?>
{
<?php echo $this->partialLoop('template/miscellaneous/attribute-partial.phtml', $this->attribute);?>

    public function selectById($id)
    {
        $repository = $this->get<?php echo $this->repository;?>();
        return $repository->selectById($id);
    }

    public function selectAll()
    {
        $repository = $this->get<?php echo $this->repository;?>();
        return $repository->selectAll();
    }

    public function create($data)
    {
        $repository = $this->get<?php echo $this->repository;?>();
        $<?= $this->str('var', $this->baseName)?> = $repository->insert($data);
<?php if ($this->imagemService) :?>
        $imagemService = $this->getImagemService();
        $imagemService->updateImages('<?= $this->str('url', $this->baseName)?>', $<?= $this->str('var', $this->baseName)?>->getId<?= $this->str('class', $this->baseName)?>());
<?php endif;?>
        return $<?= $this->str('var', $this->baseName)?>;

    }

    public function update($idTable, $data = array())
    {
        $repository = $this->get<?php echo $this->repository;?>();
        return $repository->update($idTable, $data);
    }

    public function delete($idTable)
    {
        $repository = $this->get<?php echo $this->repository;?>();
        $delete = $repository->delete($idTable);

<?php if ($this->imagemService) :?>
        $imagemService = $this->getImagemService();
        $imagemService->deleteImages('<?= $this->str('url', $this->baseName)?>', $<?= $this->str('var', $this->baseName)?>->getId<?= $this->str('class', $this->baseName)?>());
<?php endif;?>

        return $delete;
    }

<?php if ($this->imagemService) :?>
    public function getImagemService()
    {
        if (!isset($this->imagemService)) {
            $this->imagemService =
            $this->getServiceLocator()->get('ImagemUpload\Service\ImagemService');
        }
        return $this->imagemService;
    }
<?php endif;?>

<?php echo $this->partialLoop('template/miscellaneous/injection-partial.phtml', $this->injection);?>
}
