namespace <?php echo $this->module;?>\Service;

use <?php echo $this->module;?>\Service\AbstractService;

<?php if (count($this->dependency)) : foreach($this->dependency as $dependency) : ?>

<?php endforeach; endif;?>

class <?php echo $this->class;?> extends <?php echo $this->extends.PHP_EOL;?>
{
    public function getClassName()
    {
        return '<?php echo $this->class;?>';
    }

    <?php if (count($this->dependency)) : foreach($this->dependency as $dependency) : ?>
    public function setFileService(FileService $fileWriter)
    {
        $this->fileService = $fileWriter;

        return $this;
    }

    public function getFileService()
    {
        if (!isset($this->fileService)) {
            $this->fileService = $this->getServiceLocator()->get('fileService');
        }

        return $this->fileService;
    }
    <?php endforeach; endif;?>
}
