<?php
namespace MyModule\Controller;

use Zend\View\Model\ConsoleModel;
use MyModule\Repository\MyRepositoryTrait;
use Zend\Mvc\Controller\AbstractConsoleController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependencyFirstConsole extends AbstractConsoleController
{
    use MyRepositoryTrait;

    /**
     * First Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function firstActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }
}
