<?php
namespace MyModule\Controller;

use Zend\View\Model\ConsoleModel;
use MyModule\Repository\RepositoryInterface;
use Zend\Mvc\Console\Controller\AbstractConsoleController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicImplementsConsole extends AbstractConsoleController implements RepositoryInterface
{

}
