<?php
namespace MyModule\Another\Long\Namespaces;

use Zend\View\Model\ConsoleModel;
use Zend\Mvc\Controller\AbstractConsoleController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Another/Long/Namespaces
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicConsole extends AbstractConsoleController
{

}
