<?php
namespace MyModule\Controller;

use Zend\View\Model\ConsoleModel;
use MyModule\Repository\MyRepositoryOneTrait;
use MyModule\Repository\MyRepositoryTwoTrait;
use MyModule\Repository\MyRepositoryThreeTrait;
use Zend\Mvc\Controller\AbstractConsoleController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependenciesManyConsole extends AbstractConsoleController
{
    use MyRepositoryOneTrait;

    use MyRepositoryTwoTrait;

    use MyRepositoryThreeTrait;

    /**
     * First Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function firstActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }

    /**
     * Second Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function secondActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }

    /**
     * Third Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function thirdActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }

    /**
     * Four Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function fourActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }

    /**
     * Five Action
     *
     * @return \Zend\View\Model\ConsoleModel
     */
    public function fiveActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }
}
