<?php
namespace MyModule\Controller;

use Zend\View\Model\ConsoleModel;
use Zend\Mvc\Controller\AbstractConsoleActionController;

/**
 * PHP Version 5
 *
 * @category Console Controller
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicFirstConsole extends AbstractConsoleActionController
{
    public function firstActionAction()
    {
        return new ConsoleModel([***REMOVED***);
    }
}
