<?php
namespace MyModule\ConsolistsNamespace;

use Zend\View\Model\ConsoleModel;
use GearBase\Util\String\StringServiceTrait;
use Zend\Mvc\Controller\AbstractActionController;
use GearBase\Util\String\StringService;
use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/ConsolistsNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class SpecialDependencyConsole extends AbstractActionController
{
    use StringServiceTrait;


    /**
     * Constructor
     *
     * @param StringService $stringService String Service
     * @param Posix         $console       Posix
     * @param Adapter       $adapter       Adapter
     *
     * @return \MyModule\ConsolistsNamespace\SpecialDependencyConsole
     */
    public function __construct(
        StringService $stringService,
        Posix $console,
        Adapter $adapter
    ) {
        $this->stringService = $stringService;
        $this->console = $console;
        $this->adapter = $adapter;

        return $this;
    }
}
