namespace <?php echo $this->module;?>Test\RepositoryTest;

use GearBaseTest\AbstractTestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Repository
 */
class <?php echo $this->serviceNameClass;?>RepositoryTest extends AbstractTestCase
{
    protected $<?php echo $this->varLenght;?>;
<?php echo $this->static;?>

    public function get<?php echo $this->serviceNameClass;?>()
    {
        if (!isset($this-><?php echo $this->varLenght;?>)) {
            $this-><?php echo $this->varLenght;?> =
                $this->bootstrap->getServiceLocator()->get('<?php echo $this->module;?>\Repository\<?php echo $this->serviceNameClass;?>Repository');
        }
        return $this-><?php echo $this->varLenght;?>;
    }

    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->serviceNameClass;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->varLenght;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Repository\<?php echo $this->serviceNameClass;?>Repository', $<?php echo $this->varLenght;?>);
    }


    public function testSelectAll()
    {
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectAll();
        $this->assertTrue(is_array($resultSet));
        $this->assertEquals(<?php echo $this->fixtureSize;?>, count($resultSet));
    }


    public function testSelectAllWithBasicFilter()
    {
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectAll(array('likeField' => ''));
        $this->assertTrue(is_array($resultSet));
        $this->assertEquals(<?php echo $this->fixtureSize;?>, count($resultSet));
    }

    public function testSelectAllWithBasicFilterFoundNone()
    {
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectAll(array('likeField' => 'abcdefAhauhsdfguagdfaf'));
        $this->assertTrue(is_array($resultSet));
        $this->assertEquals(0, count($resultSet));
    }

    public function testSelectByIdReturnEntity()
    {
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectById(1);
        $this->assertNotNull($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->serviceNameClass;?>', $resultSet);

        $this->assertEquals(1, $resultSet->getId<?php echo $this->serviceNameClass;?>());
    }

    public function testSelectByIdReturnNull()
    {
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->selectById(60000);
        $this->assertNull($resultSet);
    }

    public function testDeleteNoExistData()
    {
        $this->mockIdentity();
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->delete(6000);
        $this->assertFalse($resultSet);
    }


<?php echo $this->oneBy;?>

<?php echo $this->order;?>


    public function testCreateNewData()
    {
        $this->mockIdentity();
        $data = array(
<?php foreach ($this->insertArray as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        );
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->insert($data);
        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->serviceNameClass;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(is_null($resultSet->getUpdated()));
<?php foreach ($this->insertAssert as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        return $resultSet;
    }

    /**
     * @depends testCreateNewData
     */
    public function testUpdateExistData($entityToUpdate)
    {
        $this->mockIdentity();
        $data = array(
<?php foreach ($this->updateArray as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        );

        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()
          ->update($entityToUpdate->getId<?php echo $this->serviceNameClass;?>(), $data);

        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->serviceNameClass;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(!is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(!is_null($resultSet->getUpdated()));
<?php foreach ($this->updateAssert as $column) : ?>
<?php echo $column;?>
<?php endforeach;?>
        return $resultSet;
    }


    /**
     * @depends testUpdateExistData
     */
    public function testDeleteExistData($entityToDelete)
    {
        $entity = $this->get<?php echo $this->serviceNameClass;?>()
          ->selectById($entityToDelete->getId<?php echo $this->serviceNameClass;?>());

        $this->mockIdentity();
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->delete($entity);
        $this->assertTrue($resultSet);
    }
}
