        $messageMax = 'O valor deve ter no máximo %max% caracteres';
        $messageMin = 'O valor deve ter no mínimo %min% caracteres';
        $this->add(array(
            'name'       => 'myColumn',
            'required'   => true,
            'allow_empty' => true,
            'filters'    => array(array('name' => 'StringTrim')),
            'validators' => array(
                array(
                    'name'    => 'StringLength',
                    'options' => array(
                        'min' => 6,
                        'max' => 20,
                        'messages' => [
                            \Zend\Validator\StringLength::TOO_SHORT => $messageMin,
                            \Zend\Validator\StringLength::TOO_LONG => $messageMax
                        ***REMOVED***
                    ),
                ),
            ),
        ));

        $this->add(array(
            'name'       => 'myColumnVerify',
            'required'   => true,
            'allow_empty' => true,
            'filters'    => array(array('name' => 'StringTrim')),
            'validators' => array(
                array(
                    'name'    => 'StringLength',
                    'options' => array(
                        'min' => 6,
                        'max' => 20,
                        'messages' => [
                            \Zend\Validator\StringLength::TOO_SHORT => $messageMin,
                            \Zend\Validator\StringLength::TOO_LONG => $messageMax
                        ***REMOVED***
                    ),
                    'break_chain_on_failure' => true
                ),
                array(
                    'name'    => 'Identical',
                    'options' => array(
                        'token' => 'myColumn',
                        'messages' => [
                            \Zend\Validator\Identical::NOT_SAME => 'Os dois valores digitados não combinam.'
                        ***REMOVED***
                    ),
                ),
            ),
        ));
