<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use MyModule\Custom\CustomNamespace\SingleDbTableForm;

/**
 * @group MyModule
 * @group SingleDbTableForm
 * @group Form
 */
class SingleDbTableFormTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->form = new SingleDbTableForm($entityManager->reveal());
    }

    public function testHasColumn()
    {
        $this->assertInstanceOf('Zend\Form\Element', $this->form->get('singleDbColumn'));
    }
}
