(function(){
    'use strict';

    var controller;

    describe('<?php echo $this->describe;?>', function () {
        beforeEach(angular.mock.module('GearApp'));

        beforeEach(inject(function($controller){
            controller = $controller('<?php echo $this->className;?>');
        }));

        describe('Test properties', function(){
            it('has version', function() {
                expect(controller.version).toBe('<?php echo $this->version;?>');
            });
        })

    });
}());