namespace <?php echo $this->module;?>Test\<?php echo $this->namespace; ?>;

use PHPUnit_Framework_TestCase as TestCase;
use <?php echo $this->module?>\<?php echo $this->testNamespace;?>\<?php echo $this->class;?>Factory;
<?php echo $this->use;?>

/**
 * @group <?php echo $this->module.PHP_EOL; ?>
 * @group <?php echo $this->class.PHP_EOL; ?>
 * @group <?php echo $this->group.PHP_EOL; ?>
 */
class <?php echo $this->class;?>FactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');
<?php echo $this->dependency;?>

        $factory = new <?php echo $this->class;?>Factory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('<?php echo $this->fullclass;?>', $instance);
    }
}
