var fs = require('fs-extra');
var path = require('path');

var basepath = null;

var tryModule = path.join(__dirname, '../../../../../vendor/mauriciopiber/gear-admin');
var tryProject = path.join(__dirname, '../../../../../../../vendor/mauriciopiber/gear-admin');

if (!fs.existsSync(tryModule) && !fs.existsSync(tryProject)) {

    if (basepath == null) {
        throw new Error('Can\'t found basepath of support files');
    }
}

basepath = (fs.existsSync(tryModule)) ? tryModule : null;
basepath = (basepath == null && fs.existsSync(tryProject)) ? tryProject : basepath;

var database = require(basepath + '/public/js/spec/e2e/support/database/database.js');
var memcached = require(basepath + '/public/js/spec/e2e/support/memcached/memcached.js');
var admin = require(basepath + '/public/js/spec/e2e/support/helper/admin.js');

module.exports = function () {

    this.Before({tags: ["@my-controller-fixture"***REMOVED***}, function (scenario, callback) {

        var Q = require('q');
        Q.fcall(function() {

            return database.query(
                'insert into my_controller set ?',
                {
                    id_my_controller: '75',
                    date_column: '2006-03-15',
                    date_pt_br_column: '2006-03-15',
                    datetime_column: '2006-03-15 03:00:15',
                    datetime_pt_br_column: '2006-03-15 03:00:15',
                    time_column: '03:00:15',
                    decimal_column: '75.75',
                    money_pt_br_column: '75.75',
                    checkbox_column: '1',
                    id_foreign_key_column: '15',
                    int_column: '75',
                    html_column: '75Html Column',
                    text_column: '75Text Column',
                    tinyint_column: '1',
                    checkbox_column: '1',
                    email_column: 'email.column75@gmail.com',
                    password_verify_column: '75PasswordVerifyColu',
                    telephone_column: '(51) 9999-9975',
                    unique_id_column: '75Unique Column',
                    upload_image_column: '/upload/table-uploadImageColumn/75-%s-uploadImageColumn.gif',
                    url_column: 'url.column75.com.br',
                    varchar_column: '75Varchar Column',
                    created: '2016-12-01 01:00:00',
                    updated: null,
                    created_by: 2,
                    updated_by: null
                }
            );
        }).then(function(text) {
            memcached.flush();
        }).then(function() {
            callback();
        });
    });

    this.Given(/^que eu estou na página de editar de My Module - My Controller "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('my-module/my-controller/editar', 30, callback);
    });

    this.Given(/^que eu estou na página de visualizar imagens de My Module - My Controller "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('my-module/my-controller/visualizar', 30, callback);
    });

    this.Given(/^que eu estou na página de editar imagens de My Module - My Controller "([^"***REMOVED****)"$/, function (arg1, callback) {
        admin.iAmOn('my-module/my-controller/upload-image', 30, callback);
    });
};