    public function testSendPostToCreatePageRedirectToGet()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::CREATE)->willReturn(<?php echo $this->table;?>Controller::CREATE);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->response = $this->prophesize('Zend\Http\PhpEnvironment\Response');
        $this->response->getStatusCode()->willReturn(303);
        $this->prg->__invoke($this-><?php echo $this->tableVar;?>Form, '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/<?php echo $this->actionUrl;?>', true)->willReturn($this->response->reveal());
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());
        $this->routeMatch->setParam('action', 'create');
        $this->request->setMethod('POST');
        $result = $this->controller->dispatch($this->request);
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
        $this->assertEquals(303, $result->getStatusCode());
    }
