namespace <?php echo $this->module;?>Test\ControllerTest;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase as TestCase;
use <?php echo $this->module?>\Controller\<?php echo $this->controllerName; ?>;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->tableName.PHP_EOL;?>
 * @group Controller
 */
class <?php echo $this->controllerName; ?>Test extends TestCase
{
<?php echo $this->extraColumns;?>
<?php echo $this->extraFilter;?>
<?php echo $this->static;?>

    public function setUp()
    {
        $this->setApplicationConfig(
            include \GearBase\Module::getProjectFolder().'/config/application.config.php'
        );
        parent::setUp();

        $this->controller = new <?php echo $this->controllerName; ?>();
        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => '<?php echo $this->controllerName; ?>'));
        $this->event      = new MvcEvent();

        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this-><?php echo $this->tableVar;?>Form = $this->prophesize('<?php echo $this->module;?>\Form\<?php echo $this->tableName;?>Form');
<?php echo $this->setUp;?>
        $this-><?php echo $this->tableVar;?>SearchForm = $this->prophesize('<?php echo $this->module;?>\Form\Search\<?php echo $this->tableName;?>SearchForm');
        $this-><?php echo $this->tableVar;?>Service = $this->prophesize('<?php echo $this->module;?>\Service\<?php echo $this->tableName;?>Service');

        $requestPlugin = new \GearBase\Controller\Plugin\RequestPlugin();
        $this->controller->getPluginManager()->setService('getRequestPlugin', $requestPlugin);

        $this->url = $this->prophesize('Zend\Mvc\Controller\Plugin\Url');
        $this->controller->getPluginManager()->setService('url', $this->url->reveal());

        $this->controller->set<?php echo $this->tableName;?>Form($this-><?php echo $this->tableVar;?>Form->reveal());
        $this->controller->set<?php echo $this->tableName;?>Service($this-><?php echo $this->tableVar;?>Service->reveal());
        $this->controller->set<?php echo $this->tableName;?>SearchForm($this-><?php echo $this->tableVar;?>SearchForm->reveal());
    }

    protected function tearDown()
    {
        $refl = new \ReflectionObject($this);
        foreach ($refl->getProperties() as $prop) {
            if (!$prop->isStatic() && 0 !== strpos($prop->getDeclaringClass()->getName(), 'PHPUnit_')) {
                $prop->setAccessible(true);
                $prop->setValue($this, null);
            }
        }
    }

    /**
     * @group controller.create
     */
    public function testEnterCreatePage()
    {
        $this->routeMatch->setParam('action', 'create');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group controller.create
     */
<?php echo $this->createPrg;?>

    /**
     * @group controller.create
     */
<?php echo $this->createValidate;?>

    /**
     * @group controller.create
     */
<?php echo $this->createSuccessful;?>

<?php echo $this->createReturnValidation;?>
    /**
     * @group controller.edit
     */
    public function testWhenEditDisplaySuccessful()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(<?php echo $this->table;?>Controller::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->routeMatch->setParam('action', 'edit');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    /**
     * @group controller.edit
     */
    public function testWhenEditRedirectWithInvalidIdToListing()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::LISTS, [***REMOVED***, [***REMOVED***, false)->willReturn(<?php echo $this->table;?>Controller::LISTS);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this-><?php echo $this->tableVar;?>Service->selectById(6000)->willReturn(null);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 6000);
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }

    public function testWhenListDisplaySuccessful()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('<?php echo $this->module;?>\Service\<?php echo $this->table;?>Service');
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/listar');
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('list');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/list');
    }


    public function testWhenFilterWithoutData()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('<?php echo $this->module;?>\Service\<?php echo $this->table;?>Service');
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/listar', 'POST', array());
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('list');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/list');
    }


    public function testWhenFilterWithoutDataWithPRG()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('<?php echo $this->module;?>\Service\<?php echo $this->table;?>Service');
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/listar', 'POST', array());
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('list');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/list');
    }


    public function testDeleteSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->mockUser();
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/excluir/6000');
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('delete');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/delete');
    }


    public function testWhenDeleteDisplaySuccessful()
    {
        $this->mockUser();
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/excluir');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('delete');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/delete');
    }


    public function testViewSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->mockUser();
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/visualizar/6000');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertRedirectTo('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/listar/page//orderBy');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('view');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/view');
    }

    public function testWhenViewDisplaySuccessful()
    {
        $this->mockUser();
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/visualizar');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('view');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/view');
    }

   /**
     * @depends testCreateSuccess
     */
    public function testWhenListDisplaySuccessfulWithValidId($resultSet)
    {
        $this->mockUser();

        $this->dispatch(
            '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar/'.$resultSet->getId<?php echo $this->table;?>()
        );

        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('edit');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit');
    }

    /**
     * @depends testCreateSuccess
     */
    public function testWhenViewDisplaySuccessfulWithValidId($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/visualizar/'.$resultSet->getId<?php echo $this->table;?>()
        );

        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('view');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/view');
    }

    /**
     * @depends testCreateSuccess
     */
    public function testWhenListRedirectSuccessfulPRGWithValidId($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar/'.$resultSet->getId<?php echo $this->table;?>(),
            'POST'
        );

        $this->assertResponseStatusCode(303);
        $this->assertRedirectTo(
            '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar/'.$resultSet->getId<?php echo $this->table;?>()
        );
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('edit');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit');
    }
<?php echo $this->editReturnValidation;?>

    /**
     * @depends testCreateSuccess
     */
    public function testEditAfterCreateOk($resultSet)
    {

        $newData = array(
<?php echo $this->updateArray;?>
        );
        $this->mockUser();
<?php echo $this->mockPRG;?>
<?php echo $this->extraUpdate; ?>
        $this->dispatch(
            '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar/'.$resultSet->getId<?php echo $this->table;?>(),
            'POST',
            $newData
        );
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('edit');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit');

        $this->assertRedirectTo(
            sprintf(
                '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/editar/%d/1',
                $resultSet->getId<?php echo $this->table;?>()
            )
        );
    }
<?php echo (!empty($this->functions)) ? $this->functions : '';?>
     /**
     * @depends testCreateSuccess
     */
    public function testDeleteAfterEditOk($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            sprintf(
                '/<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/excluir/%d',
                $resultSet->getId<?php echo $this->table;?>()
            )
        );
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->table;?>');
        $this->assertActionName('delete');
        $this->assertControllerClass('<?php echo $this->table;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/delete');
    }
}
