    public function testWhenListRedirectSuccessfulPRGWithValidId()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::EDIT, ['id' => 31***REMOVED***)->willReturn(<?php echo $this->table;?>Controller::EDIT);
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->table;?>');

        $this-><?php echo $this->tableVar;?>Service->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(303, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }
