    public function testWhenListRedirectSuccessfulPRGWithValidIdReturnValidation()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::EDIT, ['id' => 31***REMOVED***)->willReturn(<?php echo $this->table;?>Controller::EDIT.'/31');
        $this->url->setController($this->controller)->shouldBeCalled();

        $this->entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->table;?>');

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\FilePostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();
        $this->prg->__invoke($this-><?php echo $this->tableVar;?>Form, '<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit/31', true)->willReturn([***REMOVED***);
        $this->controller->getPluginManager()->setService('filepostredirectget', $this->prg->reveal());

        $this-><?php echo $this->tableVar;?>Service->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }
