    public function testEditSuccessfull()
    {
        $this->url->fromRoute(<?php echo $this->table;?>Controller::EDIT, ['id' => 31***REMOVED***)->willReturn(<?php echo $this->table;?>Controller::EDIT);
        $this->url->fromRoute("<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit", ["id" => 31, "success" => 1***REMOVED***, [***REMOVED***, false)->willReturn(<?php echo $this->table;?>Controller::EDIT.'/31/1');
        $this->url->setController($this->controller)->shouldBeCalled();

        $data = array(
        );

        $this->prg = $this->prophesize('Zend\Mvc\Controller\Plugin\PostRedirectGet');
        $this->prg->setController($this->controller)->shouldBeCalled();

        $this->prg->__invoke('<?php echo $this->moduleUrl;?>/<?php echo $this->tableUrl;?>/edit', true)->willReturn($data);

        $this->controller->getPluginManager()->setService('postredirectget', $this->prg->reveal());

        $this->entity = $this->prophesize('<?php echo $this->module;?>\Entity\<?php echo $this->table;?>');
        $this->entity->getId<?php echo $this->table;?>()->willReturn(31)->shouldBeCalled();

        $this-><?php echo $this->tableVar;?>Form->setData($data)->shouldBeCalled();
        $this-><?php echo $this->tableVar;?>Form->isValid()->willReturn(true)->shouldBeCalled();
        $this-><?php echo $this->tableVar;?>Form->getData()->willReturn($data)->shouldBeCalled();
        $this-><?php echo $this->tableVar;?>Service->update(31, $data)->willReturn($this->entity)->shouldBeCalled();
        $this-><?php echo $this->tableVar;?>Service->selectById(31)->willReturn($this->entity);

        $this->routeMatch->setParam('action', 'edit');
        $this->routeMatch->setParam('id', 31);

        $this->request->setMethod('POST');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(302, $response->getStatusCode());
        $this->assertInstanceOf('Zend\Http\PhpEnvironment\Response', $result);
    }
