<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Custom\CustomNamespace\MyTableFilterFactory;
use MyModule\Custom\CustomNamespace\MyTableFilter;
use Zend\Db\Adapter\Adapter;
use Zend\Mvc\I18n\Translator;

/**
 * @group MyModule
 * @group MyTableFilter
 * @group Filter
 */
class MyTableFilterFactoryTest extends TestCase
{
    public function testMyTableFilterFactory()
    {
        $this->serviceLocator = $this->prophesize(ServiceLocatorInterface::class);

        $this->serviceLocator->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('translate')
            ->willReturn($this->prophesize(Translator::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableFilterFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf(MyTableFilter::class, $instance);
    }
}
