<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group MyModule
 * @group MyTableFilter
 * @group Filter
 */
class MyTableFilterFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $this->serviceLocator->get('Zend\Db\Adapter\Adapter')
            ->willReturn($this->prophesize('Zend\Db\Adapter\Adapter')->reveal())
            ->shouldBeCalled();

        $factory = new \MyModule\Custom\CustomNamespace\MyTableFilterFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Custom\CustomNamespace\MyTableFilter', $instance);
    }
}
