<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use Interop\Container\ContainerInterface;
use MyModule\Custom\CustomNamespace\MyTableFilterFactory;
use MyModule\Custom\CustomNamespace\MyTableFilter;
use Zend\Db\Adapter\Adapter;
use Zend\Mvc\I18n\Translator;

/**
 * @group MyModule
 * @group MyTableFilter
 * @group Filter
 */
class MyTableFilterFactoryTest extends TestCase
{
    public function testMyTableFilterFactory()
    {
        $this->container = $this->prophesize(ContainerInterface::class);

        $this->container->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();

        $this->container->get('translate')
            ->willReturn($this->prophesize(Translator::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableFilterFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableFilter::class, $instance);
    }
}
