namespace <?php echo $this->module;?>\Repository;

use <?php echo $this->module;?>\Repository\AbstractRepository;

class <?php echo $this->class;?> extends AbstractRepository
{
    public function getMapReferences()
    {
        return array(
<?php echo $this->map;?>
        );
    }

    public function getRepositoryName()
    {
        return '<?= $this->module;?>\Entity\<?= $this->baseClass;?>';
    }

    public function getAliase()
    {
        return '<?php echo $this->aliase;?>';
    }

    public function selectById($id<?= $this->baseClassCut;?>)
    {
        return $this->getRepository()->findOneBy(
            array('id<?= $this->baseClass;?>' => $id<?= $this->baseClassCut;?>)
        );
    }

    public function update($idTable, $data)
    {
        $entity = $this->selectById($idTable);
        $entity->setUpdated(new \DateTime('now'));
        $entity->setUpdatedBy($this->getUser());
        $this->hydrate($data, $entity);
        $this->persist($entity);
        return $entity;
    }

    public function insert($data)
    {
        $entity = new \<?= $this->module;?>\Entity\<?= $this->baseClass;?>();
        $entity->setCreated(new \DateTime('now'));
        $entity->setCreatedBy($this->getUser());
        $this->hydrate($data, $entity);
        $this->persist($entity);
        return $entity;
    }
}
