namespace <?php echo $this->module;?>\Repository;

use <?php echo $this->module;?>\Repository\AbstractRepository;

class <?php echo $this->class;?>Repository extends AbstractRepository
{
    protected $entityManager;

    public function selectAll()
    {
        return $this->getEntityManager()->getRepository('<?= $this->module;?>\Entity\<?= $this->class;?>')->findAll();
    }

    public function setEntityManager($entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function getEntityManager()
    {
        if (!isset($this->entityManager)) {
            $this->entityManager = $this->getServiceLocator()->get('doctrine.entitymanager.orm_default');
        }
        return $this->entityManager;
    }
}
