<?php
namespace MyModule\Filter;

use MyModule\Filter\MyFilter;

/**
 * PHP Version 5
 *
 * @category Filter
 * @package MyModule/Filter
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicExtendsFilter extends MyFilter
{
    /**
     * Create the Filter to Form Elements
     *
     * @return BasicExtendsFilter
     *
     */
    public function getInputFilter()
    {
        return $this;
    }
}
