<?php
namespace MyModule\Basic\Feature\Issue\Task;

use Zend\InputFilter\InputFilter;

/**
 * PHP Version 5
 *
 * @category Filter
 * @package MyModule/Basic/Feature/Issue/Task
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class LongNamespaceFilter extends InputFilter
{
    /**
     * Create the Filter to Form Elements
     *
     * @return LongNamespaceFilter
     *
     */
    public function getInputFilter()
    {
        return $this;
    }
}
