# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-create
Funcionalidade: Cadastrar novo <?php echo $this->tableLabel;?>.

  Como Administrador, quero cadastrar um novo <?php echo $this->tableLabel;?>.

    @tearDown @logValidation
    Cenário: Acesso a página de Criar <?php echo $this->tableLabel;?>.
      Dado que eu estou logado na página principal
      Quando eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
      Então eu vejo o título "Criar <?php echo $this->tableLabel;?> - Admin PiberNetwork"
      E eu vejo o título central "Criar <?php echo $this->tableLabel;?>"
      E eu vejo o breadscrumb "<?php echo $this->moduleLabel;?> / <?php echo $this->tableLabel;?> / Criar"
      E eu vejo o botão de Salvar
      E eu vejo o botão de Voltar
<?php echo $this->sendKeys; ?>
      E eu clico no botão Salvar
      Então eu vejo a mensagem que foi "Sucesso! Os dados foram salvos corretamente."
<?php echo $this->expectValues; ?>

    @tearDown @form-validate
    Cenário: Crio <?php echo $this->tableLabel;?> com os campos em banco
      Dado que eu estou logado na página principal
      Quando eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
      E eu clico no botão Salvar
<?php echo $this->expectValidateNotNull; ?>