# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-create @create
Funcionalidade: Cadastrar novo <?php echo $this->tableLabel;?>.

  Como Administrador, quero cadastrar um novo <?php echo $this->tableLabel;?>.

    @tearDown @logValidation @form-success
    Cenário: Acesso a página de Criar <?php echo $this->tableLabel;?>.
      Dado que eu estou logado na página principal
      Quando eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
      Então eu vejo o título "Criar <?php echo $this->tableLabel;?> - Admin PiberNetwork"
      E eu vejo o título central "Criar <?php echo $this->tableLabel;?>"
      E eu vejo o breadscrumb "<?php echo $this->moduleLabel;?> / <?php echo $this->tableLabel;?> / Criar"
      E eu vejo o botão de Salvar
      E eu vejo o botão de Voltar
<?php echo $this->sendKeys; ?>
      E eu clico no botão Salvar
      Então eu vejo a mensagem que foi "Sucesso! Os dados foram salvos corretamente."
<?php echo $this->expectValues; ?>

    @tearDown @form-validate-null
    Cenário: Crio <?php echo $this->tableLabel;?> com os campos em banco
      Dado que eu estou logado na página principal
      Quando eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
      E eu clico no botão Salvar
<?php echo $this->expectValidateNotNull; ?>

    @form-validate-invalid
    Cenário: Crio <?php echo $this->tableLabel;?> com formatos inválidos
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
<?php echo $this->sendKeysInvalid; ?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateInvalid; ?>

    @form-validate-max
    Cenário: Crio <?php echo $this->tableLabel;?> com valores com numero de caracteres acima do permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
<?php echo $this->sendKeysMax;?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateMax;?>

    @form-validate-min
    Cenário: Crio <?php echo $this->tableLabel;?> com valores com numero de caracteres menor que o permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Criar"
<?php echo $this->sendKeysMin;?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateMin;?>
<?php echo $this->formValidateUnique;?>
