# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-edit @edit

Funcionalidade: Editar <?php echo $this->tableLabel;?> existente.

  Como Administrador, quero editar um <?php echo $this->tableLabel;?> já existente.

    @tearDown @<?php echo $this->tableUrl;?>-fixture @logValidation
    Cenário: Editar <?php echo $this->tableLabel;?> com sucesso.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "75" na linha "1"
      E eu clico no botão Editar no ítem ID "75"
      E eu vejo o título "Editar <?php echo $this->tableLabel;?> - Admin PiberNetwork"
      E eu vejo o título central "Editar <?php echo $this->tableLabel;?> - 75"
      E eu vejo o breadscrumb "<?php echo $this->moduleLabel;?> / <?php echo $this->tableLabel;?> / Editar"
<?php echo $this->expectFixtures;?>
<?php echo $this->sendKeys;?>
      E eu clico no botão Salvar
      Então eu vejo a mensagem que foi "Sucesso! Os dados foram salvos corretamente."
<?php echo $this->expectValues;?>
<?php echo $this->formValidateNotNull;?>

    @form-validate-invalid
    Cenário: Edito <?php echo $this->tableLabel;?> com formatos inválidos
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "30" na linha "1"
      E eu clico no botão Editar no ítem ID "30"
<?php echo $this->sendKeysInvalid; ?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateInvalid; ?>

    @form-validate-max
    Cenário: Edito <?php echo $this->tableLabel;?> com valores com numero de caracteres acima do permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "30" na linha "1"
      E eu clico no botão Editar no ítem ID "30"
<?php echo $this->sendKeysMax;?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateMax;?>

    @form-validate-min
    Cenário: Edito <?php echo $this->tableLabel;?> com valores com numero de caracteres menor que o permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "30" na linha "1"
      E eu clico no botão Editar no ítem ID "30"
<?php echo $this->sendKeysMin;?>
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
<?php echo $this->expectValidateMin;?>
<?php echo $this->formValidateUnique;?>