# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-edit

Funcionalidade: Editar <?php echo $this->tableLabel;?> existente.

  Como Administrador, quero editar um <?php echo $this->tableLabel;?> já existente.

    @<?php echo $this->tableUrl;?>-fixture @tearDown
    Cenário: Editar <?php echo $this->tableLabel;?> com sucesso.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "95" na linha "1"
      E eu clico no botão Editar no ítem ID "95"
      E eu vejo o título "Editar <?php echo $this->tableLabel;?> - Admin PiberNetwork"
      E eu vejo o título central "Editar <?php echo $this->tableLabel;?> - 95"
      E eu vejo o breadscrumb "<?php echo $this->moduleLabel;?> / <?php echo $this->tableLabel;?> / Editar"
<?php echo $this->expectFixtures;?>