# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-list

Funcionalidade: Listar <?php echo $this->tableLabel;?> cadastrados.

  Como Administrador, quero listar os <?php echo $this->tableLabel;?> cadastrados.

  Cenário: Acesso a página de listar <?php echo $this->tableLabel;?>.

    Dado que eu estou logado na página principal
    Quando eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
    Então eu vejo o título "Listar <?php echo $this->tableLabel;?> - Admin PiberNetwork"
    E eu vejo o título central "<?php echo $this->tableLabel;?>"
    E eu vejo o breadscrumb "<?php echo $this->moduleLabel;?> / <?php echo $this->tableLabel;?> / Listar"
    E eu vejo "10" ítens cadastrados
    E eu vejo que está "Mostrando 1 - 10 de 30" na paginação