# language: pt

@<?php echo $this->moduleUrl;?> @<?php echo $this->tableUrl;?> @<?php echo $this->tableUrl;?>-upload-image

Funcionalidade: Visualizar imagens cadastradas em um <?php echo $this->tableLabel;?>.

  Como Administrador, quero visualizar as imagens de um <?php echo $this->tableLabel;?>.

    Cenário: Acesso a página de Visualizar Imagens em <?php echo $this->tableLabel;?>.
      Dado que eu estou logado na página principal
      E eu clico no menu "<?php echo $this->moduleLabel;?> - <?php echo $this->tableLabel;?> - Listar"
      E eu vejo o ítem ID "30" na linha "1"
      Quando eu clico no botão Editar no ítem ID "30"
      E eu clico no botão "Editar Imagens"
      Então eu vejo "3" imagens cadastradas.
