# language: pt

@my-module @my-controller @my-action
Funcionalidade: Acessar a ação My Controller / My Action do módulo My Module

  Como administrador, quero acessar a página My Module / My Controller / My Action e ver a versão do gear utilizada.

  Cenário: Acessar a ação My Controller - My Action com sucesso.

    Dado que eu estou logado na página principal
    Quando eu clico no menu "My Module - My Controller - My Action"
    Então eu vejo o título "My Module - My Controller - My Action - Admin PiberNetwork"
    E eu vejo o título central "MyModule\MyController\MyAction"
    E eu vejo o breadscrumb "My Module / My Controller / My Action"
    E eu vejo o texto principal da Página "Created by Gear 0.0.99"