# language: pt

@my-module @my-controller @my-controller-create @create
Funcionalidade: Cadastrar novo My Controller.

  Como Administrador, quero cadastrar um novo My Controller.

    @tearDown @logValidation @form-success
    Cenário: Acesso a página de Criar My Controller.
      Dado que eu estou logado na página principal
      Quando eu clico no menu "My Module - My Controller - Criar"
      Então eu vejo o título "Criar My Controller - Admin PiberNetwork"
      E eu vejo o título central "Criar My Controller"
      E eu vejo o breadscrumb "My Module / My Controller / Criar"
      E eu vejo o botão de Salvar
      E eu vejo o botão de Voltar
      E eu entro com o valor "2015-07-25" no campo "Date Column Unique Not Null"
      E eu entro com o valor "25/07/2015" no campo "Date Pt Br Column Unique Not Null"
      E eu entro com o valor "2015-07-25 07:00:55" no campo "Datetime Column Unique Not Null"
      E eu entro com o valor "25/07/2015 07:00:55" no campo "Datetime Pt Br Column Unique Not Null"
      E eu entro com o valor "07:00:55" no campo "Time Column Unique Not Null"
      E eu entro com o valor "55.55" no campo "Decimal Column Unique Not Null"
      E eu entro com o valor "R$ 55,55" no campo "Money Pt Br Column Unique Not Null"
      E eu marco a caixa de escolha "Checkbox Column Unique Not Null"
      E eu escolho o valor "25Foreign Key Column Unique Not Null" na caixa para selecionar "Foreign Key Column Unique Not Null"
      E eu entro com o valor "55" no campo "Int Column Unique Not Null"
      E eu entro com o texto "55Html Column Unique Not Null" no campo html "Html Column Unique Not Null"
      E eu entro com o texto "55Text Column Unique Not Null" no campo "Text Column Unique Not Null"
      E eu marco a caixa de escolha "Tinyint Column Unique Not Null"
      E eu marco a caixa de escolha "Checkbox Column Unique Not Null"
      E eu entro com o valor "email.column.unique.not.null55@gmail.com" no campo "Email Column Unique Not Null"
      E eu entro com o valor "55PasswordVerifyColu" no campo "Password Verify Column Unique Not Null"
      E eu entro com o valor "55PasswordVerifyColu" no campo "Password Verify Column Unique Not Null Verify"
      E eu entro com o valor "(51) 9999-9955" no campo "Telephone Column Unique Not Null"
      E eu entro com uma imagem no campo "Upload Image Column Unique Not Null"
      E eu entro com o valor "url.column.unique.not.null55.com.br" no campo "Url Column Unique Not Null"
      E eu entro com o valor "55Varchar Column Unique Not Null" no campo "Varchar Column Unique Not Null"
      E eu clico no botão Salvar
      Então eu vejo a mensagem que foi "Sucesso! Os dados foram salvos corretamente."
      E eu vejo o valor "2015-07-25" no campo "Date Column Unique Not Null"
      E eu vejo o valor "25/07/2015" no campo "Date Pt Br Column Unique Not Null"
      E eu vejo o valor "2015-07-25 07:00:55" no campo "Datetime Column Unique Not Null"
      E eu vejo o valor "25/07/2015 07:00:55" no campo "Datetime Pt Br Column Unique Not Null"
      E eu vejo o valor "07:00:55" no campo "Time Column Unique Not Null"
      E eu vejo o valor "55.55" no campo "Decimal Column Unique Not Null"
      E eu vejo o valor "R$ 55,55" no campo "Money Pt Br Column Unique Not Null"
      E eu vejo marcada a caixa de escolha "Checkbox Column Unique Not Null"
      E eu vejo escolhido "25Foreign Key Column Unique Not Null" na caixa para selecionar "Foreign Key Column Unique Not Null"
      E eu vejo o valor "55" no campo "Int Column Unique Not Null"
      E eu vejo texto "55Html Column Unique Not Null" no campo html "Html Column Unique Not Null"
      E eu vejo texto "55Text Column Unique Not Null" no campo "Text Column Unique Not Null"
      E eu vejo marcada a caixa de escolha "Tinyint Column Unique Not Null"
      E eu vejo marcada a caixa de escolha "Checkbox Column Unique Not Null"
      E eu vejo o valor "email.column.unique.not.null55@gmail.com" no campo "Email Column Unique Not Null"
      E eu vejo o valor "" no campo "Password Verify Column Unique Not Null"
      E eu vejo o valor "" no campo "Password Verify Column Unique Not Null Verify"
      E eu vejo o valor "(51) 9999-9955" no campo "Telephone Column Unique Not Null"
      E eu vejo a imagem "/upload/table-uploadImageColumnUniqueNotNull/prefake-image.png" no campo "Upload Image Column Unique Not Null"
      E eu vejo o valor "url.column.unique.not.null55.com.br" no campo "Url Column Unique Not Null"
      E eu vejo o valor "55Varchar Column Unique Not Null" no campo "Varchar Column Unique Not Null"

    @tearDown @form-validate-null
    Cenário: Crio My Controller com os campos em banco
      Dado que eu estou logado na página principal
      Quando eu clico no menu "My Module - My Controller - Criar"
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Date Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Date Pt Br Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Datetime Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Datetime Pt Br Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Time Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Decimal Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Money Pt Br Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Foreign Key Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Int Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Html Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Text Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Email Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Password Verify Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Password Verify Column Unique Not Null Verify"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Telephone Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Url Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é obrigatório e não pode estar vazio" no campo "Varchar Column Unique Not Null"

    @form-validate-invalid
    Cenário: Crio My Controller com formatos inválidos
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Criar"
      E eu entro com o valor "ABCDEF" no campo "Email Column Unique Not Null"
      E eu entro com o valor "ABCDEF" no campo "Telephone Column Unique Not Null"
      E eu entro com o valor "ABCDEF" no campo "Url Column Unique Not Null"
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
      E eu vejo a o aviso de validação que "O valor é inválido" no campo "Email Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é inválido" no campo "Telephone Column Unique Not Null"
      E eu vejo a o aviso de validação que "O valor é inválido" no campo "Url Column Unique Not Null"

    @form-validate-max
    Cenário: Crio My Controller com valores com numero de caracteres acima do permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Criar"
      E eu entro com o valor "abcdefghijklmnopqrstujxywzabcdefghijklmnopqrstuvxywz" no campo "Varchar Column Unique Not Null"
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
      E eu vejo a o aviso de validação que "O valor deve ter no máximo 25 caracteres" no campo "Varchar Column Unique Not Null"

    @form-validate-min
    Cenário: Crio My Controller com valores com numero de caracteres menor que o permitido.
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Criar"
      E eu entro com o valor "abc" no campo "Varchar Column Unique Not Null"
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
      E eu vejo a o aviso de validação que "O valor deve ter no mínimo 5 caracteres" no campo "Varchar Column Unique Not Null"

    @form-validate-unique
    Cenário: Crio My Controller com valores já utilizados em outros ítens
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Criar"
      E eu entro com o valor "2010-06-30" no campo "Date Column Unique Not Null"
      E eu entro com o valor "2010-06-30 06:00:30" no campo "Datetime Column Unique Not Null"
      E eu entro com o valor "06:00:30" no campo "Time Column Unique Not Null"
      E eu entro com o valor "30.30" no campo "Decimal Column Unique Not Null"
      E eu entro com o valor "30" no campo "Int Column Unique Not Null"
      E eu entro com o valor "email.column.unique.not.null30@gmail.com" no campo "Email Column Unique Not Null"
      E eu entro com o valor "(51) 9999-9930" no campo "Telephone Column Unique Not Null"
      E eu entro com o valor "url.column.unique.not.null30.com.br" no campo "Url Column Unique Not Null"
      E eu entro com o valor "30Varchar Column Unique Not Null" no campo "Varchar Column Unique Not Null"
      E eu clico no botão Salvar
      Então eu vejo o alerta com a mensagem  "Ops! Verificar a validação dos campos para continuar"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Date Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Datetime Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Time Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Decimal Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Int Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Email Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Telephone Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Url Column Unique Not Null"
      E eu vejo a o aviso de validação que "Valor já está sendo utilizado" no campo "Varchar Column Unique Not Null"
