# language: pt

@my-module @my-controller @my-controller-create
Funcionalidade: Cadastrar novo My Controller.

  Como Administrador, quero cadastrar um novo My Controller.

    @tearDown
    Cenário: Acesso a página de Criar My Controller.
      Dado que eu estou logado na página principal
      Quando eu clico no menu "My Module - My Controller - Criar"
      Então eu vejo o título "Criar My Controller - Admin PiberNetwork"
      E eu vejo o título central "Criar My Controller"
      E eu vejo o breadscrumb "My Module / My Controller / Criar"
      E eu vejo o botão de Salvar
      E eu vejo o botão de Voltar
      E eu entro com o valor "2020-12-55" no campo "Date Column"
      E eu entro com o valor "55/12/2020" no campo "Date Pt Br Column"
      E eu entro com o valor "2020-12-55 00:00:02" no campo "Datetime Column"
      E eu entro com o valor "55/12/2020 00:00:02" no campo "Datetime Pt Br Column"
      E eu entro com o valor "00:00:55" no campo "Time Column"
      E eu entro com o valor "55.55" no campo "Decimal Column"
      E eu entro com o valor "R$ 55,55" no campo "Money Pt Br Column"
      E eu entro com o valor "Não" no campo "Checkbox Column"
      E eu entro com o valor "55Foreign Key Column" no campo "Foreign Key Column"
      E eu entro com o valor "55" no campo "Int Column"
      E eu entro com o valor "55Html Column" no campo "Html Column"
      E eu entro com o valor "55Text Column" no campo "Text Column"
      E eu entro com o valor "55" no campo "Tinyint Column"
      E eu entro com o valor "Não" no campo "Checkbox Column"
      E eu entro com o valor "email.column55@gmail.com" no campo "Email Column"
      E eu entro com o valor "(51) 9999-9955" no campo "Telephone Column"
      E eu entro com o valor com a imagem "/upload/table-uploadImageColumn/pre55uploadImageColumn.gif" no campo "Upload Image Column"
      E eu entro com o valor "url.column55.com.br" no campo "Url Column"
      E eu entro com o valor "55Varchar Column" no campo "Varchar Column"
      E eu clico no botão Salvar
      Então eu vejo a mensagem "Sucesso! Os dados foram salvos corretamente."
      E eu vejo o valor "2020-12-55" no campo "Date Column"
      E eu vejo o valor "55/12/2020" no campo "Date Pt Br Column"
      E eu vejo o valor "2020-12-55 00:00:02" no campo "Datetime Column"
      E eu vejo o valor "55/12/2020 00:00:02" no campo "Datetime Pt Br Column"
      E eu vejo o valor "00:00:55" no campo "Time Column"
      E eu vejo o valor "55.55" no campo "Decimal Column"
      E eu vejo o valor "R$ 55,55" no campo "Money Pt Br Column"
      E eu vejo o valor "Não" no campo "Checkbox Column"
      E eu vejo o valor "55Foreign Key Column" no campo "Foreign Key Column"
      E eu vejo o valor "55" no campo "Int Column"
      E eu vejo o valor "55Html Column" no campo "Html Column"
      E eu vejo o valor "55Text Column" no campo "Text Column"
      E eu vejo o valor "55" no campo "Tinyint Column"
      E eu vejo o valor "Não" no campo "Checkbox Column"
      E eu vejo o valor "email.column55@gmail.com" no campo "Email Column"
      E eu vejo o valor "(51) 9999-9955" no campo "Telephone Column"
      E eu vejo o valor com a imagem "/upload/table-uploadImageColumn/pre55uploadImageColumn.gif" no campo "Upload Image Column"
      E eu vejo o valor "url.column55.com.br" no campo "Url Column"
      E eu vejo o valor "55Varchar Column" no campo "Varchar Column"