# language: pt

@my-module @my-controller @my-controller-delete

Funcionalidade: Deletar My Controller existente.

  Como Administrador, quero deletar um My Controller já existente.

    @tearDown @my-controller-fixture
    Cenário: Acesso a página de listar e Deleto My Controller.

      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Listar"
      E eu vejo "10" ítens cadastrados
      E eu vejo o ítem ID "75" na linha "1"
      Quando eu clico no botão Remover do ítem ID "75"
      E eu clico em Deletar
      Então eu vejo a mensagem confirmando "Sucesso! My Controller #75 excluído."
      E eu não vejo o ítem ID "75" na linha "1"
