# language: pt

@my-module @my-controller @my-controller-create

Funcionalidade: Deletar My Controller existente.

  Como Administrador, quero deletar um My Controller já existente.

    @now6
    Cenário: Acesso a página de listar e Deleto My Controller.

    Dado que eu estou logado na página principal
    E eu clico no menu "Administração - My Controller - Listar"
    E eu vejo "30" My Controller cadastrados