# language: pt

@my-module @my-controller @my-controller-edit

Funcionalidade: Editar My Controller existente.

  Como Administrador, quero editar um My Controller já existente.

    Cenário: Acesso a página de Editar My Controller.

    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo o ítem ID "30" na linha "1"
    Quando eu clico no botão Editar no ítem ID "30"
    Então eu vejo o título "Editar My Controller - Admin PiberNetwork"
    E eu vejo o título central "Editar My Controller - 30"
    E eu vejo o breadscrumb "My Module / My Controller / Editar"