# language: pt

@my-module @my-controller @my-controller-edit

Funcionalidade: Editar My Controller existente.

  Como Administrador, quero editar um My Controller já existente.

    @my-controller-fixture @tearDown
    Cenário: Editar My Controller com sucesso.
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Controller - Listar"
      E eu vejo o ítem ID "95" na linha "1"
      E eu clico no botão Editar no ítem ID "95"
      E eu vejo o título "Editar My Controller - Admin PiberNetwork"
      E eu vejo o título central "Editar My Controller - 95"
      E eu vejo o breadscrumb "My Module / My Controller / Editar"
      E eu vejo o valor "2020-12-15" no campo "Date Column"
      E eu vejo o valor "15/12/2020" no campo "Date Pt Br Column"
      E eu vejo o valor "2020-12-15 03:00:02" no campo "Datetime Column"
      E eu vejo o valor "15/12/2020 03:00:02" no campo "Datetime Pt Br Column"
      E eu vejo o valor "03:00:02" no campo "Time Column"
      E eu vejo o valor "75.75" no campo "Decimal Column"
      E eu vejo o valor "R$ 75,75" no campo "Money Pt Br Column"
      E eu vejo marcada a caixa de escolha "Checkbox Column"
      E eu vejo escolhido "15Foreign Key Column" na caixa para selecionar "Foreign Key Column"
      E eu vejo o valor "75" no campo "Int Column"
      E eu vejo texto "75Html Column" no campo html "Html Column"
      E eu vejo texto "75Text Column" no campo "Text Column"
      E eu vejo marcada a caixa de escolha "Tinyint Column"
      E eu vejo marcada a caixa de escolha "Checkbox Column"
      E eu vejo o valor "email.column75@gmail.com" no campo "Email Column"
      E eu vejo o valor "" no campo "Password Verify Column"
      E eu vejo o valor "" no campo "Password Verify Column Verify"
      E eu vejo o valor "(51) 9999-9975" no campo "Telephone Column"
      E eu vejo a imagem "/upload/table-uploadImageColumn/pre75uploadImageColumn.gif" no campo "Upload Image Column"
      E eu vejo o valor "url.column75.com.br" no campo "Url Column"
      E eu vejo o valor "75Varchar Column" no campo "Varchar Column"
