# language: pt

@my-module @my-controller @my-controller-list

Funcionalidade: Listar My Controller cadastrados.

  Como Administrador, quero listar os My Controller cadastrados.

  Cenário: Acesso a página de listar My Controller.

    Dado que eu estou logado na página principal
    Quando eu clico no menu "My Module - My Controller - Listar"
    Então eu vejo o título "Listar My Controller - Admin PiberNetwork"
    E eu vejo o título central "My Controller"
    E eu vejo o breadscrumb "My Module / My Controller / Listar"
    E eu vejo "10" ítens cadastrados
    E eu vejo que está "Mostrando 1 - 10 de 30" na paginação