# language: pt

@my-module @my-controller @my-controller-list

Funcionalidade: Listar My Controller cadastrados.

  Como Administrador, quero listar os My Controller cadastrados.

  Cenário: Acesso a página de listar My Controller.
    Dado que eu estou logado na página principal
    Quando eu clico no menu "My Module - My Controller - Listar"
    Então eu vejo o título "Listar My Controller - Admin PiberNetwork"
    E eu vejo o título central "My Controller"
    E eu vejo o breadscrumb "My Module / My Controller / Listar"
    E eu vejo "10" ítens cadastrados
    E eu vejo que está "Mostrando 1 - 10 de 30" na paginação
    E eu vejo o campo "My Controller" com o valor "30" na linha "1"
    E eu vejo o campo "Date Column" com o valor "2007-06-30" na linha "1"
    E eu vejo o campo "Date Pt Br Column" com o valor "30/06/2007" na linha "1"
    E eu vejo o campo "Datetime Column" com o valor "2007-06-30 06:00:30" na linha "1"
    E eu vejo o campo "Datetime Pt Br Column" com o valor "30/06/2007 06:00:30" na linha "1"
    E eu vejo o campo "Time Column" com o valor "06:00:30" na linha "1"
    E eu vejo o campo "Decimal Column" com o valor "30.30" na linha "1"
    E eu vejo o campo "Money Pt Br Column" com o valor "R$ 30,30" na linha "1"
    E eu vejo o campo "Foreign Key Column" com o valor "30Foreign Key Column" na linha "1"
    E eu vejo o campo "Int Column" com o valor "30" na linha "1"
    E eu vejo o campo "Tinyint Column" com o valor "Não" na linha "1"
    E eu vejo o campo "Email Column" com o valor "email.column30@gmail.com" na linha "1"
    E eu vejo o campo "Telephone Column" com o valor "(51) 9999-9930" na linha "1"
    E eu vejo o campo "Url Column" com o valor "url.column30.com.br" na linha "1"
    E eu vejo o campo "Varchar Column" com o valor "30Varchar Column" na linha "1"
    E eu vejo o botão de Criar
    E eu vejo o botão de Exibir Filtro

  @pagination
  Cenário: Paginar os resultados da listagem
    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo o ítem ID "30" na linha "1"
    E eu vejo o ítem ID "21" na linha "10"
    Quando eu clico na paginação "2"
    Então eu vejo o ítem ID "20" na linha "1"
    E eu vejo o ítem ID "11" na linha "10"

  @filter
  Cenário: Filtrar os resultados da listagem
    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo "10" ítens cadastrados
    E eu vejo que está "Mostrando 1 - 10 de 30" na paginação
    Quando eu clico em Exibir Filtro
    E eu digito "20Varchar Column" no filtro "Palavra Chave"
    Então eu vejo "1" ítens cadastrados
    E eu vejo que está "Mostrando 1 - 1 de 1" na paginação

  @order
  Cenário: Ordenar os resultados da listagem
    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo o ítem ID "30" na linha "1"
    Quando eu clico em ordem na coluna "My Controller"
    Então eu vejo o ítem ID "1" na linha "1"
