# language: pt

@my-module @my-table @my-table-upload-image

Funcionalidade: Visualizar imagens cadastradas em um My Table.

  Como Administrador, quero visualizar as imagens de um My Table.

    Cenário: Acesso a página de Visualizar Imagens em My Table.
      Dado que eu estou logado na página principal
      E eu clico no menu "My Module - My Table - Listar"
      E eu vejo o ítem ID "30" na linha "1"
      Quando eu clico no botão Editar no ítem ID "30"
      E eu clico no botão "Editar Imagens"
      Então eu vejo "3" imagens cadastradas.
