# language: pt

@my-module @my-controller @my-controller-view

Funcionalidade: Visualizar um My Controller cadastrado.

  Como Administrador, quero visualizar os dados de um My Controller cadastrado.

    Cenário: Acesso a página de Visualizar My Controller.

    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo o usuário ID "30" na linha "1"
    Quando eu clico no botão Visualizar no My Controller na linha "1"
    Então eu vejo o título "Visualizar My Controller - Admin PiberNetwork"
    E eu vejo o título central "Visualizar My Controller - 30"
    E eu vejo o breadscrumb "My Module / My Controller / Visualizar"