# language: pt

@my-module @my-controller @my-controller-view

Funcionalidade: Visualizar um My Controller cadastrado.

  Como Administrador, quero visualizar os dados de um My Controller cadastrado.

    Cenário: Acesso a página de Visualizar My Controller.

    Dado que eu estou logado na página principal
    E eu clico no menu "My Module - My Controller - Listar"
    E eu vejo o ítem ID "30" na linha "1"
    Quando eu clico no botão Visualizar no ítem ID "30"
    Então eu vejo o título "Visualizar My Controller - Admin PiberNetwork"
    E eu vejo o título central "Visualizar My Controller - 30"
    E eu vejo o breadscrumb "My Module / My Controller / Visualizar"
    E eu vejo o atributo "Date Column" com o valor "2020-12-30"
    E eu vejo o atributo "Date Pt Br Column" com o valor "30/12/2020"
    E eu vejo o atributo "Datetime Column" com o valor "2020-12-30 00:00:02"
    E eu vejo o atributo "Datetime Pt Br Column" com o valor "30/12/2020 00:00:02"
    E eu vejo o atributo "Time Column" com o valor "00:00:30"
    E eu vejo o atributo "Decimal Column" com o valor "30.30"
    E eu vejo o atributo "Money Pt Br Column" com o valor "R$30,30"
    E eu vejo o atributo "Checkbox Column" com o valor "Não"
    E eu vejo o atributo "Foreign Key Column" com o valor "30foreignKeyColumn"
    E eu vejo o atributo "Int Column" com o valor "30"
    E eu vejo o atributo "Html Column" com o valor "30htmlColumn"
    E eu vejo o atributo "Text Column" com o valor "30textColumn"
    E eu vejo o atributo "Tinyint Column" com o valor "30"
    E eu vejo o atributo "Checkbox Column" com o valor "Não"
    E eu vejo o atributo "Email Column" com o valor "email30@gmail.com"
    E eu vejo o atributo "Telephone Column" com o valor "30 3030-3030"
    E eu vejo o atributo "Upload Image Column" com a imagem "uploadImage.gif"
    E eu vejo o atributo "Url Column" com o valor "http://url.com"
    E eu vejo o atributo "Varchar Column" com o valor "30varchar"