/**
 * @author Maurício Piber Fão
 * @SuppressWarning(PHPMD)
 */
$I = new \FunctionalTester($scenario);
$I->wantTo('See the message of module creation was sucessfull');
$I->amOnPage(\<?php echo $this->module;?>\Pages\ModuleMainPage::$URL);
$I->see(
    '<?php echo $this->moduleLabel;?> module was created sucessfull with Gear Engine Version <?php echo $this->version?>',
    \<?php echo $this->module;?>\Pages\ModuleMainPage::$moduleName
);
