<?php
namespace MyModuleTest\ControllerTest;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase as TestCase;
use MyModule\Controller\BasicFactoryDependenciesAction;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;
use GearBaseTest\Assertions\AclAssertTrait;

/**
 * @group BasicFactoryDependenciesAction
 * @group Controller
 */
class BasicFactoryDependenciesActionTest extends TestCase
{
    use AclAssertTrait;

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp()
    {
        $this->setApplicationConfig(
            include \GearBase\Module::getProjectFolder().'/config/application.config.php'
        );

        parent::setUp();

        $this->myRepositoryOne = $this->prophesize('MyModule\Repository\MyRepositoryOne');
        $this->myRepositoryTwo = $this->prophesize('MyModule\Repository\MyRepositoryTwo');
        $this->myRepositoryThree = $this->prophesize('MyModule\Repository\MyRepositoryThree');

        $this->controller = new BasicFactoryDependenciesAction(
            $this->myRepositoryOne->reveal(),
            $this->myRepositoryTwo->reveal(),
            $this->myRepositoryThree->reveal()
        );

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'BasicFactoryDependenciesAction'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this->schema = (new \MyModule\Module())->getLocation().'/../schema/module.json';
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
