<?php
namespace MyModuleTest\ControllerTest;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;
use MyModule\Controller\BasicFactoryDependenciesAction;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Router\RouteMatch;

/**
 * @group BasicFactoryDependenciesAction
 * @group Controller
 */
class BasicFactoryDependenciesActionTest extends TestCase
{

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp() : void
    {
        parent::setUp();

        $this->myRepositoryOne = $this->prophesize('MyModule\Repository\MyRepositoryOne');
        $this->myRepositoryTwo = $this->prophesize('MyModule\Repository\MyRepositoryTwo');
        $this->myRepositoryThree = $this->prophesize('MyModule\Repository\MyRepositoryThree');

        $this->controller = new BasicFactoryDependenciesAction(
            $this->myRepositoryOne->reveal(),
            $this->myRepositoryTwo->reveal(),
            $this->myRepositoryThree->reveal()
        );

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'BasicFactoryDependenciesAction'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
