<?php
namespace MyModuleTest\FilterTest;

use PHPUnit\Framework\TestCase;
use MyModule\Filter\TableNotNullFilter;

/**
 * @group MyModule
 * @group TableNotNullFilter
 * @group Filter
 */
class TableNotNullFilterTest extends TestCase
{
    public static $validate = 'vendor/zendframework/zend-i18n-resources/languages/pt_BR/Zend_Validate.php';

    public function setUp()
    {
        $this->filter = new TableNotNullFilter();
        $this->filter->setAdapter($this->getAdapterMock());

        $this->translator = new \Zend\I18n\Translator\Translator();
        $this->translator->addTranslationFile(
            'phpArray',
            \GearBase\Module::getProjectFolder().'/'.static::$validate,
            'default',
            'pt_BR'
        )->setLocale('pt_BR');

        $this->translator = new \Zend\Mvc\I18n\Translator($this->translator);
    }


    /**
     * @group MyModule
     * @group TableNotNullFilter
     */
    public function testGetRequiredInvalidPost()
    {
        $inputFilter = $this->filter->getInputFilter();
        $inputFilter->setData(array());
        $this->assertFalse($inputFilter->isValid());
        $this->messages = $inputFilter->getMessages();

        $this->assertMessage(
            'dateColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'datePtBrColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'datetimeColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'datetimePtBrColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'timeColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'decimalColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'moneyPtBrColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'checkboxColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'idForeignKeyColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'intColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'htmlColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'textColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'tinyintColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'checkboxColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'emailColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'passwordVerifyColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'telephoneColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'urlColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );

        $this->assertMessage(
            'varcharColumnNotNull',
            'isEmpty',
            'O valor é obrigatório e não pode estar vazio'
        );
    }

    public function assertMessage($column, $filter, $message)
    {
        $this->assertArrayHasKey($column, $this->messages);
        $this->assertArrayHasKey($filter, $this->messages[$column***REMOVED***);
        $this->assertEquals(
            $message,
            $this->translator->translate($this->messages[$column***REMOVED***[$filter***REMOVED***)
        );
    }
    public function mockUploadImage()
    {
        $maker = new \GearBaseTest\UploadImageMock();
        return $maker->mockUploadFile(\MyModule\Module::getLocation());
    }

    /**
     * @group MyModule
     * @group TableNotNullFilter
     */
    public function testReturnTrueWithValidPost()
    {
        $data = [
            'idMyController' => '99',
            'dateColumnNotNull' => '2007-03-09',
            'datePtBrColumnNotNull' => '09/03/2007',
            'datetimeColumnNotNull' => '2007-03-09 03:00:39',
            'datetimePtBrColumnNotNull' => '09/03/2007 03:00:39',
            'timeColumnNotNull' => '03:00:39',
            'decimalColumnNotNull' => '99.99',
            'moneyPtBrColumnNotNull' => 'R$ 99,99',
            'checkboxColumnNotNull' => 'Sim',
            'idForeignKeyColumnNotNull' => '9Foreign Key Column Not Null',
            'intColumnNotNull' => '99',
            'htmlColumnNotNull' => '99Html Column Not Null',
            'textColumnNotNull' => '99Text Column Not Null',
            'tinyintColumnNotNull' => 'Sim',
            'checkboxColumnNotNull' => 'Sim',
            'emailColumnNotNull' => 'email.column.not.null99@gmail.com',
            'passwordVerifyColumnNotNull' => '99PasswordVerifyColu',
            'passwordVerifyColumnNotNullVerify' => '99PasswordVerifyColu',
            'telephoneColumnNotNull' => '(51) 9999-9999',
            'uniqueIdColumnNotNull' => '99Unique Column Not Null',
            'uploadImageColumnNotNull' => array(
                'error' => 0,
                'name' => 'uploadImageColumnNotNull99insert.gif',
                'tmp_name' => $this->mockUploadImage(),
                'type'      =>  'image/gif',
                'size'      =>  42,
            ),
            'urlColumnNotNull' => 'url.column.not.null99.com.br',
            'varcharColumnNotNull' => '99Varchar Column Not Null',
        ***REMOVED***;

        $inputFilter = $this->filter->getInputFilter();
        $inputFilter->get('uploadImageColumnNotNull')->setAutoPrependUploadValidator(false);
        $inputFilter->setData($data);
        $this->assertTrue($inputFilter->isValid());
    }

    protected function getAdapterMock()
    {
        $adapter = $this->prophesize('Zend\Db\Adapter\Adapter');
        $driver = $this->prophesize('Zend\Db\Adapter\Driver\DriverInterface');

        $platform = $this->prophesize('Zend\Db\Adapter\Platform\Mysql');

        $adapter->getDriver()->willReturn($driver->reveal());
        $adapter->getPlatform()->willReturn($platform->reveal());

        $stmt = $this->prophesize('Zend\Db\Adapter\Driver\Pdo\Statement');

        $driver->createStatement()->willReturn($stmt->reveal());
        $driver->formatParameterName('where1')->willReturn(null);

        $resultSet = $this->prophesize('Zend\Db\ResultSet\ResultSetInterface');
        $resultSet->current()->willReturn(false);

        $paramContainer = $this->prophesize('Zend\Db\Adapter\ParameterContainer');

        $stmt->execute()->willReturn($resultSet->reveal());
        $stmt->getParameterContainer()->willReturn($paramContainer->reveal());
        $stmt->setSql("SELECT  WHERE  =")->willReturn($stmt->reveal());

        return $adapter->reveal();
    }
}
