<?php
namespace SchemaModule\Filter;

use GearBase\Filter\AbstractFilter;

class ColumnsNotNullFilter extends AbstractFilter
{
    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     */
    public function getInputFilter()
    {
        $this->add(
            array(
                'name' => 'columnDateNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnDatetimeNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnTimeNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnIntNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnTinyintNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnDecimalNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnVarcharNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnLongtextNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnTextNotNull',
                'required' => false,
            )
        );
        $this->add(
            array(
                'name' => 'columnDatetimePtBrNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnDatePtBrNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnDecimalPtBrNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnIntCheckboxNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnTinyintCheckboxNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnVarcharEmailNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnVarcharPasswordVerifyNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnVarcharUniqueIdNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'columnVarcharUploadImageNotNull',
                'required' => false,
            )
        );
        $this->add(
            array(
                'name' => 'columnForeignKeyCopyNotNull',
                'required' => true,
            )
        );
        return $this;
    }
}
