return [
    'router' => [
        'routes' => [
            '<?php echo $this->moduleUrl;?>-index' => [
                'options' => [
                    'route' => '<?php echo $this->moduleUrl;?>',
                    'defaults' => [
                        'controller' => '<?php echo $this->module;?>\Controller\IndexController',
                        'action' => 'index'
                    ***REMOVED***
                ***REMOVED***
            ***REMOVED***,

        ***REMOVED***
    ***REMOVED***
***REMOVED***;
