{
    "name" : "mauriciopiber/<?php echo $this->moduleUrl;?>",
    "require" : {
<?php echo $this->require;?>
    },
    "require-dev" : {
<?php echo $this->requireDev;?>
    },
    "autoload" : {
        "psr-4" : {
            "<?php echo $this->module;?>\\" : "src"
        }
    },
    "autoload-dev" : {
        "psr-4" : {
            "<?php echo $this->module;?>\\Test\\" : "test/unit"
        }
    },
    "config": {
        "secure-http": false
    },
    "repositories" : [
        {
            "type" : "composer",
            "url" : "http://satis"
        },
        { "packagist" : false }
    ***REMOVED***
}
