{
    "name" : "mauriciopiber/<?php echo $this->moduleUrl;?>",
    "require" : {
<?php echo $this->require;?>
    },
    "require-dev" : {
<?php echo $this->requireDev;?>
    },
    "autoload" : {
        "psr-4" : {
            "<?php echo $this->namespace;?>" : "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "<?php echo $this->namespaceTest;?>" : "test/unit"
        }
    },
    "repositories" : [
        {
            "type" : "composer",
            "url" : "https://mirror.piber.network"
        },
        { "packagist" : false }
    ***REMOVED***
}
