module.exports = function(config) {
  config.set({
    basePath: '',
    frameworks: ['jasmine'***REMOVED***,
    files: [
      '../../../vendor/mauriciopiber/gear-admin/public/dist/internal.js',
      '../app/**/*.js',
      'unit/**/*Spec.js'
    ***REMOVED***,
    exclude: [
    ***REMOVED***,
    preprocessors : {
        '../app/**/*.js': 'coverage'
    },
    coverageReporter : {
        type : 'html',
        dir : '../../../build/coverage-js/'
    },
    port: 9876,
    colors: true,
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['PhantomJS'***REMOVED***,
    singleRun : true,
    reporters : ['progress', 'dots', 'junit', 'coverage'***REMOVED***,
    junitReporter : {
      outputDir : '../../../build',
      outputFile: 'karma-results.xml'
    }
  })
}
