paths:
    migrations: %%PHINX_CONFIG_DIR%%/{data/migrations,vendor/mauriciopiber/**/migrations,,vendor/mauriciopiber/**/data/migrations}
environments:
    default_migration_table: migrations
    default_database: development
    development:
        adapter: mysql
        host: localhost
        name: <?php echo $this->module.PHP_EOL;?>
        user: root
        pass: gear
        port: 3306
        charset: utf8
    testing:
        adapter: mysql
        host: localhost
        name: <?php echo $this->module.PHP_EOL;?>
        user: root
        pass: gear
        port: 3306
        charset: utf8
