paths:
    migrations: '%%PHINX_CONFIG_DIR%%/{data/migrations,vendor/mauriciopiber/**/migrations,,vendor/mauriciopiber/**/data/migrations}'
environments:
    default_migration_table: migrations
    default_database: DEVELOPMENT
    DEVELOPMENT:
        adapter: mysql
        host: mysql
        name: <?php echo $this->module.PHP_EOL;?>
        user: root
        pass: gear
        port: 3306
        charset: utf8
    TESTING:
        adapter: mysql
        host: mysql
        name: <?php echo $this->module.PHP_EOL;?>
        user: root
        pass: gear
        port: 3306
        charset: utf8
    STAGING:
        adapter: mysql
        host: mysql
        name: <?php echo $this->module.PHP_EOL;?>
        user: root
        pass: gear
        port: 3306
        charset: utf8
