var HtmlScreenshotReporter = require('protractor-jasmine2-screenshot-reporter');

exports.config = {
  directConnect: true,
  capabilities: {
      'browserName': 'chrome'
  },
  rootElement: '[ng-app***REMOVED***',
  baseUrl:	'http://<?php echo $this->moduleUrl;?>.gear.dev',
  framework: 'custom',
  frameworkPath: require.resolve('protractor-cucumber-framework'),
  specs: [
      'e2e/**/*.feature',
  ***REMOVED***,
  cucumberOpts: {
    require: [
        '../../../vendor/mauriciopiber/gear-admin/public/js/spec/e2e/support/env/env.js',
        '../../../vendor/mauriciopiber/gear-admin/public/js/spec/e2e/support/**/*.stepDefinitions.js',
        '../../../vendor/mauriciopiber/gear-admin/public/js/spec/e2e/support/*.stepDefinitions.js',
        '../../../vendor/mauriciopiber/gear-admin/public/js/spec/e2e/support/helper/admin.js',
        'e2e/**/*.stepDefinitions.js',
        'e2e/support/*.js',
    ***REMOVED***,
    format: 'pretty',
    profile: false,
    'no-source': true
  },
  onPrepare: function() {
	  'use strict';

      require('protractor-http-mock').config = {
	        rootDirectory: __dirname, // default value: process.cwd()
	        protractorConfig: 'end2end.conf.js' // default value: 'protractor.conf'
	  };
  },
};
