namespace <?php echo $this->namespace;?>\Controller;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use <?php echo $this->namespace;?>\Controller\IndexController;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package <?php echo $this->module;?>/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class IndexControllerFactory implements FactoryInterface
{
    /**
     * Create Index Controller
     *
     * @param ServiceLocatorInterface $controllerManager Controller Manager
     *
     * @return IndexController
     */
    public function createService(ServiceLocatorInterface $controllerManager)
    {
        unset($controllerManager);
        $indexController = new IndexController();
        return $indexController;
    }
}
