<tr>
            <td>
                <?php echo $this->escapeHtml($this->idEmail); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->remetente); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->destino); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->assunto); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->mensagem); ?>
            </td>
        <td>
        <a href="<?php echo $this->url('teste/email/view', array('id' => $this->idEmail)); ?>">
            <span class="glyphicon glyphicon-resize-full"></span>
        </a>
        <a href="<?php echo $this->url('teste/email/edit', array('id' => $this->idEmail)); ?>">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('teste/email/delete', array('id' => $this->idEmail)); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Email" data-message="<?php echo $this->translate('Desejas realmente deletar Email?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>