<div class="row">
	<div class="col-lg-12">
        <h3 id="pageTitle"><?php echo $this->translate('View');?>&nbsp;<?php echo $this->translate('Email');?> - <?php echo $this->id;?></h3>
	</div>
</div>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <div class="form-group">
            <table id="viewData" class="viewData">
                <tbody>
                        <tr><td><?php echo $this->translate('ID');?></td><td><?php echo $this->escapeHtml($this->idEmail);?></td></tr>
                        <tr><td><?php echo $this->translate('Remetente');?></td><td><?php echo $this->escapeHtml($this->remetente);?></td></tr>
                        <tr><td><?php echo $this->translate('Destino');?></td><td><?php echo $this->escapeHtml($this->destino);?></td></tr>
                        <tr><td><?php echo $this->translate('Assunto');?></td><td><?php echo $this->escapeHtml($this->assunto);?></td></tr>
                        <tr><td><?php echo $this->translate('Mensagem');?></td><td><?php echo $this->escapeHtml($this->mensagem);?></td></tr>
                    </tbody>
            </table>
        </div>
        <div class="form-group">
            <a id="btnBack" class="btn btn-default" href="<?php echo $this->url('teste/email/list');?>"><?php echo $this->translate('Back');?></a>
            <a id="btnPrev" class="btn btn-default" href="<?php echo $this->url('teste/email/view', array('id' => $this->id-1));?>"><?php echo $this->translate('Prev');?></a>
            <a id="btnNext" class="btn btn-default" href="<?php echo $this->url('teste/email/view', array('id' => $this->id+1));?>"><?php echo $this->translate('Next');?></a>
            <a id="btnEdit" class="btn btn-default" href="<?php echo $this->url('teste/email/edit', array('id' => $this->id));?>"><?php echo $this->translate('Edit');?></a>
            <a id="btnDelete" class="btn btn-default" href="<?php echo $this->url('teste/email/delete', array('id' => $this->id));?>"><?php echo $this->translate('Delete');?></a>
            <a id="btnCreate" class="btn btn-primary" href="<?php echo $this->url('teste/email/create');?>"><?php echo $this->translate('New');?></a>
        </div>
    </div>
</div>