        $this->repository = new <?php echo $this->className;?>();
        $this->entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->repository->setEntityManager($this->entityManager->reveal());
        $this->entityRepository = $this->prophesize('Doctrine\ORM\EntityRepository');
        $this->repository->setRepository($this->entityRepository->reveal());
        $this->queryBuilder = $this->prophesize('GearBase\Repository\QueryBuilder');
        $this->repository->setQueryBuilder($this->queryBuilder->reveal());
