return array(
    'default_role' => 'guest',
    'authenticated_role' => 'admin',
    'identity_provider' => 'BjyAuthorize\Provider\Identity\AuthenticationIdentityProvider',
    'role_providers' => array(
        'BjyAuthorize\Provider\Role\ObjectRepositoryProvider' => array(
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'role_entity_class' => 'GearAdmin\Entity\Role'
        ),
    'BjyAuthorize\Provider\Role\Config' => array(
        'guest' => array(
            'children' => array(
                'admin' => array(),
                'cliente' => array()
            )
        ),
            'admin' => array()
        )
    ),
    'resource_providers' => array(),
    'rule_providers' => array(),
    'guards' => array(
        'doctrine_controler_guard' => array(
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'rule_entity_class' => 'GearAdmin\Entity\Rule'
        )
    ),
    'unauthorized_strategy' => 'BjyAuthorize\View\UnauthorizedStrategy',
    'template' => 'error/403',
    'cache_options' => array(
        'adapter' => array(
            'name' => 'memory'
        ),
        'plugins' => array(
            'serializer'
        )
    ),
    'cache_key' => 'bjyauthorize_acl'
);
