<?php
namespace MyModule\Filter;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Filter\MyTableFilter;
use Zend\Db\Adapter\Adapter;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Filter
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableFilterFactory implements FactoryInterface
{
    /**
     * Create MyTableFilter
     *
     * @param ContainerInterface $container ServiceManager instance
     *
     * @return MyTableFilter
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        $factory = new MyTableFilter(
            $container->get(Adapter::class),
            $container->get('translate')
        );

        return $factory;
    }
}
