<?php
namespace MyModule\Filter;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Filter\MyTableFilter;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Filter
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MyTableFilterFactory implements FactoryInterface
{
    /**
     * Create MyTableFilter
     *
     * @param ServiceLocatorInterface $serviceLocator ServiceManager instance
     * @return \MyModule\Filter\MyTableFilter
     */
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $factory = new MyTableFilter(
            $serviceLocator->get('Zend\Db\Adapter\Adapter')
        );
        unset($serviceLocator);
        return $factory;
    }
}
