namespace <?php echo $this->module;?>\<?= $this->srcType;?>;

use <?php echo $this->module;?>\<?= $this->srcType;?>\<?= $this->srcName;?>;

trait <?= $this->srcName;?>Trait {

    protected $<?= $this->var;?>;

    public function get<?= $this->srcName;?>()
    {
        if (!isset($this-><?= $this->var;?>)) {
            $this-><?= $this->var;?> = $this->getServiceLocator()->get('<?= $this->serviceManager;?>');
        }
        return $this-><?= $this->var;?>;
    }

    public function set<?= $this->srcName;?>(<?= $this->srcName;?> $<?= $this->var;?>)
    {
        $this-><?= $this->var;?> = $<?= $this->var;?>;
        return $this;
    }
}
