namespace <?php echo $this->module;?>\<?= $this->srcType;?>;

use <?php echo $this->module;?>\<?= $this->srcType;?>\<?= $this->srcName;?>;

trait <?= $this->srcName;?>Trait
{
    protected $<?= $this->var;?>;

    public function get<?= $this->srcName;?>()
    {
        if (!isset($this-><?= $this->var;?>)) {
            $serviceName = '<?= $this->serviceManager;?>';
            $this-><?= $this->var;?> = $this->getServiceLocator()->get($serviceName);
        }
        return $this-><?= $this->var;?>;
    }

    public function set<?= $this->srcName;?>(<?= $this->srcName;?> $<?= $this->lenght;?>)
    {
        $this-><?= $this->var;?> = $<?= $this->lenght;?>;
        return $this;
    }
}
