namespace <?php echo $this->module;?>Test\<?php echo $this->namespace;?>;

use PHPUnit_Framework_TestCase as TestCase;
use <?php echo $this->module;?>\<?php echo $this->testNamespace;?>\<?php echo $this->class;?>;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group SearchForm
 */
class <?php echo $this->class;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->search = new <?php echo $this->class;?>($entityManager->reveal());
    }

    public function testHasColumn()
    {
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('likeField'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('clear'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('submit'));
    }
}
