namespace <?php echo $this->module;?>Test\FormTest\SearchTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group SearchForm
 */
class <?php echo $this->class;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->search = new \<?php echo $this->module;?>\Form\Search\<?php echo $this->class;?>($entityManager->reveal());
    }

    public function testHasColumn()
    {
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('likeField'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('clear'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('submit'));
    }
}
