<?php return [
    'default' => [
        [
            'label' => 'My Module',
            'route' => 'my-module',
            'pages' => [
                [
                    'label' => 'Index',
                    'route' => 'my-module'
                ***REMOVED***,
                [
                    'label' => 'Table',
                    'route' => 'my-module/table',
                    'pages' => [
                        [
                            'label' => 'Create',
                            'route' => 'my-module/table/create'
                        ***REMOVED***,
                        [
                            'label' => 'Edit',
                            'show_in_menu' => false,
                            'route' => 'my-module/table/edit'
                        ***REMOVED***,
                        [
                            'label' => 'List',
                            'route' => 'my-module/table/list'
                        ***REMOVED***,
                        [
                            'label' => 'Delete',
                            'show_in_menu' => false,
                            'route' => 'my-module/table/delete'
                        ***REMOVED***,
                        [
                            'label' => 'View',
                            'show_in_menu' => false,
                            'route' => 'my-module/table/view'
                        ***REMOVED***
                    ***REMOVED***
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***
***REMOVED***;
