<?php return [
    'default' => [
        [
            'label' => 'My Module',
            'route' => 'my-module',
            'pages' => [
                [
                    'label' => 'Index',
                    'route' => 'my-module'
                ***REMOVED***,
                [
                    'label' => 'My',
                    'route' => 'my-module/my',
                    'pages' => [
                        [
                            'label' => 'My Action',
                            'route' => 'my-module/my/my-action'
                        ***REMOVED***
                    ***REMOVED***
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***
***REMOVED***;
