(function(){
    'use strict';

    angular.module('GearApp').controller('<?=$this->controller;?>ListController', <?=$this->controller;?>ListController);

    function <?=$this->controller;?>ListController() {

        var vm = this;

        vm.textFilter = 'Exibir Filtro';
        vm.showFilter   = false;
       	vm.toggleFilter = toggleFilter;

       	function toggleFilter()
    	{
       		vm.showFilter = !vm.showFilter;
       		vm.textFilter = (vm.showFilter) ? 'Esconder Filtro' : 'Exibir Filtro';
    	}

    }

}());
