(function(){
    'use strict';

    angular.module('GearApp').controller('<?=$this->controller?>ListController', <?=$this->controller?>ListController);

    function <?=$this->controller?>ListController() {

        var vm = this;
        vm.test = myController;
        vm.test();

        function myController()
        {
            console.log('<?=$this->controller?>ListController');
        }

    }

}());
