<?php echo sprintf('<?php $this->headTitle()->prepend(\'Criar %s\');?>', $this->label).PHP_EOL;?>
<div ng-controller="<?php echo $this->class;?>CreateController as create">
    <div class="row">
    	<div class="col-lg-12">
            <h3 class="page-header"><?php echo '<?php echo $this->translate(\'Create\');?>&nbsp;';?><?php echo sprintf('<?php echo $this->translate(\'%s\');?>', $this->label);?></h3>
    	</div>
    </div>
<?php echo '    <?php if($this->error) : echo $this->render(\'layout/error\'); endif; ?>'.PHP_EOL ;?>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
<?php
$link = sprintf('%s', $this->route, $this->class, $this->class);
echo <<<EOS
            <?php
                \$form = \$this->form;
                \$form->setAttribute('action', \$this->url('{$link}'));
                \$form->prepare();
                echo \$this->form()->openTag(\$form);
            ?>

EOS;
?>
<?php echo $this->formElements;?>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <?php echo '<?php
                                echo $this->formSubmit(
                                    $form->get(\'submit\')->setAttribute(\'class\', \'btn btn-default\')->setAttribute(\'id\', \'btn-save\')
                                );
                            ?>'.PHP_EOL; ?>
                            <a id="btn-back" class="btn btn-default reset" href="<?php echo sprintf('<?php echo $this->url(\'%s\');?>', $this->routeBack);?>">Voltar</a>
                        </div>
                    </div>
                </div>
            <?php echo '<?php echo $this->form()->closeTag(); ?>'.PHP_EOL; ?>
        </div>
    </div>
</div>
