<?php $partial = array('layout/breadscrumb', 'default') ?>
<?php $this->navigation('navigation')->breadcrumbs()->setPartial($partial); ?>
<?php $this->navigation('navigation')->setTranslator();?>
<?php echo $this->doctype(); ?>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- Bootstrap Core CSS -->
        <link href="/sb-admin-2/css/bootstrap.min.css" rel="stylesheet">
        <!-- MetisMenu CSS -->
        <link href="/sb-admin-2/css/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
        <!-- Timeline CSS -->
        <link href="/sb-admin-2/css/plugins/timeline.css" rel="stylesheet">
        <!-- Custom CSS -->
        <link href="/sb-admin-2/css/sb-admin-2.css" rel="stylesheet">
        <!-- Morris Charts CSS -->
        <link href="/sb-admin-2/css/plugins/morris.css" rel="stylesheet">
        <!-- Custom Fonts -->
        <link href="/sb-admin-2/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9***REMOVED***>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif***REMOVED***-->

        <?php echo $this->headTitle($this->translate('Security'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath() . '/css/style.css')
            ->prependStylesheet($this->basePath() . '/bower_components/jquery-ui/themes/base/jquery-ui.css')
            ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/engine.js')
            ->prependFile($this->basePath() . '/bower_components/jquery.validation/dist/jquery.validate.min.js')
            ->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/bower_components/jquery-ui/ui/jquery-ui.js')
            ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js')
            ?>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-sm-9">
    			    <div class="row">
                        <div class="col-lg-12">
                            <div class="pull-left">
                                <?php echo $this->navigation('navigation')->breadcrumbs()->render(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <div class="footer">
            <div class="container">
                <p class="text-muted">Criado por <a href="http://www.pibernetwork.com.br" alt="Piber Network">Piber Network</a></p>
                <p class="text-muted">
                    Gerado por <a href="http://gear.pibernetwork.com.br" alt="Gear Engine">Gear</a>
                    <a href="http://gear.pibernetwork.com.br/novidades/0.1.0"> 0.1.0</a>
                </p>
            </div>
        </div>
        <!-- jQuery Version 1.11.0 -->
        <script src="/sb-admin-2/js/jquery-1.11.0.js"></script>
        <!-- Bootstrap Core JavaScript -->
        <script src="/sb-admin-2/js/bootstrap.min.js"></script>
        <!-- Metis Menu Plugin JavaScript -->
        <script src="/sb-admin-2/js/plugins/metisMenu/metisMenu.min.js"></script>
        <!-- Custom Theme JavaScript -->
        <script src="/sb-admin-2/js/sb-admin-2.js"></script>
    </body>
</html>