<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle"><?php echo $this->translate('Edit');?>&nbsp;<?php echo $this->translate('Email');?> - <?php echo $this->idEmail;?></h3>
	</div>
</div>
<?php if($this->success) :?>
<?php echo $this->render('layout/success');?>
<?php endif;?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('teste/email/edit', array('id' => $this->idEmail)));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <?php echo $this->formHidden($form->get('idEmail')->setAttribute('class','form-control')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idEmail'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('remetente'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('destino'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('assunto'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('mensagem'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default" href="<?php echo $this->url('teste/email/view', array('id' => $this->idEmail));?>"><?php echo $this->translate('View');?></a>
            <a class="btn btn-primary" href="<?php echo $this->url('teste/email/create');?>"><?php echo $this->translate('Create');?></a>
            <a class="btn btn-default reset" href="<?php echo $this->url('teste/email/list');?>"><?php echo $this->translate('Back');?></a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>