namespace <?php echo $this->module;?>;

$db                 = require 'ext/db.config.php';
$translator         = require 'ext/translator.config.php';
$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$controllerPlugins  = require 'ext/controller.plugin.config.php';
$cache              = require 'ext/cache.config.php';
$console            = require 'ext/console.route.config.php';
$fixture            = array(
    __NAMESPACE__.'_fixture' => __DIR__ . '/../src/Fixture'
);
$gear = [
    'modules' => [
        '<?php echo $this->moduleUrl;?>' => [
            'version' => '0.1.0',
            'acl' => true,
            'name' => __NAMESPACE__,
            'git' => 'git@bitbucket.org:mauriciopiber/<?php echo $this->moduleUrl;?>.git'
        ***REMOVED***
    ***REMOVED***
***REMOVED***;

return [
    'bjyauthorize' => [
        'acl_key' => __NAMESPACE__
    ***REMOVED***,
    'session_config' => [
        'save_path' => __DIR__.'/../data/session'
    ***REMOVED***,
    'gear'               => $gear,
    'db'                 => $db,
    'console'            => $console,
    'translator'         => $translator,
    'controllers'        => $controller,
    'service_manager'    => $servicemanager,
    'controller_plugins' => $controllerPlugins,
    'data-fixture'       => $fixture,
***REMOVED***;
