namespace <?php echo $this->module;?>;

$servicemanager     = require 'ext/servicemanager.config.php';
$controller         = require 'ext/controller.config.php';
$controllerPlugins  = require 'ext/controller.plugin.config.php';
$console            = require 'ext/console.route.config.php';

return [
    'console'            => $console,
    'controllers'        => $controller,
    'service_manager'    => $servicemanager,
    'controller_plugins' => $controllerPlugins,
***REMOVED***;
