<?php
namespace MyModuleTest\FormTest;

use PHPUnit\Framework\TestCase;
use MyModule\Form\MyFormFactory;

/**
 * @group MyModule
 * @group MyForm
 * @group Form
 */
class MyFormFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->container    = $this->prophesize('Zend\ServiceManager\ContainerInterface');

        $this->container->get('MyModule\Repository\MyDependencyOne')
            ->willReturn($this->prophesize('MyModule\Repository\MyDependencyOne')->reveal())
            ->shouldBeCalled();

        $this->container->get('MyModule\Service\MyDependencyTwo')
            ->willReturn($this->prophesize('MyModule\Service\MyDependencyTwo')->reveal())
            ->shouldBeCalled();

        $factory = new MyFormFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf('MyModule\Form\MyForm', $instance);
    }
}
