<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use MyModule\Controller\MyControllerFactory;

/**
 * @group MyModule
 * @group MyController
 * @group Controller
 */
class MyControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $this->serviceLocator = $this->prophesize('Zend\ServiceManager\ServiceManager');
        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal());

        $factory = new MyControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('MyModule\Controller\MyController', $instance);
    }
}
