<?php
namespace MyModuleTest\ControllerTest;

use GearBaseTest\AbstractTestCase;

/**
 * @group MyModule
 * @group MyController
 * @group Controller
 */
class MyControllerFactoryTest extends AbstractTestCase
{
    public function testCreateFactory()
    {
        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $factory = new \MyModule\Controller\MyControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('MyModule\Controller\MyController', $instance);
    }
}
