<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use MyModule\Controller\MyControllerFactory;

/**
 * @group MyModule
 * @group MyController
 * @group Controller
 */
class MyControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->container = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $this->container = $this->prophesize('Zend\ServiceManager\ServiceManager');


        $factory = new MyControllerFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf('MyModule\Controller\MyController', $instance);
    }
}
