<?php
namespace MyModuleTest\ServiceTest;

use PHPUnit\Framework\TestCase;
use MyModule\Service\MyServiceFactory;

/**
 * @group MyModule
 * @group MyService
 * @group Service
 */
class MyServiceFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->container    = $this->prophesize('Zend\ServiceManager\ContainerInterface');

        $factory = new MyServiceFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf('MyModule\Service\MyService', $instance);
    }
}
