<?php
namespace MyModuleTest\ServiceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Service\MyServiceFactory;

/**
 * @group MyModule
 * @group MyService
 * @group Service
 */
class MyServiceFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $factory = new MyServiceFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Service\MyService', $instance);
    }
}
