<?php
namespace MyModuleTest\ServiceTest;

use GearBaseTest\AbstractTestCase;

/**
 * @group MyModule
 * @group MyService
 * @group Service
 */
class MyServiceFactoryTest extends AbstractTestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $factory = new \MyModule\Service\MyServiceFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Service\MyService', $instance);
    }
}
