namespace <?php echo $this->namespace;?>;

<?php echo $this->use;?>
use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;

class <?php echo $this->controllerName;?> extends <?php echo $this->extends.PHP_EOL;?>
{
<?php foreach ($this->actions as $i => $action) : ?>
    public function <?php echo $this->str('var', $action->getName());?>Action()
    {
        return new ViewModel(
            array(
            )
        );
    }<?php echo ($i < count($this->actions)-1) ? PHP_EOL : '';; endforeach; echo PHP_EOL;?>
}
