namespace <?php echo $this->namespace;?>;

use Zend\View\Model\ViewModel;
use Zend\View\Model\JsonModel;
<?php echo $this->use;?>
<?php echo $this->classDocs;?>
class <?php echo $this->controllerName;?> extends <?php echo $this->extends.PHP_EOL;?>
{
<?php echo ($this->attribute) ? $this->attribute : '';?>
<?php echo ($this->constructor) ? $this->constructor : '';?>
<?php echo (empty($this->attribute) && empty($this->constructor)) ? PHP_EOL : '';?>
}
