
    public function test<?php echo $this->actionName;?>Action()
    {
        $this->routeMatch->setParam('action', '<?php echo $this->actionNameUrl;?>');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }
