namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use <?php echo $this->module?>Test\ControllerTest\AbstractControllerTestCase;

/**
 * @group Controller
 */
class <?php echo $this->controllerName; ?>Test extends AbstractControllerTestCase
{
    public function setUp()
    {
        parent::setUp();
        $this-><?php echo $this->controllerVar;?> = new \<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->controllerName;?>();
    }
}
