
    /**
     * @depends testCreateSuccess
     */
    public function testWhenListRedirectSuccessfulPRGWithValidIdReturnValidation($resultSet)
    {
        $this->mockUser();
<?php echo $this->postRedirectGet;?>
        $this->dispatch('/<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl;?>/editar/'.$resultSet->getId<?php echo $this->class;?>(), 'POST', array());
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('<?php echo $this->module;?>');
        $this->assertControllerName('<?php echo $this->module;?>\Controller\<?php echo $this->class;?>');
        $this->assertActionName('edit');
        $this->assertControllerClass('<?php echo $this->class;?>Controller');
        $this->assertMatchedRouteName('<?php echo $this->moduleUrl;?>/<?php echo $this->classUrl;?>/edit');
    }
