namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use <?php echo $this->module?>Test\ControllerTest\AbstractControllerTestCase;
use <?php echo $this->module?>\<?php echo $this->namespace;?>\<?php echo $this->controllerName;?>;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;

/**
 * @group <?php echo $this->controllerName.PHP_EOL; ?>
 * @group Controller
 */
class <?php echo $this->controllerName; ?>Test extends AbstractControllerTestCase
{
    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp()
    {
        parent::setUp();

        $this->controller = new <?php echo $this->controllerName;?>();
        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => '<?php echo $this->controllerName;?>'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
