<tr>
            <td>
                <?php echo $this->escapeHtml($this->object->getIdPais()); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getNome()); ?>
            </td>
    <td>
        <a href="<?php echo $this->url('test-until/pais/edit', array('id' => $this->object->getIdPais())); ?>">
            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('test-until/pais/delete', array('id' => $this->object->getIdPais())); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Pais" data-message="<?php echo $this->translate('Desejas realmente deletar Pais?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>