<?php
namespace GearItTest\ServiceTest;

use PHPUnit_Framework_TestCase as TestCase;
use GearIt\Service\MyServiceTrait;

/**
 * @group GearIt
 * @group MyService
 * @group Service
 */
class MyServiceTraitTest extends TestCase
{
    use MyServiceTrait;

    public function setUp()
    {
        $this->myService = $this->prophesize('GearIt\Service\MyService');
    }

    public function testGetEmpty()
    {
        $myService = $this->getMyService();
        $this->assertNull($myService);
    }

    public function testSet()
    {
        $this->setMyService($this->myService->reveal());
        $myService = $this->getMyService();

        $this->assertInstanceOf(
            'GearIt\Service\MyService',
            $myService
        );

        $this->assertEquals(
            $this->myService->reveal(),
            $myService
        );
    }
}
