<?php
namespace GearItTest\ServiceTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\ServiceManager\ServiceLocatorAwareTrait;
use Zend\ServiceManager\ServiceManager;
use GearIt\Service\MyServiceTrait;

/**
 * @group GearIt
 * @group MyService
 * @group Service
 */
class MyServiceTraitTest extends TestCase
{
    use ServiceLocatorAwareTrait;

    use MyServiceTrait;

    public function setUp()
    {
        $serviceManager = new ServiceManager();
        $this->mocking = $this->prophesize('GearIt\Service\MyService');
        $serviceManager->setService('GearIt\Service\MyService', $this->mocking->reveal());
        $this->setServiceLocator($serviceManager);
    }

    public function testGet()
    {
        $serviceLocator = $this->getMyService();
        $this->assertInstanceOf('GearIt\Service\MyService', $serviceLocator);
    }

    public function testSet()
    {
        $mocking = $this->prophesize('GearIt\Service\MyService')->reveal();
        $this->setMyService($mocking);
        $this->assertEquals($mocking, $this->getMyService());
    }
}
