<?php
namespace MyModule\Repository;

use MyModule\Repository\MyTrait;

/**
 * PHP Version 5
 *
 * @category Repository
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
trait MyTraitTrait
{
    protected $myTrait;

    /**
     * Get My Trait
     *
     * @return MyTrait
     */
    public function getMyTrait()
    {
        return $this->myTrait;
    }

    /**
     * Set My Trait
     *
     * @param MyTrait $myTrait My Trait
     *
     * @return MyTrait
     */
    public function setMyTrait(
        MyTrait $myTrait
    ) {
        $this->myTrait = $myTrait;
        return $this;
    }
}
