<?php
namespace SchemaModule\SchemaModuleTest\EntityTest;

use GearBaseTest\AbstractTestCase;

/**
 * @group Entity
 */
class ColumnsTest extends AbstractTestCase
{
    protected $columns;

    public function getColumns()
    {
        if (!isset($this->columns)) {
            $this->columns = $this->bootstrap->getServiceLocator()->get(
                'SchemaModule\Entity\Columns'
            );
        }
        return $this->columns;
    }

    /**
     * @group SchemaModule
     * @group Columns
     */
    public function testCallUsingServiceLocator()
    {
        $columns = $this->getColumns();
        $this->assertInstanceOf('SchemaModule\Entity\Columns', $columns);
    }


    public function testGetterInitiateByNull()
    {
        $entity = $this->getColumns();
        $this->assertNull($entity->getIdColumns());
        $this->assertNull($entity->getColumnDate());
        $this->assertNull($entity->getColumnDatetime());
        $this->assertNull($entity->getColumnTime());
        $this->assertNull($entity->getColumnInt());
        $this->assertNull($entity->getColumnTinyint());
        $this->assertNull($entity->getColumnDecimal());
        $this->assertNull($entity->getColumnVarchar());
        $this->assertNull($entity->getColumnLongtext());
        $this->assertNull($entity->getColumnText());
        $this->assertNull($entity->getCreated());
        $this->assertNull($entity->getUpdated());
        $this->assertNull($entity->getCreatedBy());
        $this->assertNull($entity->getUpdatedBy());
        $this->assertNull($entity->getColumnDatetimePtBr());
        $this->assertNull($entity->getColumnDatePtBr());
        $this->assertNull($entity->getColumnDecimalPtBr());
        $this->assertNull($entity->getColumnIntCheckbox());
        $this->assertNull($entity->getColumnTinyintCheckbox());
        $this->assertNull($entity->getColumnVarcharEmail());
        $this->assertNull($entity->getColumnVarcharPasswordVerify());
        $this->assertNull($entity->getColumnVarcharUniqueId());
        $this->assertNull($entity->getColumnVarcharUploadImage());
        $this->assertNull($entity->getColumnForeignKey());
    }

    /**
     * @SuppressWarnings(PHPMD.ExcessiveParameterList)
     * @dataProvider getProvider
     */
    public function testSetterAndGet(
        $columnDate,
        $columnDatetime,
        $columnTime,
        $columnInt,
        $columnTinyint,
        $columnDecimal,
        $columnVarchar,
        $columnLongtext,
        $columnText,
        $created,
        $updated,
        $createdBy,
        $updatedBy,
        $columnDatetimePtBr,
        $columnDatePtBr,
        $columnDecimalPtBr,
        $columnIntCheckbox,
        $columnTinyint,
        $columnVarcharEmail,
        $columnVarcharVerify,
        $columnVarcharUnique,
        $columnVarcharUpload,
        $columnForeignKey
    ) {
        $entity = $this->getColumns();
        $entity->setColumnDate($columnDate);
        $this->assertEquals($columnDate, $entity->getColumnDate());

        $entity->setColumnDatetime($columnDatetime);
        $this->assertEquals($columnDatetime, $entity->getColumnDatetime());

        $entity->setColumnTime($columnTime);
        $this->assertEquals($columnTime, $entity->getColumnTime());

        $entity->setColumnInt($columnInt);
        $this->assertEquals($columnInt, $entity->getColumnInt());

        $entity->setColumnTinyint($columnTinyint);
        $this->assertEquals($columnTinyint, $entity->getColumnTinyint());

        $entity->setColumnDecimal($columnDecimal);
        $this->assertEquals($columnDecimal, $entity->getColumnDecimal());

        $entity->setColumnVarchar($columnVarchar);
        $this->assertEquals($columnVarchar, $entity->getColumnVarchar());

        $entity->setColumnLongtext($columnLongtext);
        $this->assertEquals($columnLongtext, $entity->getColumnLongtext());

        $entity->setColumnText($columnText);
        $this->assertEquals($columnText, $entity->getColumnText());

        $entity->setCreated($created);
        $this->assertEquals($created, $entity->getCreated());

        $entity->setUpdated($updated);
        $this->assertEquals($updated, $entity->getUpdated());

        $entity->setCreatedBy($createdBy);
        $this->assertEquals($createdBy, $entity->getCreatedBy());

        $entity->setUpdatedBy($updatedBy);
        $this->assertEquals($updatedBy, $entity->getUpdatedBy());

        $entity->setColumnDatetimePtBr($columnDatetimePtBr);
        $this->assertEquals($columnDatetimePtBr, $entity->getColumnDatetimePtBr());

        $entity->setColumnDatePtBr($columnDatePtBr);
        $this->assertEquals($columnDatePtBr, $entity->getColumnDatePtBr());

        $entity->setColumnDecimalPtBr($columnDecimalPtBr);
        $this->assertEquals($columnDecimalPtBr, $entity->getColumnDecimalPtBr());

        $entity->setColumnIntCheckbox($columnIntCheckbox);
        $this->assertEquals($columnIntCheckbox, $entity->getColumnIntCheckbox());

        $entity->setColumnTinyintCheckbox($columnTinyint);
        $this->assertEquals($columnTinyint, $entity->getColumnTinyintCheckbox());

        $entity->setColumnVarcharEmail($columnVarcharEmail);
        $this->assertEquals($columnVarcharEmail, $entity->getColumnVarcharEmail());

        $entity->setColumnVarcharPasswordVerify($columnVarcharVerify);
        $this->assertEquals($columnVarcharVerify, $entity->getColumnVarcharPasswordVerify());

        $entity->setColumnVarcharUniqueId($columnVarcharUnique);
        $this->assertEquals($columnVarcharUnique, $entity->getColumnVarcharUniqueId());

        $entity->setColumnVarcharUploadImage($columnVarcharUpload);
        $this->assertEquals($columnVarcharUpload, $entity->getColumnVarcharUploadImage());

        $entity->setColumnForeignKey($columnForeignKey);
        $this->assertEquals($columnForeignKey, $entity->getColumnForeignKey());

    }

    public function getProvider()
    {
        $userCreatedBy = $this->getMockBuilder('GearAdmin\Entity\User')->getMock();

        $userUpdatedBy = $this->getMockBuilder('GearAdmin\Entity\User')->getMock();

        $foreignKeysColumnKey = $this->getMockBuilder('SchemaModule\Entity\ForeignKeys')->getMock();

        return array(
            array(
                'Column Date',
                'Column Datetime',
                'Column Time',
                'Column Int',
                'Column Tinyint',
                'Column Decimal',
                'Column Varchar',
                'Column Longtext',
                'Column Text',
                'Created',
                'Updated',
                $userCreatedBy,
                $userUpdatedBy,
                'Column Datetime Pt Br',
                'Column Date Pt Br',
                'Column Decimal Pt Br',
                'Column Int Checkbox',
                'Column Tinyint Checkbox',
                'Column Varchar Email',
                'Column Varchar Password Verify',
                'Column Varchar Unique',
                'Column Varchar Upload Image',
                $foreignKeysColumnKey
            )
        );
    }
}
