namespace <?php echo $this->module;?>\Functional;

use <?php echo $this->module;?>\FunctionalTester;
use <?php echo $this->module;?>\Functional\AbstractCest;

/**
 * @SuppressWarnings(PHPMD)
 */
class ModuleMainPageCest extends AbstractCest
{
    public function seeModuleMainPageCest(FunctionalTester $I)
    {
        $I->wantTo('See the message of module creation was sucessfull');
        $I->amOnPage(\<?php echo $this->module;?>\Pages\ModuleMainPage::$URL);
        $I->see(
            '<?php echo $this->moduleLabel;?> module was created sucessfull with Gear Engine Version <?php echo $this->version?>',
            \<?php echo $this->module;?>\Pages\ModuleMainPage::$moduleName
        );
    }
}
