namespace <?php echo $this->fileNamespace;?>

use PHPUnit_Framework_TestCase as TestCase;
use <?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>;

/**
 * @group Service
 */
class <?php echo $this->className;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->service = $this->getMockForAbstractClass('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>', [***REMOVED***, '', false);
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>', $this->service);
    }
<?php echo $this->functions;?>
}
