<?php
namespace MyModuleTest\FormTest\SearchTest;

use PHPUnit\Framework\TestCase;
use Interop\Container\ContainerInterface;
use MyModule\Form\Search\MyTableSearchFormFactory;
use MyModule\Form\Search\MyTableSearchForm;
use Doctrine\ORM\EntityManager;

/**
 * @group MyModule
 * @group MyTableSearchForm
 * @group SearchForm
 */
class MyTableSearchFormFactoryTest extends TestCase
{
    public function testMyTableSearchFormFactory()
    {
        $this->container = $this->prophesize(ContainerInterface::class);

        $this->entityManager = $this->prophesize(EntityManager::class);
        $this->container->get('doctrine.entitymanager.orm_default')->willReturn($this->entityManager);

        $factory = new MyTableSearchFormFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableSearchForm::class, $instance);
    }
}
