<?php
namespace MyModuleTest\FormTest\SearchTest;

use PHPUnit\Framework\TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Form\Search\MyTableSearchFormFactory;
use MyModule\Form\Search\MyTableSearchForm;
use Doctrine\ORM\EntityManager;

/**
 * @group MyModule
 * @group MyTableSearchForm
 * @group SearchForm
 */
class MyTableSearchFormFactoryTest extends TestCase
{
    public function testMyTableSearchFormFactory()
    {
        $this->serviceLocator = $this->prophesize(ServiceLocatorInterface::class);

        $this->entityManager = $this->prophesize(EntityManager::class);
        $this->serviceLocator->get('doctrine.entitymanager.orm_default')->willReturn($this->entityManager);

        $factory = new MyTableSearchFormFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf(MyTableSearchForm::class, $instance);
    }
}
