<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Custom\CustomNamespace\MyTableSearchFormFactory;

/**
 * @group MyModule
 * @group MyTableSearchForm
 * @group SearchForm
 */
class MyTableSearchFormFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $this->entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->serviceLocator->get('doctrine.entitymanager.orm_default')->willReturn($this->entityManager);

        $factory = new MyTableSearchFormFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Custom\CustomNamespace\MyTableSearchForm', $instance);
    }
}
