return array(
    'db' => array(
        'driver' => 'Pdo',
        'dsn' => 'mysql:dbname=<?php echo $this->module; ?>;host=localhost',
        'driver_options' => array(
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        )
    ),
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => array(
                    'host' => 'localhost',
                    'port' => '3306',
                    'dbname' => '<?php echo $this->module; ?>',
                    'charset' => 'utf8'
                )
            )
        ),
        'configuration' => array(
        	'orm_default' => array(
        	    'metadata_cache' => 'filesystem',
        	    'query_cache' => 'filesystem',
        	    'result_cache' => 'filesystem',
        	    'hydration_cache' => 'filesystem',
            )
        ),
    ),
    'phinx' => array(
        'adapter' => 'mysql',
        'host' => 'localhost',
        'name'=> '<?php echo $this->module; ?>'
    )
);
