return [
    'db' => [
        'driver' => 'Pdo',
        'dsn' => 'mysql:dbname=<?php echo $this->dbname; ?>;host=<?php echo $this->module;?>-mysql',
        'driver_options' => [
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES \'UTF8\''
        ***REMOVED***
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
                'configuration' => 'orm_default',
                'eventmanager' => 'orm_default',
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => [
                    'host' => '<?php echo $this->module;?>-mysql',
                    'port' => '3306',
                    'dbname' => '<?php echo $this->dbname; ?>',
                    'charset' => 'utf8'
                ***REMOVED***
            ***REMOVED***
        ***REMOVED***,
        'configuration' => [
            'orm_default' => [
                'metadata_cache' => 'filesystem',
                'query_cache' => 'filesystem',
                'result_cache' => 'filesystem',
                'hydration_cache' => 'filesystem',
            ***REMOVED***
        ***REMOVED***,
    ***REMOVED***,
    'phinx' => [
        'adapter' => 'mysql',
        'host' => '<?php echo $this->module;?>-mysql',
        'name'=> '<?php echo $this->dbname; ?>'
    ***REMOVED***
***REMOVED***;
