return [
    'db' => [
        'username' => 'root',
        'password' => 'gear',
    ***REMOVED***,
    'doctrine' => [
        'connection' => [
            'orm_default' => [
               'params' => [
                    'user'     => 'root',
                    'password' => 'gear',
               ***REMOVED***,
            ***REMOVED***
        ***REMOVED***
    ***REMOVED***,
    'phinx' => [
        'user' => 'root',
        'pass' => 'gear',
    ***REMOVED***,
    'webhost' => '<?php echo $this->module; ?>.gear.dev',
***REMOVED***;
