<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle"><?php echo $this->translate('Edit');?>&nbsp;<?php echo $this->translate('Columns');?> - <?php echo $this->idColumns;?></h3>
	</div>
</div>
<?php if($this->success) :?>
<?php echo $this->render('layout/success');?>
<?php endif;?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('column/columns/edit', array('id' => $this->idColumns)));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <?php echo $this->formHidden($form->get('idColumns')->setAttribute('class','form-control')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idColumns'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDate'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDatetime'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnTime'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnInt'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnTinyint'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDecimal'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnVarchar'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnLongtext'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnText'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDatetimePtBr'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDatePtBr'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnDecimalPtBr'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnIntCheckbox'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnTinyintCheckbox'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnVarcharEmail'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnVarcharPasswordVerify'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnVarcharPasswordVerifyVerify'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formLabel($form->get('columnVarcharUploadImage')); ?>
            <?php echo $this->formFile($form->get('columnVarcharUploadImage')); ?>
            <?php echo $this->formElementErrors($form->get('columnVarcharUploadImage')); ?>
        </div>
        <div class="form-group">
            <?php if ($this->columnVarcharUploadImage) : ?>
                <img src="<?php echo $this->columnVarcharUploadImage;?>" height="100" width="100"/>
            <?php endif;?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('columnForeignKey'));?>
        </div>
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default" href="<?php echo $this->url('column/columns/view', array('id' => $this->idColumns));?>"><?php echo $this->translate('View');?></a>
            <a class="btn btn-primary" href="<?php echo $this->url('column/columns/create');?>"><?php echo $this->translate('Create');?></a>
            <a class="btn btn-default reset" href="<?php echo $this->url('column/columns/list');?>"><?php echo $this->translate('Back');?></a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>