<div class="row filterFlag" style="display:none">
    
    <?php

        $form = $this->search;
        $form->setAttribute('action', $this->url('column/columns/list'));
        $form->prepare();
        echo $this->form()->openTag($form);
    ?>

        <div class="col-lg-12">
        <div class="form-group">
                <?php echo $this->formRow($form->get('likeField')->setAttribute('class','form-control')); ?>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatePre'));?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatePos'));?>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDecimalPre'));?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDecimalPos'));?>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatetimePtBrPre'));?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatetimePtBrPos'));?>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatePtBrPre'));?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDatePtBrPos'));?>
        </div>
    </div>
    <div class="col-lg-12">
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDecimalPtBrPre'));?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('columnDecimalPtBrPos'));?>
        </div>
    </div>

	    <div class="col-lg-12">
            <div class="form-group">
                <?php $this->formRow($form->get('columnForeignKey')); ?>
            </div>
        </div>    <div class="col-lg-12">
        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-success')); ?>
            <?php echo $this->formSubmit($form->get('clear')->setAttribute('class','btn btn-default')); ?>
        </div>
    </div>
    
    <?php
        echo $this->form()->closeTag();
    ?>
    <hr>
</div>