
<?php if ($this->imagemService) :?>
        $this->getImagemService()->appendPlugin();
<?php endif;?>

        $redirectUrl = $this->url()->fromRoute(self::CREATE);
        $prg = $this->prg($redirectUrl, true);

        $form = $this->get<?= $this->data?>Factory();

        $service = $this->get<?= $this->data?>Service();

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;
            $form->setData($post);

            if ($form->isValid()) {

                $data = $form->getData();

                $create = $service->create($data);

                if ($create) {
<?php if ($this->imagemService) :?>
                    $this->getImagemService()->clearCache();
<?php endif;?>
                    return $this->redirect()->toRoute(
                        self::EDIT,
                        array('id' => $create->getId<?= $this->data?>(), 'success' => 1)
                    );
                }
            }
        }


        return new ViewModel(
            array(
                'form' => $form,
<?php if ($this->imagemService) :?>
                'contexto' => '<?php echo $this->str('url', $this->data);?>'
<?php endif; ?>
            )
        );