        $redirectUrl = $this->url()->fromRoute(self::CREATE);
        $prg = $this->prg($redirectUrl, true);

        $form = $this->get<?php echo $this->data;?>Factory();

        $service = $this->get<?php echo $this->str('class', $this->data);?>Service();

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;
            $form->setData($post);

            if ($form->isValid()) {

                $data = $form->getData();
                $create = $service->create($data);

                return $this->redirect()->toRoute(self::EDIT);
            }
        }



        return new ViewModel(
            array(
                'form' => $form,
                'id<?php echo $this->str('class', $this->data);?>' => $service->initialize()
            )
        );