
    public function editAction()
    {
        $id<?= $this->data?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$id<?= $this->data?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->get<?= $this->data?>Service()->selectById($id<?= $this->data?>);

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $form    = $this->get<?= $this->data?>Factory();
        $service = $this->get<?= $this->data?>Service();

        $redirectUrl = $this->url()->fromRoute(self::EDIT, array('id' => $id<?= $this->data?>));

<?php if (is_array($this->speciality) && in_array('upload-image', $this->speciality)) { ?>
        $prg = $this->filePostRedirectGet($form, $redirectUrl, true);
<?php } else { ?>
        $prg = $this->prg($redirectUrl, true);
<?php }?>

<?php if (is_array($this->speciality)) : ?>
<?php foreach ($this->speciality as $column => $speciality) : ?>
<?php if ('upload-image' == $speciality):?>

        $<?php echo $this->str('var', $column);?> = '';

<?php endif;?>
<?php endforeach;?>
<?php endif;?>

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;

            $form->setData($post);

            if ($form->isValid()) {
                $data = $form->getData();
                $update = $service->update($id<?= $this->data?>, $data);

                if ($update) {
<?php if ($this->imagemService) :?>
                    $this->getImagemService()->clearCache();
<?php endif;?>
                    $view = $this->redirect()->toRoute(
                        self::EDIT,
                        array('id' => $update->getId<?= $this->data?>(), 'success' => 1)
                    );
                }
            }
        } else {
            $data = $this->get<?= $this->data?>Service()->selectById($id<?= $this->data?>);
            $form->bind($data);
        }

<?php if (is_array($this->speciality)) : ?>
<?php foreach ($this->speciality as $column => $speciality) : ?>
<?php if ('upload-image' == $speciality):?>

        if ($data instanceof \<?php echo $this->module;?>\Entity\<?= $this->data?> && $data->get<?php echo $this->str('class', $column);?>() !== null) {
            $<?php echo $this->str('var', $column);?> = str_replace('/public', '', sprintf($data->get<?php echo $this->str('class', $column);?>(), 'pre'));
        }

<?php endif;?>
<?php endforeach;?>
<?php endif;?>

        $sucesso = $this->getEvent()->getRouteMatch()->getParam('success', null);

        return (isset($view)) ? $view : new ViewModel(
            array(
                'form' => $form,
                'success' => $sucesso,
<?php if (is_array($this->speciality)) : ?>
<?php foreach ($this->speciality as $column => $speciality) : ?>
<?php if ('upload-image' == $speciality):?>
                '<?php echo $this->str('var', $column);?>' => $<?php echo $this->str('var', $column);?>,
<?php endif;?>
<?php endforeach;?>
<?php endif;?>
<?php if ($this->imagemService) :?>
                'contexto' => '<?php echo $this->str('url', $this->data);?>',
<?php endif; ?>
                'id<?= $this->data?>' => $id<?= $this->data.PHP_EOL;?>
            )
        );
    }
