<?php if ($this->imagemService) :?>
        $this->getImagemService()->appendPlugin();
<?php endif;?>

        $identifier = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$identifier) {
            return $this->redirect()->toRoute(self::LISTS);
        }
        $form = $this->get<?= $this->data?>Factory();

        $redirectUrl = $this->url()->fromRoute(self::EDIT, array('id' => $identifier));

        <?php if (is_array($this->speciality) && in_array('metaimagem', $this->speciality)) { ?>
        $prg = $this->filePostRedirectGet($form, $redirectUrl, true);
        <?php } else { ?>
        $prg = $this->prg($redirectUrl, true);
        <?php }?>

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;

            $form->setData($post);

            if ($form->isValid()) {

                $data = $form->getData();
                $service = $this->get<?= $this->data?>Service();

                $update = $service->update($identifier, $data);


                if ($update) {
<?php if ($this->imagemService) :?>
                    $this->getImagemService()->clearCache();
<?php endif;?>
                    return $this->redirect()->toRoute(
                        self::EDIT,
                        array('id' => $update->getId<?= $this->data?>(), 'success' => 1)
                    );
                }
            }
        } else {
            $data = $this->get<?= $this->data?>Service()->selectById($identifier);
            $form->bind($data);
        }

<?php if (is_array($this->speciality)) : ?>
<?php foreach ($this->speciality as $column => $speciality) : ?>
        $<?php echo $this->str('var', $column);?> = sprintf($form->get('<?php echo $this->str('var', $column);?>')->getValue(), 'preview');
<?php endforeach;?>
<?php endif;?>


        $sucesso = $this->getEvent()->getRouteMatch()->getParam('success', null);

        return new ViewModel(
            array(
                'form' => $form,
                'success' => $sucesso,
<?php if (is_array($this->speciality)) : ?>
<?php foreach ($this->speciality as $column => $speciality) : ?>
                '<?php echo $this->str('var', $column);?>' => $<?php echo $this->str('var', $column);?>,
<?php endforeach;?>
<?php endif;?>
<?php if ($this->imagemService) :?>
                'contexto' => '<?php echo $this->str('url', $this->data);?>',
<?php endif; ?>
                'id<?= $this->data?>' => $identifier
            )
        );