<?php if ($this->imagemService) :?>
        $this->getImagemService()->appendPlugin();
<?php endif;?>

        $identifier = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$identifier) {
            return $this->redirect()->toRoute(self::LISTS);
        }
        $form = $this->get<?= $this->data?>Factory();

        $redirectUrl = $this->url()->fromRoute(self::EDIT, array('id' => $identifier));
        $prg = $this->prg($redirectUrl, true);

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;

            $form->setData($post);

            if ($form->isValid()) {

                $data = $form->getData();
                $service = $this->get<?= $this->data?>Service();
                $update = $service->update($identifier, $data);

                if ($update) {
<?php if ($this->imagemService) :?>
                    $this->getImagemService()->clearCache();
<?php endif;?>
                    return $this->redirect()->toRoute(
                        self::EDIT,
                        array('id' => $update->getId<?= $this->data?>(), 'sucesso' => 1)
                    );
                }
            }
        }

        $data = $this->get<?= $this->data?>Service()->selectById($identifier);
        $form->bind($data);


        return new ViewModel(
            array(
                'form' => $form,
<?php if ($this->imagemService) :?>
                'contexto' => '<?php echo $this->str('url', $this->data);?>'
<?php endif; ?>
                'id<?= $this->data?>' => $identifier
            )
        );