namespace <?php echo $this->module;?>\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
use Zend\Stdlib\ResponseInterface as Response;
use Zend\Stdlib\Parameters;
<?php echo $this->use;?>
class <?php echo $this->controllerName;?> extends AbstractActionController
{
    const CREATE = '<?php echo $this->str('url', $this->module);?>/<?php echo $this->str('url', str_replace('Controller', '', $this->controllerName));?>/create';
    const EDIT   = '<?php echo $this->str('url', $this->module);?>/<?php echo $this->str('url', str_replace('Controller', '', $this->controllerName));?>/edit';
    const LISTS  = '<?php echo $this->str('url', $this->module);?>/<?php echo $this->str('url', str_replace('Controller', '', $this->controllerName));?>/list';
    const IMAGE  = '<?php echo $this->str('url', $this->module);?>/<?php echo $this->str('url', str_replace('Controller', '', $this->controllerName));?>/upload-image';

<?php echo $this->attribute;?>
<?php echo $this->createAction;?>
<?php echo $this->editAction;?>
<?php echo $this->viewAction;?>
<?php echo $this->deleteAction;?>
<?php echo $this->uploadImageAction;?>
<?php echo $this->listAction;?>
<?php echo $this->injections;?>
<?php echo $this->imagemService;?>
}
