namespace <?php echo $this->module;?>\Controller;

use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;
<?php echo $this->partialLoop('template/miscellaneous/use-partial.phtml', $this->use);?>

class <?php echo $this->controllerName;?> extends AbstractActionController
{
<?php echo $this->partialLoop('template/miscellaneous/attribute-partial.phtml', $this->attribute);?>

    <?php foreach ($this->actions as $i => $action) : echo PHP_EOL;?>
    public function <?php echo $this->str('var', $action->getName());?>Action()
    {
<?php echo $this->render(sprintf('template/src/controller/%s.phtml', $this->str('url', $action->getName())), array('data' => str_replace('Controller', '',  $this->controllerName))).PHP_EOL;?>
    }<?php echo PHP_EOL; endforeach;?>
<?php echo $this->partialLoop('template/miscellaneous/injection-partial.phtml', $this->injection);?>
}
