        $this->getImagemService()->appendPlugin();

        $identifier = $this->getEvent()->getRouteMatch()->getParam('id', null);

        $redirectUrl = $this->url()->fromRoute(self::IMAGE, array('id' => $identifier));
        $prg = $this->prg($redirectUrl, true);

        $success = 0;

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $post = $prg;
            $imagemService = $this->getImagemService();
            $imagemService->updateImages('<?= $this->str('url', $this->data)?>', $identifier);
            $success = $imagemService->updatePosition($post);
            $this->getImagemService()->clearCache();
        }

        return new ViewModel(
            array(
                'id<?= $this->data?>' => $identifier,
                'contexto' => '<?php echo $this->str('url', $this->data);?>',
                'success' => $success
            )
        );
