
    public function listAction()
    {
        $formSearch = $this->get<?php echo $this->str('var', $this->data);?>SearchFactory();

        $redirectUrl = $this->url()->fromRoute(self::LISTS);
        $prg = $this->prg($redirectUrl, true);

        if ($prg instanceof Response) {
            return $prg;
        } elseif ($prg !== false) {
            $formSearch->setData($prg);
        } else {
            $prg = array();
        }

        $<?php echo $this->str('var', $this->data);?>Service = $this->get<?php echo $this->data;?>Service();

        return new ViewModel(
            array(
                'sucesso'   => $this->viewMessages()->listSuccess(),
                'search'    => $formSearch,
                'tableService' => $<?php echo $this->str('var', $this->data);?>Service,
                'orderBy'   => $<?php echo $this->str('var', $this->data);?>Service->getOrderBy(),
                'order'     => $<?php echo $this->str('var', $this->data);?>Service->getOrder(),
                'data'      => $<?php echo $this->str('var', $this->data);?>Service->getData($prg),
            )
        );
    }
