        $id<?= $this->data?> = $this->getEvent()->getRouteMatch()->getParam('id', null);

        if (!$id<?= $this->data?>) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        $data = $this->get<?= $this->data?>Service()->selectById($id<?= $this->data?>);

        if (!$data) {
            return $this->redirect()->toRoute(self::LISTS);
        }

        return new ViewModel(
            array_merge(
                array(
                    'id' => $data->getId<?= $this->data?>()
                ),
                $this->get<?= $this->data?>Service()->extract($data)
            )
        );