<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->controllerManager = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $factory = new IndexControllerFactory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf('MyModule\Controller\IndexController', $instance);
    }
}
