<?php
namespace MyModuleTest\RepositoryTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Repository\MyTableRepositoryFactory;
use MyModule\Repository\MyTableRepository;
use Doctrine\ORM\EntityManager;
use GearBase\Repository\QueryBuilder;

/**
 * @group MyModule
 * @group MyTableRepository
 * @group Repository
 */
class MyTableRepositoryFactoryTest extends TestCase
{
    public function testMyTableRepositoryFactory()
    {
        $this->serviceLocator = $this->prophesize(ServiceLocatorInterface::class);

        $this->serviceLocator->get('doctrine.entitymanager.orm_default')
            ->willReturn($this->prophesize(EntityManager::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(QueryBuilder::class)
            ->willReturn($this->prophesize(QueryBuilder::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableRepositoryFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf(MyTableRepository::class, $instance);
    }
}
