<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use Interop\Container\ContainerInterface;
use MyModule\Custom\CustomNamespace\MyTableRepositoryFactory;
use MyModule\Custom\CustomNamespace\MyTableRepository;
use Doctrine\ORM\EntityManager;
use GearBase\Repository\QueryBuilder;

/**
 * @group MyModule
 * @group MyTableRepository
 * @group Repository
 */
class MyTableRepositoryFactoryTest extends TestCase
{
    public function testMyTableRepositoryFactory()
    {
        $this->container = $this->prophesize(ContainerInterface::class);

        $this->container->get('doctrine.entitymanager.orm_default')
            ->willReturn($this->prophesize(EntityManager::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(QueryBuilder::class)
            ->willReturn($this->prophesize(QueryBuilder::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableRepositoryFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableRepository::class, $instance);
    }
}
