<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Custom\CustomNamespace\MyTableRepositoryFactory;

/**
 * @group MyModule
 * @group MyTableRepository
 * @group Repository
 */
class MyTableRepositoryFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $this->serviceLocator->get('doctrine.entitymanager.orm_default')
            ->willReturn($this->prophesize('Doctrine\ORM\EntityManager')->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('GearBase\Repository\QueryBuilder')
            ->willReturn($this->prophesize('GearBase\Repository\QueryBuilder')->reveal())
            ->shouldBeCalled();

        $factory = new MyTableRepositoryFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Custom\CustomNamespace\MyTableRepository', $instance);
    }
}
