<?php
namespace MyModule\Filter;

use GearBase\Filter\AbstractFilter;

/**
 * Filter for Table Not Null Controller.
 *
 * PHP Version 5
 *
 * @category Filter
 * @package MyModule/Filter
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class TableNotNullFilter extends AbstractFilter
{

    /**
     * Get The Input Filter
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @return TableNotNullFilter
     */
    public function getInputFilter()
    {
        $this->add(
            array(
                'name' => 'dateColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'datePtBrColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'datetimeColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'datetimePtBrColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'timeColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'decimalColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'moneyPtBrColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'checkboxColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'idForeignKeyColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'intColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'htmlColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'textColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'tinyintColumnNotNull',
                'required' => true,
            )
        );
        $this->add(
            array(
                'name' => 'checkboxColumnNotNull',
                'required' => true,
            )
        );
        $message = 'O valor é inválido';
        $this->add(
            array(
                'name' => 'emailColumnNotNull',
                'required' => true,
                'filters'    => array(array('name' => 'StringTrim')),
                'validators' => array(
                    array(
                        'name' => 'EmailAddress',
                        'options' => array(
                            'messages' => array(
                                \Zend\Validator\EmailAddress::INVALID            => $message,
                                \Zend\Validator\EmailAddress::INVALID_FORMAT     => $message,
                                \Zend\Validator\EmailAddress::INVALID_HOSTNAME   => $message,
                                \Zend\Validator\EmailAddress::INVALID_MX_RECORD  => $message,
                                \Zend\Validator\EmailAddress::INVALID_SEGMENT    => $message,
                                \Zend\Validator\EmailAddress::DOT_ATOM           => $message,
                                \Zend\Validator\EmailAddress::QUOTED_STRING      => $message,
                                \Zend\Validator\EmailAddress::INVALID_LOCAL_PART => $message,
                                \Zend\Validator\EmailAddress::LENGTH_EXCEEDED    => $message,
                            ),
                        ),
                        'break_chain_on_failure' => true
                    )
                )
            )
        );
        $messageMax = 'O valor deve ter no máximo %max% caracteres';
        $messageMin = 'O valor deve ter no mínimo %min% caracteres';
        $this->add(array(
            'name'       => 'passwordVerifyColumnNotNull',
            'required'   => true,
            'allow_empty' => true,
            'filters'    => array(array('name' => 'StringTrim')),
            'validators' => array(
                array(
                    'name'    => 'StringLength',
                    'options' => array(
                        'min' => 6,
                        'max' => 20,
                        'messages' => [
                            \Zend\Validator\StringLength::TOO_SHORT => $messageMin,
                            \Zend\Validator\StringLength::TOO_LONG => $messageMax
                        ***REMOVED***
                    ),
                ),
            ),
        ));

        $this->add(array(
            'name'       => 'passwordVerifyColumnNotNullVerify',
            'required'   => true,
            'allow_empty' => true,
            'filters'    => array(array('name' => 'StringTrim')),
            'validators' => array(
                array(
                    'name'    => 'StringLength',
                    'options' => array(
                        'min' => 6,
                        'max' => 20,
                        'messages' => [
                            \Zend\Validator\StringLength::TOO_SHORT => $messageMin,
                            \Zend\Validator\StringLength::TOO_LONG => $messageMax
                        ***REMOVED***
                    ),
                    'break_chain_on_failure' => true
                ),
                array(
                    'name'    => 'Identical',
                    'options' => array(
                        'token' => 'passwordVerifyColumnNotNull',
                        'messages' => [
                            \Zend\Validator\Identical::NOT_SAME => 'Os dois valores digitados não combinam.'
                        ***REMOVED***
                    ),
                ),
            ),
        ));
        $message = 'O valor é inválido';
        $this->add(
            array(
                'name' => 'telephoneColumnNotNull',
                'required' => true,
                'filters'    => array(array('name' => 'StringTrim')),
                'validators' => array(
                     array(
                        'name' => 'Regex',
                        'options' =>  array(
                            'pattern'   => '/^(\([0-9***REMOVED***{2}\))\s([9***REMOVED***{1})?([0-9***REMOVED***{4})-([0-9***REMOVED***{4})$/',
                            'messages'  => [
                                \Zend\Validator\Regex::INVALID => $message,
                                \Zend\Validator\Regex::NOT_MATCH => $message,
                                \Zend\Validator\Regex::ERROROUS => $message
                            ***REMOVED***
                        )
                    )
                )
            )
        );
        // File Input
        $fileInput = new \Zend\InputFilter\FileInput('uploadImageColumnNotNull');
        $fileInput->setRequired(false);
        $fileInput->getFilterChain()->attachByName(
            'filerenameupload',
            array(
                'target'    =>
                \GearBase\Module::getProjectFolder().'/public/_temp/uploadImageColumnNotNulltempimg.png',
                'randomize' => true,
            )
        );
        $this->add($fileInput);
        $message = 'O valor é inválido';
        $this->add(
            array(
                'name' => 'urlColumnNotNull',
                'required' => true,
                'filters'    => array(array('name' => 'StringTrim')),
                'validators' => array(
                    [
                        'name' => 'Hostname',
                        'options' => [
                            'messages' => [
                                \Zend\Validator\Hostname::CANNOT_DECODE_PUNYCODE  => $message,
                                \Zend\Validator\Hostname::INVALID                 => $message,
                                \Zend\Validator\Hostname::INVALID_DASH            => $message,
                                \Zend\Validator\Hostname::INVALID_HOSTNAME        => $message,
                                \Zend\Validator\Hostname::INVALID_HOSTNAME_SCHEMA => $message,
                                \Zend\Validator\Hostname::INVALID_LOCAL_NAME      => $message,
                                \Zend\Validator\Hostname::INVALID_URI             => $message,
                                \Zend\Validator\Hostname::IP_ADDRESS_NOT_ALLOWED  => $message,
                                \Zend\Validator\Hostname::LOCAL_NAME_NOT_ALLOWED  => $message,
                                \Zend\Validator\Hostname::UNDECIPHERABLE_TLD      => $message,
                                \Zend\Validator\Hostname::UNKNOWN_TLD             => $message
                            ***REMOVED***
                        ***REMOVED***
                    ***REMOVED***
                )
            )
        );
        $messageMax = 'O valor deve ter no máximo %max% caracteres';
        $messageMin = 'O valor deve ter no mínimo %min% caracteres';
        $this->add(
            array(
                'name' => 'varcharColumnNotNull',
                'required' => true,
                'filters'    => array(array('name' => 'StringTrim')),
                'validators' => array(
                    array(
                        'name'    => 'StringLength',
                        'options' => array(
                            'min' => 3,
                            'max' => 45,
                            'messages' => [
                                \Zend\Validator\StringLength::TOO_SHORT => $messageMin,
                                \Zend\Validator\StringLength::TOO_LONG => $messageMax
                            ***REMOVED***
                        )
                    )
                )
            )
        );
        return $this;
    }
}
