apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: <?php echo $this->module;?>-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /*
spec:
  tls:
    - secretName: letsencrypt-prod
  rules:
  - host: <?php echo $this->module;?>.piber.network
    http:
      paths:
      - path: /*
        backend:
          serviceName: <?php echo $this->module;?>-service
          servicePort: 80
