# Version v1.0.0
<?php echo $this->deployment; ?>
---
<?php echo $this->deploymentDev; ?>
---
kind: Service
apiVersion: v1
metadata:
  name: <?php echo $this->module;?>-service
  labels:
    run: <?php echo $this->module.PHP_EOL;?>
spec:
  selector:
    run: <?php echo $this->module.PHP_EOL;?>
  ports:
    - port: 80 # Default port for image
---
kind: Service
apiVersion: v1
metadata:
  name: <?php echo $this->module;?>-dev-service
  labels:
    run: <?php echo $this->module;?>-dev
spec:
  selector:
    run: <?php echo $this->module;?>-dev
  ports:
    - port: 80 # Default port for image
---
<?php echo $this->ingress; ?>
---
<?php echo $this->ingressDev; ?>
