namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use PHPUnit_Framework_TestCase as TestCase;
use <?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>;

/**
 * @group Repository
 */
class <?php echo $this->className;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->className = '<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>';
<?php echo $this->dependency;?>

        $this->repository = $this->getMockBuilder($this->className)
            ->disableoriginalConstructor()
            ->getMockForAbstractClass();
    }

    public function testClassExists()
    {
        $reflectedClass = new \ReflectionClass($this->className);
        $constructor = $reflectedClass->getConstructor();
        $class = $constructor->invoke(
            $this->repository<?php echo (!empty($this->dependencyReveal)) ? ',' : '';?><?php echo PHP_EOL;?>
<?php echo $this->dependencyReveal;?>
        );

        $this->assertInstanceOf('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>', $class);
    }
<?php echo $this->functions;?>
}
