namespace <?php echo $this->module;?>Test\<?php echo $this->namespaceFile;?>;

use PHPUnit\Framework\TestCase;
use <?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>;

/**
 * @group Repository
 */
class <?php echo $this->className;?>Test extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->repository = $this->getMockForAbstractClass('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>', [***REMOVED***, '', false);
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('<?php echo $this->module;?>\<?php echo $this->namespace;?>\<?php echo $this->className;?>', $this->repository);
    }
<?php echo $this->functions;?>
}
