<?php
namespace SchemaModuleTest\FilterTest;

use GearBaseTest\AbstractTestCase;

/**
 * @group Filter
 */
class MyFilterTest extends AbstractTestCase
{
    protected $myFilter;

    public function getMyFilter()
    {
        if (!isset($this->myFilter)) {
            $this->myFilter = $this->bootstrap->getServiceLocator()->get('SchemaModule\Filter\MyFilter');
        }
        return $this->myFilter;
    }

    /**
     * @group SchemaModule
     * @group MyFilter
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->getMyFilter()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group SchemaModule
     * @group MyFilter
     */
    public function testCallUsingServiceLocator()
    {
        $myFilter = $this->getMyFilter();
        $this->assertInstanceOf('SchemaModule\Filter\MyFilter', $myFilter);
    }


    /**
     * @group SchemaModule
     * @group MyFilter
    */
    public function testGetInputFilter()
    {
        $myFilter = $this->getMyFilter();
        $className = $myFilter->getInputFilter();
        $this->assertInstanceOf('SchemaModule\Filter\MyFilter', $className);
    }
}
