<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\Custom\CustomNamespace\MyTableServiceFactory;
use MyModule\Custom\CustomNamespace\MyTableService;
use Zend\Cache\Storage\Adapter\Memcached;
use MyModule\Custom\CustomNamespace\MyTableRepository;
use GearImage\Service\ImageService;

/**
 * @group MyModule
 * @group MyTableService
 * @group Service
 */
class MyTableServiceFactoryTest extends TestCase
{
    public function testMyTableServiceFactory()
    {
        $this->serviceLocator = $this->prophesize(ServiceLocatorInterface::class);

        $this->serviceLocator->get('memcached')
            ->willReturn($this->prophesize(Memcached::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(MyTableRepository::class)
            ->willReturn($this->prophesize(MyTableRepository::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(ImageService::class)
            ->willReturn($this->prophesize(ImageService::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableServiceFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf(MyTableService::class, $instance);
    }
}
