<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use Interop\Container\ContainerInterface;
use MyModule\Custom\CustomNamespace\MyTableServiceFactory;
use MyModule\Custom\CustomNamespace\MyTableService;
use Zend\Cache\Storage\Adapter\Memcached;
use MyModule\Custom\CustomNamespace\MyTableRepository;
use GearImage\Service\ImageService;

/**
 * @group MyModule
 * @group MyTableService
 * @group Service
 */
class MyTableServiceFactoryTest extends TestCase
{
    public function testMyTableServiceFactory()
    {
        $this->container = $this->prophesize(ContainerInterface::class);

        $this->container->get('memcached')
            ->willReturn($this->prophesize(Memcached::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(MyTableRepository::class)
            ->willReturn($this->prophesize(MyTableRepository::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(ImageService::class)
            ->willReturn($this->prophesize(ImageService::class)->reveal())
            ->shouldBeCalled();

        $factory = new MyTableServiceFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MyTableService::class, $instance);
    }
}
