<?php
namespace MyModuleTest\ServiceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Service\MyTableServiceFactory;

/**
 * @group MyModule
 * @group MyTableService
 * @group Service
 */
class MyTableServiceFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $this->serviceLocator->get('memcached')
            ->willReturn($this->prophesize('Zend\Cache\Storage\Adapter\Memcached')->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('MyModule\Repository\MyTableRepository')
            ->willReturn($this->prophesize('MyModule\Repository\MyTableRepository')->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('GearImage\Service\ImageService')
            ->willReturn($this->prophesize('GearImage\Service\ImageService')->reveal())
            ->shouldBeCalled();

        $factory = new MyTableServiceFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\Service\MyTableService', $instance);
    }
}
