<?php
return [
    'invokables' => [
        'controllerService'                    => 'Gear\Mvc\Controller\ControllerService',
        'Gear\Mvc\Controller\Controller'       => 'Gear\Mvc\Controller\Controller',
        'Gear\Mvc\Controller\ControllerTest'   => 'Gear\Mvc\Controller\ControllerTest',
        'Gear\Mvc\Controller\ControllerConfig' => 'Gear\Mvc\Controller\ControllerConfig',
        'Gear\Mvc\TestService'                 => 'Gear\Mvc\TestService',
        'Gear\Mvc\ViewService'                 => 'Gear\Mvc\ViewService',

        'languageService'           => 'Gear\Mvc\LanguageService',
        'entityService'             => 'Gear\Service\Mvc\EntityService',
        'entityTestService'         => 'Gear\Service\Test\EntityTestService',
        'repositoryService'         => 'Gear\Service\Mvc\RepositoryService',
        'repositoryTestService'     => 'Gear\Service\Test\RepositoryTestService',
        'formService'               => 'Gear\Service\Mvc\FormService',
        'formTestService'           => 'Gear\Service\Test\FormTestService',
        'searchTestService'           => 'Gear\Service\Test\SearchTestService',
        'filterService'             => 'Gear\Service\Mvc\FilterService',
        'filterTestService'         => 'Gear\Service\Test\FilterTestService',
        'factoryService'            => 'Gear\Service\Mvc\FactoryService',
        'factoryTestService'        => 'Gear\Service\Test\FactoryTestService',
        'valueObjectService'        => 'Gear\Service\Mvc\ValueObjectService',
        'valueObjectTestService'    => 'Gear\Service\Test\ValueObjectTestService',
        'controllerPluginService'      => 'Gear\Service\Mvc\ControllerPluginService',
        'controllerPluginTestService'  => 'Gear\Service\Test\ControllerPluginTestService',
        'serviceService'            => 'Gear\Service\Mvc\ServiceService',
        'viewService'               => 'Gear\Service\Mvc\ViewService',
        'ViewService\TableService'  => 'Gear\Service\Mvc\ViewService\TableService',
        'ViewService\FormService'   => 'Gear\Service\Mvc\ViewService\FormService',
        'ViewService\SearchService' => 'Gear\Service\Mvc\ViewService\SearchService',
        'codeceptionService'        => 'Gear\Service\Test\CodeceptionService',
        'zendServiceLocatorService' => 'Gear\Service\Test\ZendServiceLocatorService',
        'controllerTestService'     => 'Gear\Mvc\Controller\ControllerTestService',
        'functionalTestService'     => 'Gear\Service\Test\FunctionalTestService',
        'repositoryTestService'     => 'Gear\Service\Test\RepositoryTestService',
        'serviceTestService'        => 'Gear\Service\Test\ServiceTestService',
        'acceptanceTestService'     => 'Gear\Service\Test\AcceptanceTestService',
        'pageTestService'           => 'Gear\Service\Test\PageTestService',
        'configService'             => 'Gear\Mvc\Config\ConfigService',
        'Gear\Mvc\Config\Router'         => 'Gear\Mvc\Config\Router',
        'Gear\Mvc\Config\ServiceManager' => 'Gear\Mvc\Config\ServiceManager',
        'Gear\Mvc\Config\Navigation'     => 'Gear\Mvc\Config\Navigation',
        'Gear\Mvc\Config\Controller'     => 'Gear\Mvc\Config\Controller',
        'Gear\Mvc\Config\UploadImage'    => 'Gear\Mvc\Config\UploadImage',

    ***REMOVED***
***REMOVED***;