#!/bin/bash

headerDir="$( cd "$( dirname "${BASH_SOURCE[0***REMOVED***}" )" && pwd )"

function not_in_array() {
    local haystack=${1}[@***REMOVED***
    local needle=${2}
    for i in ${!haystack}; do
        if [[ ${i} == ${needle} ***REMOVED******REMOVED***; then
            return 1
        fi
    done
    return 0
}

declare -a availableCmds=("create" "reset" "construct" "module-create" "module-construct" "module-reset")

cmd=${1}

if not_in_array availableCmds "${cmd}"; then
	
	echo "Exiting with invalid command ${cmd}"
	exit 1
	
fi

if [ "${2}" == "--help" ***REMOVED***; then
	
	Gear_Help "project" "$cmd"
	exit 0
fi

if [ "$cmd" == "create" ***REMOVED***; then


    # Params
    if [ $# -lt 7 ***REMOVED***; then
        echo "usage $0: command project scriptDir modules local ci jira"
        exit 1
    fi
	
	# Gear_Project_Create ${2} ${3} ${4} "1" "0" "0" 
	exit 0
	
fi

if [ "$cmd" == "construct" ***REMOVED***; then
	
	# Params
    if [ $# -lt 7 ***REMOVED***; then
        echo "usage $0: command project scriptDir modules local ci jira"
        exit 1
    fi
   
	exit 0
	
fi

if [ "$cmd" == "reset" ***REMOVED***; then
	

fi

if [ "$cmd" == "module-create" ***REMOVED***; then


    # Params
    if [ $# -lt 8 ***REMOVED***; then
        echo "usage $0: command project moduleName gearfile migrations local ci jira"
        exit 1
    fi
	
	# Gear_Project_Create ${2} ${3} ${4} "1" "0" "0" 
	exit 0
	
fi

if [ "$cmd" == "module-construct" ***REMOVED***; then
	
    # Params
    if [ $# -lt 8 ***REMOVED***; then
        echo "usage $0: command project moduleName gearfile migrations local ci jira"
        exit 1
    fi
	
fi


