namespace <?php echo $this->module;?>Test\ServiceTest;

use GearBaseTest\AbstractTestCase;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
 * @group Service
 */
class <?php echo $this->serviceNameClass;?>Test extends AbstractTestCase
{
    protected $<?php echo $this->serviceNameUline;?>;
<?php echo $this->static;?>

    public function get<?php echo $this->serviceNameClass;?>()
    {
        if (!isset($this-><?php echo $this->serviceNameUline;?>)) {
            $this-><?php echo $this->serviceNameUline;?> =
                $this->bootstrap->getServiceLocator()->get(
                    '<?php echo $this->module;?>\Service\<?php echo $this->serviceNameClass;?>'
                );
        }
        return $this-><?php echo $this->serviceNameUline;?>;
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->serviceNameClass;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->serviceNameClass.PHP_EOL;?>
    */
    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->serviceNameUline;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Service\<?php echo $this->serviceNameClass;?>', $<?php echo $this->serviceNameUline;?>);
    }
<?php echo $this->injection;?>

<?php echo $this->extraColumns;?>

    public function testSetSelectAllCache()
    {
        $this->mockIdentity();

        $this->get<?php echo $this->serviceNameClass;?>()->setSessionName('testing');

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem('testingResult')) {
            $cache->removeItem('testingResult');
        }

        $data = $this->get<?php echo $this->serviceNameClass;?>()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->get<?php echo $this->serviceNameClass;?>()->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->mockIdentity();

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'DESC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy());
        $this->assertEquals('DESC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());

        $this->get<?php echo $this->serviceNameClass;?>()->selectAll();

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch($this->getRouteMatch(1, '<?php echo $this->firstString;?>', 'ASC'));

        $this->assertEquals('<?php echo $this->firstString;?>', $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy());
        $this->assertEquals('ASC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());

        $cache = $this->bootstrap->getServiceLocator()->get('memcached');

        if ($cache->hasItem($this->get<?php echo $this->serviceNameClass;?>()->getSessionName())) {
            $cache->removeItem($this->get<?php echo $this->serviceNameClass;?>()->getSessionName());
        }

        $this->get<?php echo $this->serviceNameClass;?>()->setRouteMatch(
            $this->getRouteMatch(1, 'id<?php echo $this->class;?>', 'DESC')
        );

        $this->assertEquals(
            'id<?php echo $this->class;?>',
            $this->get<?php echo $this->serviceNameClass;?>()->getOrderBy()
        );
        $this->assertEquals('DESC', $this->get<?php echo $this->serviceNameClass;?>()->getOrder());
    }

    public function testGetMappingInfo()
    {
        $<?php echo $this->serviceNameVar;?> = $this->get<?php echo $this->serviceNameClass;?>();
        $resultSet = $<?php echo $this->serviceNameVar;?>->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $<?php echo $this->serviceNameVar;?> = $this->get<?php echo $this->serviceNameClass;?>();
<?php echo $this->mockauthadapter.PHP_EOL;?>
        $resultSet = $<?php echo $this->serviceNameVar;?>->selectById(1);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);
        $this->assertEquals(1, $resultSet->getId<?php echo $this->class;?>());
    }
<?php echo $this->selectbyidnull;?>

<?php echo $this->oneBy;?>

    /**
     * @group Service.Create
     */
    public function testCreate()
    {
        $this->mockIdentity();
        $data = array(
<?php echo $this->insertArray;?>
        );
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()->create($data);
        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(is_null($resultSet->getUpdated()));
<?php echo $this->insertAssert;?>
        return $resultSet;
    }

    /**
     * @depends testCreate
     */
    public function testUpdate($entityToUpdate)
    {
        $this->mockIdentity();
        $data = array(
<?php echo $this->updateArray;?>
        );
        $resultSet = $this->get<?php echo $this->serviceNameClass;?>()
            ->update($entityToUpdate->getId<?php echo $this->class;?>(), $data);

        $this->bootstrap->getEntityManager()->refresh($resultSet);
        $this->assertInstanceOf('<?php echo $this->module;?>\Entity\<?php echo $this->class;?>', $resultSet);

        $this->assertTrue(!is_null($resultSet->getCreatedBy()));
        $this->assertTrue(!is_null($resultSet->getCreated()));
        $this->assertTrue(!is_null($resultSet->getUpdatedBy()));
        $this->assertTrue(!is_null($resultSet->getUpdated()));
<?php echo $this->updateAssert;?>
        return $resultSet;
    }

    /**
     * @depends testUpdate
     */
    public function testDelete($entityToDelete)
    {

        $<?php echo $this->serviceNameVar;?> = $this->get<?php echo $this->serviceNameClass;?>();
<?php echo $this->mockauthadapter.PHP_EOL;?>
        $resultSet = $<?php echo $this->serviceNameVar;?>->delete($entityToDelete->getId<?php echo $this->class;?>());
        $this->assertTrue($resultSet['success'***REMOVED***);
    }

    public function getRouteMatch($page, $orderBy = 'id<?php echo $this->class;?>', $order = 'DESC')
    {
        $routeMatch = new \Zend\Mvc\Router\Http\RouteMatch(array(
            'controller' => '<?php echo $this->module;?>\Controller\<?php echo $this->class;?>',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('<?php echo $this->str('url', $this->module)?>/<?php echo $this->str('url', $this->class)?>');
        return $routeMatch;
    }
}
