<?php if ($this->speciality !== null) :?>
<?php echo $this->speciality->getFormElement($this->var, $this->name, $this->id, $this->label).PHP_EOL;?>
<?php elseif ($this->type == 'text' || $this->type == 'int' || $this->type == 'textarea' || $this->type == 'hidden') : ?>
        $<?=$this->var;?> = new Element('<?=  $this->name;?>');
        $<?=$this->var;?>->setAttributes(array(
            'name' => '<?= $this->name;?>',
            'id' => '<?=  $this->id;?>',
            'type' => '<?=  $this->type;?>',
        ));
        $<?=$this->var;?>->setLabel('<?=  $this->label;?>');
        $this->add($<?=$this->var;?>);
<?php elseif ($this->type == 'select') :?>
        $<?=$this->var;?> = array(
            'name' => '<?=  $this->name;?>',
            'type' => 'DoctrineModule\Form\Element\ObjectSelect',
            'options' => array(
                'label' =>' <?= $this->label;?>',
                'object_manager' => $this->getEntityManager(),
                'target_class' => '<?= $this->module;?>\Entity\<?= $this->entity;?>',
                'property' => 'nome',
                'empty_option' => 'Escolher:',
            ),
        );
        $this->add($<?=$this->var;?>);
<?php endif;?>
