    /**
     * @group <?= $this->baseClass ?>
     */
    public function testSet<?= $this->class ?>()
    {
        $mock = $this->getMockBuilder('<?= $this->service;?>')
          ->disableOriginalConstructor()
          ->getMock();
        $<?= $this->baseVar?> = $this->get<?= $this->baseClass;?>();
        $<?= $this->baseVar?>->set<?= $this->class ?>($mock);
        $this->assertInstanceOf('<?= $this->service;?>', $mock);
        return $this;
    }

    /**
     * @group <?= $this->baseClass ?>
     */
    public function testGet<?= $this->class ?>()
    {
        $<?= $this->baseVar?> = $this->get<?= $this->baseClass;?>();
        $<?= $this->var?> = $<?= $this->baseVar?>->get<?= $this->class ?>();
        $this->assertInstanceOf('<?= $this->service;?>', $<?= $this->var?>);

    }<?php echo PHP_EOL;?>