<?php
namespace MyModule\Greatest;

use MyModule\ColumnInterface\RepositoryBeforeInterface;
use MyModule\ColumnInterface\RepositoryAfterInterface;
use MyModule\Repository\MyDependencyOneTrait;
use MyModule\Logic\MyDependencyTwoTrait;
use MyModule\Mvc\MyDependencyThreeTrait;
use MyModule\Repository\AbstractRepository;

abstract class AbstractCompleteInvokablesRepository extends AbstractRepository implements
    RepositoryBeforeInterface,
    RepositoryAfterInterface
{
    use MyDependencyOneTrait;

    use MyDependencyTwoTrait;

    use MyDependencyThreeTrait;
}
