<?php
namespace MyModule\Repository;

use MyModule\Repository\MyDependencyOneTrait;
use MyModule\Repository\MyDependencyTwoTrait;
use MyModule\Repository\MyDependencyThreeTrait;

/**
 * PHP Version 5
 *
 * @category Repository
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependenciesRepository
{
    use MyDependencyOneTrait;

    use MyDependencyTwoTrait;

    use MyDependencyThreeTrait;
}
