<?php
namespace MyModule\Repository;

use MyModule\Repository\MyDependencyOneTrait;
use MyModule\Repository\MyDependencyTwoTrait;
use MyModule\Repository\MyDependencyThreeTrait;
use MyModule\Repository\MyDependencyOne;
use MyModule\Repository\MyDependencyTwo;
use MyModule\Repository\MyDependencyThree;

class BasicDependenciesFactoryRepository
{
    use MyDependencyOneTrait;

    use MyDependencyTwoTrait;

    use MyDependencyThreeTrait;

    public function __construct(
        MyDependencyOne $myDependencyOne,
        MyDependencyTwo $myDependencyTwo,
        MyDependencyThree $myDependencyThree
    ) {
        $this->myDependencyOne = $myDependencyOne;
        $this->myDependencyTwo = $myDependencyTwo;
        $this->myDependencyThree = $myDependencyThree;
    }
}
