<?php
namespace MyModule\Repository;

use Zend\ServiceManager\ServiceLocatorAwareInterface;
use MyModule\Repository\DbQueryInterface;
use MyModule\Repository\DbAdapterInterface;
use Zend\ServiceManager\ServiceLocatorAwareTrait;
use MyModule\Repository\DbQueryTrait;
use MyModule\Repository\DbAdapterTrait;

/**
 * PHP Version 5
 *
 * @category Repository
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicImplementsDependenciesRepository implements
    ServiceLocatorAwareInterface,
    DbQueryInterface,
    DbAdapterInterface
{
    use ServiceLocatorAwareTrait;

    use DbQueryTrait;

    use DbAdapterTrait;
}
