<?php
namespace MyModule\Repository;

use MyModule\Repository\MyDependencyOneTrait;
use MyModule\Repository\MyDependencyTwoTrait;
use MyModule\Repository\MyDependencyThreeTrait;
use MyModule\Repository\MyDependencyOne;
use MyModule\Repository\MyDependencyTwo;
use MyModule\Repository\MyDependencyThree;

/**
 * PHP Version 5
 *
 * @category Repository
 * @package MyModule/Repository
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependenciesFactoryRepository
{
    use MyDependencyOneTrait;

    use MyDependencyTwoTrait;

    use MyDependencyThreeTrait;

    public function __construct(
        MyDependencyOne $myDependencyOne,
        MyDependencyTwo $myDependencyTwo,
        MyDependencyThree $myDependencyThree
    ) {
        $this->myDependencyOne = $myDependencyOne;
        $this->myDependencyTwo = $myDependencyTwo;
        $this->myDependencyThree = $myDependencyThree;

        return $this;
    }
}
