<?php
namespace MyModuleTest\ServiceTest;

use PHPUnit\Framework\TestCase;
use MyModule\Service\BasicDependencyService;

/**
 * @group Service
 */
class BasicDependencyServiceTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->service = new BasicDependencyService();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Service\BasicDependencyService', $this->service);
    }
}
