<?php
namespace MyModuleTest\BasicTest;

use PHPUnit\Framework\TestCase;
use MyModule\Basic\BasicNamespaceService;

/**
 * @group Service
 */
class BasicNamespaceServiceTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->service = new BasicNamespaceService();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Basic\BasicNamespaceService', $this->service);
    }
}
