<?php
namespace MyModuleTest\ServiceTest;

use PHPUnit\Framework\TestCase;
use MyModule\Service\BasicImplementsService;

/**
 * @group Service
 */
class BasicImplementsServiceTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->service = new BasicImplementsService();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Service\BasicImplementsService', $this->service);
    }
}
