<?php
namespace MyModuleTest\GreatestTest;

use PHPUnit\Framework\TestCase;
use MyModule\Greatest\CompleteFactoriesService;

/**
 * @group Service
 */
class CompleteFactoriesServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->myDependencyOne = $this->prophesize('MyModule\Service\MyDependencyOne');
        $this->myDependencyTwo = $this->prophesize('MyModule\Logic\MyDependencyTwo');
        $this->myDependencyThree = $this->prophesize('MyModule\Mvc\MyDependencyThree');

        $this->service = new CompleteFactoriesService(
            $this->myDependencyOne->reveal(),
            $this->myDependencyTwo->reveal(),
            $this->myDependencyThree->reveal()
        );
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Greatest\CompleteFactoriesService', $this->service);
    }
}
