<?php
namespace MyModuleTest\BasicTest\FeatureTest\IssueTest\TaskTest;

use PHPUnit\Framework\TestCase;
use MyModule\Basic\Feature\Issue\Task\LongNamespaceService;

/**
 * @group Service
 */
class LongNamespaceServiceTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->service = new LongNamespaceService();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\Basic\Feature\Issue\Task\LongNamespaceService', $this->service);
    }
}
