<?php
namespace MyModuleTest\BestNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\BestNamespace\MySrcWithSpecialDependency;

/**
 * @group Service
 */
class MySrcWithSpecialDependencyTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->stringService = $this->prophesize('GearBase\Util\String\StringService');
        $this->console = $this->prophesize('Zend\Console\Adapter\Posix');
        $this->adapter = $this->prophesize('Zend\Db\Adapter\Adapter');

        $this->service = new MySrcWithSpecialDependency(
            $this->stringService->reveal(),
            $this->console->reveal(),
            $this->adapter->reveal()
        );
    }

    public function testClassExists()
    {
        $this->assertInstanceOf('MyModule\BestNamespace\MySrcWithSpecialDependency', $this->service);
    }
}
