<?php
namespace MyModule\Entity;

use GearBase\Entity\LogTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * MvcBasicUploadImage
 *
 * PHP Version 5
 *
 * @category Entity
 * @package MyModule/Entity
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 *
 * @ORM\Table(
 *     name="mvc_basic_upload_image",
 *     indexes={
 *         @ORM\Index(name="created_by", columns={"created_by"}),
 *         @ORM\Index(name="updated_by", columns={"updated_by"})
 *     }
 * )
 * @SuppressWarnings(PHPMD)

 * @ORM\Entity
 */
class MvcBasicUploadImage
{
    use LogTrait;

    /**
     * @var integer
     *
     * @ORM\Column(name="id_mvc_basic_upload_image", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $idMvcBasicUploadImage;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="clm_tme_bsc_upl", type="time", nullable=false)
     */
    private $clmTmeBscUpl;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="clm_dtt_bsc_upl", type="datetime", nullable=false)
     */
    private $clmDttBscUpl;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="clm_dte_bsc_upl", type="date", nullable=false)
     */
    private $clmDteBscUpl;

    /**
     * @var string
     *
     * @ORM\Column(name="clm_vrc_bsc_upl", type="string", length=150, nullable=false)
     */
    private $clmVrcBscUpl;

    /**
     * @var string
     *
     * @ORM\Column(name="clm_txt_bsc_upl", type="text", length=65535, nullable=false)
     */
    private $clmTxtBscUpl;

    /**
     * @var string
     *
     * @ORM\Column(name="clm_dcm_bsc_upl", type="decimal", precision=10, scale=2, nullable=false)
     */
    private $clmDcmBscUpl;

    /**
     * @var boolean
     *
     * @ORM\Column(name="clm_boo_bsc_upl", type="boolean", nullable=false)
     */
    private $clmBooBscUpl;

    /**
     * @var integer
     *
     * @ORM\Column(name="clm_int_bsc_upl", type="integer", nullable=false)
     */
    private $clmIntBscUpl;

    /**
     * Get idMvcBasicUploadImage
     *
     * @return integer
     */
    public function getIdMvcBasicUploadImage()
    {
        return $this->idMvcBasicUploadImage;
    }

    /**
     * Set clmTmeBscUpl
     *
     * @param \DateTime $clmTmeBscUpl Clm Tme Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmTmeBscUpl($clmTmeBscUpl)
    {
        $this->clmTmeBscUpl = $clmTmeBscUpl;

        return $this;
    }

    /**
     * Get clmTmeBscUpl
     *
     * @return \DateTime
     */
    public function getClmTmeBscUpl()
    {
        return $this->clmTmeBscUpl;
    }

    /**
     * Set clmDttBscUpl
     *
     * @param \DateTime $clmDttBscUpl Clm Dtt Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmDttBscUpl($clmDttBscUpl)
    {
        $this->clmDttBscUpl = $clmDttBscUpl;

        return $this;
    }

    /**
     * Get clmDttBscUpl
     *
     * @return \DateTime
     */
    public function getClmDttBscUpl()
    {
        return $this->clmDttBscUpl;
    }

    /**
     * Set clmDteBscUpl
     *
     * @param \DateTime $clmDteBscUpl Clm Dte Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmDteBscUpl($clmDteBscUpl)
    {
        $this->clmDteBscUpl = $clmDteBscUpl;

        return $this;
    }

    /**
     * Get clmDteBscUpl
     *
     * @return \DateTime
     */
    public function getClmDteBscUpl()
    {
        return $this->clmDteBscUpl;
    }

    /**
     * Set clmVrcBscUpl
     *
     * @param string $clmVrcBscUpl Clm Vrc Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmVrcBscUpl($clmVrcBscUpl)
    {
        $this->clmVrcBscUpl = $clmVrcBscUpl;

        return $this;
    }

    /**
     * Get clmVrcBscUpl
     *
     * @return string
     */
    public function getClmVrcBscUpl()
    {
        return $this->clmVrcBscUpl;
    }

    /**
     * Set clmTxtBscUpl
     *
     * @param string $clmTxtBscUpl Clm Txt Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmTxtBscUpl($clmTxtBscUpl)
    {
        $this->clmTxtBscUpl = $clmTxtBscUpl;

        return $this;
    }

    /**
     * Get clmTxtBscUpl
     *
     * @return string
     */
    public function getClmTxtBscUpl()
    {
        return $this->clmTxtBscUpl;
    }

    /**
     * Set clmDcmBscUpl
     *
     * @param string $clmDcmBscUpl Clm Dcm Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmDcmBscUpl($clmDcmBscUpl)
    {
        $this->clmDcmBscUpl = $clmDcmBscUpl;

        return $this;
    }

    /**
     * Get clmDcmBscUpl
     *
     * @return string
     */
    public function getClmDcmBscUpl()
    {
        return $this->clmDcmBscUpl;
    }

    /**
     * Set clmBooBscUpl
     *
     * @param boolean $clmBooBscUpl Clm Boo Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmBooBscUpl($clmBooBscUpl)
    {
        $this->clmBooBscUpl = $clmBooBscUpl;

        return $this;
    }

    /**
     * Get clmBooBscUpl
     *
     * @return boolean
     */
    public function getClmBooBscUpl()
    {
        return $this->clmBooBscUpl;
    }

    /**
     * Set clmIntBscUpl
     *
     * @param integer $clmIntBscUpl Clm Int Bsc Upl
     *
     * @return MvcBasicUploadImage
     */
    public function setClmIntBscUpl($clmIntBscUpl)
    {
        $this->clmIntBscUpl = $clmIntBscUpl;

        return $this;
    }

    /**
     * Get clmIntBscUpl
     *
     * @return integer
     */
    public function getClmIntBscUpl()
    {
        return $this->clmIntBscUpl;
    }
}
