<?php echo sprintf('<?php $this->headTitle()->prepend(\'Editar %s\');?>', $this->label).PHP_EOL;?>
<div ng-controller="<?php echo $this->class;?>EditController as edit">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="page-header">
<?php echo <<<EOS
                <?php echo \$this->translate('Edit');?>&nbsp;<?php echo \$this->translate('{$this->label}');?> - <?php echo \$this->id{$this->class};?>
EOS;
?>

            </h3>
        </div>
<?php if ($this->imageContainer) :?>
        <div class="row">
            <div class="col-lg-4 col-lg-offset-2">
                <a class="btn btn-primary" href="<?php echo sprintf('<?php echo $this->url(\'%s\', array(\'id\' => %s));?>', $this->routeImage, '$this->id'.$this->class).PHP_EOL;?>"><?php echo '<?php echo $this->translate(\'Editar Imagens\');?>';?></a>
            </div>
        </div>
<?php endif;?>
    </div>
<?php echo <<<EOS
    <?php if(\$this->success) : echo \$this->render('layout/success'); endif; ?>
    <?php if(\$this->error) : echo \$this->render('layout/error'); endif; ?>

EOS;
?>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
<?php

echo <<<EOS
            <?php
                \$form = \$this->form;
                \$form->setAttribute('action', \$this->url('{$this->route}', array('id' => \$this->id{$this->class})));
                \$form->prepare();
                echo \$this->form()->openTag(\$form);
                echo \$this->formHidden(\$form->get('id{$this->class}')->setAttribute('class','form-control'));
            ?>

EOS;
?>
<?php echo $this->formElements;?>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
<?php echo <<<EOS
                            <?php echo \$this->formSubmit(\$form->get('submit')->setAttribute('class','btn btn-default')->setAttribute('id', 'btn-save')); ?>
                            <a class="btn btn-default reset"
                               id="btn-back"
                                href="<?php echo \$this->url('{$this->routeBack}');?>">
                                <?php echo \$this->translate('Back');?>
                            </a>
                            <a id="btn-view" class="btn btn-info"
                                href="<?php echo \$this->url('{$this->routeView}', array('id' => \$this->id{$this->class}));?>">
                                <?php echo \$this->translate('View');?>
                            </a>
                            <a id="btn-create" class="btn btn-success"
                                href="<?php echo \$this->url('{$this->routeNew}');?>">
                                <?php echo \$this->translate('Create');?>
                            </a>

EOS;
?>
                        </div>
                    </div>
                </div>
            <?php echo '<?php echo $this->form()->closeTag(); ?>'.PHP_EOL; ?>
        </div>
    </div>
</div>