<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\Mvc\Router\Http\RouteMatch;
use MyModule\Custom\CustomNamespace\TableService;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group MyModule
 * @group TableService
 * @group Service
 */
class TableServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
        $this->zfcuserAuthService = $this->prophesize('Zend\Authentication\AuthenticationService');
        $this->imageService = $this->prophesize('GearImage\Service\ImageService');

        $this->service = new TableService(
            $this->repository->reveal(),
            $this->cache->reveal(),
            $this->zfcuserAuthService->reveal(),
            $this->imageService->reveal()
        );
    }

    public function mockUploadImage()
    {
        $maker = new \GearBaseTest\UploadImageMock();
        return $maker->mockUploadFile(\MyModule\Module::getLocation());
    }

    public function testSetSelectAllCache()
    {
        $this->service->setSessionName('testing');

        $data = $this->service->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
        $data = $this->service->setSelectAllCache(array('data' => true));
        $this->assertEquals(array('data' => true), $data);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->service->setRouteMatch($this->getRouteMatch(1, 'idTable', 'DESC'));

        $this->assertEquals('idTable', $this->service->getOrderBy());
        $this->assertEquals('DESC', $this->service->getOrder());

        $this->service->selectAll();

        $this->service->setRouteMatch($this->getRouteMatch(1, 'idTable', 'ASC'));

        $this->assertEquals('idTable', $this->service->getOrderBy());
        $this->assertEquals('ASC', $this->service->getOrder());

        $this->service->setRouteMatch(
            $this->getRouteMatch(1, 'idTable', 'DESC')
        );

        $this->assertEquals(
            'idTable',
            $this->service->getOrderBy()
        );
        $this->assertEquals('DESC', $this->service->getOrder());
    }

    public function testTableHead()
    {
        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->getMapReferences()->willReturn([***REMOVED***)->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $resultSet = $this->service->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $this->entity = $this->prophesize('MyModule\Entity\Table');
        $this->entity->getIdTable()->willReturn(1);

        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->selectById(1)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $resultSet = $this->service->selectById(1);
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(1, $resultSet->getIdTable());
    }

    public function testSelectOne()
    {
        $this->entity = $this->prophesize('MyModule\Entity\Table');
        $this->entity->getIdTable()->willReturn(30);

        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->selectOneBy(['idTable' => 30***REMOVED***)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $resultSet = $this->service->selectOneBy(
            array(
                'idTable' =>
                    30
            )
        );
        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(
            30,
            $resultSet->getIdTable()
        );
    }

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
            'uploadImageColumn' => 'image123',
        );

        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->createUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->service->create($data);

        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = array(
            'uploadImageColumn' => 'image123',
        );

        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $this->service->setCache($this->cache->reveal());

        $this->imageService->overwriteImage(
            ["uploadImageColumn" => "image123"***REMOVED***,
            "table",
            "uploadImageColumn"
        )->willReturn('tableuploadimagecolumn')->shouldBeCalled();

        $this->imageService->updateUploadImage(
            'tableuploadimagecolumn',
            'table-uploadImageColumn',
            'image123'
        )->shouldBeCalled();

        $resultSet = $this->service
            ->update(31, $data);


        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);
        $this->assertEquals(31, $resultSet->getIdTable());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->service->setCache($this->cache->reveal());

        $resultSet = $this->service->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $resultSet = $this->service->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('MyModule\Entity\Table');
        $entity->getIdTable()->willReturn(31);

        $data = ['idTableService' => 31***REMOVED***;
        $this->repository = $this->prophesize('MyModule\Custom\CustomNamespace\TableRepository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();

        $this->service->setTableRepository($this->repository->reveal());

        $resultSet = $this->service->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'idTable', $order = 'DESC')
    {
        $routeMatch = new RouteMatch(array(
            'controller' => 'MyModule\Controller\Table',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('my-module/table');
        return $routeMatch;
    }
}
