<?php
namespace MyModuleTest\MyTableTableTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\Mvc\Router\Http\RouteMatch;
use MyModule\MyTableTable\MyTableTableService;

/**
 * @SuppressWarnings(PHPMD.TooManyMethods)
 * @group MyModule
 * @group MyTableTableService
 * @group Service
 */
class MyTableTableServiceTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->cache = $this->prophesize('Zend\Cache\Storage\Adapter\Memcached');
        $this->zfcuserAuthService = $this->prophesize('Zend\Authentication\AuthenticationService');
        $this->imageService = $this->prophesize('GearImage\Service\ImageService');

        $this->service = new MyTableTableService(
            $this->repository->reveal(),
            $this->cache->reveal(),
            $this->zfcuserAuthService->reveal(),
            $this->imageService->reveal()
        );
    }

    public function testSetSelectAllCache()
    {
        $this->service->setSessionName('testing');

        $data = ['data' => true***REMOVED***;

        $this->cache->hasItem('testingResult')->willReturn(null);
        $this->cache->addItem('testingResult', $data)->willReturn(null);
        $this->cache->getItem('testingResult')->willReturn($data);

        $selected = $this->service->setSelectAllCache($data);
        $this->assertEquals($data, $selected);
        $selected = $this->service->setSelectAllCache($data);
        $this->assertEquals($data, $selected);
    }

    public function testSelectAllCacheWithCache()
    {
        $this->service->setRouteMatch($this->getRouteMatch(1, 'idMyTableTable', 'DESC'));

        $this->assertEquals('idMyTableTable', $this->service->getOrderBy());
        $this->assertEquals('DESC', $this->service->getOrder());

        $this->service->selectAll();

        $this->service->setRouteMatch($this->getRouteMatch(1, 'idMyTableTable', 'ASC'));

        $this->assertEquals('idMyTableTable', $this->service->getOrderBy());
        $this->assertEquals('ASC', $this->service->getOrder());

        $this->service->setRouteMatch(
            $this->getRouteMatch(1, 'idMyTableTable', 'DESC')
        );

        $this->assertEquals(
            'idMyTableTable',
            $this->service->getOrderBy()
        );
        $this->assertEquals('DESC', $this->service->getOrder());
    }

    public function testTableHead()
    {
        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->repository->getMapReferences()->willReturn([***REMOVED***)->shouldBeCalled();

        $this->service->setMyTableTableRepository($this->repository->reveal());

        $resultSet = $this->service->getTableHead();
        $this->assertTrue(is_array($resultSet));
    }

    public function testSelectById()
    {
        $this->entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $this->entity->getIdMyTableTable()->willReturn(1);

        $this->repository->selectById(1)->willReturn($this->entity->reveal())->shouldBeCalled();

        $resultSet = $this->service->selectById(1);
        $this->assertInstanceOf('MyModule\Entity\MyTableTable', $resultSet);
        $this->assertEquals(1, $resultSet->getIdMyTableTable());
    }

    public function testSelectOne()
    {
        $this->entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $this->entity->getIdMyTableTable()->willReturn(30);

        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->repository->selectOneBy(['idMyTableTable' => 30***REMOVED***)->willReturn($this->entity->reveal())->shouldBeCalled();

        $this->service->setMyTableTableRepository($this->repository->reveal());

        $resultSet = $this->service->selectOneBy(
            array(
                'idMyTableTable' =>
                    30
            )
        );
        $this->assertInstanceOf('MyModule\Entity\MyTableTable', $resultSet);
        $this->assertEquals(
            30,
            $resultSet->getIdMyTableTable()
        );
    }

    /**
     * @group service.create
     */
    public function testCreate()
    {
        $entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $entity->getIdMyTableTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->repository->insert($data)->willReturn($entity)->shouldBeCalled();

        $this->service->setMyTableTableRepository($this->repository->reveal());


        $resultSet = $this->service->create($data);

        $this->assertInstanceOf('MyModule\Entity\MyTableTable', $resultSet);
        $this->assertEquals(31, $resultSet->getIdMyTableTable());

        return $resultSet;
    }

    /**
     * @group service.update
     */
    public function testUpdate()
    {
        $entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $entity->getIdMyTableTable()->willReturn(31);

        $data = array(
        );

        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->repository->update(31, $data)->willReturn($entity)->shouldBeCalled();

        $this->service->setMyTableTableRepository($this->repository->reveal());

        $this->service->setCache($this->cache->reveal());


        $resultSet = $this->service->update(31, $data);


        $this->assertInstanceOf('MyModule\Entity\MyTableTable', $resultSet);
        $this->assertEquals(31, $resultSet->getIdMyTableTable());

        return $resultSet;
    }

    /**
     * @group service.delete
     */
    public function testDelete()
    {
        $entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $entity->getIdMyTableTable()->willReturn(31);

        $this->repository->selectById(31)->willReturn($entity->reveal())->shouldBeCalled();
        $this->repository->deleteSafe($entity->reveal())->willReturn(true)->shouldBeCalled();

        $this->service->setCache($this->cache->reveal());

        $resultSet = $this->service->delete(31);
        $this->assertTrue($resultSet);
    }

    /**
     * @group service.delete
     */
    public function testDeleteWithoutExistingData()
    {
        $this->repository->selectById(31)->willReturn(false)->shouldBeCalled();

        $resultSet = $this->service->delete(31);
        $this->assertFalse($resultSet['success'***REMOVED***);
        $this->assertEquals('EntityNotFound', $resultSet['error'***REMOVED***);
    }

    /**
     * @group service.extract
     */
    public function testExtract()
    {
        $entity = $this->prophesize('MyModule\Entity\MyTableTable');
        $entity->getIdMyTableTable()->willReturn(31);

        $data = ['idMyTableTableService' => 31***REMOVED***;
        $this->repository = $this->prophesize('MyModule\MyTableTable\MyTableTableRepository');
        $this->repository->extract($entity)->willReturn($data)->shouldBeCalled();

        $this->service->setMyTableTableRepository($this->repository->reveal());

        $resultSet = $this->service->extract($entity->reveal());
        $this->assertEquals($data, $resultSet);
    }

    public function getRouteMatch($page, $orderBy = 'idMyTableTable', $order = 'DESC')
    {
        $routeMatch = new RouteMatch(array(
            'controller' => 'MyModule\Controller\MyTableTable',
            'action'     => 'list',
            'page' => $page,
            'orderBy' => $orderBy,
            'order' => $order
        ));

        $routeMatch->setMatchedRouteName('my-module/my-table-table');
        return $routeMatch;
    }
}
