{
        "optimize": {
                "js": {
                        "files": {
                                "internal": [
                                        "./vendor/mauriciopiber/gear-admin/public/js/internal.js"
                                ***REMOVED***,
                                "external": [
                                        "./vendor/mauriciopiber/gear-admin/public/js/external.js"

                                ***REMOVED***
                        }
                },
                "css": {
                        "files": [
                                "./vendor/mauriciopiber/gear-admin/public/css/external.css"
                        ***REMOVED***
                }
        }
}

