namespace <?php echo $this->module;?>\Filter;

use GearBase\Filter\AbstractFilter;

/**
 * Filter for <?php echo $this->tableLabel;?> Controller.
 *
 * PHP Version 5
 *
 * @category Filter
 * @package <?php echo $this->package.PHP_EOL;?>
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class <?php echo $this->class;?> extends AbstractFilter
{

    /**
     * Get The Input Filter
     *
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     *
     * @return <?php echo $this->class.PHP_EOL;?>
     */
<?php echo $this->header;?>
    {
<?php echo $this->filterElements;?>
        return $this;
    }
}
