namespace <?php echo $this->namespace;?>;

<?php echo $this->use;?>

<?php echo $this->classDocs;?>
class <?php echo $this->class;?> extends <?php echo $this->extends;?><?php echo $this->implements;?>
{
<?php echo ($this->attributes) ? $this->attributes : '';?>
<?php echo (!empty($attributes) && !empty($constructor)) ? PHP_EOL : '';?>
<?php echo $this->constructor;?>
<?php echo (empty($attributes) && !empty($constructor)) ? PHP_EOL : '';?>
    /**
     * Create the Filter to Form Elements
     *
     * @return <?php echo $this->class.PHP_EOL;?>
     *
     */
    public function getInputFilter()
    {
        return $this;
    }
}
