namespace <?php echo $this->namespace;?>;

<?php echo $this->use;?>
<?php echo $this->classDocs;?>
class <?php echo $this->class;?> extends <?php echo $this->extends.PHP_EOL;?>
{
    /**
     * Create the Filter to Form Elements
     *
     * @return \<?php echo $this->namespace;?>\<?php echo $this->class.PHP_EOL;?>
     *
     */
    public function getInputFilter()
    {
        return $this;
    }
}
