<?php echo sprintf('<?php $this->headTitle()->prepend(\'Visualizar %s\');?>', $this->label).PHP_EOL;?>
<div ng-controller="<?php echo $this->class;?>ViewController as view">
    <div class="row">
        <div class="col-lg-12">
            <h3 class="page-header">
                <?php echo '<?php echo $this->translate(\'View\');?>&nbsp;';?><?php echo sprintf('<?php echo $this->translate(\'%s\');?>', $this->label);?> - <?php echo sprintf('<?php echo $this->id%s;?>', $this->class).PHP_EOL;?>
            </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
            <div class="form-group">
                <table class="table table-bordered table-hover">
                    <tbody>
<?php foreach ($this->values as $value) :?>
<?php echo $value; ?>
<?php endforeach;?>
                    </tbody>
                </table>
            </div>
<?php echo $this->images;?>
<?php echo $this->actions.PHP_EOL;?>
        </div>
    </div>
    <gear-delete-dialog
        title="Deletar <?php echo $this->label;?>"
        body="Desejas deletar o <?php echo $this->label;?> #{{view.getLastExclude()}}?"
        confirm="Deletar"
        close-dialog-delete="view.closeDialogDelete()"
        confirm-dialog-delete="view.confirmDialogDelete()"
    >
    </gear-delete-dialog>
</div>