<?php
namespace MyModuleTest\FastestNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\ServiceManager\ServiceLocatorInterface;
use MyModule\FastestNamespace\MySrcWithSpecialDependencyFactory;
use MyModule\FastestNamespace\MySrcWithSpecialDependency;
use GearBase\Util\String\StringService;
use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;

/**
 * @group MyModule
 * @group MySrcWithSpecialDependency
 * @group Repository
 */
class MySrcWithSpecialDependencyFactoryTest extends TestCase
{
    public function testMySrcWithSpecialDependencyFactory()
    {
        $this->serviceLocator = $this->prophesize(ServiceLocatorInterface::class);

        $this->serviceLocator->get('GearBase\Util\String')
            ->willReturn($this->prophesize(StringService::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get('console')
            ->willReturn($this->prophesize(Posix::class)->reveal())
            ->shouldBeCalled();

        $this->serviceLocator->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();

        $factory = new MySrcWithSpecialDependencyFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf(MySrcWithSpecialDependency::class, $instance);
    }
}
