<?php
namespace MyModuleTest\BestNamespaceTest;

use PHPUnit\Framework\TestCase;
use Interop\Container\ContainerInterface;
use MyModule\BestNamespace\MySrcWithSpecialDependencyFactory;
use MyModule\BestNamespace\MySrcWithSpecialDependency;
use Gear\Util\String\StringService;
use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;

/**
 * @group MyModule
 * @group MySrcWithSpecialDependency
 * @group Service
 */
class MySrcWithSpecialDependencyFactoryTest extends TestCase
{
    public function testMySrcWithSpecialDependencyFactory()
    {
        $this->container = $this->prophesize(ContainerInterface::class);

        $this->container->get('Gear\Util\String\StringService')
            ->willReturn($this->prophesize(StringService::class)->reveal())
            ->shouldBeCalled();

        $this->container->get('console')
            ->willReturn($this->prophesize(Posix::class)->reveal())
            ->shouldBeCalled();

        $this->container->get(Adapter::class)
            ->willReturn($this->prophesize(Adapter::class)->reveal())
            ->shouldBeCalled();

        $factory = new MySrcWithSpecialDependencyFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf(MySrcWithSpecialDependency::class, $instance);
    }
}
