<?php
namespace MyModuleTest\BestNamespaceTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\BestNamespace\MySrcWithSpecialDependencyFactory;

/**
 * @group MyModule
 * @group MySrcWithSpecialDependency
 * @group Service
 */
class MySrcWithSpecialDependencyFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->serviceLocator    = $this->prophesize('Zend\ServiceManager\ServiceLocatorInterface');

        $factory = new MySrcWithSpecialDependencyFactory();

        $instance = $factory->createService($this->serviceLocator->reveal());

        $this->assertInstanceOf('MyModule\BestNamespace\MySrcWithSpecialDependency', $instance);
    }
}
