<?php
namespace MyModule\CompleteController;

use Zend\View\Model\JsonModel;
use MyModule\Controller\BasicController;

/**
 * PHP Version 5
 *
 * @category Controller
 * @package MyModule/CompleteController
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicRest extends BasicController
{

}
