<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use Zend\Mvc\Controller\ControllerManager;
use MyModule\Controller\IndexController;
use MyModule\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function setUp() : void
    {
        $this->factory = new IndexControllerFactory();

    }

    public function testCreateFactory()
    {
        $this->container = $this->prophesize(ControllerManager::class);
        $instance = $this->factory->__invoke($this->container->reveal(), null);
        $this->assertInstanceOf(IndexController::class, $instance);
    }
}
