<?php
namespace MyModuleTest\AnotherTest\LongTest\NamespacesTest;

use PHPUnit\Framework\TestCase;
use MyModule\Another\Long\Namespaces\BasicFactoryNamespaceConsole;
use Zend\Console\Request;
use Zend\Mvc\MvcEvent;
use Zend\Router\RouteMatch;

/**
 * @group BasicFactoryNamespaceConsole
 * @group Controller
 */
class BasicFactoryNamespaceConsoleTest extends TestCase
{

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp() : void
    {
        parent::setUp();

        $this->controller = new BasicFactoryNamespaceConsole();

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'BasicFactoryNamespaceConsole'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
