<?php
namespace MyModuleTest\ConsolistsNamespaceTest;

use Zend\Test\PHPUnit\Controller\AbstractConsoleControllerTestCase as TestCase;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;
use Zend\Console\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;
use GearBaseTest\Assertions\AclAssertTrait;

/**
 * @group SpecialDependencyConsole
 * @group Controller
 */
class SpecialDependencyConsoleTest extends TestCase
{
    use AclAssertTrait;

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp()
    {
        $this->setApplicationConfig(
            include \GearBase\Module::getProjectFolder().'/config/application.config.php'
        );

        parent::setUp();

        $this->stringService = $this->prophesize('Gear\Util\String\StringService');
        $this->console = $this->prophesize('Zend\Console\Adapter\Posix');
        $this->adapter = $this->prophesize('Zend\Db\Adapter\Adapter');

        $this->controller = new SpecialDependencyConsole(
            $this->stringService->reveal(),
            $this->console->reveal(),
            $this->adapter->reveal()
        );

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'SpecialDependencyConsole'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this->schema = (new \MyModule\Module())->getLocation().'/../schema/module.json';
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
