<?php
namespace MyModuleTest\ConsolistsNamespaceTest;

use PHPUnit\Framework\TestCase;
use MyModule\ConsolistsNamespace\SpecialDependencyConsole;
use Zend\Console\Request;
use Zend\Mvc\MvcEvent;
use Zend\Router\RouteMatch;

/**
 * @group SpecialDependencyConsole
 * @group Controller
 */
class SpecialDependencyConsoleTest extends TestCase
{

    protected $controller;
    protected $request;
    protected $response;
    protected $routeMatch;
    protected $event;

    public function setUp() : void
    {
        parent::setUp();

        $this->stringService = $this->prophesize('Gear\Util\String\StringService');
        $this->console = $this->prophesize('Zend\Console\Adapter\Posix');
        $this->adapter = $this->prophesize('Zend\Db\Adapter\Adapter');

        $this->controller = new SpecialDependencyConsole(
            $this->stringService->reveal(),
            $this->console->reveal(),
            $this->adapter->reveal()
        );

        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'SpecialDependencyConsole'));
        $this->event      = new MvcEvent();
        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);
    }

    public function test404()
    {
        $this->routeMatch->setParam('action', 'action-that-doesnt-exist');
        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(404, $response->getStatusCode());
    }
}
