<?php
namespace MyModuleTest\ControllerTest;

use Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase as TestCase;
use MyModule\Controller\TableController;
use Zend\Http\Request;
use Zend\Mvc\MvcEvent;
use Zend\Mvc\Router\RouteMatch;

/**
 * @group MyModule
 * @group Table
 * @group Controller
 */
class TableControllerTest extends TestCase
{

    public function setUp()
    {
        $this->setApplicationConfig(
            include \GearBase\Module::getProjectFolder().'/config/application.config.php'
        );
        parent::setUp();

        $this->controller = new TableController();
        $this->request    = new Request();
        $this->routeMatch = new RouteMatch(array('controller' => 'TableController'));
        $this->event      = new MvcEvent();

        $this->event->setRouteMatch($this->routeMatch);
        $this->controller->setEvent($this->event);

        $this->tableForm = $this->prophesize('MyModule\Form\TableForm');
        $uploadImageColumn = $this->prophesize('Zend\Form\Element\File');
        $uploadImageColumn->getMessages()->willReturn(['no-file' => true***REMOVED***);
        $this->tableForm->get('uploadImageColumn')->willReturn($uploadImageColumn->reveal());
        $this->tableSearchForm = $this->prophesize('MyModule\Form\Search\TableSearchForm');
        $this->tableService = $this->prophesize('MyModule\Service\TableService');

        $requestPlugin = new \GearBase\Controller\Plugin\RequestPlugin();
        $this->controller->getPluginManager()->setService('getRequestPlugin', $requestPlugin);

        $this->url = $this->prophesize('Zend\Mvc\Controller\Plugin\Url');
        $this->controller->getPluginManager()->setService('url', $this->url->reveal());

        $this->controller->setTableForm($this->tableForm->reveal());
        $this->controller->setTableService($this->tableService->reveal());
        $this->controller->setTableSearchForm($this->tableSearchForm->reveal());
    }

    protected function tearDown()
    {
        $refl = new \ReflectionObject($this);
        foreach ($refl->getProperties() as $prop) {
            if (!$prop->isStatic() && 0 !== strpos($prop->getDeclaringClass()->getName(), 'PHPUnit_')) {
                $prop->setAccessible(true);
                $prop->setValue($this, null);
            }
        }
    }

    /**
     * @group controller.create
     */
    public function testEnterCreatePage()
    {
        $this->routeMatch->setParam('action', 'create');

        $result = $this->controller->dispatch($this->request);
        $response = $this->controller->getResponse();
        $this->assertEquals(200, $response->getStatusCode());
        $this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
    }

    /**
     * @group Controller.Create
     */
    public function testWhenCreateDisplaySuccessfulWithRedirect()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/criar', 'POST', array());
        $this->assertResponseStatusCode(303);
        $this->assertRedirectTo('/my-module/table/criar');
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('create');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/create');
    }

    public function testWhenEditDisplaySuccessful()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/editar');
        $this->assertResponseStatusCode(302);
        $this->assertRedirectTo('/my-module/table/listar/page//orderBy');
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('edit');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/edit');
    }

    public function testWhenEditRedirectWithInvalidIdToListing()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/editar/6000');
        $this->assertResponseStatusCode(302);
        $this->assertRedirectTo('/my-module/table/listar/page//orderBy');
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('edit');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/edit');
    }


    public function testWhenListDisplaySuccessful()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('MyModule\Service\TableService');
        $this->dispatch('/my-module/table/listar');
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('list');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/list');
    }


    public function testWhenFilterWithoutData()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('MyModule\Service\TableService');
        $this->dispatch('/my-module/table/listar', 'POST', array());
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('list');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/list');
    }


    public function testWhenFilterWithoutDataWithPRG()
    {
        $this->mockUser();
        $this->mockServiceSelectAll('MyModule\Service\TableService');
        $this->dispatch('/my-module/table/listar', 'POST', array());
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('list');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/list');
    }


    public function testDeleteSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/excluir/6000');
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('delete');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/delete');
    }


    public function testWhenDeleteDisplaySuccessful()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/excluir');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('delete');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/delete');
    }


    public function testViewSucessfullAndRedirectToListWithFailNotFound()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/visualizar/6000');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('MyModule');
        $this->assertRedirectTo('/my-module/table/listar/page//orderBy');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('view');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/view');
    }

    public function testWhenViewDisplaySuccessful()
    {
        $this->mockUser();
        $this->dispatch('/my-module/table/visualizar');
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('view');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/view');
    }

    /**
     * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
     * @group Controller.Create
     */
    // enviar submit da tela com dados completo,
    // ser adicionado o elemento e redirecionado para página de editar com sucesso = 1.
    public function testCreateSuccess()
    {
        $newData = array(
        );
        $this->mockUser();
        $this->mockPluginPostRedirectGet($newData);
        $this->dispatch('/my-module/table/criar', 'POST', $newData);
        $this->assertResponseStatusCode(302);

        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('create');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/create');


        $resultSet =  $this->bootstrap
            ->getEntityManager()
            ->getRepository('MyModule\Entity\Table')
            ->findOneBy(
                array(
                ),
                array('idTable' => 'DESC')
            );

        $this->assertInstanceOf('MyModule\Entity\Table', $resultSet);

        $this->assertRedirectTo(
            sprintf(
                '/my-module/table/editar/%d/1',
                $resultSet->getIdTable()
            )
        );


        return $resultSet;
    }

   /**
     * @depends testCreateSuccess
     */
    public function testWhenListDisplaySuccessfulWithValidId($resultSet)
    {
        $this->mockUser();

        $this->dispatch(
            '/my-module/table/editar/'.$resultSet->getIdTable()
        );

        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('edit');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/edit');
    }

    /**
     * @depends testCreateSuccess
     */
    public function testWhenViewDisplaySuccessfulWithValidId($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            '/my-module/table/visualizar/'.$resultSet->getIdTable()
        );

        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('view');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/view');
    }

    /**
     * @depends testCreateSuccess
     */
    public function testWhenListRedirectSuccessfulPRGWithValidId($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            '/my-module/table/editar/'.$resultSet->getIdTable(),
            'POST'
        );

        $this->assertResponseStatusCode(303);
        $this->assertRedirectTo(
            '/my-module/table/editar/'.$resultSet->getIdTable()
        );
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('edit');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/edit');
    }

    /**
     * @depends testCreateSuccess
     */
    public function testEditAfterCreateOk($resultSet)
    {

        $newData = array(
            'dateColumn' => '2012-10-28',
            'datePtBrColumn' => '28/10/2012',
            'datetimeColumn' => '2012-10-28 10:00:58',
            'datetimePtBrColumn' => '28/10/2012 10:00:58',
            'timeColumn' => '10:00:58',
            'decimalColumn' => '58.58',
            'moneyPtBrColumn' => 'R$ 58,58',
            'checkboxColumn' => '0',
            'idForeignKeyColumn' => '28',
            'intColumn' => '58',
            'htmlColumn' => '58Html Column',
            'textColumn' => '58Text Column',
            'tinyintColumn' => '0',
            'checkboxColumn' => '0',
            'emailColumn' => 'email.column58@gmail.com',
            'passwordVerifyColumn' => '58PasswordVerifyColu',
            'passwordVerifyColumnVerify' => '58PasswordVerifyColu',
            'telephoneColumn' => '(51) 9999-9958',
            'uploadImageColumn' => array(
                'error' => 0,
                'name' => 'uploadImageColumn58insert.gif',
                'tmp_name' => $this->mockUploadImage(),
                'type'      =>  'image/gif',
                'size'      =>  42,
            ),
            'urlColumn' => 'url.column58.com.br',
            'varcharColumn' => '58Varchar Column',
        );
        $this->mockUser();
        $this->mockPluginPostRedirectGet($newData);
        $this->dispatch(
            '/my-module/table/editar/'.$resultSet->getIdTable(),
            'POST',
            $newData
        );
        $this->assertResponseStatusCode(302);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('edit');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/edit');

        $this->assertRedirectTo(
            sprintf(
                '/my-module/table/editar/%d/1',
                $resultSet->getIdTable()
            )
        );
    }
    public function testCantCreateWithWrongImage()
    {
        $newData = array(

        );
        $this->mockUser();
        $this->mockPluginPostRedirectGet($newData);
        $this->mockPluginFilePostRedirectGet($newData);
        $this->dispatch('/my-module/table/criar', 'POST', $newData);
        $this->assertResponseStatusCode(200);

        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('create');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/create');
    }
     /**
     * @depends testCreateSuccess
     */
    public function testDeleteAfterEditOk($resultSet)
    {
        $this->mockUser();
        $this->dispatch(
            sprintf(
                '/my-module/table/excluir/%d',
                $resultSet->getIdTable()
            )
        );
        $this->assertResponseStatusCode(200);
        $this->assertModuleName('MyModule');
        $this->assertControllerName('MyModule\Controller\Table');
        $this->assertActionName('delete');
        $this->assertControllerClass('TableController');
        $this->assertMatchedRouteName('my-module/table/delete');
    }
}
