<?php
namespace MyModule\Service;

use GearBase\Service\AbstractService;
use GearBase\Service\PasswordVerifyTrait;
use GearImage\Service\ImageServiceTrait;

class TableService extends AbstractService
{
    use PasswordVerifyTrait;
    use ImageServiceTrait;

    protected $sessionName;

    protected $authService;

    public function getTableHead()
    {
        $map = $this->getTableRepository()->getMapReferences();
        return $this->getTableHeadFromMap($map);
    }

    public function getSessionName()
    {
        if (!isset($this->sessionName)) {
            $this->sessionName = 'tableSession';
        }
        return $this->sessionName;
    }

    public function selectOneBy(array $data)
    {
        return $this->getTableRepository()->selectOneBy($data);
    }

    public function selectAll($select = array())
    {
        $this->cache      = $this->getCache();
        $this->repository = $this->getTableRepository();

        return parent::selectAll($select);

    }

    public function create($data)
    {
        $repository = $this->getTableRepository();

        $this->createPassword('passwordVerifyColumn');
        $uploadImageColumn = $this->getImageService()->overwriteImage(
            $data,
            'table',
            'uploadImageColumn'
        );

        $table = $repository->insert($data);
        if ($table) {
            if (isset($data['uploadImageColumn'***REMOVED***)) {
                $this->getImageService()->createUploadImage(
                    $uploadImageColumn,
                    'table-uploadImageColumn',
                    $data['uploadImageColumn'***REMOVED***
                );
            }
            $this->clearCache();
        }
        return $table;
    }

    public function update($idTable, $data = array())
    {
        $repository = $this->getTableRepository();

        $this->createPassword('passwordVerifyColumn');
        $uploadImageColumn = $this->getImageService()->overwriteImage(
            $data,
            'table',
            'uploadImageColumn'
        );

        $table = $repository->update($idTable, $data);
        if ($table) {
            if (isset($data['uploadImageColumn'***REMOVED***)) {
                $this->getImageService()->updateUploadImage(
                    $uploadImageColumn,
                    'table-uploadImageColumn',
                    $data['uploadImageColumn'***REMOVED***
                );
            }
            $this->clearCache();
        }
        return $table;
    }

    public function delete($idTable)
    {
        $entity = $this->selectById($idTable);

        if (!$entity) {
            return ['success' => false, 'error' => 'EntityNotFound'***REMOVED***;
        }

        $repository = $this->getTableRepository();
        $table = $repository->deleteSafe($entity);


        if ($table) {
            $this->getImageService()->deleteImages($idTable, 'table');
            $this->getImageService()->deleteUploadImage($idTable, 'table');
            $this->clearCache();
        }
        return $table;
    }

    public function extract(\MyModule\Entity\Table $data)
    {
        $repository = $this->getTableRepository();
        return $repository->extract($data);
    }

    public function selectById($idToSelect)
    {
        $repository = $this->getTableRepository();
        return $repository->selectById($idToSelect);
    }
}
