<?php
namespace MyModule\BestNamespace;

use Zend\Console\Adapter\Posix;
use Zend\Db\Adapter\Adapter;
use GearBase\Util\String\StringServiceTrait;
use GearBase\Util\String\StringService;

/**
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/BestNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MySrcWithSpecialDependency
{
    use StringServiceTrait;

    /**
     * Constructor
     *
     * @param Posix         $console       Console
     * @param Adapter       $adapter       Adapter
     * @param StringService $stringService String Service
     *
     * @return \MyModule\BestNamespace\MySrcWithSpecialDependency
     */
    public function __construct(Posix $console, Adapter $adapter, StringService $stringService)
    {
        $this->console = $console;
        $this->adapter = $adapter;
        $this->stringService = $stringService;
        return $this;
    }
}
