<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use MyModule\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {

        $factory = new IndexControllerFactory();

        $instance = $factory->createService($this->container->reveal());

        $this->assertInstanceOf('MyModule\Controller\IndexController', $instance);
    }
}
