<?php
namespace MyModuleTest\ControllerTest;

use PHPUnit\Framework\TestCase;
use MyModule\Controller\IndexControllerFactory;

class IndexControllerFactoryTest extends TestCase
{
    public function testCreateFactory()
    {
        $this->container = $this->prophesize('Zend\Mvc\Controller\ControllerManager');

        $factory = new IndexControllerFactory();

        $instance = $factory->__invoke($this->container->reveal(), null);

        $this->assertInstanceOf('MyModule\Controller\IndexController', $instance);
    }
}
