(function () {
    'use strict';

    angular.module('GearApp').controller('<?=$this->controller;?>ListController', <?=$this->controller;?>ListController);

    function <?=$this->controller;?>ListController(exclude, filter, order) {

        var vm;
        vm = this;

        vm.data                  = data;<?php echo $this->userId;?>

        vm.order                 = order.order;
        vm.order.sortKey         = 'id<?=$this->controller;?>';
        vm.order.reverse         = true;

        vm.filter                = filter.filter;

        vm.exclude               = exclude.exclude;
        vm.exclude.url           = '/<?=$this->moduleUrl;?>/<?=$this->controllerUrl;?>/excluir';
        vm.exclude.id            = 'id<?=$this->controller;?>';
        vm.exclude.name          = '<?=$this->label;?>';
        vm.exclude.successDelete = successDelete;

        vm.getLastExclude        = vm.exclude.getLastExclude;
        vm.closeDialogDelete     = vm.exclude.closeDialog;
        vm.confirmDialogDelete   = vm.exclude.confirmExclude;

        function successDelete()
        {
            vm.data = vm.data.filter(function( obj ) {
                return obj[vm.exclude.id***REMOVED*** !== vm.exclude.lastExclude;
            });
            vm.exclude.showSuccessMessage();
        }
    }

    <?=$this->controller;?>ListController.$inject = ['exclude', 'filter', 'order'***REMOVED***;
}());