<project name="<?php echo $this->moduleName;?>" default="build" basedir=".">
    <target name="build" depends="prepare, set-vendor, parallel-lint, protractor, karma, jshint-ci, phpcs-ci, phpmd-ci, phpcpd-ci, buildHelper, unit-ci, phploc-ci, pdepend, phpdox" />
    <target name="dev" depends="prepare, set-vendor, parallel-lint, phpcs, phpmd, phpcpd, unit" />
    <target name="js" depends="prepare, set-vendor, protractor, karma, jshint" />

	<target name="protractor">
		 <exec executable="${basedir}/node_modules/.bin/protractor" >
		 	<arg value="protractor.conf.js" />
		 </exec>
	</target>

	<target name="karma">
		 <exec executable="${basedir}/node_modules/.bin/karma" >
		 	<arg value="start" />
		 </exec>
	</target>

	<target name="jshint-ci">
        	<exec executable="${basedir}/node_modules/.bin/jshint" >
                <arg value="--jslint-reporter" />
	        <arg value="${basedir}/public/js/app" />
	        <redirector output="build/logs/jshint.xml" alwayslog="true"/>
	    </exec>
	</target>
	<target name="jshint">
        	<exec executable="${basedir}/node_modules/.bin/jshint" >
	        <arg value="${basedir}/public/js/app" />
	    </exec>
	</target>

    <target name="parallel-lint" depends="set-vendor" description="Run PHP parallel lint For Continuous Integration">
        <exec executable="${vendor}/bin/parallel-lint" failonerror="true">
            <arg line="--exclude" />
            <arg path="${basedir}/vendor" />
            <arg line="--exclude" />
            <arg path="${basedir}/node_modules" />
            <arg path="${basedir}" />
        </exec>
    </target>

    <target name="phpmd" description="MessDetector" depends="set-vendor">
        <exec executable="${vendor}/bin/phpmd">
            <arg path="${basedir}/src" />
            <arg value="text" />
            <arg value="${basedir}/config/jenkins/phpmd.xml" />
        </exec>
    </target>
    <target name="phpmd-ci" description="PHPMD" depends="set-vendor">
        <exec executable="${vendor}/bin/phpmd">
            <arg path="${basedir}/src" />
            <arg value="xml" />
            <arg value="${basedir}/config/jenkins/phpmd.xml" />
            <arg value="--reportfile" />
            <arg value="${basedir}/build/logs/pmd.xml" />
            <arg value="--exclude" />
            <arg value="test/_support/_generated" />
        </exec>
    </target>
    <target name="phpcs" description="Code Sniffer" depends="set-vendor">
        <exec executable="${vendor}/bin/phpcs">
            <arg value="--standard=PSR2" />
            <arg path="${basedir}" />
            <arg value="--ignore=public" />
            <arg value="--ignore=data" />
            <arg value="--ignore=build" />
            <arg value="--ignore=vendor" />
            <arg value="--ignore=node_modules" />
            <arg value="--ignore=test/_support/_generated" />
        </exec>
    </target>
    <target name="phpcs-ci" description="PHP_CodeSniffer Continuous Integration" depends="set-vendor">
        <exec executable="${vendor}/bin/phpcs" output="/dev/null">
            <arg value="--report=checkstyle" />
            <arg value="--report-file=${basedir}/build/logs/checkstyle.xml" />
            <arg value="--standard=PSR2" />
            <arg path="${basedir}/" />
            <arg value="--ignore=public" />
            <arg value="--ignore=data" />
            <arg value="--ignore=build" />
            <arg value="--ignore=vendor" />
            <arg value="--ignore=node_modules" />
            <arg value="--ignore=test/_support/_generated" />
        </exec>
    </target>

    <target name="phpcpd" description="PHPCPD" depends="set-vendor, codeception-clean">
        <exec executable="${vendor}/bin/phpcpd">
            <arg path="${basedir}/src" />
        </exec>
    </target>
    <target name="phpcpd-ci" description="Find duplicate code using PHPCPD" depends="codeception-clean, set-vendor">
        <exec executable="${vendor}/bin/phpcpd">
            <arg value="--log-pmd" />
            <arg value="${basedir}/build/logs/pmd-cpd.xml" />
            <arg path="${basedir}/src" />
        </exec>
    </target>

    <target name="buildHelper" depends="set-vendor">
        <exec executable="${vendor}/bin/codecept">
            <arg value="build" />
        </exec>
    </target>

    <target name="codeception-clean">
        <delete file="${basedir}/test/_support/AcceptanceTester.php" />
        <delete file="${basedir}/test/_support/FunctionalTester.php" />
        <delete file="${basedir}/test/_support/UnitTester.php" />
    </target>

    <target name="unit-ci" depends="prepare, set-vendor, buildHelper" description="Run unit tests with Codeception For Continuous Integration">
        <exec executable="${vendor}/bin/codecept">
            <arg value="run" />
            <arg value="unit" />
            <arg value="--xml" />
            <arg value="--coverage-xml" />
            <arg value="--coverage-html" />
        </exec>
    </target>
    <!-- most important action for acceptance/functional until then. -->
    <target name="unit" depends="prepare, set-vendor, buildHelper">
        <exec executable="${vendor}/bin/codecept">
            <arg value="run" />
            <arg value="unit" />
        </exec>
    </target>
    <target name="unit-group" depends="set-vendor, buildHelper">
        <exec executable="${vendor}/bin/codecept">
            <arg value="run" />
            <arg value="unit" />
            <arg value="-g" />
            <arg value="${s}" />
        </exec>
    </target>
    <target name="unit-coverage" description="Run unit tests with PHPUnit" depends="set-vendor, buildHelper">
        <exec executable="${vendor}/bin/codecept">
            <arg value="run" />
            <arg value="unit" />
            <arg value="--coverage" />
            <arg value="--coverage-html" />
        </exec>
    </target>
    <target name="unit-group-coverage" depends="set-vendor, buildHelper">
        <exec executable="${vendor}/bin/codecept">
            <arg value="run" />
            <arg value="unit" />
            <arg value="-g" />
            <arg value="${s}" />
            <arg value="--coverage-html" />
        </exec>
    </target>
    <target name="pdepend" description="Calculate software metrics using PHP_Depend" depends="set-vendor">
        <exec executable="${vendor}/bin/pdepend">
            <arg value="--jdepend-xml=${basedir}/build/logs/jdepend.xml" />
            <arg value="--jdepend-chart=${basedir}/build/pdepend/dependencies.svg" />
            <arg value="--overview-pyramid=${basedir}/build/pdepend/overview-pyramid.svg" />
            <arg path="${basedir}/src" />
        </exec>
    </target>
    <target name="phploc" description="Measure project size using PHPLOC" depends="set-vendor">
        <exec executable="${vendor}/bin/phploc">
            <arg path="${basedir}/src" />
        </exec>
    </target>
    <target name="phploc-ci" depends="prepare, set-vendor" description="Measure project size using PHPLOC and log result in CSV and XML format. Intended for usage within a continuous integration environment.">
        <exec executable="${vendor}/bin/phploc">
            <arg value="--count-tests" />
            <arg value="--log-csv" />
            <arg path="${basedir}/build/logs/phploc.csv" />
            <arg value="--log-xml" />
            <arg path="${basedir}/build/logs/phploc.xml" />
            <arg path="${basedir}/src" />
            <arg path="${basedir}/test" />
        </exec>
    </target>
    <target name="phpdox" description="Generate API documentation using phpDox">
        <exec executable="phpdox" />
    </target>
    <target name="clean" description="Cleanup build artifacts">
        <delete dir="${basedir}/build/api" />
        <delete dir="${basedir}/build/coverage" />
        <delete dir="${basedir}/build/logs" />
        <delete dir="${basedir}/build/pdepend" />
        <delete dir="${basedir}/build/phpdox" />
    </target>
    <target name="prepare" depends="clean" description="Prepare for build">
        <mkdir dir="${basedir}/build/api" />
        <mkdir dir="${basedir}/build/coverage" />
        <mkdir dir="${basedir}/build/logs" />
        <mkdir dir="${basedir}/build/pdepend" />
        <mkdir dir="${basedir}/build/phpdox" />
    </target>
    <target name="set-vendor" depends="isRunningAsModule, isRunningAsVendor, isRunningAsProject" />
    <target name="isRunningAsModule" depends="check.runningAsModule" if="dir.exists">
        <property name="vendor" value="${basedir}/../../vendor" />
    </target>
    <target name="isRunningAsVendor" depends="check.runningAsVendor" if="dir.exists">
        <property name="vendor" value="${basedir}/../../../vendor" />
    </target>
    <target name="isRunningAsProject" depends="check.runningAsProject" if="dir.exists">
        <property name="vendor" value="${basedir}/vendor" />
    </target>
    <target name="check.runningAsModule">
        <condition property="dir.exists">
            <available file="${basedir}/../../vendor" type="dir" />
        </condition>
    </target>
    <target name="check.runningAsVendor">
        <condition property="dir.exists">
            <available file="${basedir}/../../../vendor" type="dir" />
        </condition>
    </target>
    <target name="check.runningAsProject">
        <condition property="dir.exists">
            <available file="${basedir}/vendor" type="dir" />
        </condition>
    </target>
</project>