<?php
namespace MyModuleTest\BasicTest\FeatureTest\IssueTest\TaskTest;

use PHPUnit_Framework_TestCase as TestCase;
use MyModule\Basic\Feature\Issue\Task\BasicNamespaceExtendsFactoryFilter;

/**
 * @group Filter
 */
class BasicNamespaceExtendsFactoryFilterTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();
        $this->filter = new BasicNamespaceExtendsFactoryFilter();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf(
            'MyModule\Basic\Feature\Issue\Task\BasicNamespaceExtendsFactoryFilter',
            $this->filter->getInputFilter()
        );
    }
}
