<?php
namespace MyModuleTest\FilterTest;

use PHPUnit\Framework\TestCase;
use MyModule\Filter\BasicFilter;

/**
 * @group Filter
 */
class BasicFilterTest extends TestCase
{
    public function setUp() : void
    {
        parent::setUp();
        $this->filter = new BasicFilter();
    }

    public function testClassExists()
    {
        $this->assertInstanceOf(
            'MyModule\Filter\BasicFilter',
            $this->filter->getInputFilter()
        );
    }
}
