<?php
namespace MyModule\Service;

use MyModule\Service\MyDependencyOneTrait;
use MyModule\Service\MyDependencyTwoTrait;
use MyModule\Service\MyDependencyThreeTrait;
use MyModule\Service\MyDependencyOne;
use MyModule\Service\MyDependencyTwo;
use MyModule\Service\MyDependencyThree;

/**
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/Service
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicDependenciesFactoryService
{
    use MyDependencyOneTrait;

    use MyDependencyTwoTrait;

    use MyDependencyThreeTrait;

    /**
     * Constructor
     *
     * @param MyDependencyOne   $myDependencyOne   My Dependency One
     * @param MyDependencyTwo   $myDependencyTwo   My Dependency Two
     * @param MyDependencyThree $myDependencyThree My Dependency Three
     *
     * @return BasicDependenciesFactoryService
     */
    public function __construct(
        MyDependencyOne $myDependencyOne,
        MyDependencyTwo $myDependencyTwo,
        MyDependencyThree $myDependencyThree
    ) {
        $this->myDependencyOne = $myDependencyOne;
        $this->myDependencyTwo = $myDependencyTwo;
        $this->myDependencyThree = $myDependencyThree;

        return $this;
    }
}
