<?php
namespace MyModule\BestNamespace;

/**
 * PHP Version 5
 *
 * @category Service
 * @package MyModule/BestNamespace
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class MySrcWithSpecialDependency
{
    /**
     * Constructor
     *
     * @return \MyModule\BestNamespace\MySrcWithSpecialDependency
     */
    public function __construct()
    {
        return $this;
    }
}
