namespace <?php echo $this->module;?>Test\FormTest\SearchTest;

/**
use PHPUnit\Framework\TestCase;
 * @group <?php echo $this->module.PHP_EOL;?>
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group Search
 */
class <?php echo $this->class;?>Test extends TestCase
{
    protected $<?php echo $this->var;?>;

    protected function setUp() : void
    {
        $this->bootstrap = new \<?php echo $this->module;?>\ZendServiceLocator();
    }

    protected function tearDown() : void
    {
        unset($this->bootstrap);
    }
    public function get<?php echo $this->class;?>()
    {
        if (!isset($this-><?php echo $this->var;?>)) {
            $this-><?php echo $this->var;?> = $this->bootstrap->get(
                '<?php echo $this->callable; ?>'
            );
        }
        return $this-><?php echo $this->var;?>;
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->class.PHP_EOL;?>
     */
    public function testServiceLocator()
    {
        $serviceLocator = $this->get<?php echo $this->class;?>()->getServiceLocator();
        $this->assertInstanceOf('Zend\ServiceManager\ServiceManager', $serviceLocator);
    }

    /**
     * @group <?php echo $this->module.PHP_EOL;?>
     * @group <?php echo $this->class.PHP_EOL;?>
     */
    public function testCallUsingServiceLocator()
    {
        $<?php echo $this->var;?> = $this->get<?php echo $this->class;?>();
        $this->assertInstanceOf('<?php echo $this->module;?>\Form\Search\<?php echo $this->class;?>', $<?php echo $this->var;?>);
    }
}
