namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage;
use <?php echo $this->module;?>\AcceptanceTester\ViewSteps;

/**
 * @SuppressWarnings(PHPMD)
 * @group <?php echo $this->class.PHP_EOL;?>
 * @group View
 */
class <?php echo $this->class;?>ViewCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(ViewSteps $I)
    {
// @codingStandardsIgnoreEnd
<?php echo $this->preFixture;?>
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixture;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );
<?php echo $this->posFixture;?>
        parent::_before($I);
    }

    public function view<?php echo $this->class;?>(ViewSteps $I)
    {
        $I->wantTo('View <?php echo $this->classLabel;?> Successful');
        $I->verifyOnPage(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>ViewPage',
            '<?php echo $this->classLabel;?>',
            $this->fixture
        );

<?php echo $this->seeLabel;?>
<?php echo $this->seeValue;?>
    }
<?php echo $this->functions;?>
}
