namespace <?php echo $this->module;?>\Acceptance;

use <?php echo $this->module;?>\AcceptanceTester;
use <?php echo $this->module;?>\Pages\<?php echo $this->class;?>EditPage;
use <?php echo $this->module;?>\AcceptanceTester\UploadImageSteps;

/**
 * @SuppressWarnings(PHPMD)

 * @group <?php echo $this->class.PHP_EOL;?>
 * @group UpdateImage
 */
class <?php echo $this->class;?>UploadImageCest extends \<?php echo $this->module;?>\Acceptance\AbstractCest
{
    protected $fixture;

// @codingStandardsIgnoreStart
    public function _before(UploadImageSteps $I)
    {
// @codingStandardsIgnoreEnd
<?php echo $this->preFixture;?>
        $this->fixture = $I->haveInDatabase(
            '<?php echo $this->classUnderline;?>',
            array(
<?php echo $this->fixture;?>
                'created' => '<?php echo $this->created->format('Y-m-d H:i:s');?>',
                'created_by' => 2
            )
        );
        parent::_before($I);
    }

    public function uploadImage<?php echo $this->class;?>(UploadImageSteps $I)
    {
        $I->wantTo('Upload <?php echo $this->classLabel;?> Successful');

        $I->verifyOnPage(
            '<?php echo $this->module;?>\Pages\<?php echo $this->class;?>UploadImagePage',
            '<?php echo $this->classLabel;?> - '.$this->fixture,
            $this->fixture
        );
    }
}
