{
    "optimize": {
        "js": {
            "files": {
                "internal": [
                    "./vendor/mauriciopiber/gear-admin/public/dist/internal.js"
                ***REMOVED***,
                "external": [
                    "./vendor/mauriciopiber/gear-admin/public/dist/external.js"
                ***REMOVED***
            }
        },
        "css": {
            "files": [
                "./vendor/mauriciopiber/gear-admin/public/dist/external.css"
            ***REMOVED***
        }
    }
}

