paths:
    migrations: %%PHINX_CONFIG_DIR%%/{data/migrations,vendor/mauriciopiber/**/migrations,vendor/mauriciopiber/**/data/migrations}

environments:
    default_migration_table: migrations
    default_database: DEVELOPMENT
    DEVELOPMENT:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
    TESTING:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
    STAGING:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
    PRODUCTION:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
