paths:
    migrations: %%PHINX_CONFIG_DIR%%/data/migrations

environments:
    default_migration_table: migrations
    default_database: development
    development:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
    testing:
        adapter: mysql
        host: localhost
        name: <?php echo $this->database.PHP_EOL;?>
        user: <?php echo $this->username.PHP_EOL;?>
        pass: <?php echo $this->password.PHP_EOL;?>
        port: 3306
        charset: utf8
    staging:
        adapter: mysql
        host: ''
        name: ''
        user: ''
        pass: ''
        port: 3306
        charset: utf8
    production:
        adapter: mysql
        host: ''
        name: ''
        user: ''
        pass: ''
        port: 3306
        charset: utf8
