<project name="<?php echo $this->project;?>" default="build" basedir=".">
    <target name="build" depends="prepare,lint,phploc-ci,pdepend,phpmd-ci,phpcs-ci,phpcpd-ci,codeception-ci,phpdox"/>
    <target name="lint" description="Perform syntax check of sourcecode files">
        <apply executable="php" >
            <arg value="-l" />

            <fileset dir="${basedir}/module">
                <include name="**/*.php" />
                <modified />
            </fileset>
        </apply>
    </target>
    <target name="clean" description="Cleanup build artifacts">
        <delete dir="${basedir}/build/api" />
        <delete dir="${basedir}/build/coverage" />
        <delete dir="${basedir}/build/logs" />
        <delete dir="${basedir}/build/pdepend" />
        <delete dir="${basedir}/build/phpdox" />
    </target>
    <target name="prepare" depends="clean" description="Prepare for build">
        <mkdir dir="${basedir}/build/api" />
        <mkdir dir="${basedir}/build/coverage" />
        <mkdir dir="${basedir}/build/logs" />
        <mkdir dir="${basedir}/build/pdepend" />
        <mkdir dir="${basedir}/build/phpdox" />
    </target>
	<target name="phploc-ci"
	         depends="prepare"
	         description="Measure project size using PHPLOC and log result in CSV and XML format. Intended for usage within a continuous integration environment.">
	  <exec executable="${basedir}/vendor/bin/phploc">
	   <arg value="--count-tests" />
	   <arg value="--log-csv" />
	   <arg path="${basedir}/build/logs/phploc.csv" />
	   <arg value="--log-xml" />
	   <arg path="${basedir}/build/logs/phploc.xml" />
	   <arg path="${basedir}/module" />
	  </exec>
	 </target>
	 <target name="phpmd" description="MessDetector">
        <exec executable="${basedir}/vendor/bin/phpmd"  >
            <arg path="${basedir}/module" />
            <arg value="text" />
            <arg value="${basedir}/config/jenkins/phpmd.xml" />
        </exec>
    </target>
	<target name="phpmd-ci" description="PHPMD">
		<exec executable="${basedir}/vendor/bin/phpmd">
			<arg path="${basedir}/module" />
			<arg value="xml" />
			<arg value="${basedir}/config/jenkins/phpmd.xml" />
			<arg value="--reportfile" />
			<arg value="${basedir}/build/logs/pmd.xml" />
		</exec>
	</target>
    <target name="phpcs" description="Code Sniffer">
        <exec executable="${basedir}/vendor/bin/phpcs"  >
            <arg value="--standard=PSR2" />
            <arg path="${basedir}/module" />
            <arg value="--ignore=public" />
        </exec>
    </target>
  	<target name="phpcs-ci" description="PHP_CodeSniffer Continuous Integration" >
		<exec executable="${basedir}/vendor/bin/phpcs" output="/dev/null">
			<arg value="--report=checkstyle" />
			<arg value="--report-file=${basedir}/build/logs/checkstyle.xml" />
			<arg value="--standard=PSR2" />
			<arg path="${basedir}/module" />
		    <arg value="--ignore=public" />
		</exec>
	</target>
    <target name="phpcpd-ci" description="Find duplicate code using PHPCPD">
		<exec executable="${basedir}/vendor/bin/phpcpd">
			<arg value="--log-pmd" />
			<arg value="${basedir}/build/logs/pmd-cpd.xml" />
			<arg path="${basedir}/module" />
		</exec>
    </target>
    <target name="pdepend" description="Calculate software metrics using PHP_Depend">
		<exec executable="${basedir}/vendor/bin/pdepend">
			<arg value="--jdepend-xml=${basedir}/build/logs/jdepend.xml" />
			<arg value="--jdepend-chart=${basedir}/build/pdepend/dependencies.svg" />
			<arg
				value="--overview-pyramid=${basedir}/build/pdepend/overview-pyramid.svg" />
			<arg path="${basedir}/module" />
		</exec>
	</target>
    <target name="codeception-ci" depends="prepare">
	    <exec executable="${basedir}/vendor/bin/codecept" >
	       <arg value="run" />
	       <arg value="--xml"/>
	       <arg value="--coverage-xml"/>
	       <arg value="--coverage-html"/>
	   </exec>
    </target>
	<target name="phpdox" description="Generate API documentation using phpDox">
		<exec executable="phpdox">
	    </exec>
	</target>
</project>