<?php
namespace MyModule\Basic\Feature\Issue\Task;

use Zend\Form\Form;

/**
 * PHP Version 5
 *
 * @category Form
 * @package MyModule/Basic/Feature/Issue/Task
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicNamespaceFactoryForm extends Form
{
    /**
     * Create the Form
     *
     * @return \MyModule\Basic\Feature\Issue\Task\BasicNamespaceFactoryForm
     */
    public function __construct()
    {
        parent::__construct('basic-namespace-factory-form');

        return $this;
    }
}
