<?php
namespace MyModule\Form;

use MyModule\Form\MyForm;

/**
 * PHP Version 5
 *
 * @category Form
 * @package MyModule/Form
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class BasicExtendsForm extends MyForm
{
    /**
     * Create the Form
     *
     * @return \MyModule\Form\BasicExtendsForm
     */
    public function __construct()
    {
        parent::__construct('basic-extends-form');

        return $this;
    }
}
