namespace <?php echo $this->module;?>Test\<?php echo $this->namespace; ?>;

use PHPUnit_Framework_TestCase as TestCase;
use Zend\Mvc\Controller\ControllerManager;
use Zend\ServiceManager\ServiceManager;
use <?php echo $this->module?>\<?php echo $this->testNamespace;?>\<?php echo $this->class;?>Factory;
use <?php echo $this->module?>\<?php echo $this->testNamespace;?>\<?php echo $this->class;?>;
<?php echo $this->use;?>

/**
 * @group <?php echo $this->module.PHP_EOL; ?>
 * @group <?php echo $this->class.PHP_EOL; ?>
 * @group <?php echo $this->group.PHP_EOL;?>
 */
class <?php echo $this->class;?>FactoryTest extends TestCase
{
    public function test<?php echo $this->class;?>Factory()
    {
        $this->controllerManager = $this->prophesize(ControllerManager::class);

        $this->serviceLocator = $this->prophesize(ServiceManager::class);
<?php echo $this->dependency;?>

        $this->controllerManager->getServiceLocator()->willReturn($this->serviceLocator->reveal());

        $factory = new <?php echo $this->class;?>Factory();

        $instance = $factory->createService($this->controllerManager->reveal());

        $this->assertInstanceOf(<?php echo $this->class;?>::class, $instance);
    }
}
