<?php
namespace MyModule\Controller;

use Zend\ServiceManager\Factory\FactoryInterface;
use Interop\Container\ContainerInterface;
use MyModule\Controller\IndexController;

/**
 * PHP Version 5
 *
 * @category Factory
 * @package MyModule/Controller
 * @author Mauricio Piber <mauriciopiber@gmail.com>
 * @license GPL3-0 http://www.gnu.org/licenses/gpl-3.0.en.html
 * @link http://pibernetwork.com
 */
class IndexControllerFactory implements FactoryInterface
{
    /**
     * Create Index Controller
     *
     * @param ContainerInterface $container Controller Manager
     *
     * @return IndexController
     */
    public function __invoke(ContainerInterface $container, $requestedName = null, $options = [***REMOVED***)
    {
        unset($container);
        $indexController = new IndexController();
        return $indexController;
    }
}
