<div class="row">
	<div class="col-lg-6">
        <h3 id="pageTitle">Preco Tipo Servico</h3>
	</div>
</div>
<?php if($this->success) :?>
<?php echo $this->render('layout/success');?>
<?php endif;?>
<div class="row">
    <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('piber-network/preco-tipo-servico/edit', array('id' => $this->idPrecoTipoServico)));
            $form->prepare();
            echo $this->form()->openTag($form);
        ?>
        <?php echo $this->formHidden($form->get('idPrecoTipoServico')->setAttribute('class','form-control')); ?>
        <div class="form-group">
            <?php echo $this->formRow($form->get('idTipoServico')->setAttribute('class','form-control')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('precoHora')->setAttribute('class','form-control money')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('dataInicio')->setAttribute('class','form-control date-pt-br')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('dataFinal')->setAttribute('class','form-control date-pt-br')); ?>
        </div>

        <div class="form-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class','btn btn-default')); ?>
            <a class="btn btn-default reset" href="<?php echo $this->url('piber-network/preco-tipo-servico/list');?>">Voltar</a>
        </div>
        <?php echo $this->form()->closeTag(); ?>

    </div>
</div>