<tr>
            <td>
                <?php echo $this->escapeHtml($this->object->getIdPrecoTipoServico()); ?>
            </td>
            <td>
                <?php echo ($this->object->getIdTipoServico() !== null) ? $this->escapeHtml($this->object->getIdTipoServico()->getNome()) : ''; ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->currencyFormat($this->object->getPrecoHora())); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getDataInicio()->format('d/m/Y')); ?>
            </td>
            <td>
                <?php echo $this->escapeHtml($this->object->getDataFinal()->format('d/m/Y')); ?>
            </td>
    <td>
        <a href="<?php echo $this->url('piber-network/preco-tipo-servico/edit', array('id' => $this->object->getIdPrecoTipoServico())); ?>">            <span class="glyphicon glyphicon-pencil"></span>
        </a>
        <form method="POST" action="<?php echo $this->url('piber-network/preco-tipo-servico/delete', array('id' => $this->object->getIdPrecoTipoServico())); ?>" accept-charset="UTF-8" style="display:inline">
            <a data-toggle="modal" data-target="#confirmDelete" data-title="Deletar Preco Tipo Servico" data-message="<?php echo $this->translate('Desejas realmente deletar Preco Tipo Servico?');?>">
                <i class="glyphicon glyphicon-trash"></i>
            </a>
        </form>
    </td>
</tr>