#!/bin/bash

cp config/autoload/local.php.dist config/autoload/local.php

echo "Deploy Testing - Composer"

ls -l vendor/autoload.php &> /dev/null

if [ "$?" != "0" ***REMOVED***; then
    composer update
fi;

echo "Deploy Testing - NodeJS"
vendor/bin/install-nodejs

echo "Deploy Testing - VirtualHost"

ls -l /etc/apache2/sites-enabled/<?php echo $this->moduleUrl;?>.gear.dev.conf > /dev/null
if [ "$?" != "0" ***REMOVED***; then
    sudo vendor/bin/virtualhost  $(pwd) <?php echo $this->moduleUrl;?>.gear.dev testing
fi

echo "Deploy Testing - Database"
sudo vendor/bin/install-db-module <?php echo $this->moduleUrl;?>.mysql.sql <?php echo $this->module.PHP_EOL;?>

echo "Deploy Testing - Gulp"
vendor/bin/gulp

chmod 777 -R build
chmod 777 -R data/session
chmod 777 -R data/logs
chmod 777 -R data/cache
chmod 777 -R data/DoctrineModule
chmod 777 -R data/DoctrineORMModule

echo "flush_all" | nc -q 2 localhost 11211
