#!/bin/bash


ls -l node_modules/.bin/webdriver-manager &> /dev/null

#if [ "$?" != "0" ***REMOVED***; then

    #npm install
    #node_modules/.bin/webdriver-manager update

#fi

ls -l vendor/autoload.php &> /dev/null

if [ "$?" != "0" ***REMOVED***; then
    composer update
fi;

ls -l /etc/apache2/sites-enabled/<?php echo $this->moduleUrl;?>.gear.dev.conf > /dev/null

if [ "$?" != "0" ***REMOVED***; then
    vendor/bin/virtualhost  $(pwd) <?php echo $this->moduleUrl;?>.gear.dev development
fi

ls -l data/<?php echo $this->moduleUrl;?>.mysql.sql &> /dev/null

if [ "$?" != "0" ***REMOVED***; then

    database=$(php -r '$global = require_once("config/autoload/global.php"); echo $global["doctrine"***REMOVED***["connection"***REMOVED***["orm_default"***REMOVED***["params"***REMOVED***["dbname"***REMOVED***;')
    username=$(php -r '$local = require_once("config/autoload/local.php"); echo $local["doctrine"***REMOVED***["connection"***REMOVED***["orm_default"***REMOVED***["params"***REMOVED***["user"***REMOVED***;')
    password=$(php -r '$local = require_once("config/autoload/local.php"); echo $local["doctrine"***REMOVED***["connection"***REMOVED***["orm_default"***REMOVED***["params"***REMOVED***["password"***REMOVED***;')

    vendor/bin/database $database $username $password
    vendor/bin/merge-migrations
    vendor/bin/phinx migrate

    vendor/bin/unload-module BjyAuthorize
    php public/index.php gear project setUpAcl --memcached --user --role
    php public/index.php gear module load BjyAuthorize --after=ZfcUserDoctrineORM
    php public/index.php gear database module dump <?php echo $this->module.PHP_EOL;?>
    php public/index.php gear module dump-autoload <?php echo $this->module.PHP_EOL;?>
    vendor/bin/gulp
fi









