<?php
namespace MyModuleTest\FormTest\SearchTest;

use PHPUnit_Framework_TestCase as TestCase;

/**
 * @group MyModule
 * @group TableSearchForm
 * @group SearchForm
 */
class TableSearchFormTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->search = new \MyModule\Form\Search\TableSearchForm($entityManager->reveal());
    }

    public function testHasColumn()
    {
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('likeField'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('clear'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('submit'));
    }
}
