<?php
namespace MyModuleTest\CustomTest\CustomNamespaceTest;

use PHPUnit\Framework\TestCase;
use MyModule\Custom\CustomNamespace\SingleDbTableSearchForm;

/**
 * @group MyModule
 * @group SingleDbTableSearchForm
 * @group SearchForm
 */
class SingleDbTableSearchFormTest extends TestCase
{
    public function setUp()
    {
        parent::setUp();

        $entityManager = $this->prophesize('Doctrine\ORM\EntityManager');
        $this->search = new SingleDbTableSearchForm($entityManager->reveal());
    }

    public function testHasColumn()
    {
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('likeField'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('clear'));
        $this->assertInstanceOf('Zend\Form\Element', $this->search->get('submit'));
    }
}
