namespace FunctionalTester;

class BreadcrumbSteps extends \FunctionalTester
{
    public function validate($pageObject, $module, $controller, $action)
    {
        $I = $this;
        $I->see($module, $pageObject::$breadscrumbModule);
        $I->see($controller, $pageObject::$breadscrumbController);
        $I->see($action, $pageObject::$breadscrumbAction);
        $I->seeNumberOfElements($pageObject::$breadscrumbList, 3);
    }
}