namespace FunctionalTester;

class FilterSteps extends \FunctionalTester
{
    public function validate($pageObject)
    {
        $I = $this;

        $I->see('Exibir Filtro',$pageObject::$filterBtn);
        $I->click($pageObject::$filterBtn);
        $I->see('Esconder Filtro', $pageObject::$filterBtn);

        $I->seeInField($pageObject::$filterSearchBtn, 'Pesquisar');
        $I->seeInField($pageObject::$filterClearBtn, 'Limpar');
        $I->seeInField($pageObject::$filterLikeField, '');
    }
}
