namespace FunctionalTester;

class PaginatorSteps extends \FunctionalTester
{
    public function validate($pageObject)
    {
        $I = $this;
        $I->see('Mostrando 1 até 10 de 30 entradas', $pageObject::$paginatorCount);
        $I->see('<<', $pageObject::$paginatorOne);
        $I->see('1', $pageObject::$paginatorTwo);
        $I->seeLink('1', $pageObject::$URL);
        $I->see('2', $pageObject::$paginatorThree);
        $I->seeLink('2', $pageObject::$URL);
        $I->see('3', $pageObject::$paginatorFour);
        $I->seeLink('3', $pageObject::$URL);
        $I->see('>>', $pageObject::$paginatorFive);
        $I->seeNumberOfElements($pageObject::$paginatorList, 5);
    }
}
