<?php
namespace ModuleUnit\Free\MyClass;

use ModuleUnit\Free\MyClass\UnitSrcName;

trait UnitSrcNameTrait
{
    /** @var \ModuleUnit\Free\MyClass\UnitSrcName */
    protected $unitSrcName;

    public function setUnitSrcName(UnitSrcName $unitSrcName)
    {
        $this->unitSrcName = $unitSrcName;
        return $this;
    }

    public function getUnitSrcName()
    {
        if (!isset($this->unitSrcName)) {
            $this->unitSrcName = $this->getServiceLocator()->get('ModuleUnit\Free\MyClass\UnitSrcName');
        }
        return $this->unitSrcName;
    }
}
