<?php
namespace NoExtendsTest\TryWithoutExtendsTest;

use GearBaseTest\AbstractTestCase;
use NoExtends\TryWithoutExtends\ClassWithoutExtendsTrait;

class ClassWithoutExtendsTest extends AbstractTestCase
{
    use ClassWithoutExtendsTrait;

    public function testSetClassWithoutExtends()
    {
        $mockClassWithoutExtends = $this->getMockSingleClass('NoExtends\TryWithoutExtends\ClassWithoutExtends');
        $this->setClassWithoutExtends($mockClassWithoutExtends);
        $this->assertEquals($mockClassWithoutExtends, $this->getClassWithoutExtends());
    }

    public function testGetClassWithoutExtends()
    {
        $this->assertInstanceOf(
            'NoExtends\TryWithoutExtends\ClassWithoutExtends',
            $this->getClassWithoutExtends()
        );
    }
}
