<?php
namespace NoExtends\TryWithoutExtends;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use NoExtends\TryWithoutExtends\ClassWithoutExtends;

class ClassWithoutExtendsFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $classWithoutExtends = new ClassWithoutExtends();
        return $classWithoutExtends;
    }
}
