<?php
namespace ModuleUnitTwo\Free\MyClassTwo;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use ModuleUnitTwo\Free\MyClassTwo\UnitSrcNameTwo;

class UnitSrcNameTwoFactory extends FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $unitSrcNameTwo = new UnitSrcNameTwo();
        return $unitSrcNameTwo;
    }
}
